### ISSUE TITLE
Need me some specs!!!

### ISSUE THREAD

**Issue by 130nk3r5** [tari-project/tari#1]
Do it already!!!

**Comment by TheCharlatan** [comment]
pls

**Comment by 130nk3r5** [comment]
Doesn't seem like anything is happening here. Still waiting.

**Comment by wojtasss** [comment]
I have download repo and don't know what to do to launch Tari, can anybody help me?

**Comment by CjS77** [comment]
> Doesn't seem like anything is happening here. Still waiting.

We've started writing up proposals in https://github.com/tari-project/RFC, which you're welcome to contribute to. Also join in design discussions on freenode at #tari-dev

**Comment by CjS77** [comment]
I think we're at a point that we can close this out now.
