### ISSUE TITLE
[Feature] Transaction Details Screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1006]
**When I want to know more details about a transaction than what I can see on the Transactions List, (e.g. exactly when a transaction happened, what was the entire note that I or the other party wrote about it, how much of a fee I paid, etc.), I should be able to drill down from a list item to see those details.**

Design Specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e189002a53d3faa70faa51d

Open Question: Do we have transaction IDs that we’d want to display per the design?

----

**Acceptance Criteria** 

- When I tap any transaction of any status from the Transactions List, I should be sent to its Transaction Detail screen
- The heading of the screen should read:
    - “Payment Sent” if completed transaction where user is sender
    - “Payment Received” if completed transaction where user is receiver
    - “Pending Payment Sent” if transaction where user is sender is in any other status but Completed
    - “Pending Payment Received” if transaction where user is receiver is in any other status but Completed
- The timestamp under the heading should read:
    - If current user is Sender, the timestamp should be when the payment was initiated in the user’s current local time zone
    - If current user is Received, the timestamp should be when the payment was received/accepted in the user’s current local time zone
    - The format of the timestamp should include abbreviated day of week and also abbreviate the month, e.g. “Mon, Nov 1st 2019 at 2:39 PM” (the design does not currently reflect this)
- The transaction fee should only appear for payments of any status where current user is the sender
- Top label should either read “From” or “To” depending on whether current user is receiver or sender
- “Add Contact Name” should appear next to the Emoji ID of the other party if no name exists
- Tapping “Add Contact Name” should reveal the Contact Name input AND display the keyboard AND focus in the Contact Name input field
- After entering a contact name, tapping Return should save the name, hide the keyboard, and display the read-only state of the field
- Tapping the “Edit” link next to any existing Contact Name turns the field into its editable state again, brings up the keyboard, and focuses on the end of the name in the field

**Comment by CjS77** [comment]
Sounds good - except that the date format `Mon, Nov 1st 2019 at 2:39 PM` is American. Users from other countries would expect a different format. e.g. in South Africa

`Mon, 1st Nov 2019 at 14:39` would be more natural
