### ISSUE TITLE
Full blockchain and contextual validation of received blocks

### ISSUE THREAD

**Issue by neonknight64** [tari-project/tari#1020]
- Perform additional validation of the block before calling add_block in the block handler
- Extend block events with more detailed rejection reasons and remove BlockAddResult and ChainStorageError from BlockEvent.

**Comment by SWvheerden** [comment]
Block validation is currently tested on unit test level,  This needs to be done on integration level

**Comment by SWvheerden** [comment]
Branch name of current code: sw_chain_validation
