### ISSUE TITLE
Implement Monero merge mining difficulty calculation

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1035]
Given a block header, we must be able to determine the achieved difficulty for the data contained in the `pow` field in the header.

For Monero, this entails:
* Deserialise the pow field into a MoneroBlockHeader
* Running header through a RandomX VM and return the difficulty recorded

The `achieved_difficulty` function in `base_layer/core/src/proof_of_work/monero.rs` is the wrapper for this functionality

**Comment by SWvheerden** [comment]
I believe this is merged into development as of #2098
