### ISSUE TITLE
Create async TCP transport using tokio TcpStream

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#1044]
Before starting: Investigate using `async-std::net::TcpStream` rather than tokio. 
 - [ ] How would wire framing be done? Is there a `tokio::codec::Framed` equivalent? Any reason we can't use https://substrate.dev/rustdocs/v1.0/unsigned_varint/codec/struct.UviBytes.html? 
- [ ] Any missing features in async-std that we'd need?

Possible trait definition for Transport

```rust
trait Transport {
    // For Tcp: TcpStream
    type Output;

    // Error type
    type Error: std::error::Error;

    // For Tcp: TcpListener 
    type Listener: Stream<Item = Result<(Self::Inbound, Multiaddr), Self::Error>>;

    // For Tcp: Ok(TcpStream)
    type Inbound: Future<Output = Result<Self::Output, Self::Error>> + Send;

    // For Tcp: Ok(TcpStream)
    type Outbound: Future<Output = Result<Self::Output, Self::Error>>;

    // Listen on address
    fn listen(&self, addr: Multiaddr) -> Result<(Self::Listener, Multiaddr), Self::Error>;

    // Connect (dial) to a peer
    fn connect(&self, addr: Multiaddr) -> Result<Self::Outbound, Self::Error>;
}
```

**Comment by CjS77** [comment]
Some sanity checks:

Do we need this layer of abstraction, i.e. is `trait Transport` necessary? What other transport types might be used?
Why not just use TcpStream as is?

I ask because I've been guilty of adding layers myself in the past and it ends up adding more boilerplate than value oftentimes.

**Comment by sdbondi** [comment]
This is basically lifted from libp2p and libra - I think while it's pretty nice to be able to use this abstraction in it's full glory, like so:

```rust
let fancy_some_transport = SomeTransport::new()
     // Run this upgrade ....
    .and_then(NoiseProtocol::upgrade)
     // and then this upgrade
    .and_then(Yamux::upgrade); 
let (fancy_listener, addr) = fancy_some_transport.listen("/ip4/127.0.0.1/tcp/1234");
fancy_listener.incoming().for_each(|sock| {
  // This socket is encrypted and speaks yamux ...fancy
});
```

... and while being able to create a `MemoryTransport` is great for no-IO tests.

I agree that there is little value in putting effort into completely abstracting the transport from other components right now esp. since we'll be using one kind of transport that is "upgraded" in the same way for all connections. Perhaps there's no harm in implementing it for `TcpTransport` and not genericising the components which use it?
