### ISSUE TITLE
[Feature] Sending Tari: Adding a recipient by Emoji ID or Contact Name

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1057]
**User Stories**

> When I want to send someone Tari, I want to be able to enter their unique Tari ID so the app knows who they are

> When I want to send Tari to someone I’ve transacted with already, I want to be able to do so without having to type in their ID again

> When I want to see if I already have someone’s ID to transact with them, I need a way of scanning through my existing contacts quickly

-----

**UX/UI**

1. Refer to the following group of Zeplin screens  -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android.

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5df83c289c2f1097b8fcbf83

Note that the styles are slightly inconsistent across screens. The screens WITH the pipes in between emojis and the more square buttons are the final styles. 

Assets should be in Dropbox folder, pls let Karim know if any are missing.

-----

**Open Questions**

1. ~How do we define a valid emoji ID? @CjS77 Have we determined how many chars it will have to be yet? Maybe we can just use a placeholder rule for now like "string of 10+ emoji chars AND no non-emoji unicode chars."~

There's a checksum, but yes, we can have a stub is_valid() checksum check as @talmahaj suggests above.

It might be easier to maintain separate Rust, Java and Swift libraries for Emoji Ids rather than going through the pain of FFIs. Maybe Rust and Java if it's easy to bring Rust into Swift.

2. @Karim-tari What happens after you enter a "valid" emoji ID? does user get any sort of feedback? 

3. @Karim-tari What does blank transaction list look like after user enters an emoji ID, if it doesn't match any existing users? Need empty state designed, for now we'll just leave it blank.

-----

**Acceptance Criteria**

User Flow

1. User hits Send Tari button from Dashboard Screen/Transaction List View
    - Send Tari CTA button should animate just like CTAs in original prototype, around timestamp 00:33 https://vimeo.com/369345180

2. Add Recipient screen comes in from the right
    - Text field should be in focus by default (with keyboard visible)
    - If user has a valid emoji ID in their clipboard already (see Open Questions section above) the list should be dimmed except for the input AND a CTA banner appears pinned to keyboard: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5de718dc4154c3575468a33b
        - In the banner, the emoji ID should appear with pipes (not reflected in the design) whether or not they were part of the copied string (easiest would probably be to strip out from string if needed, and just use input masking)
        - If user taps anywhere in banner, emoji ID should be pasted into input field AND dimming, keyboard, and banner should disappear
    - First section of list should be called "Recent" (not "Recent Transactions" like in the mockup" and should display the last 3 users transacted with -- whether as a sender or receiver -- ordered by timestamp of when transaction was initiated by either side (descending)
        - If fewer than 3 users transacted with, display only 1-2
        - If no users transacted with, do not display "Recent" section
        - If user is saved as a Contact (Emoji IDs user has stored an alphanumeric name for locally), display Contact name; if not display their Emoji ID
    - Second section of list should be called "Contacts" and display a descending alphabetical list (0-9, A-Z) of all of your Contacts
        - There is no limit to the number of Contacts; if a user has 100, display all 100
        - Users known only by their Emoji ID should NOT be displayed in this list
    - Tapping anywhere in the list should collapse the keyboard and remove focus from input
    - Header and input should be sticky even as user scrolls down the list: https://zpl.io/bWnqMDk
    - Selecting an existing Contact Name or Emoji ID from list should immediately send user to the next screen where they enter the transaction amount (not built yet, use blank view as placeholder as desired)
    - When a user pastes anything or starts typing into input field (whether emojis or alphanumeric chars):
        - The existing 2 lists of recent transactions and contacts should disappear
        - Whatever the user enters in the field should be used as a substring match filter against a single list of all of a user's contacts AND all of a user's historical transactions
        - The list should be filtered such that only matching users appear, based on their emoji ID OR contact name matching the typed string
                - The search results should appear as a descending alphabetical list (0-9, A-Z) if alphanumeric, or in whatever order your merry developer heart desires if in emojis because #whocares
                - If user enters the emoji ID of a named Contact, that Contact name should still appear in the search results; that is, if I enter Karim's emoji ID (because I forgot I had already saved him as a Contact) he should still appear in the search results under "Karim"
                - If a filtered list includes both emoji IDs and Contact Names -- e.g. if I type a smiley face emoji, and that emoji is a substring match for 3 recent transactions, only 1 of which has a contact name saved -- then Contact Names should always appear first before emoji-only users
        - "Continue" button should appear whenever a valid Emoji ID is entered (and disappear if user changes input such that Emoji ID is no longer valid)
    - User should be able to delete any characters entered or typed into the input field
    - All pipe characters should be stripped out of a pasted Emoji ID string, however...
    - When an Emoji ID is entered or pasted, pipe characters *should always* appear in input field using input masking

-----

**Implementation Notes**

1. QR code icon should be nonfunctional for now; scanning feature is out of scope for this ticket

**Comment by CjS77** [comment]
Open Question 1: There's a checksum, but yes, we can have a stub `is_valid()` checksum check as @talmahaj suggests above.

It might be easier to maintain separate Rust, Java and Swift libraries for Emoji Ids rather than going through the pain of FFIs.  Maybe Rust and Java if it's easy to bring Rust into Swift.

**Comment by Karim-tari** [comment]
@talmahaj 

For "What does the Continue/next step CTA look like and how does it appear once a recipient is selected?" Wouldn't we go to the next screen as soon as the user taps on a recipient? (no need for a continue button there)?

**Comment by talmahaj** [comment]
Thanks @Karim-tari @CjS77 that sounds good!

@CjS77 added a few more success criteria around filtering, see all the bullets after "Header and input should be sticky"

**Comment by CjS77** [comment]
> Users known only by their Emoji ID should NOT be displayed in this list

This only applies to the Contacts list. You want emojis to be displayed in the Recent list if there isn't an alias for that user?

**Comment by talmahaj** [comment]
That’s what we were thinking since your most recent transactions may be with people you haven’t saved an alias for (if you’ve saved any at all). Whereas we intended Contacts = ppl you’ve explicitly saved as a contact. Does that seem weird to you?

**Comment by CjS77** [comment]
Nope - just wanted clarification on the spec. 👍

**Comment by talmahaj** [comment]
Edited ticket to accommodate behavior around emoji ID "chunking" with pipe characters

**Comment by kukabi** [comment]
Do we take pending in/out transactions into account when listing the most recent transaction contacts? @talmahaj @CjS77

**Comment by talmahaj** [comment]
@kukabi Sure, let's take them into account. Thx, good catch!

**Comment by kukabi** [comment]
So it seems like if the other of any of the wallet's complete tx list (complete & pending in/out) is a public key that does not exist in my contact list, then the tx was made through emoji ID only, so we display emoji ID only. Can you confirm please? @CjS77 @talmahaj

**Comment by CjS77** [comment]
It's like on WhatsApp -- if you get a message from a number that's not in your contact list, then the number is displayed. Similarly, if a TX from a public key (emoji id) is not in your contact list / doesn't have an alias, you just display the emoji id

**Comment by kukabi** [comment]
@CjS77 Got it, thanks. Do we display pipes in the input field only when the emoji ID is complete (12 emojis), or add 1 after every 4 as it gets typed?

**Comment by talmahaj** [comment]
@kukabi please add the pipe after each 4 as it gets typed, just like when typing phone numbers into a form. Thanks!

**Comment by kukabi** [comment]
@talmahaj alright, can aliases have emojis in them?

**Comment by kukabi** [comment]
...asking this to understand whether I can assume the user is entering an emoji id (thus it should be masked) when the first character input is an emoji.

**Comment by talmahaj** [comment]
> @talmahaj alright, can aliases have emojis in them?

I suppose they could, but we wouldn't need to decide whether to mask unless they enter 4 in a row, right? I think it's safe to assume that if they enter 4 in a row with no other alphanumeric characters that it's an emoji ID.

**Comment by talmahaj** [comment]
@kukabi forgot to tag above, sry

**Comment by kukabi** [comment]
@talmahaj alright, 4 in a row, got it thanks:) I guess it also means that any non-emoji character after 4 emojis breaks the id and "invalid emoji" gets displayed? Or do we wait until 12 characters?

**Comment by talmahaj** [comment]
Yep, showing the error message after 4 sounds good to me!
