### ISSUE TITLE
[Feature] New transaction: Add an amount

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1058]
**User Stories**

> When I’m sending Tari, I want to be able to not only easily enter an amount, but verify who I am sending it to and what fee I will be charged in order to have peace of mind

-----

**UX/UI**

1. Refer to the following group Zeplin screens  -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android.
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5df91ab66b256c1a29fe7153

2. Animation for entering amount: https://vimeo.com/showcase/6606770/video/375491638

3. Animation for available balance exceeded: https://vimeo.com/showcase/6606770/video/377085854

4. Assets should be in Dropbox folder, pls let Karim know if any are missing.

-----

**Open Questions**

N/A

-----

**Acceptance Criteria**

Navigation

1. User should be able to reach this screen from the Recipient screen

Nav Bar

1. Persistent back button should return user to Recipient screen (which should be reset to default with no recipient selected, a la Paypal)
2. Recipient's collapsed Emoji ID or Contact Name should appear at top of nav bar
    1. If user taps collapsed Emoji ID, should expand per zpl.io/amwokBD
        1. When Emoji ID is expanded, user can tap anywhere on the screen to collapse it

Amount

1. Amount should animate in as user types: https://vimeo.com/showcase/6606770/video/375491638
2. Transaction fee should animate in per video above once we have a signal that the user may be done entering the amount, e.g. should appear 1000 milliseconds after last digit tapped
    1. If user has an amount with a transaction fee, and then starts changing the amount, the transaction fee should disappear until the above rule (1000 milliseconds elapsed) is valid again
3. If the user enters enough digits to exceed the left and right padding in zpl.io/bzRrgMl, the font size should get smaller as user types
4. Hint text icon next to transaction fee has not been designed yet, so don't worry about that one yet -- will be in a separate ticket
5. If user enters an amount that exceeds their currently available balance (not including any pending transactions), error message should animate in as follows: https://vimeo.com/showcase/6606770/video/377085854

Other

1. Continue Button should be disabled until amount is >0 AND is an amount that does not exceed the user's available balance (that is, the amount that is available for them to spend at that moment)
2. Delete key removes one digit at a time (the last one)
3. Amount must always be a valid number (that is, cannot have 2+ decimal points)

-----

**Implementation Notes**

N/A

**Comment by CjS77** [comment]
I take it we're using a standard fee rate for MVP.

For interest' sake, fees are calculated as follows:
```
Total Fee (µT) = 1 + (num_inputs  + 4 * num_outputs) * r
```
_r_ is the only user-configurable variable here and has a system-configured minimum

**Comment by CjS77** [comment]
I don't see why we should limit input to 2 d.p. If a user wants to send thousands of a tari, why not let her do that?

**Comment by talmahaj** [comment]
Why would that limit her? Don’t you guys use commas to delimit hundreds place from thousands place? A number can have multiple decimal points in SA?

**Comment by CjS77** [comment]
Maybe I misunderstood your spec:
> Amount must always be a valid number (that is, _cannot have 2+ decimal points_)

If we're allowing more than 1/100 precision, then we're all good.

**Comment by kukabi** [comment]
@CjS77 you mentioned that the emoji id was going to be 25 emojis. It probably won't fit, do we ellipsize? @talmahaj

**Comment by Tas4tari** [comment]
Closing as all corresponding issues have been merged and closed
