### ISSUE TITLE
[Feature] New transaction: Add a note to a transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1059]
**User Stories**

> When I’m sending Tari, I want to be able to indicate what it's for so that my recipient knows the reason, and so that I can easily identify the transaction in the future

-----

**UX/UI**

1. Refer to the following group Zeplin screens  -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android.
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5df9244ae677e717f5908bd7

2. Assets should be in Dropbox folder, pls let Karim know if any are missing.

-----

**Open Questions**

N/A

-----

**Acceptance Criteria**

Navigation

1. User should be able to reach this screen from the Amount screen

Nav Bar

1. Persistent back button should return user to Recipient screen (which should be reset to default with no recipient selected, a la Paypal)
2. Recipient's collapsed Emoji ID or Contact Name should appear at top of nav bar
    1. If user taps collapsed Emoji ID, should expand per zpl.io/amwokBD
        1. When Emoji ID is expanded, user can tap anywhere on the screen to collapse it (without triggering any of the actions underneath)

Input and CTA

1. Keyboard should be open by default with note field in focus
2. As soon as user starts typing, label turns gray per mockup and hint text disappears
3. Limit to 256 chars. No need to indicate that to user, just don't let them type anymore
4. CTA should be disabled whenever input field is empty
5. CTA should animate per timestamp 1:10 in https://vimeo.com/369345180

-----

**Implementation Notes**

N/A

**Comment by CjS77** [comment]
Any reason for limiting the message to 300 chars?

Other limits might include:
* ~270 chars to completely fit message + metadata into a tweet.
* 256 chars (or other power of 2) - simplifies serialisation and DB storage in some cases (mostly historical; not so relevant today)

@philipr-za - Can you confirm that we effectively have no back-end limit to the length of the message (besides the protobuf limit of 4GB) at present?

**Comment by philipr-za** [comment]
> Can you confirm that we effectively have no back-end limit to the length of the message (besides the protobuf limit of 4GB) at present?

Correct. There is a config setting somewhere on our inbound route to define the largest messages we will accept up to the protobuf limit of 4GB.

**Comment by talmahaj** [comment]
Nope, it was totally arbitrary, so feel free to override if either of you have a strong opinion on what it should be. We may add the ability to include photos or gifs in the future in these too.

**Comment by CjS77** [comment]
This isn't consensus critical, so let's make it 256 chars for now, and we can increase in a future release if necessary.

**Comment by kukabi** [comment]
@talmahaj @CjS77 Does the enter key on the keyboard finish text editing & hide keyboard or does it insert a line-break? I.e. do we allow multi-line notes?

**Comment by kukabi** [comment]
@Karim-tari is there an animation between the enabled & disabled states of the CTA?

**Comment by talmahaj** [comment]
> @talmahaj @CjS77 Does the enter key on the keyboard finish text editing & hide keyboard or does it insert a line-break? I.e. do we allow multi-line notes?

Hmmm, I'm not sure! I don't feel strongly, do any of you @CjS77 @kukabi @Karim-tari ? Sorry for the delay on seeing this one.

**Comment by talmahaj** [comment]
> @Karim-tari is there an animation between the enabled & disabled states of the CTA?

I don't think we got to it but a quick fade between the two states would probably look good, we trust your judgment :) We can always refine later if need be.

**Comment by Tas4tari** [comment]
Closing this issue as corresponding IOS and Android tickets have been merged
