### ISSUE TITLE
[Feature] New transaction: Finalize transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1060]
**User Stories**

> After I've finalized my transaction, I want feedback and peace of mind that it went through successfully

-----

**UX/UI**

1. Refer to the following group Zeplin screens  -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android: **[TO ADD]**

2. Animation: **[TO ADD]**

3. Assets should be in Dropbox folder, pls let Karim know if any are missing.

-----

**Open Questions**

N/A

-----

**Acceptance Criteria**

1. After finalizing the transaction note, the user should be prompted to authenticate again per https://github.com/tari-project/tari/issues/993
    1. Edge case handling: If user keeps failing authentication after multiple retries (including fallback from biometric to passcode/pin if relevant), don't worry about a fallback screen for now -- it's an edge case we're not too worried about. You can just nuke the transaction and send them back to the Transactions List screen after a certain number of retries if you want to give them an out and it's not more than a few minutes of work.
2. After authenticating, user should see the following animation and confirmation screen: **[TO ADD]**
3. Display confirmation screen for 2000 milliseconds and then send user back to Transaction List screen
    1. Once the user reaches the list screen again (maybe 500ms after? You can play around with the timing), the pending transaction (and Pending transaction section) should animate in as was spec'd in the transaction list ticket
    2. Once the user reaches the list screen again (maybe 500ms after? You can play around with the timing on this one too), the old available balance should animate as was spec'd in the transaction list ticket until it displays the new available balance

-----

**Implementation Notes**

N/A

**Comment by Jasonvdb** [comment]
@talmahaj how come this was closed?

**Comment by talmahaj** [comment]
@Jasonvdb because I created it as a WIP a bajillion years ago, then completely forgot about it and made a whole 'nother ticket for it when the designs were ready: https://github.com/tari-project/tari/issues/1176

...then I rediscovered this one and closed it as a dupe.
