### ISSUE TITLE
Add parameterized range queries to list requests to Wallet API

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1074]
Set the default to 20 items per page

**Comment by philipr-za** [comment]
This feature should allow a client library to request the list of Transactions from the backend by specifying ranges of indices and time:
- Request total number of TXs
- Request time of oldest Tx
- Request TXs as a range of indices
- Request TXs as a range of time.

**Comment by CjS77** [comment]
No paginating at libwallet
