### ISSUE TITLE
Use Geometric mean for proof of work comparison when looking at reorgs

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#1075]
We will use more than one proof of work which will mean we will have more than one total accumulated difficulty. When comparing two chains with different proof of work done on them, we want to weight the accumulated difficulty so that they count the same so that we dont use favor one above the other one. 

Currently the proposal is to calculate weights based on a certain time window and then use that to compare the forks. 

This is to propose we rather use a geometric mean which is easier to calculate and means we only have to look at the tip to do a comparison. 
[Geometric mean](https://en.wikipedia.org/wiki/Geometric_mean)

**Comment by CjS77** [comment]
I like & support this idea for 2 reasons:

1. It doesn't require state (specifically, looking back at the blockchain history).
2. Geometric mean "autoscales".

**Comment by SWvheerden** [comment]
RFC 0120 needs to be updated with these changes as well
