### ISSUE TITLE
Write benchmark tests for Tari signature code

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#109]
Write some benchmarking tests for
* Private & public key creation
* Signature creation
* Signature verification

**Comment by ricjhill** [comment]
Does this need doing. If so assign it to me please/
I assume you are benchmarking  the time taken to create  N keys and signatures. Is this correct.
How much of it is already implemented. I cant find much in ./tests or ./benches so which tools are preferred?

**Comment by CjS77** [comment]
Hey..
That'd be great.

There are a few benchmarks in crypto/benches/signatures.rs

We've recently switched to using criterion as the bm framework.


Although not "signature" benchmarks per se, we could do with some benches
for the range proof and pedersen commitment code, comparing mul to
batch_mul. And increasing code coverage in unit tests generally.

**Comment by ricjhill** [comment]
thanks.. 
 Im looking at https://criterion.readthedocs.io/en/latest/setup.html#installation   now

**Comment by CjS77** [comment]
Done in #628
