### ISSUE TITLE
Convert Peer Manager to use SQLite rather than LMDB

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1142]
The LMDB backend for the Peer Manager has been the root of some bugs so going forward we feel it should be migrated to Sqlite.

The interface to the backend database is well-defined, so one could write the new backend without affecting any existing code or operations; the choice of backend could potentially even be a configuration option.

@sdbondi and @philipr-za  can help with pointers if need be.

**Comment by stringhandler** [comment]
I think it's actually fine in lmdb, is there still a need for this?
