### ISSUE TITLE
Difficulty adjustment manager has inverted dependency

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1162]
The difficulty adjustment manager consists of 2 nested structs:

`DiffAdjManager` contains a `DiffAdjStorage`. The latter contains a references to a `BlockchainDatabase`, `LinearWeightedMovingAverage`, which in turn references `ConsensusRules`.

There are a few unfortunate results of this arrangement:
* This makes things very hard to test because one cannot write any code for `DiffAdjManager` without creating a database instance.
* The `LinearWeightedMovingAverage` class which is a general mathematical construct, has knowledge about our consensus rules.

Both of these issues can be resolved by flipping the dependency graph.

 The inner difficulty adjustment class (`DiffAdjStorage` right now), should just be able calculate difficulties based on slices preferably, or a simple storage backend (either explicit, or maybe `Arraylike`). It doesn't have any requirements to instantiate (very heavyweight) classes in order to write tests for the basic difficulty adjustment logic.

The outer class will then take a reference to a database, and pass through the data to the inner, simpler diff adj class.

If the same thing is done for LWMA, we can write very small, simple unit tests for these classes, and drop the integration tests, which are 70% setup and boilerplate code.

**Comment by SWvheerden** [comment]
`DiffAdjStorage` Does not calculate difficulties, only `LWMA` does. `LWMA` Calculates difficulties based on slices it receives from `DiffAdjStorage`. 

How the current responsibilities work:
`DiffAdjManager` only providing multi-thread access to `DiffAdjStorage`
`DiffAdjStorage` only queries  `BlockchainDatabase` for values to provide slices to `LinearWeightedMovingAverage`
`LinearWeightedMovingAverage` Only calculates difficulties based on slices of u64's it gets from `DiffAdjStorage`

**Comment by CjS77** [comment]
Fixed in #1124
