### ISSUE TITLE
[Feature] Sending Tari: Adding a recipient by QR Code

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1174]
**User Stories**

> When I want to test out sending a transaction to someone I’m physically with at the time, I want to be able to quickly get their Emoji ID without them having to copy it and manually send it to my phone for me to have to copy again.

-----

**UX/UI**

1. Refer to the following Zeplin screen  -- it's in 1x for iOS so just convert 1:1 from pt to dp for Android: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e1892ca7c824ea796c48ae9

-----

**Acceptance Criteria**

- When the user is on the Add Recipient screen, they can tap on or around the purple QR code icon to pop open the scanner
- Scanner should slide up from bottom of screen
- The scanner should be customized to appear like the design
- User should be able to hit X icon on top left corner to close scanner (scanner should slide back down out of view) and return to Recipient page 
- The QR code will be a JSON string, as described in #1179

**Comment by CjS77** [comment]
The QR code will be a JSON string, as described in #1179

**Comment by talmahaj** [comment]
> The QR code will be a JSON string, as described in #1179

Edited ticket to add, thx!
