### ISSUE TITLE
[Feature] Sending Tari: Transaction fee tooltip modal

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1175]
**User Stories**

> When I see that a transaction fee is being added, I want to know what that means and whether it's justified

-----

**UX/UI**

1. Refer to the following group of Zeplin screens  -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android.

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e1894621bdb03abd5cda76d

-----

**Acceptance Criteria**

User Flow

- Whether when creating a transaction, or viewing the Detail screen of an existing transaction: when a user taps anywhere on the transaction fee (whether the amount of the fee, the label below, or the hint text), the background should darken and the informational modal should appear.
- Tapping Close or anywhere outside the modal should close the modal

**Comment by CjS77** [comment]
What do we want to put in that modal for MVP? A generic message?

**Comment by talmahaj** [comment]
@CjS77 I'm still waiting on approval on the copy.

Re: changing the fee we pay, I think we'd want to consider the UX implications first given that that paradigm doesn't exist outside of crypto
