### ISSUE TITLE
[Feature] Sending Tari: Finalizing a transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1176]
@talmahaj commented on [Fri Jan 10 2020](https://github.com/tari-project/wallet-ios/issues/91)

**User Stories**

> When I am done sending someone Tari, I want feedback that it's been successfully sent so that I can have peace of mind

-----

**UX/UI**

Animation: https://www.dropbox.com/s/cjvba184c55shw8/Sending-Tari.mp4?dl=0

Design Specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e189aff34ae967eceef28b0

-----

**Acceptance Criteria**

Note that edge case handling is out of scope of this ticket. Separate tickets will be made for those.

- After a user slides to send from the Add a Note screen, they should see the animation with the amount of Tari sent
- After the animation, they should be sent to the transactions list screen, at which point they should be able to see the new pending transaction animate into the transaction list
- Use copy from Zeplin specs rather than from video

**Comment by CjS77** [comment]
I don't particularly like the full-screen interstitial here. When you send a text message on chat apps, you don't get your UI taken over by a confirmation.

The ack from the receiver will usually happen very quickly (usually faster than the animation), so I favour a more subtle confirmation, perhaps just updating the status in the tx list. As presented we're slowing the user experience down for no real reason.

Furthermore, what happens when the receiver is offline (I know edge cases aren't handled here, but it's very pertinent)? Does the UI sit with the animation spinning forever? I'd guess not. It would time out and then display pending in the TX list, right? So the animation is then purely cosmetic and IMHO detracts from a snappy UX.

**Comment by talmahaj** [comment]
@Karim-tari see Cayle's comment above.

**Comment by talmahaj** [comment]
@CjS77

I can definitely understand why this doesn't feel snappy enough for you, and I definitely think there are a few quick wins that can address that particular symptom, but I think there are some important differences between our app and a chat app that defend the use of an interstitial or other prominent feedback mechanism.

Here are my thoughts:

1. It feels slow because the copy doesn't change at all in the video. In the specs, you'll see that it's divided into two different feedback steps, "sending" and "sent," which are the two pieces of feedback you'll see universally in *every* payment app whether or not they use full screen interstitials or not to communicate each of those.

 I'm not saying that every app does it, but full-screen interstitials are the norm on many popular payment apps (as are often short artificial delays to prevent too-jarring transitions). I see where you're coming from, and I def think that if your concern is it not feeling snappy enough we can for sure address that, but there are tradeoffs either way because prominent feedback when it comes to sensitive stuff like sending money makes it easier (and more obvious) to get peace of mind as a user rather than searching for a subtle indicator. I'm also not sure messaging and chat apps are an appropriate comparison due to the wildly different feedback frequencies; could be every few seconds for chat vs. every few hours or days at most for payments, so it would make sense that one would be subtle and completely out of your way whereas the other would err on the side of giving a user more explicit feedback. To make it more tangible: if the status in the transaction list just updated to "Pending" and I was given no other feedback, how would I know for sure that the other person knows I've sent them money? How would I know that Pending is a state that comes *after* money is sent and a recipient notified, rather than a loading state *before* that happens? "Pending" isn't a status that you're already familiar with in payment apps so the user doesn't have a mental model in place yet to know where it is in the sequence. (And as for the edge case, the "sending..." part of the animation would appear and then the error so it's less jarring for the user than hit-button-boom-error).

@Karim-tari how do you think we can address @CjS77 's concerns and still provide the user with adequate feedback? Maybe we can try speeding up what we currently have vs. something more subtle like either a confirmation modal or banner on the list screen that disappears after a few seconds if the user doesn't close it out?

**Comment by talmahaj** [comment]
@CjS77

I can definitely understand why this doesn't feel snappy enough for you, and I think there are a few quick wins that can address that particular symptom, but I think there are some important differences between our app and a chat app that defend the use of an interstitial or other prominent feedback mechanism.

I'll share a few thoughts and suggestions:

1. It feels even slower in the video right now than it should IRL, because the copy doesn't change at all in the video right now. In the specs, you'll see that it's divided into two different feedback steps, "sending" and "sent," which are the two pieces of feedback you'll see universally in every payment app. Whether they use progress bars or full screen interstitials or something more subtle to communicate each of those, they always show both steps separately with enough time for the user to process, even if it means a slight artificial delay (because otherwise it's very jarring).

I'm not saying that every app does it, but full-screen interstitials are the norm on many popular payment apps (as are often short artificial delays to prevent too-jarring transitions). I see where you're coming from, and I def think that if your concern is it not feeling snappy enough we can for sure address that, but there are tradeoffs either way because prominent feedback when it comes to sensitive stuff like sending money makes it easier (and more obvious) to get peace of mind as a user rather than searching for a subtle indicator. I'm also not sure messaging and chat apps are an appropriate comparison due to the wildly different feedback frequencies; could be every few seconds for chat vs. every few hours or days at most for payments, so it would make sense that one would be subtle and completely out of your way whereas the other would err on the side of giving a user more explicit feedback. To make it more tangible: if the status in the transaction list just updated to "Pending" and I was given no other feedback, how would I know for sure that the other person knows I've sent them money? How would I know that Pending is a state that comes after money is sent and a recipient notified, rather than a loading state before that happens? "Pending" isn't a status that you're already familiar with in payment apps so the user doesn't have a mental model in place yet to know where it is in the sequence. (And as for the edge case, the "sending..." part of the animation would appear and then the error so it's less jarring for the user than hit-button-boom-error).

@Karim-tari how do you think we can address @CjS77 's concerns and still provide the user with adequate feedback? Maybe we can try speeding up what we currently have vs. something more subtle like either a confirmation modal or banner on the list screen that disappears after a few seconds if the user doesn't close it out?

**Comment by talmahaj** [comment]
@CjS77

I can definitely understand why this doesn't feel snappy enough for you, and I think there are a few quick wins that can address that particular symptom, but I think there are some important differences between our app and a chat app that defend the use of an interstitial or other prominent feedback mechanism.

I'll share a few thoughts and suggestions:

1. I'm not saying that every app does it, nor that *we* have to do it, but full-screen interstitials are the norm on many popular payment apps (as are often short artificial delays to prevent too-jarring transitions). 

See example from Paypal.
![IMG_2224 2](https://user-images.githubusercontent.com/1817246/72432366-b7908c80-374b-11ea-96a0-a6234dfca145.PNG)

2. Universal patterns for transaction feedback:
It feels even slower in the video right now than it should IRL, because the copy doesn't change at all in the video right now. In the specs, you'll see that it's divided into two different feedback steps, "sending" and "sent," which are the two pieces of feedback you'll see universally in every payment app. Whether they use progress bars or full screen interstitials or something more subtle to communicate each of those, they always show both steps separately with enough time for the user to process, even if it means a slight artificial delay (because otherwise it's very jarring).

Here's an example from Venmo of a subtle "in progress" state (blue loading bar paired with green CTA button copy changing from "Pay" to "Paying...":
![IMG_2226](https://user-images.githubusercontent.com/1817246/72432379-bf503100-374b-11ea-925d-1f02e626f58c.PNG)

3. Mental model gap --> gotta give 'em a map
"Pending" isn't a status that you're already familiar with if you've used traditional online payment apps, so in our brave new world the user doesn't have a mental model in place yet to know where the heck that is in the order of operations.  So we have to tell them.
That is, without a map and a "you are here" sign (figuratively), you might very well think that pending means "pending being sent to recipient," and that the recipient doesn't know about it yet, because you have no way of knowing either way that this isn't actually what's going on:
Hit Send > Pending > Recipient is Notified

4. The less frequent, the less familiar
I can see why you drew this comparison, but I'm not sure messaging and chat apps are an appropriate comparison due to the wildly different feedback frequencies; could be every few seconds for chat vs. every few hours or days at most for payments, so it would make sense that one would be subtle and completely out of your way, whereas the other would err on the side of giving a user more explicit feedback on something they rarely do because the peace-of-mind-to-annoyance balance is completely different at that frequency.

4. Peace of mind and snappiness can be at odds
Deliberate, slower feedback at each step of the way when it comes to sensitive stuff like sending money makes it easier (and more obvious) to get peace of mind as a user, rather than skipping it and reflect actual system speed, which may lead nervous users to have to then search for subtle indicators they aren't already familiar with from staring at all day every day a la WhatsApp (even if they do already know what Pending means). Some more examples of artificial delay UX in case you're curious: https://www.fastcompany.com/3061519/the-ux-secret-that-will-ruin-apps-for-you

5. As for the edge case, in the flow we already have spec'd out, I'd envisioned that the "sending..." part of the animation would appear, and then the error instead of the "sent!" step, so it's less jarring for the user than hit-send-error. But that transition is UI element-agnostic; the Sending state to Error state sequence would apply even if we didn't do a full page interstitial and did what Venmo does instead

@Karim-tari when you get a few min free, can you do a version of the video with the Sending --> Sent text change and each feedback step slightly sped up to see if it makes a difference for @CjS77? Any ideas of other quick things we can try out to address his feedback without revisiting the whole thing altogether? We could potentially bring the Sending step back into the prior screen a la Venmo...?

**Comment by Karim-tari** [comment]
@talmahaj @CjS77 Yeah, we can explore having that confirmation on the feed screen instead of the interstitial screen. Though, I do agree with Tal that at this stage it's pretty different than a chat app so the interstitial screen IMO helps give the user clear confirmation that the payment was sent, even if it's just 2-3 seconds. If/when we have chat in the app and a user sends Tari to another then there should definitely not be any interstitial screen.

**Comment by CjS77** [comment]
Ok, I'm happy with the justifications.
