### ISSUE TITLE
[Case Handling] Transaction List Screen: Displaying available balance when sent transaction pending

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1178]
After a user sends money through any payment app, they expect their prior balance minus the amount they sent to be their newly available balance. E.g., if I had $10, and I sent you $2, I’d then have $8 left, and that’s what I’d expect to see as my new balance.

However, Tari works a bit differently. Even if you only send someone 2 Tari including fees, our protocol temporarily ties up some of your other Tari until the transaction is mined (e.g. perhaps it ties up another 1.5 Tari), which means you don’t actually have 8 Tari to spend until after the transaction is complete.

See a more thorough explanation by Philip and Cayle here: https://github.com/tari-project/tari/issues/1003

That said, given how infrequent we expect transactions to be at first, and because of the mining time will only be on average 2 min, we anticipate very few of our users will try to send more Tari than possible while their prior sent transaction is still being mined, and so we don't need to expose the above (very confusing) behavior to our users in the app. We can show them what they expect, and then manage by exception for the few users who do manage to trip the wire.

**Acceptance Criteria**

- If a user has at least 1 pending transaction as a sender, the amount of Tari that appears at the top of their transaction list screen under “available balance” should equal: (their previous available balance) minus (the amount of Tari across all pending transactions). 
- If, on the Select Amount screen when sending Tari, the user enters an amount that exceeds their true available balance AND does *not* exceed their displayed available balance:
    - do not show the standard “balance exceeded” error message as seen in https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5df9171bb877981601d6a95c
    - wait until the user attempts to continue to the next step in the the flow, and then display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e189f34d210f57e4b0050ac
        - The link in the design that reads "Close" should actually read "Learn More" and pop open a browser window with a URL that is still TBD -- feel free to use http://tari.com as a placeholder. It will eventually link to relevant FAQ content around this edge case.
        - To close the modal, use can still tap anywhere outside of it

**Comment by CjS77** [comment]
Awesome idea. Building on this, can I suggest that the modal links to a more detailed explanation on the Tari.com FAQ?

**Comment by talmahaj** [comment]
> Awesome idea. Building on this, can I suggest that the modal links to a more detailed explanation on the Tari.com FAQ?

Absolutely, great idea. Updated ticket to include that.
