### ISSUE TITLE
[Feature] New user - wallet creation animated sequence

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1215]
**User Story**

> When I am creating my wallet and learning about Emoji ID, I want to receive feedback and guidance at each step in the process to reduce uncertainty, and so I don't experience any startling or unexpected transitions

-----

**Acceptance Criteria**

1. New user can view the part of the sequence where they are introduced to their newly created wallet, and to the concept of an Emoji ID 00:30 - 00:50  https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 (after seeing the initial on boarding sequence with the black background from ticket #991)
2. Animation sequence is connected with that in ticket #991 such that user can go through the flow from video timestamps 00:00-00:50 seamlessly
3.  Timing for animations and transitions is the same as in video (even if artificial delays required)
4. Android uses emojis native to the platform
 
-----

**Implementation Notes**

This part of the sequence follows the initial onboarding sequence (the part with the black background): https://github.com/tari-project/tari/issues/991 
None of these screens have been built yet.

-----

**Assets**

Animation reference: https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0
Timestamp 00:30 through 00:50 (first white screen appears through screen with animated nerd emoji appearing)

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e2548746e3cdd2b733ba9e7

Assets should be in the Dropbox folder: https://www.dropbox.com/sh/2770a3fxx6ikll1/AADDByhZ8tyXlVhmJFjJmLwaa?dl=0

----

**Open Questions**

How should @Karim-tari export the different animations? Lottie file for each? Karim, pls also ensure you generate the Android version of all these assets and animations.

**Comment by CjS77** [comment]
Looks pretty standard.

For consistency, shouldn't the spinning ring at 0:33 - 0:39 be a spinning Tari logo instead?

**Comment by talmahaj** [comment]
> Looks pretty standard.
> 
> For consistency, shouldn't the spinning ring at 0:33 - 0:39 be a spinning Tari logo instead?

@Karim-tari thoughts?

**Comment by CjS77** [comment]
Going through this again, the "Awesome, Now create your Emoji ID" is unnecessary. We can go from the check mark after the wallet has been created straight to the Emoji ID animation. One less click (don't you lose 30% of users per click?) and we don't lose the informational aspect of the FUE onboarding flow.

@talmahaj @Karim-tari thoughts?

**Comment by talmahaj** [comment]
We actually added it on purpose to give the user some more feedback points in the narrative, but this is something we could definitely split test... if we could split test things :( let me look into it some more...
