### ISSUE TITLE
[Feature] New user - emoji ID creation animated sequence

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1216]
**User Story**

> When I am creating an Emoji ID, I want to understand what it is and how I use it

-----

**Acceptance Criteria**

1. New user sees the emoji ID creation animation, and then the screen that tells them their emoji ID per 00:55 - 00:59 of
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 
2. Animation sequence is connected with that in [ticket #1215](https://github.com/tari-project/tari/issues/1215) such that user can go through the flow from video timestamps 00:00- 00:59 seamlessly
3.  Timing for animations and transitions is the same as in video (even if artificial delays required)
4. Android uses emojis native to the platform
 
-----

**Implementation Notes**

Reuse button styles, including loading state, from https://github.com/tari-project/tari/issues/990

None of these screens have been built yet.

-----

**Assets**

Animation reference: https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0
Timestamp 00:55 - 00:59  (everything that happens after user hits the CTA to create their emoji ID, until their emoji ID appears with the Continue button at the bottom)

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e254887bb66d7540a24ff25

Assets should be in the Dropbox folder.

----

**Open Questions**

How should @Karim-tari export the different animations? Lottie file for each? Karim, pls also ensure you generate the Android version of all these assets and animations.

@Karim-tari How should this look given our Emoji ID will likely end up having 13 emojis instead of 12?

**Comment by Jasonvdb** [comment]
@talmahaj with that spinning circle of emojis, are those ones generic? So only when we display the "This is your Emoji ID" do we show the user's actual emojis? If the spinning circle of emojis is the same for each user then lottie would be preferable. If it's user specific then the animation will need to be created custom per platform, which could be a fair amount of work.

**Comment by talmahaj** [comment]
Let’s go with same for each user, lord have mercy on us otherwise given our timeline 😂😂😂

**Comment by Jasonvdb** [comment]
Awesome, was really hoping you would say that. 😄
Then if @Karim-tari could just do the lottie file we good. 
Not sure if it's worth it or what work is involved but we could use a different animation for Android style emojis if needed.

**Comment by Karim-tari** [comment]
@Jasonvdb I'm starting to add the Lottie exports here https://www.dropbox.com/sh/1uib8xguxf2mz8b/AAAu2CJgmeai26fjUO4b-nqva?dl=0 let me know if they need any tweaking in any way.

**Comment by talmahaj** [comment]
> Awesome, was really hoping you would say that. 😄
> Then if @Karim-tari could just do the lottie file we good.
> Not sure if it's worth it or what work is involved but we could use a different animation for Android style emojis if needed.

We will indeed need Android specific ones too, @Karim-tari I know you're already aware of that
