### ISSUE TITLE
[Feature] New user - Local authentication prompt screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1217]
**User Story**

> When I am prompted to enable local authentication, I want to understand why it's important, and I want it to be immediately clear that it's just reusing my lock screen option rather than asking me to create an additional new pin, passcode, etc. just for that app

-----

**Acceptance Criteria**

1. The screen that explains why they should protect their wallet with local authentication should animate in per the video (around 1:07): https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 
2. Animation sequence is stitched together with the [prior step](https://github.com/tari-project/tari/issues/1216) such that user can go through the flow from first app launch to local auth prompt seamlessly
3. Hitting “Use [auth method]” pops the default native permissions modals for users to enable local authentication on iOS and Android, which was already partially built as part of [this ticket](https://github.com/tari-project/tari/issues/993)
4. Determine which image and copy to show using the logic already built as part of [that same ticket](https://github.com/tari-project/tari/issues/993)
    1. iOS
        1. “Face ID” with image of face - iOS only, Face ID enabled
        2. “Touch ID” with image of fingerprint - iOS only, Touch ID enabled
    2. Android
        1. “Face Unlock” with image of face - Android only, Face unlock enabled
        2. “Fingerprint” or “Swipe” with image of fingerprint - Android only, fingerprint enabled
        3. “your device Pattern” or “your device PIN” or “your device Password” with image of keypad - Android only (note addition of “your device” in copy for these, to make it explicit for user that it’s the same as their lock screen)
5. User should NOT be able to skip local authentication, despite “Skip” button that appears in the designs. (This button should not be built at this time).
 
-----

**Implementation Notes**

Reuse button styles, including loading state, from prior tickets like https://github.com/tari-project/tari/issues/990

This part of the flow was already partially built as part of a prior local authentication ticket, and needs to be completed for new users only: [this ticket, also referenced above](https://github.com/tari-project/tari/issues/993)

(Final design and behavior for *existing* users will be spec’d in separate ticket)

-----

**Assets**

Animation reference: https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 (around 1:07)

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e2548927b386169804234a7

Assets should be in the Dropbox folder.

----

**Open Questions**

Kutsal, are there any lock screen options that I’m missing for Android? What if a user uses a 3rd party lock screen? Do you think we should just have the language say “lock screen” in that case with some generic icon?

**Comment by Tas4tari** [comment]
Closing issue
