### ISSUE TITLE
Implement eID support

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1222]
In addition to `as_hex()` and `as_bytes()`, public keys should support producing an emoji ID as a valid UTF-8 string.

The emoji id spec is presented [TBD](https://).

**Comment by StriderDM** [comment]
#1297

**Comment by CjS77** [comment]
Spec is here: #1328

**Comment by CjS77** [comment]
Checksums added: #1322

**Comment by CjS77** [comment]
Node IDs are compatible with spec: #1331

**Comment by CjS77** [comment]
Going to close this for now, until the eID spec is finalised. Changing things form the Rust side is elementary
