### ISSUE TITLE
Wallet FFI - eID support

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1223]
The FFI should support these functions:

1. Given a public key in hexadecimal format, return the equivalent emoji id string:
`fn emoji_from_hex(hex: *const c_char, error_out: *mut c_int) -> *mut c_char` 
1. Given a emojiID, return the equivalent hex string:
`fn hex_from_emoji(hex: *const c_char, error_out: *mut c_int) -> *mut c_char` (or similar)
1. Given a emojiID, return the equivalent public key:
`fn public_key_from_emoji(emoji: *const c_char, error_out: *mut c_int) -> *mut TariPublicKey`

The eID support from #1222 should be used

**Comment by StriderDM** [comment]
#1297
