### ISSUE TITLE
[Feature] New user - onboarding flow faucet transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1224]
**User Story**

> As soon as I am done with the onboarding sequence, I want to immediately be sent some Tari and be encouraged to send some right back, so I can try out transacting without the intimidating cognitive burden of figuring out who to transact with and/or how  to get Testnet Tari

---

**Acceptance Criteria**

1. Around three (3) seconds after user swipes out of Welcome Screen in [this ticket](https://github.com/tari-project/tari/issues/1219), they should receive an actual transaction from the faucet server
2. User should already have the faucet server’s Emoji ID stored with contact name “Tari Bot” so that it appears with that name in the transaction list
3. Right after the transaction happens, before the user is able to tap on it in the list, [this modal](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e25462975bd196f41df09d0) should appear to encourage user to send back some Tari.
    - Hitting the "Send Tari" button should take the user to the Add Recipient screen where they can select their existing contact, Tari Bot, to send money to (or scan someone else's QR code or paste another emoji ID, if they wish)
    - Tapping "I'll try it later" should close the modal and allow the user to see the transaction list in its normal state
4. This transaction will otherwise behave like any normal one (e.g. if user no longer has app in foreground, they get a push notification)

---

**Implementation Notes/Open Questions**

- The first 4000 wallets created in the app will have their initial faucet transaction pre-mined as part of the genesis block, so it would skip all the transaction states we currently map to “pending” in the UI and be completed right away. @philipr-za has made a good point that not showing the transaction as "pending" at all could be misleading, so is there any easy way to create a small delay so that it shows as pending for 3-4 seconds?

- How many Tari should we send to each user? A nice tidy number like 5.00 or 10.00 would be nice. 

---

**Assets**

User Flow & Design Specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e2548a4d78e4558e45a9214

**Comment by CjS77** [comment]
## Notes

* We can send any amount we want to the user. There's no limit
* We should mention that this is _TestNet_ Tari; 
* that it has no value;
* and that these funds can disappear if we reset the testnet; 
* and that you don't keep the Tari when we flip to mainnet.
* And you won't get free Tari on mainnet

**Comment by CjS77** [comment]
To be clear; if the user elects to send Tari via the model prompt, then the usual transaction sending flow is used. i.e. This is not a mock/tutorial, we'll actually send the testnet Tari on the blockchain (and we'll have to have a little bot wallet online to receive it)

**Comment by CjS77** [comment]
**Update:**

The faucet flow is now as follows:

* There are 4,000 immediately spendable UTXOs in the testnet genesis block for the purposes of onboarding users.
* We need to query the wallet service for:
  * Our pubkey, `my_pubkey`
  * and a public_nonce and signature from `signMessage("Hello Tari from" + my_pubkey)` 
* we make that POST call, using our pubkey: `https://faucet.tari.com/free_tari/allocate/{my_pubkey}`
* with body `{"public_nonce":"{nonce}","signature":"{signature}"}`
* When you get a 200 response from the faucet, e.g. : `{
    "key": "c3413...d10fb4079779c30b80e",
    "value": "5030000000",
    "return_wallet_id": "0123456789ABCDEFFEDCBA98765432100123456789ABCDEFFEDCBA98765432100123456789ABCDEFFEDCBA9876543210"
}`,
you must add "Tari Bot" to your contacts using the `return_wallet_id` value
* And then call `importUTXO(value, "From Tari bot / whatever", private_key, return_wallet_id)`
