### ISSUE TITLE
[Feature] Notify user when they are sent Tari

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1226]
**User Story**

> When someone sends me Tari, I want to be sure I am made aware whether or not I have the app open in the foreground

-----

**Acceptance Criteria**

1. If app is open in foreground AND user is viewing transactions list screen: new transaction should appear in Pending section in transactions list
2. If app is open in foreground AND user is NOT viewing transactions list screen: Display an [in-app notification](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e268272d1d3982ab84b185e)
    1. Tapping in-app notification opens corresponding transaction detail screen
3. If app is NOT open in foreground: display a push notification with payload of heading "You've got Tari!" and copy "Someone just sent you some Testnet Tari"

-----

**Assets**

Design specs for in-app notification (@Karim-tari how does this animate in/out?): https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e268272d1d3982ab84b185e

-----

**Implementation details**

[Add any details needed about waking up client to receive notif]

**Comment by CjS77** [comment]
By in-app notification, do you mean a custom notification view in our app, rather than using the OS's notification machinery; or are you referring to a [Heads up notification](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up) (for e.g. Android?)

**Comment by talmahaj** [comment]
> By in-app notification, do you mean a custom notification view in our app, rather than using the OS's notification machinery; or are you referring to a [Heads up notification](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up) (for e.g. Android?)

iOS does not allow you to use the push notification view when your app is already open in the foreground, so yes, this would be a custom view in both platforms... unless @kukabi Android allows/encourages the standard push view or heads up notif while app is already in foreground?

**Comment by kukabi** [comment]
I think we can do heads-up notifications on Android, but I don't know at the moment how it behaves with a foregrounded/backgrounded app, so I'll clarify this later on after a bit of experimentation. For now I will make a rough estimation for this issue. @CjS77 @talmahaj

**Comment by Tas4tari** [comment]
@kukabi @talmahaj Closing this as the related Android and IOS tickets have been closed
