### ISSUE TITLE
[Feature] Edge case handling: persistent notifications when app unusable

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1227]
**User Story**

> When I can't use the app, I want an informative, persistent notification telling me why and what to do next

---

**Acceptance Criteria**

1. If the edge cases in either [row 2, 4, or 5 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) are true, display persistent modal with [the following copy](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e26abe8de3d8994256095e8)
2. If the user has inadequate or no connectivity per [row 15 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) display persistent modal with [the following copy](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e26abe911211a5362ade578)
3. User cannot get rid of a persistent modal by tapping anywhere on the screen; it goes away automatically in real-time once the relevant issue is resolved

---

**Design**

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e26ac2d8a5b6752fe7a0377

-----

**Implementation Notes**

- Note that modal is very similar to our standard modal, except shorter due to no button AND use cannot get rid of it by tapping on the screen

- More details on the wallet edge cases can be found here: https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0

**Comment by CjS77** [comment]
@talmahaj - This has been implemented; albeit slightly differently to the description. Happy to close?

**Comment by Tas4tari** [comment]
Closing this as the corresponding component tickets have been closed
cc @talmahaj
