### ISSUE TITLE
Investigate implementing dandelion

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#1278]
We should employ something like dandelion with with our transactions and do cut through and transaction aggregation with them. This will greatly increase privacy in tari.

**Comment by SWvheerden** [comment]
This is also linked to #1277

**Comment by CjS77** [comment]
I would argue that Tor is an alternative to, and superior to, Dandelion for IP obfuscation; obviously Tor doesn't let us add things like decoy outputs and the associated cut-through, but dandelion AND Tor is probably less than optimal; but happy to discuss.

**Comment by SWvheerden** [comment]
Dandelion and Tor does different things. 
Tor obfuscates the IP, 
Dandelion obfuscates the UTXO. 

They should not influence each other at all.
