### ISSUE TITLE
[Feature] Matomo analytics for Mobile

### ISSUE THREAD

**Issue by lelandlee** [tari-project/tari#1298]
**User Story**

>Whenever a user takes an action on the mobile app, we want to understand what they are doing and if there are any 

---

**Acceptance Criteria**

Partial integration just to get page view tracking. For full event tracking will come later.

---
**Implementation details**
For v1 pass through let's look exclusively at page view ([iOS](https://github.com/tari-project/tari/issues/1298)) + [Android](https://github.com/matomo-org/matomo-sdk-android/wiki/Getting-started)
Because there is no login mechanism, every time a new wallet is created, create a [new user id](https://matomo.org/docs/user-id/)

**Comment by CjS77** [comment]
For privacy, use a hash of the device as the user ID instead of any actual identifiable information.

In fact, it should be standard practice to  hash any identifiable  info to anonymise it where necessary.
