### ISSUE TITLE
Update Wallet to use NodeIDs instead of PublicKeys for Contacts

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1312]
Currently the Wallet uses CommsPublicKeys for its Contacts and the send_transaction(...) function. However for the EmojiID we want to use a 128-bit key/address so the proposal is to instead use a 128-bit NodeID for contacts and the initial send_transaction(...) function.

To do:
* [ ] Update Contact Service to use NodeID instead of PublicKey
* [ ] Update the Wallet's base node peer storage to use NodeID instead of PublicKey
* [ ] On Add New Contact send Ping to contact and then wait with a timeout for the Pong reply. On timeout we must either send a follow up ping OR create a callback to the frontend to report we cannot find the contact
* [ ] Update the `send_transaction(...)` function to use a NodeID rather than a CommsPublicKey
* [ ] Update the sign and verify message to request the Comms Public and Private keys from the PeerManager using the NodeID and handling the case that the Discovery has not succeeded.

**Comment by philipr-za** [comment]
@CjS77 For MVP when we timeout on a Pong should we just send it again rather than inform the frontend of the issue because I think there are no designs to display that data on the frontend?

**Comment by philipr-za** [comment]
For MVP if a Pong times out just send a new Ping until the contact replies with a Pong

**Comment by CjS77** [comment]
@talmahaj I think we should add an "off- on-lnie" icon next to recipient names in pending transaction lists. Perhaps fast-follow after MVP

**Comment by StriderDM** [comment]
Closing issue, was discovered that this will break privacy when peer discovery occurs.
