### ISSUE TITLE
Update Emoji ID implementations to be for NodeIDs rather than Public Keys

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1313]
The initial imlementation of the emoji ID was to treat it as a representation of a Comms Public Key. However we have moved to wallet contacts using NodeID's for communication.

Update the EmojiID implementation and the functionality that uses it to to reflect a NodeID.

**Comment by StriderDM** [comment]
Closing issue, was discovered that this will break privacy when peer discovery occurs.
