### ISSUE TITLE
Base node not shutting down

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#1327]
When the exit signal is given by a user, the basenode does not shutdown. Miner and UI does. 
Pressing ctrl-c again, closes all

**Comment by CjS77** [comment]
It's working now; however all threads must finish before gracefully closing down, so sometimes this takes a few seconds.

**Comment by CjS77** [comment]
That said, polling on BaseNodeStateMachine could be done more frequently

**Comment by CjS77** [comment]
That's a good suggestion

**Comment by stringhandler** [comment]
Closing due to staleness
