### ISSUE TITLE
Emoji Id clipboard and deep link format

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1333]
# Overview

UPDATE: The current proposal for emoji IDs (Mar 12, 2020) is as follows:

* An alphabet of 256 emoji (8 bits / emoji). 
* This makes a 256-bit pubkey 32 emoji long.
* And a single checksum emoji, giving us 33 characters for an emoji ID

## Copying and pasting

* Copying the id to the clipboard (by whatever UI means) actually copies the deep URI to the clipboard (format below).
* Pasting an emoji Id into an emoji ID field should accept a naked emoji string of 33 characters. The string must be validated in this case and the user warned that the emoji OD is invalid.
* Pasting an emoji Id into an emoji ID field should also accept a deep link URL and strip the emoji ID from the link. The emoji ID must be validated.
* When displaying the QR code from "My Profile", the deep link url is encoded in the QR code.

### Behaviour

The app will register the URI and so will be able to open the app from anywhere, for example, scanning a QR code from a different scanning app, or clicking on a link in Whatsapp or the phone's browser.

### Edge cases
If a deep link is activated, but the user hasn't created a wallet yet, the user will first be led through the FUE onboarding; and then taken to the Send Tari flow using the URI's emoji id as the recipient. The "Send to Tari Bot" prompt can be skipped.

Post MVP, it would be more intuitive to take the user to the "Add to Contacts" flow rather than the Send Tari flow

## Deep URI format

Currently, the link is of the form:
<s>`tari://[network]/[pubkey-64char hex]?emoji_id=[emoji_id-12char_string]`</s>
Update: 
`tari://[network]/eid/[emoji_id-33char_string]`

In future, we may support additional query parameters, e.g.
`tari://[network]/eid/[emoji_id-33char_string]?alias=Bob`

`[network]` is one of:
* mainnet
* rincewind (testnet 1)

*Note:* There's a proposal to implement "Vanity IDs" in the future, which would allow users to register a shorter emoji ID on the blockchain to identify themselves on the network (similar to a DNS). We can differentiate between the types with the path, so someone might link to 
`tari://mainnet/vid/🍷🍷🍷`  which would resolve to their pubkey once a base node looked it up for us.

Deep links can also accept hex codes:

`tari://[network]/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a`

## Example 
The following URIs are equivalent
```
tari://rincewind/eid/🖖🥴😍🙃💦🤘🤜👁🙃🙌😱🖐🙀🤳🖖👍✊🐈☂💀👚😶🤟😳👢😘😺🙌🎩🤬🐼😎🥺

tari://rincewind/pubkey/70350e09c474809209824c6e6888707b7dd09959aa227343b5106382b856f73a`
```

<a rel='nofollow' href='https://www.qr-code-generator.com/
            ' border='0' style='cursor:default'><img src='https://chart.googleapis.com/chart?cht=qr&chl=tari%3A%2F%2Ftestnet%2Feid%2F%F0%9F%96%96%F0%9F%A5%B4%F0%9F%98%8D%F0%9F%99%83%F0%9F%92%A6%F0%9F%A4%98%F0%9F%A4%9C%F0%9F%91%81%F0%9F%99%83%F0%9F%99%8C%F0%9F%98%B1%F0%9F%96%90%F0%9F%99%80%F0%9F%A4%B3%F0%9F%96%96%F0%9F%91%8D%E2%9C%8A%F0%9F%90%88%E2%98%82%F0%9F%92%80%F0%9F%91%9A%F0%9F%98%B6%F0%9F%A4%9F%F0%9F%98%B3%F0%9F%91%A2%F0%9F%98%98%F0%9F%98%BA%F0%9F%99%8C%F0%9F%8E%A9%F0%9F%A4%AC%F0%9F%90%BC%F0%9F%98%8E%F0%9F%A5%BA&chs=180x180&choe=UTF-8&chld=L|2' alt=''></a>

**Comment by talmahaj** [comment]
@CjS77 Assuming we should close this for now, right?

**Comment by CjS77** [comment]
Emoji format has been updated
