### ISSUE TITLE
Build basenode in Ubuntu from scratch with source

### ISSUE THREAD

**Issue by leet4tari** [tari-project/tari#1408]
Notes on what is needed to do a source install on Ubuntu 18.04  
  
Install base OS packages  
```
sudo apt-get -y install openssl libssl-dev pkg-config libsqlite3-dev clang git cmake libc++-dev libc++abi-dev
```
Install rust and bits using defaults
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
Don't forget to add ```cargo``` too your path
```
export PATH="$HOME/.cargo/bin:$PATH"
```
In your folder of choice, clone the Tari repo
```
git clone https://github.com/tari-project/tari.git
```
Grab a cup of coffee and begin the Tair build
```
cd tari
cargo build --release
```
Successful build should output something as follows
```
   Compiling tari_wallet v0.0.9 (/home/vagrant/src/tari/base_layer/wallet)
   Compiling test_faucet v0.0.1 (/home/vagrant/src/tari/applications/test_faucet)
   Compiling tari_wallet_ffi v0.0.9 (/home/vagrant/src/tari/base_layer/wallet_ffi)
   Compiling tari_base_node v0.0.9 (/home/vagrant/src/tari/applications/tari_base_node)
    Finished release [optimized] target(s) in 2m 24s
```

**Comment by CjS77** [comment]
At the "In your folder of choice, clone the Tari repo" step, if you really just want the executable and aren't interested in the source code, at this point

`cargo install tari_base_node`

should work and put the executable in `~/.cargo/bin` which, being in your path already, will let you simply run `tari_base_node`
