### ISSUE TITLE
Add CircleCI / Github action that pushes docker images to quay.io

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1429]
Whenever a tagged commit is made to `master`, a github action/trigger / CircleCI job should

1. Run `docker build -t tari_base_node:$TAG_VERSION -f ./buildtools/base_node.Dockerfile .`
2. Create a `latest` alias for the image
3. Push both images to quay.io

**Comment by CjS77** [comment]
See also #573

**Comment by stringhandler** [comment]
I think this can be closed?

**Comment by delta1** [comment]
Yeah quay has a trigger set up.
