### ISSUE TITLE
Write a script that runs the node from the docker image

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1430]
Write a bash script for either OsX or Linux that:

1. Pulls the latest image for the base node from quay.io (we should have a script that automatically manages docker images, so that there's a tagged image for each release, and `latest` points to the most recent. See #1429)
2. Then runs essentially the same script as described in #1428; However, we run the docker image instead of a local executable, and
3. The data directory is still on the host machine at `~/.tari` and mounted as a volume on the docker container.

**Comment by flipchan** [comment]
What the link from quay.io ?

**Comment by CjS77** [comment]
@Krakaw can likely help you out, since he's done some work on this

**Comment by flipchan** [comment]
so the script to push to quay is not created yet? 
https://github.com/tari-project/tari/issues/573

**Comment by flipchan** [comment]
https://github.com/tari-project/tari/blob/e5c0cd8ef200a9dd414852a4d5f860299c73f000/.circleci/config.yml okay

**Comment by flipchan** [comment]
so docker pull quay.io/tarilabs/tari_base_node

**Comment by Krakaw** [comment]
@CjS77 / @leet4tari can you add the build triggers on quay.io so that the image is built on push to development / tags. That'll effectively solve #1429 
![image](https://user-images.githubusercontent.com/41575888/82929540-20063a80-9f84-11ea-922d-fb724bd636d0.png)

Once we have images building on push (with the latest code) we'll have a good starting point. 

For the docker-compose.yml you could add a volume mount to the host directory, and use the script to create the dir first if doesn't exist. 
```yaml
volumes:
 - "$HOME/.tari:/root/.tari"
```

Something I noticed not on the `README.md` that should be there (I forgot to put it in) is the docker image CMD is now `start.sh` that checks for configs and runs `--init --create-id` if it doesn't find it, then re-runs the `tari_base_node` executable.

**Comment by Krakaw** [comment]
[This line](https://github.com/tari-project/tari/blob/4039de1a6f6d7223c7c179e0db7aa53533216e6f/buildtools/base_node.Dockerfile#L35) is the [start.sh](https://gist.github.com/Krakaw/2c47cd466c371f58f378cecb463b85d3) script

**Comment by flipchan** [comment]
so:
```
docker pull quay.io/tarilabs/tari_base_node                                    
docker run -ti quay.io/tarilabs/tari_base_node -v $HOME/.tari
```

**Comment by flipchan** [comment]
docker pull quay.io/tarilabs/tari_base_node                                    
docker run -ti quay.io/tarilabs/tari_base_node

**Comment by flipchan** [comment]
docker not working with docker run -ti quay.io/tarilabs/tari_base_node

```
2020-05-26T21:20:17.564861963+02:00 container attach 4673cf30b87511c6b3055058ad
8f55c0b7c386117e92b14f8bea223dc8636a33 (image=quay.io/tarilabs/tari_base_node, 
name=hardcore_ganguly)                                                         
2020-05-26T21:20:17.989008442+02:00 network connect 26f1f419a054cca5a2107a89977
22065753b5409e321f5996a823ef6fcb6aef3 (container=4673cf30b87511c6b3055058ad8f55
c0b7c386117e92b14f8bea223dc8636a33, name=bridge, type=bridge)                  
2020-05-26T21:20:21.014666888+02:00 container start 4673cf30b87511c6b3055058ad8
f55c0b7c386117e92b14f8bea223dc8636a33 (image=quay.io/tarilabs/tari_base_node, n
ame=hardcore_ganguly)                                                          
2020-05-26T21:20:21.130710060+02:00 container resize 4673cf30b87511c6b3055058ad
8f55c0b7c386117e92b14f8bea223dc8636a33 (height=39, image=quay.io/tarilabs/tari_
base_node, name=hardcore_ganguly, width=78)                                    
2020-05-26T21:20:21.432556443+02:00 container die 4673cf30b87511c6b3055058ad8f5
5c0b7c386117e92b14f8bea223dc8636a33 (exitCode=132, image=quay.io/tarilabs/tari_
base_node, name=hardcore_ganguly)                                              
2020-05-26T21:20:21.718361227+02:00 network disconnect 26f1f419a054cca5a2107a89
97722065753b5409e321f5996a823ef6fcb6aef3 (container=4673cf30b87511c6b3055058ad8
f55c0b7c386117e92b14f8bea223dc8636a33, name=bridge, type=bridge)               

```

**Comment by flipchan** [comment]
compiling from scratch works like a charm
docker build -t tari_base_node:latest -f ./buildtools/base_node.Dockerfile .
docker run --rm -ti tari_base_node tari_base_node --help

```

docker run --rm -ti tari_base_node tari_base_node --create-id                                                             
Config file does not exist. We can create a default one for you now, or you ca
n say 'no' here, and generate a customised one at https://config.tari.com.
Would you like to try the default configuration (Y/n)?
Y
Installing new config file at /root/.tari/config.toml
Initializing logging according to "/root/.tari/log4rs.yml"

```

**Comment by flipchan** [comment]
maybe it's the latest one that is weird, trying the other one
docker pull quay.io/tarilabs/tari_base_node:0.0.9-1405 
Digest: sha256:ddb4a17d08f9e7e7e4f8430009426bc6ec3a879550bb11d4436cba4786d00fd1
Status: Downloaded newer image for quay.io/tarilabs/tari_base_node:0.0.9-1405
quay.io/tarilabs/tari_base_node:0.0.9-1405

**Comment by flipchan** [comment]
nope ... 
```
2020-05-26T22:11:59.106999021+02:00 container die a4bc22d59c0a5e53c9d3cb8a
713a7f5f6953bfa41b86c4ab9fda38acb3ebee42 (exitCode=132, image=quay.io/tari
labs/tari_base_node:0.0.9-1405, name=confident_davinci)                   

```

**Comment by flipchan** [comment]
@CjS77 / @leet4tari c



> @CjS77 / @leet4tari can you add the build triggers on quay.io so that the image is built on push to development / tags. That'll effectively solve #1429
> ![image](https://user-images.githubusercontent.com/41575888/82929540-20063a80-9f84-11ea-922d-fb724bd636d0.png)
> 
> Once we have images building on push (with the latest code) we'll have a good starting point.
> 
> For the docker-compose.yml you could add a volume mount to the host directory, and use the script to create the dir first if doesn't exist.
> 
> ```yaml
> volumes:
>  - "$HOME/.tari:/root/.tari"
> ```
> 
> Something I noticed not on the `README.md` that should be there (I forgot to put it in) is the docker image CMD is now `start.sh` that checks for configs and runs `--init --create-id` if it doesn't find it, then re-runs the `tari_base_node` executable.

Please enable the github push(es) so it gets the latest from the dev branch

**Comment by Krakaw** [comment]
The build triggers have been added, but quay.io has been having issues the last couple of days. Hopefully after a manual re-trigger we'll have working images.

**Comment by leet4tari** [comment]
Setup the quay.io repo - https://quay.io/repository/tarilabs/tari_base_node with hooks into https://github.com/tari-project/tari ... New pushs into ```develope``` or TAGs starting ```v```, will be build, as in ```docker pull quay.io/tarilabs/tari_base_node:v0.2.6```  
  
Setup a basic docker-compose.yml
```
version: "3"

services:
  tari_base_node:
    image: quay.io/tarilabs/tari_base_node:v0.2.6
    restart: unless-stopped
    volumes:
      - ./data:/root/.tari
```
Pulls our image, start tor and then tari_base_node, but ends shortly after with ```Error: EoF``` and ```Goodbye!```

```
tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 66% (loading_descriptors): Loading relay descriptors
tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tari_base_node_1  | May 31 21:06:40.000 [notice] Bootstrapped 100% (done): Done
tari_base_node_1  | Initializing logging according to "/root/.tari/log4rs.yml"
tari_base_node_1  | May 31 21:06:43.000 [notice] New control connection opened from 127.0.0.1.
tari_base_node_1  | May 31 21:06:43.000 [notice] New control connection opened from 127.0.0.1.
tari_base_node_1  |
tari_base_node_1  |                                             ▄▄▄▄▄▄▄
tari_base_node_1  |   ▄▄▄  ▓██▄     ░                      ▄▒█████████████▄                       ░▐  ░▐                           ▄▄▄▄          ▄▄▄▄
tari_base_node_1  |   ▀███▄ ▀▓█▓     ░                   ▄▓█████████████████▌                      ░░░░ ▒ ░                      ███████▄      ▄███████
tari_base_node_1  |  ▄▄ ▀▓██▄ ▓██▄      ▓███            ▓█████████████████████▄                  ░▄▄▒░▒▄▒░░░░░                 ▐█████████▌    ██████████
tari_base_node_1  | ▐▓██▄ ▀███▄▐███▄   ▐▓▓▓            ▓▌  ▄▄▄▄  ░▀▀▀  ▄▄▄▄▄  ▓░               ▒▒▓▓▀▒▀▓▓▓▒░░░░░░               ███████████   ▐███████████
tari_base_node_1  |   ▀▓██▌ ▀███▓████▄▄██▓▒            ▓▓ ▐██ ░░   ▄  ░░ ███░▐▓▒             ▐▒▒▓▓▓▄ ▄▓▓▓▒▒░ ░░░              ▐▐█░   █████▌  ▀██   ▀█████
tari_base_node_1  |   ▄ ▐▓██▌░▓███████████▓           ▐▒▓▌▐███▄▄  ▓█▌ ▄▄████ ▓▓▒            ▌▒▒▓▓▓▓▓▓▓▓▓▓▒▒▒░ ░░                     ▐████▌        ░█████
tari_base_node_1  |  ▀██▓▄▐███████████████▓░           ▒▓▓▓▄▄▄▄▄▄█████▄▄▄▄▄▄█▓▒▒           ██▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒                  ░   ▄▒█████▒  ░    ▒██████
tari_base_node_1  |    ▀▓██▄▄████████████▓▓▒            ▒▓▓▓▓ ▀▀██████▀▀ ▓▓▓▓▒▒           ▀▀██▌▒▒░░░░░░░░░▒▒▒▒                 ▀█████████▌    ██████████░
tari_base_node_1  |       ▓█████████████▓▒▒              ▒▒▓▓▓▓       ▓▓▓▓▓▒▒░            ▒▒███▒       ░░▒▒▒▒▒                  ▀███████▌      ████████░
tari_base_node_1  |         ▀▓███████▓▓▓▒▒                 ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓░                            ░▒▒▒▀                     ▀▀█▀▀          ▀██▀▀
tari_base_node_1  |            ▀▓▓▓▓▓▒▒▒                       ▀▒▒▒▒▒▒▀
tari_base_node_1  |
tari_base_node_1  |
tari_base_node_1  |
tari_base_node_1  |
tari_base_node_1  |                                            ▄▄▄▄▄▄▄▄▄▄        ▄▄      ▄▄▄▄▄▄▄▄▄▄    ▄▄▄▄▄▄
tari_base_node_1  |                                            ██ ▀███ ▐█      ▐████      ████   ███    ▐███
tari_base_node_1  |                                               ▐███        ███  ███    ███▌   ███    ▐███
tari_base_node_1  |                                               ▐███      ███▌    ███▌  ████▄▄▄██▀    ▐███
tari_base_node_1  |                                               ▐███      ███████████▌  ███▌ ███▌     ▐███
tari_base_node_1  |                                               ▐███      ███▌    ███▌  ███▌   ███    ▐███
tari_base_node_1  |                                              ▄████▄▄    ███▌    ███▌ ▄███▌   ███   ▄████▄
tari_base_node_1  |
tari_base_node_1  | ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
tari_base_node_1  | │                                                                                                                                   │
tari_base_node_1  | │                                                             ▄███████▄                                                             │
tari_base_node_1  | │                                                          ▄████▀  ▀▀████▄                                                          │
tari_base_node_1  | │                                                       ▄███▀          ▀▀███▄                                                       │
tari_base_node_1  | │                                                      █████████▄▄         ▀██                                                      │
tari_base_node_1  | │                                                      ██▌  ▀▀▀███████▄▄   ▐██                                                      │
tari_base_node_1  | │                                                      ██▌       ██ ▀▀████████                                                      │
tari_base_node_1  | │                                                       ▀██▄     ██      ▄██▀                                                       │
tari_base_node_1  | │                                                         ▀██▄   ██    ▄██▀                                                         │
tari_base_node_1  | │                                                           ▀██▄ ██  ▄██▀                                                           │
tari_base_node_1  | │                                                             ▀███████▀                                                             │
tari_base_node_1  | │                                                               ▀███▀                                                               │
tari_base_node_1  | │                                                                 ▀                                                                 │
tari_base_node_1  | │                                                                                                                                   │
tari_base_node_1  | │                                                           Tari Base Node                                                          │
tari_base_node_1  | │                                                           ~~~~~~~~~~~~~~                                                          │
tari_base_node_1  | │                                        Copyright 2019-2020. The Tari Development Community                                        │
tari_base_node_1  | │                                                   Version 0.2.4-b1b8f09-release                                                   │
tari_base_node_1  | ├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
tari_base_node_1  | │                                                              Commands                                                             │
tari_base_node_1  | │                                                              ~~~~~~~~                                                             │
tari_base_node_1  | ├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
tari_base_node_1  | │                           help                               version                            get-balance                       │
tari_base_node_1  | │                        list-utxos                       list-transactions               list-completed-transactions               │
tari_base_node_1  | │                    cancel-transaction                       send-tari                       get-chain-metadata                    │
tari_base_node_1  | │                        list-peers                      reset-offline-peers                       ban-peer                         │
tari_base_node_1  | │                         unban-peer                       list-connections                      list-headers                       │
tari_base_node_1  | │                         check-db                           calc-timing                         discover-peer                      │
tari_base_node_1  | │                        get-block                        get-mempool-stats                    get-mempool-state                    │
tari_base_node_1  | │                          whoami                           toggle-mining                      get-mining-state                     │
tari_base_node_1  | │                        make-it-rain                         coin-split                        get-state-info                      │
tari_base_node_1  | │                           quit                                exit                                                                │
tari_base_node_1  | └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
tari_base_node_1  | Error: Eof
tari_base_node_1  | Goodbye!
```

**Comment by leet4tari** [comment]
Worried about the wrong version number, in this release, need to investigate?

**Comment by Krakaw** [comment]
> Setup the quay.io repo - https://quay.io/repository/tarilabs/tari_base_node with hooks into https://github.com/tari-project/tari ... New pushs into `develope` or TAGs starting `v`, will be build, as in `docker pull quay.io/tarilabs/tari_base_node:v0.2.6`
> 
> Setup a basic docker-compose.yml
> 
> ```
> version: "3"
> 
> services:
>   tari_base_node:
>     image: quay.io/tarilabs/tari_base_node:v0.2.6
>     restart: unless-stopped
>     volumes:
>       - ./data:/root/.tari
> ```
> 
> Pulls our image, start tor and then tari_base_node, but ends shortly after with `Error: EoF` and `Goodbye!`
> 
> ```
> tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 66% (loading_descriptors): Loading relay descriptors
> tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
> tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
> tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
> tari_base_node_1  | May 31 21:06:38.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
> tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
> tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
> tari_base_node_1  | May 31 21:06:39.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
> tari_base_node_1  | May 31 21:06:40.000 [notice] Bootstrapped 100% (done): Done
> tari_base_node_1  | Initializing logging according to "/root/.tari/log4rs.yml"
> tari_base_node_1  | May 31 21:06:43.000 [notice] New control connection opened from 127.0.0.1.
> tari_base_node_1  | May 31 21:06:43.000 [notice] New control connection opened from 127.0.0.1.
> tari_base_node_1  |
> tari_base_node_1  |                                             ▄▄▄▄▄▄▄
> tari_base_node_1  |   ▄▄▄  ▓██▄     ░                      ▄▒█████████████▄                       ░▐  ░▐                           ▄▄▄▄          ▄▄▄▄
> tari_base_node_1  |   ▀███▄ ▀▓█▓     ░                   ▄▓█████████████████▌                      ░░░░ ▒ ░                      ███████▄      ▄███████
> tari_base_node_1  |  ▄▄ ▀▓██▄ ▓██▄      ▓███            ▓█████████████████████▄                  ░▄▄▒░▒▄▒░░░░░                 ▐█████████▌    ██████████
> tari_base_node_1  | ▐▓██▄ ▀███▄▐███▄   ▐▓▓▓            ▓▌  ▄▄▄▄  ░▀▀▀  ▄▄▄▄▄  ▓░               ▒▒▓▓▀▒▀▓▓▓▒░░░░░░               ███████████   ▐███████████
> tari_base_node_1  |   ▀▓██▌ ▀███▓████▄▄██▓▒            ▓▓ ▐██ ░░   ▄  ░░ ███░▐▓▒             ▐▒▒▓▓▓▄ ▄▓▓▓▒▒░ ░░░              ▐▐█░   █████▌  ▀██   ▀█████
> tari_base_node_1  |   ▄ ▐▓██▌░▓███████████▓           ▐▒▓▌▐███▄▄  ▓█▌ ▄▄████ ▓▓▒            ▌▒▒▓▓▓▓▓▓▓▓▓▓▒▒▒░ ░░                     ▐████▌        ░█████
> tari_base_node_1  |  ▀██▓▄▐███████████████▓░           ▒▓▓▓▄▄▄▄▄▄█████▄▄▄▄▄▄█▓▒▒           ██▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒                  ░   ▄▒█████▒  ░    ▒██████
> tari_base_node_1  |    ▀▓██▄▄████████████▓▓▒            ▒▓▓▓▓ ▀▀██████▀▀ ▓▓▓▓▒▒           ▀▀██▌▒▒░░░░░░░░░▒▒▒▒                 ▀█████████▌    ██████████░
> tari_base_node_1  |       ▓█████████████▓▒▒              ▒▒▓▓▓▓       ▓▓▓▓▓▒▒░            ▒▒███▒       ░░▒▒▒▒▒                  ▀███████▌      ████████░
> tari_base_node_1  |         ▀▓███████▓▓▓▒▒                 ▀▓▓▓▓▓▓▓▓▓▓▓▓▓▓░                            ░▒▒▒▀                     ▀▀█▀▀          ▀██▀▀
> tari_base_node_1  |            ▀▓▓▓▓▓▒▒▒                       ▀▒▒▒▒▒▒▀
> tari_base_node_1  |
> tari_base_node_1  |
> tari_base_node_1  |
> tari_base_node_1  |
> tari_base_node_1  |                                            ▄▄▄▄▄▄▄▄▄▄        ▄▄      ▄▄▄▄▄▄▄▄▄▄    ▄▄▄▄▄▄
> tari_base_node_1  |                                            ██ ▀███ ▐█      ▐████      ████   ███    ▐███
> tari_base_node_1  |                                               ▐███        ███  ███    ███▌   ███    ▐███
> tari_base_node_1  |                                               ▐███      ███▌    ███▌  ████▄▄▄██▀    ▐███
> tari_base_node_1  |                                               ▐███      ███████████▌  ███▌ ███▌     ▐███
> tari_base_node_1  |                                               ▐███      ███▌    ███▌  ███▌   ███    ▐███
> tari_base_node_1  |                                              ▄████▄▄    ███▌    ███▌ ▄███▌   ███   ▄████▄
> tari_base_node_1  |
> tari_base_node_1  | ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> tari_base_node_1  | │                                                                                                                                   │
> tari_base_node_1  | │                                                             ▄███████▄                                                             │
> tari_base_node_1  | │                                                          ▄████▀  ▀▀████▄                                                          │
> tari_base_node_1  | │                                                       ▄███▀          ▀▀███▄                                                       │
> tari_base_node_1  | │                                                      █████████▄▄         ▀██                                                      │
> tari_base_node_1  | │                                                      ██▌  ▀▀▀███████▄▄   ▐██                                                      │
> tari_base_node_1  | │                                                      ██▌       ██ ▀▀████████                                                      │
> tari_base_node_1  | │                                                       ▀██▄     ██      ▄██▀                                                       │
> tari_base_node_1  | │                                                         ▀██▄   ██    ▄██▀                                                         │
> tari_base_node_1  | │                                                           ▀██▄ ██  ▄██▀                                                           │
> tari_base_node_1  | │                                                             ▀███████▀                                                             │
> tari_base_node_1  | │                                                               ▀███▀                                                               │
> tari_base_node_1  | │                                                                 ▀                                                                 │
> tari_base_node_1  | │                                                                                                                                   │
> tari_base_node_1  | │                                                           Tari Base Node                                                          │
> tari_base_node_1  | │                                                           ~~~~~~~~~~~~~~                                                          │
> tari_base_node_1  | │                                        Copyright 2019-2020. The Tari Development Community                                        │
> tari_base_node_1  | │                                                   Version 0.2.4-b1b8f09-release                                                   │
> tari_base_node_1  | ├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
> tari_base_node_1  | │                                                              Commands                                                             │
> tari_base_node_1  | │                                                              ~~~~~~~~                                                             │
> tari_base_node_1  | ├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
> tari_base_node_1  | │                           help                               version                            get-balance                       │
> tari_base_node_1  | │                        list-utxos                       list-transactions               list-completed-transactions               │
> tari_base_node_1  | │                    cancel-transaction                       send-tari                       get-chain-metadata                    │
> tari_base_node_1  | │                        list-peers                      reset-offline-peers                       ban-peer                         │
> tari_base_node_1  | │                         unban-peer                       list-connections                      list-headers                       │
> tari_base_node_1  | │                         check-db                           calc-timing                         discover-peer                      │
> tari_base_node_1  | │                        get-block                        get-mempool-stats                    get-mempool-state                    │
> tari_base_node_1  | │                          whoami                           toggle-mining                      get-mining-state                     │
> tari_base_node_1  | │                        make-it-rain                         coin-split                        get-state-info                      │
> tari_base_node_1  | │                           quit                                exit                                                                │
> tari_base_node_1  | └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> tari_base_node_1  | Error: Eof
> tari_base_node_1  | Goodbye!
> ```

This is because it needs an interactive tty. Your docker-compose.yml needs
```yaml
version: "3"

services:
  tari_base_node:
    image: quay.io/tarilabs/tari_base_node:v0.2.6
    restart: unless-stopped
    volumes:
      - ./data:/root/.tari
   # These 2 params are required for an interactive docker-compose session
    stdin_open: true
    tty: true
```

**Comment by leet4tari** [comment]
Just a collection of notes for docker image  
  
docker-compose.yaml
```
version: "3"

services:
  tari_base_node:
#    image: quay.io/tarilabs/tari_base_node:v0.2.6
    image: quay.io/leet4tari/tari_base_node:leet-docker
    restart: unless-stopped
    volumes:
      - ./data:/root/.tari
# These 2 params are required for an interactive docker-compose session
    stdin_open: true
    tty: true
    expose:
      - 18142
    ports:
      - "18142:18142"
```
then run docker-compose up -d  
  
Using ```docker ps``` to get the container ID to attach to tari_base_node in docker
```
CONTAINER ID        IMAGE                                          COMMAND             CREATED             STATUS              PORTS                      NAMES
e2699c823f4e        quay.io/leet4tari/tari_base_node:leet-docker   "start.sh"          8 minutes ago       Up 10 seconds       0.0.0.0:18142->18142/tcp   tari_tari_base_node_1
```
```docker attach e2699c823f4e```  
Will give you access too the cli  
  
But run into the dreaded ```Illegal instruction``` #1811

**Comment by leet4tari** [comment]
Two quay builds running with workaround:  
 - quay.io/leet4tari/tari_base_node:leet-cpu-test-edf87aa [skylake CPU]  
 - quay.io/leet4tari/tari_base_node:leet-cpu-test-410ead4 [core2 CPU]  
  
Using branch - https://github.com/tari-project/tari/tree/croaring-remove-march-native  
  
Working on a long term fix that support easier cross-platform building

**Comment by stringhandler** [comment]
This is implemented in https://github.com/tari-project/tari-launchpad
