### ISSUE TITLE
Use a log4rs appender that creates rolling log files

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1431]
The log files can generate a lot of data at their default settings, especially `network.log`. If a node is running for weeks/months, we could fill up a disk :(

Modify the default `log4rs.yml` file to have the policy:

* Rolls log files daily
* Keeps logs for a maximum of 30 days

To implement, it looks like one only needs to 

* add [log4rs-rolling-file](https://sfackler.github.io/log4rs-rolling-file/doc/v0.2.0/log4rs_rolling_file/index.html)
* Perhaps modify the `log4rs::init_file` call to include the `log4rs-rolling-file` deserializer
* Modify `log4rs.yml` to use the `log4rs-rolling-file` appender with the desired policy.

Note that this only updates the default log policy. Power users still have total control to modify `log4rs.yml` to produce whatever logs they want.

**Comment by SWvheerden** [comment]
log4rs-rolling-file is deprecated and merged into log4rs
