### ISSUE TITLE
Investigate from_string -> netaddress fn for parsing problems and slowness

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#146]
Would it not be better to have a function interpret the string and then do this via a match?

I dont know how rust deals with fails eg (errors) but other languages are really slow if you rely on the "catch" part to function. In effect here we try to parse, them, if they fail we try the next one. If we do this the order is going to very important here as well.

_Originally posted by @SWvheerden in https://github.com/tari-project/tari/pull/142_

**Comment by CjS77** [comment]
Investigated. Not an issue.
