### ISSUE TITLE
[Feature] Splash Page User Agreement/Privacy Policy Links

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1509]
We need to add 2 links to the splash page for the user to reach the User Agreement and Privacy Policy pages, which will pop open a browser window with the relevant page

Zeplin: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e71c19d33a5a6bf098a58be

Acceptance criteria:
- Add text below splash screen CTA with links to the Terms and Privacy Policy
- The links should pop open these two in a browser window respectively (doesn't need to be a webview, even whatsapp sends users to browser)
https://tarilabs.com/user_agreement/
https://tarilabs.com/privacy_policy/

Please let @karim-tari know if we need a new orb video to accommodate this new spacing!

**Comment by talmahaj** [comment]
Note that we are awaiting final copy for both of these docs, but feel free to use what's there for now...

**Comment by Jasonvdb** [comment]
We could spend a lot of time copying and pasting this doc and formatting it in the native app each time for correct display. For every update of doc, it could be some dev time our side. Thinking of maybe converting it to a plain text file and loading it in remotely or even committing to git. Then for each doc change no coding needs to be done. @kukabi what do you think?

**Comment by kukabi** [comment]
@Jasonvdb agreed, good idea.

**Comment by talmahaj** [comment]
@kukabi @Jasonvdb updated ticket to reflect that links should open URLs in browser, no need for in-app pages

**Comment by Tas4tari** [comment]
@talmahaj  Closing this issue as the corresponding Android and IOS tickets have been closed

**Comment by talmahaj** [comment]
Thanks for cleaning up! This is super helpful.
