### ISSUE TITLE
[Feature] Testnet Tari Store - Add icon and modal

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1511]
![item_bundle](https://user-images.githubusercontent.com/1817246/77494783-0ed26d80-6e1d-11ea-8c36-a9bbbf2fb67e.png)
Our marketing promotion for our testnet launch is a store with which you can buy real items with testnet Tari. In order to drive users to the store, we need to be able to send them to their browser from the app.

**Design:**

Final t-shirt graphic: attached to this ticket

Modal design (outdated graphic): https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e71cb37653b9cb4986e9592
(asset files are available by clicking the specific elements)

**Final copy**

Heading: "Spend testnet Tari on real (exclusive) stuff"

Body: "Check out Testnet Tari Limited (TTL) to spend your "hard-earned” testnet Tari on exclusive, one-of-a-kind stuff produced by the team at Tari Labs. Enjoy!"

Button: "Visit the TTL Store"

Link: "I’ll check it out later"

**Acceptance Criteria:**
- Update profile icon to reflect updated design
- Add store icon next to profile icon
- Tapping store icon should open up the modal
- Modal should include copy above, NOT the copy in the design
- Hitting "I'll check it out later" or anywhere else outside the modal closes it
- Hitting the button in the modal sends the user to tarilabs.com/store using their default web browser

**Comment by Tas4tari** [comment]
Closing as the corresponding IOS issue is in UAT and will be closed as well 
https://github.com/tari-project/wallet-ios/issues/181
