### ISSUE TITLE
[FEATURE] Pop store modal after user first sends Tari

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1513]
After I try sending Tari back to Tari Bot or to a friend for the first time, I feel comfortable transacting and I want to know what I should do next in the app.

**Acceptance Criteria** 

- After user completes initiating their first pending Tari transaction -- regardless of recipient -- and is returned to their transaction list to view their pending transaction, the store promotion modal from [this ticket](https://github.com/tari-project/tari/issues/1511) should appear.

**Comment by Tas4tari** [comment]
@talmahaj Is this still blocked?

**Comment by talmahaj** [comment]
This was completed a long time ago

**Comment by Tas4tari** [comment]
@talmahaj Thanks will close this issue

**Comment by talmahaj** [comment]
Go for it!
