### ISSUE TITLE
[Feature] Wallet setup interstitial

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1529]
![Screen Shot 2020-03-19 at 3.37.54 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/cf3a1db9-8a1f-402e-83b2-af15e5914ad6)

The current swipe down interaction in this screen is not working well for users -- it failed in our user testing, everyone swipes the wrong way -- so we are going to change the behavior and implement it as a brief interstitial instead that disappears on its own and requires no user interaction. If we removed it altogether, the user wouldn't have any feedback to signal the end of setup, so hopefully this will feel adequately lightweight!

**Acceptance Criteria**

- Remove arrow icon
- Screen should appear for 1500 milliseconds and then slide down automatically
- User should not be able to interact with screen; it should be an animation now instead of an interaction

**Comment by Jasonvdb** [comment]
@talmahaj while testing this 1500ms seems too fast, maybe test and make sure yourself. It's a quick change. Maybe I'm just a slow reader 🤷‍♂
