### ISSUE TITLE
[Enhancement] Final copy for all mobile wallet screens!

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1531]
We have final approval on copy to go across the entire mobile wallet app!

Please go through screen by screen and apply all the final copy in this document. Let myself and Karim know if there are wrapping issues caused by the new copy, e.g. overlap or cramping on lower res devices due to needing an additional line, and we'll decide how to address together!

https://docs.google.com/document/d/1nn8rA388Lm9aU8ft7keSlDse8at0D-3w9MCapD-de2s/edit?usp=sharing

**Acceptance Criteria**
- The copy across all screens in theapp perfectly matches the text in the Google doc above.

**Comment by talmahaj** [comment]
One tweak: we need to have the T in testnet be lowercase across the app, unless it's the beginning of a sentence or part of a title.

Places we need to fix the copy to say "testnet" instead of "Testnet":
- App splash screen subheading
- The note from Tari Bot
- The modal that appears with the Tari Bot transaction: one instance in heading, one in body copy

**Comment by talmahaj** [comment]
One more small tweak:

On the "This is your Emoji ID" screen, Naveen points out that the "Secure your wallet" button is redundant with the button on the following screen that reads "Secure with ______."

Instead of "Secure your wallet," let's have it now read "Continue" instead.

**Comment by Tas4tari** [comment]
@talmahaj Closing as the corresponding IOS and Android tickets have been closed
