### ISSUE TITLE
[BUG] Getting error message incorrectly when attempting to send 2nd simultaneous transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1532]
@talmahaj commented on [Thu Mar 19 2020](https://github.com/tari-project/wallet-ios/issues/191)

**Describe the bug**
Despite a balance of 5,000 Tari, I am receiving a "not enough Tari available to send" error when trying to send 2 very small transactions simultaneously.

**To Reproduce**
1. Create a new wallet with the 5000 Tari deposited
2. Send 12 Tari to Tari bot
3. While transaction is pending, try to send another 1 Tari to Tari Bot
4. Get the balance exceeded error that should only appear in this edge case: https://github.com/tari-project/tari/issues/1178#issuecomment-574290828

**Expected behavior**
Given that there were 5000 Tari and that the transactions were only 12 Tari and 1 Tari respectively, shouldn't have it sent much smaller bills such that you could have these transactions pending simultaneously?

**Comment by Jasonvdb** [comment]
@talmahaj if you're on the latest version you should see this "Hold your horses" modal. And this is the edge case mentioned here: https://github.com/tari-project/tari/issues/1178 . Until the first TX is mined, we're stuck without a spendable balance.


![IMG_2E31F2EFF1AB-1](https://user-images.githubusercontent.com/5300488/77138199-bf391e00-6a79-11ea-94ec-8ef3fa9356b4.jpeg)

**Comment by philipr-za** [comment]
This modal is also present in the Android build and it is a function of that edge case where initially the user has only 1 UTXO to spend so until they get their change they cannot do another transaction yet.

@CjS77 When the base node is more mature I believe we can actually spend the change before the previous transaction gets mined by the miner including both transactions in the same block but the base node will have to do some more advanced validation and we will have to be sure that the transactions end up in the same mempool.
