### ISSUE TITLE
[Feature] Double UTXOs so each new mobile user has 10,000 Tari from faucet

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1565]
Currently, no mobile wallet user can send 2 transactions simultaneously due to the single UTXO constraint. A number of internal testers are reporting this as a bug because it was unanticipated by them.

@CjS77 suggests we can double the UTXO such that a second simultaneous transaction can be sent.

*Acceptance Criteria*
1. User should continue to receive their first 5K Tari after finishing the onboarding flow, per the current behavior
2. AFTER the user sends their first transaction to any recipient, including TariBot: about ~2 seconds after they are returned to the home screen, they should receive their second faucet transaction with the note "Nice work! Here's more Tari to fill your coffers. Be sure to hit the Store icon to see real, exclusive items you can redeem with your "hard-earned" testnet Tari.

**Comment by Jasonvdb** [comment]
@talmahaj so the note `Nice work! Here's more Tari to fill your coffers. Be sure to hit the Store icon to see real, exclusive items you can redeem with your "hard-earned" testnet Tari.` will be too long for the home tx list view and will be cut off. But will show the full note on the tx detail view. That alright?

**Comment by kukabi** [comment]
@Jasonvdb I'm proceeding with that message, does get cut off. @talmahaj

**Comment by talmahaj** [comment]
@kukabi @Jasonvdb Yep, we're aware it gets cut off, but the user should still see "Nice work! Here's more Tari..." and they can always tap on the transaction to read the rest :)
