### ISSUE TITLE
Low-level PING session for comms

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#1605]
Allow an optional number of liveness sessions over the configured for base node monitoring purposes.

This will require a change to the wire protocol for comms.

Suggested change:
Every initiator must first send a protocol flag as the first byte

`0x00` tari protocol
`0x50` (P) - PING protocol - switching to a telnet-friendly text framing and counting towards the allotted PING sessions

PING sessions would be set to 0 by default and have to be enabled by the admin if they want to do basic health checks - an IP whitelist can also be applied for PING sessions

**Comment by leet4tari** [comment]
Supporting info - Services provider like ```Pingdom``` can monitor TCP port with a string to send and to expect in return - https://help.pingdom.com/hc/en-us/articles/203749792-What-is-a-check-
