### ISSUE TITLE
Consolidate Hashing Struct

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#167]
Right now there are 3 different implementations of Hashing running around:

* the naked `Digest` trait
* `Hashable`
* `Challenge`

We should use a single struct/trait across the project, either using `Digest` directly, or at least consolidating `Hashable` and `Challenge` into a single piece of code.

This issue is for discussing the way forward on this and implementing the solution.

Requires #126 
Requires #161
Requires #63
Requires #42

**Comment by SWvheerden** [comment]
The MMR needs a wrapper around the digest trait, it cannot just use the `digest`.

`Hashable` uses digest and describes how an object should be hashed to get a single hash. 

I am almost finsihed with a PR that consolidates the usage of hashable, as well as add a macro with which you can only say :
```
#[derive(Hashable)]
#[Digest = "Blake2b"]
```

and it will create the hashable trait for.

**Comment by SWvheerden** [comment]
The use case from the MMR side is this: 
https://github.com/tari-project/tari/blob/da6ad1534d95f09e1504829be6538411aaae791a/infrastructure/merklemountainrange/src/merklemountainrange.rs#L218-L221

The impl hashable trait is something like this:
https://github.com/tari-project/tari/blob/da6ad1534d95f09e1504829be6538411aaae791a/infrastructure/merklemountainrange/tests/support/testobject.rs#L26-L43
