### ISSUE TITLE
Dynamic adjustment of LMDB environment map size

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#1670]
This proposal is (tick applicable):

* [ ] A new feature
* [X] An extension to an existing RFC/proposal: [RFC-0111/BaseNodesArchitecture](https://rfc.tari.com/RFC-0111_BaseNodeArchitecture.html?highlight=lmdb#blockchain-state-module).
* [ ] An alternative approach to an existing RFC or proposal <LINK>

### Change log

| Date | Changes |
|:-----|:--------|
|      |         |

### Goals
Static database sizing to be changed to dynamic database sizing. In this way, we would not need to re-deploy base nodes if database limits are reached. 

### Assumptions
PR #1642 must be implemented.

### Abstract
Dynamic adjustment of LMDB environment map size will mitigate the need to re-deploy base nodes if database limits are reached and optimize space usage for Windows builds. In Windows, files are pre-allocated when `set_mapsize()` is called vs the sparse file system of Linux where this does not happen.

## Description
The [LMBD set_mapsize](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/struct.Environment.html#method.set_mapsize) function was introduced with the 2015-08-11 v0.87 release notes: _"Environment.set_mapsize() was added to allow runtime adjustment of the  environment map size."_

These and other references make it clear that in Windows files are pre-allocated vs the sparse file system of Linux:
- [LMDB write scalability problem](https://github.com/lmdbjava/benchmarks/issues/9#issuecomment-354064608)
- [How to assign proper mapsize for LMDB?](https://groups.google.com/d/msg/caffe-users/0RKsTTYRGpQ/CL_ajpPyq2wJ)

Grin implemented `needs_resize` and `do_resize` functions to dynamically change the database size when needed - see their [store/src/lmdb.rs](https://github.com/mimblewimble/grin/blob/master/store/src/lmdb.rs) and [store/tests/lmdb.rs](https://github.com/mimblewimble/grin/blob/master/store/tests/lmdb.rs) code. 
```
/// number of bytes to grow the database by when needed
pub const ALLOC_CHUNK_SIZE_DEFAULT: usize = 134_217_728; //128 MB
/// And for test mode, to avoid too much disk allocation on windows
pub const ALLOC_CHUNK_SIZE_DEFAULT_TEST: usize = 1_048_576; //1 MB
```
I believe we should implement something similar.

**Comment by delta1** [comment]
closed by #2193
