### ISSUE TITLE
Implement key events for tracking in Matomo

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1687]
Implement the events we cannot trigger via mobile (the last 3) at https://github.com/tari-project/wallet-android/wiki/Matomo-Event-Tracking

**Comment by talmahaj** [comment]
@philipr-za @hansieodendaal What is the level of effort for this? I may ask to queue it up after Store & Forward is done. Thanks!

**Comment by philipr-za** [comment]
It is definitely doable. Will have to build a service to hit up the Matomo endpoints and then monitor the wallets event streams so probably a couple days of work.

@sdbondi was looking at this for network events so I hope that by the time the wallet support of Store and Forward is ready he might have something ready that we can build on. Will discuss it in standup today and add it to the queue.

**Comment by sdbondi** [comment]
@philip-za I've also checked out matomo, we definitely can produce some good data points from existing internal event streams in comms e.g number of messages sent to/recieved from a given node, which node is this node connected to etc. Let's discuss what data to collect both from a product analytics perspective and a technical/network topography/debugging perspective

**Comment by Tas4tari** [comment]
Closing this off as the component tickets on Android and iOS have been tested and closed
cc @talmahaj
