### ISSUE TITLE
[Spec Still WIP] Store and Forward UX

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1688]
# SPEC STILL WIP

**Acceptance Criteria: Initiating Transaction**

Scenario: Today, without store and forward completed, if the recipient not found within 20 seconds of the discovery process starting, the transaction fails. However, once store and forward is implemented, the sender should get the same UX immediately after they send a transaction, whether or not it's accepted synchronously or asynchronously. 

That is, the following should happen if the user is found online during the discovery period OR if the initial discovery period times out because recipient is offline:
- User sees success state with tick mark and is returned to transaction list screen
- Transaction will appear under Pending instead of the error message appearing
- Amount of Tari is deducted from the balance that appears to the sender at the top of the screen
- The recipient is immediately sent a push notification

**Acceptance Criteria: Accepting Transaction Asynchronously**

Scenario: Offline recipient sees push notification that someone sent them Tari, then taps push notification to open app

- If the recipient taps the push motif and reaches their transaction list, but cannot not see the new transaction because Tor and base node connections may still be in progress, then [deep link implementation?]
- If recipient opens the Tari app but it is not through the push notification, we have no way of knowing they have a transaction to accept until they're fully connected, so, unfortunately, we'll have to just hope and pray they keep the app open long enough...

**Acceptance Criteria: Broadcasting Transaction Asynchronously**

Scenario: Sender is offline when Recipient accepts the transaction, and app cannot be successfully woken up from background

- Sender is sent a push notification reading:
"Finalize your transaction"
"One last step! Please open Tari Aurora to finalize your transaction"
- If user opens the Tari app via tapping push notification, [deep link implementation?]
- If user opens the Tari app but it is not through the push notification, we have no way of knowing they have a transaction to broadcast until they're fully connected, so, unfortunately, we'll have to just hope and pray they keep the app open long enough...

**Acceptance Criteria: Other**

Scenario: Sender's transaction is never claimed by recipient

- Send a reminder push notification to recipient 24 hours after transaction sent
"You've been sent Tari!"
"Open Tari Aurora to see how much and from whom"
- Send a reminder push notification to recipient 48 hours after transaction sent
"Claim your Tari before it expires"
"Open Tari Aurora to claim the Tari that was sent to you"
- If recipient does not accept Tari after 72 hours, the transaction should expire
- Expired transaction should no longer appear on transactions list for sender or recipient (maybe not ideal but we can address after MVP)
- When transaction expires, send push notification to sender:
"Your transaction expired"
"Your recipient never claimed the Tari you sent them, so we've added it back to your balance"
- When transaction expires, send push notification to recipient:
"Your transaction expired"
"Sorry! You didn't claim the Tari sent to you within 3 days, so we returned it to the sender"

Scenario: Accepted transaction is never broadcast by sender

- Send a reminder push notification to sender 24 hours after transaction sent:
"You still need to finalize your transaction"
"One last step! Open Tari Aurora to finalize your outgoing transaction"
- Send a reminder push notification to sender 48 hours after transaction sent:
"Finalize your transaction before it expires"
"Open Tari Aurora to finalize your outgoing transaction within 24 hours, or we'll return the money to your balance"
- If sender does not broadcast transaction after 72 hours, the transaction should expire
- Expired transaction should no longer appear on transactions list for sender or recipient (maybe not ideal but we can address after MVP)
- When transaction expires, send push notification to sender:
"Your outgoing transaction expired"
"You never finalized your outgoing transaction, so we've added it back to your balance"
- When transaction expires, send push notification to recipient:
"Your incoming transaction expired"
"Sorry! Your sender didn't finalize the transaction within 3 days, so the transaction expired"

Scenario: After a transaction expires, sender or recipient open app by tapping push notification

- If the sender or recipient reaches their transaction list, but is still seeing the expired transaction because Tor and base node connections may still be in progress, then [deep link implementation?]
- If recipient opens the Tari app but it is not through the push notification, we'll have to just hope and pray they keep the app open long enough for it to connect...

**Comment by Jasonvdb** [comment]
> * If recipient opens the Tari app but it is not through the push notification, we have no way of knowing they have a transaction to accept until they're fully connected, so, unfortunately, we'll have to just hope and pray they keep the app open long enough...

I know this idea has probably been pitched before, but possibly having a status indicator on the home view that stays in a pending state until we know for sure the app is online and synced with a basenode. That might  incentive the user to keep it open until they see the icon switch to a "synced" state?

**Comment by philipr-za** [comment]
If we are going to leave transactions hanging for up to 3 days there should probably be a feature for a Sender to cancel a transaction in order to free funds up if the receiver does not respond adn the sender needs the funds for something else within the 3 day limit. 

This does imply that there must be a message created to let the recipient know that the transaction was cancelled.

**Comment by Jasonvdb** [comment]
@talmahaj one possibility we chatted about is actually encrypting tx details and adding them to the payload of the push notification. So if a user taps a notification the app will be able to get the tx details before it's actually connected to the network. Perhaps that could help display the placeholder in the meantime? Although it would need to be made clear to the user that the app needs to stay open until it's received the same stored message from a base node.

**Comment by talmahaj** [comment]
> > * If recipient opens the Tari app but it is not through the push notification, we have no way of knowing they have a transaction to accept until they're fully connected, so, unfortunately, we'll have to just hope and pray they keep the app open long enough...
> 
> I know this idea has probably been pitched before, but possibly having a status indicator on the home view that stays in a pending state until we know for sure the app is online and synced with a basenode. That might incentive the user to keep it open until they see the icon switch to a "synced" state?

Thanks for resurfacing this idea, we've created a wireframe of this and I'm now waiting on design from Karim. 

Hold tight!
