### ISSUE TITLE
FFI occasionally fails to init a pub key from a valid emoji ID 

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/tari#1692]
**Describe the bug**
Attempting to init a pubkey using FFI `emoji_id_to_public_key` and about half the time it returns error code 6 (InvalidEmojiId). Emoji ID was generated with another phone.

`😷💍💎🐍🤩💺🚔💊🧗🤤😉⛅🐶✋🧦🧜🤠🧤💻🌸📌👸🥁🍇🏀🎲😵💇❓⛵💊🦋🎸`

**To Reproduce**
1. Go to add recipient view with the above emoji ID in clipboard
2. Try to select emoji ID from clipboard. Might have to do this a few time to reproduce as it doesn't happen every time.

**Comment by StriderDM** [comment]
https://github.com/tari-project/wallet-ios/pull/269

**Comment by Jasonvdb** [comment]
Thanks @StriderDM!
