### ISSUE TITLE
[Epic] Store & Forward UX 

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1694]
We have Naveen's signoff on all but one of the sections in my Store & Forward Case Handling doc, which I indicated inline: 

https://docs.google.com/document/d/1H3gcrmq5a_gJSaBzFf5KiOmgjFhiLm9120eJFuVQFkA/edit#heading=h.5wsyccz9yaic

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e97a63d0757177ccd4f493e

Animation videos (check out both):
https://www.dropbox.com/s/f4osdzkfhmf0rbl/store-and-forward-receiving-nothing-new.mp4?dl=0
https://www.dropbox.com/s/sk1q0oh7grp6pn8/store-and-forward-new-transfer.mp4?dl=0

Animation Acceptance Criteria:
- If Tor is not connected and/or base node isn't in sync: Sand timer icon and "Checking for updates"
- If user is connected/synced AND has a transaction to accept: Handshake icon and "Receiving new transactions" (should show for minimum 3 seconds)
- If user is connected/synced AND has a transaction to broadcast: Handshake icon and "Completing your transaction" (should show for a minimum 3 seconds)
- If user is connected/synced AND has no more outstanding transaction interactions "You are up to date!" (if there is a new transaction accepted, should appear in list at the same time as the above does)
- If user is connected/synced AND has a transaction that expired: Handshake icon and "Updating your transaction" (should show for a minimum 3 seconds)
- If user pulls down on transaction list to refresh, force a base node sync manually and display sand timer icon and "checking for updates" for at least 2 seconds

**Comment by Tas4tari** [comment]
Closing this issue as the component tickets in Android and iOS have been closed
cc @talmahaj
