### ISSUE TITLE
Base layer wallet software

### ISSUE THREAD

**Issue by neonknight64** [tari-project/tari#17]
# Base layer wallet software

## Metadata

This proposal is (tick applicable):

* [X] A new feature
* [ ] An extension to an existing RFC/proposal <LINK>
* [ ] An alternative approach to an existing RFC or proposal <LINK>

### Change log

| Date | Changes |
|:-----|:--------|
|2018/12/19|Initial version|

### Goals
This document will propose the functionality and techniques required by the base layer Tari software wallet.

### Assumptions
- A working implementation of a base layer full node. 
- A Tari blockchain implemented using Mimblewimble.

### Abstract
The Wallet software is responsible for constructing and negotiating transactions for transferring and receiving Tari coins on the base layer. It should also provide functionality to generate, store and recover a master seed key and derived cryptographic key pairs that can be used for base layer addresses and signing of transactions.

## Description

A detailed description of the required functionality of the Tari software wallet is provided in three parts: basic functionality, maintaining of private keys and wallet recovery.

Basic functionality required of the Tari software wallet:
- It must be able to send and receive Tari coins using mimblewimble transactions.
- It should be able to establish a connection between different user wallets to negotiate:
      - the construction of a transaction and
      - the signing of multi signature transactions.
- The Tari software wallet should be implemented as a library or API so that GUI or CLI applications can be constructed on it.
- It requires a local or remote connection to a base layer full node to submit transactions and monitor the Tari blockchain. 
- It should maintain an internal ledger to keep track of the Tari coin balance of the wallet.
- It should be able to estimate and calculate transaction fees taking into account:
      - transaction byte size,
      - network congestion and
      - the desired transaction priority.
- It needs to monitor and display the states (Spent, Unspent or Unconfirmed) of previously submitted transactions and wallet addresses by querying information from the connected full node.
- The wallet software should be able to update its software to patch potential security vulnerabilities. Automatic updating will be selected by default, but users can decided to opt out.
- Wallet features requiring querying a full node for information, should have caching capabilities to reduce bandwidth consumption.

Required functionality related to the maintaining of the master seed key and derived private cryptographic keys:
- It should be able to generate a master seed key for the wallet by using:
      - the manual input from a user such as letting the user use a visual randomisation tool to generate the seed or
      - an entropy seeded random number generator.
- It should be able to generate derived transactional cryptographic key pairs from the master seed key using Hierarchical Deterministic key pair generation.
- It should store the wallet state using a password or passphrase encrypted persistent Key-value database.
- It should provide the ability to backup the wallet state to a single encrypted file to simplify wallet recovery and reconstruction at a later stage.
- It may provide the ability to export the master seed key or wallet state as a printable paper wallet using coded markers.

Different methods for recovering the wallet state of the Tari software wallet:
- It should be able to reconstruction the wallet state from a manually entered master seed key.
- The master seed key should be derivable from mnemonic word sequences using known word lists.
- It should enable the reconstruction of the master seed key by scanning a coded marker of a paper wallet.

**Comment by CjS77** [comment]
> The tari software wallet should be able to run as a GUI or CLI application.
I'd suggest we keep wallet functionality as an API and let app developers build on top of it. 
We could offer a CLI and maybe GUI wallet as a reference-- whatever people want to build

**Comment by CjS77** [comment]
* I would add that every feature that "uses a full node", e.g. balance etc. should have caching capabilities to reduce bandwidth consumption. 

Since there's no possibility of passive reception of coins (i.e. no addresses), the wallet never needs to query the balance in principle (unless you are recovering a wallet). It starts with a zero balance and can update an internal ledger every time it signs a transaction. All it needs to check the blockchain for is that it's transactions get confirmed.

**Comment by neonknight64** [comment]
I have made changes to the proposal based on the comments of CjS77 and the IRC/tari-dev 20-12-2018 discussion.

**Comment by CjS77** [comment]
This issue has been converted into an RFC PR (https://github.com/tari-project/tari/pull/24)
