### ISSUE TITLE
Migrate from `derive-error` to `thiserror`/`anyhow`

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1718]
`derive-error` served us well, but it's a little long in the tooth and does not seem to be very actively maintained anymore.

We've decided to standardize on [`thiserror`](https://crates.io/crates/thiserror) as the error handling library going forward. 

This entails migrating alllllllll the current error types over to `thiserror` and dropping the derive-error dependency as a finla goal.

**Comment by delta1** [comment]
issue can be closed @mikethetike @CjS77 #2112
