### ISSUE TITLE
Command Line Resize

### ISSUE THREAD

**Issue by StriderDM** [tari-project/tari#1728]
The Tari Base Node, does not  automatically resize the terminal window on startup, leading to text being wrapped onto subsequent lines and breaking   up the intended UI

**To Reproduce**
In a new un-resized terminal window, run   `cargo run --bin tari_base_node`

**Expected behavior**
The terminal should resize to fit the longest string on startup when displaying the UI

**Screenshots**
Current:
![Screen Shot 2020-04-18 at 8 55 37 AM](https://user-images.githubusercontent.com/51991544/79630529-629d5180-8152-11ea-9296-3eb61f9e7e76.png)

Expected
![Screen Shot 2020-04-18 at 9 00 24 AM](https://user-images.githubusercontent.com/51991544/79630605-0be44780-8153-11ea-912a-6d693d34c645.png)

**Comment by dunxen** [comment]
I could take a crack at this. 🙂

**Comment by StriderDM** [comment]
@duncandean contributions are welcome :)

**Comment by flipchan** [comment]
redo this function then 
https://github.com/tari-project/tari/blob/4039de1a6f6d7223c7c179e0db7aa53533216e6f/applications/tari_base_node/src/cli.rs#L106

**Comment by flipchan** [comment]
you want to fingerprint stdout then , which is different libc functions on different sys

https://github.com/eminence/terminal-size/blob/master/src/unix.rs here is one with *unsafe* rust

**Comment by flipchan** [comment]
cat src/main.rs
```rust   
root@burk0:/tmp/asd# cat src/main.rs 
use libc::ioctl;
use libc::isatty;
use libc::{winsize as WinSize, TIOCGWINSZ};



fn main() {
        let fd = libc::STDOUT_FILENO;
        let is_tty: bool = unsafe { isatty(fd) == 1 };
    if !is_tty {
        panic!("no tty");
    }
    let mut winsize = WinSize {
        ws_row: 0,
        ws_col: 0,
        ws_xpixel: 0,
        ws_ypixel: 0,
    };
    if unsafe { ioctl(fd, TIOCGWINSZ.into(), &mut winsize) } == -1 {
        panic!("nope");
    }
    let rows = winsize.ws_row as usize;
    let cols = winsize.ws_col as usize;
    if rows > 0 && cols > 0 {
        println!("fluff: {} {}",cols, rows) 
        }
        let fluff = "h".repeat(cols);
    println!("{}", fluff);

}
```

**Comment by flipchan** [comment]
Working:
![terminal resize](https://i.imgur.com/8CyzWLz.png)

**Comment by flipchan** [comment]
working code:
```rust
use libc::ioctl;
use libc::isatty;
use libc::{winsize as WinSize, TIOCGWINSZ};

fn box_line(length: usize, is_top: bool) -> String {
    if length < 2 {
        return format!("");
    }
    if is_top {
        format!("{}{}{}", "┌", "─".repeat(length - 2), "┐")
    } else {
        format!("{}{}{}", "└", "─".repeat(length - 2), "┘")
    }
}

fn box_data(data: String, target_length: usize) -> String {
    let padding = if ((target_length - 2) / 2) > (data.chars().count() / 2) {
        ((target_length - 2) / 2) - (data.chars().count() / 2)
    } else {
        0
    };
    let mut s = format!("{}{}{}{}", " ".repeat(padding), data, " ".repeat(padding), "│");
    // for integer rounding error, usually only 1 char, to ensure border lines up
    while s.chars().count() < target_length - 1 {
        s = format!("{}{}", " ", s);
    }
    format!("{}{}", "│", s)
}


fn main() {
	let fd = libc::STDOUT_FILENO;
	let is_tty: bool = unsafe { isatty(fd) == 1 };
    if !is_tty {
        panic!("no tty");
    }
    let mut winsize = WinSize {
        ws_row: 0,
        ws_col: 0,
        ws_xpixel: 0,
        ws_ypixel: 0,
    };
    if unsafe { ioctl(fd, TIOCGWINSZ.into(), &mut winsize) } == -1 {
        panic!("nope");
    }
    let rows = winsize.ws_row as usize;
    let cols = winsize.ws_col as usize;
    if rows > 0 && cols > 0 {
        println!("fluff: {} {}",cols, rows) 
	}
	let fluff = "h".repeat(cols);
	println!("{}",box_line(cols, true));
	let rows = rows-3;
	for tari in 0..rows{
		println!("{}", box_data("test".to_string(),cols))
		}
	println!("{}",box_line(cols, false));
//    println!("{}", fluff);

}

```

**Comment by flipchan** [comment]
Working when resizing terminals in tmux
first smaller one:
![first](https://i.imgur.com/lXgyREM.png)
then make the window bigger:
![second](https://i.imgur.com/H1HgoWV.png)
and re run the script it finds the new screen width
![third](https://i.imgur.com/0WKfFQi.png)

**Comment by flipchan** [comment]
lets give find terminal size in to a function:
```rust
//give me the width and height of your terminal size
fn gimmesize() -> (usize, usize) {
        let fd = libc::STDOUT_FILENO;
        let is_tty: bool = unsafe { isatty(fd) == 1 };
    if !is_tty {
        panic!("no tty");
    }
    let mut winsize = WinSize {
        ws_row: 0,
        ws_col: 0,
        ws_xpixel: 0,
        ws_ypixel: 0,
    };
    if unsafe { ioctl(fd, TIOCGWINSZ.into(), &mut winsize) } == -1 {
        panic!("nope");
    }
    let height = winsize.ws_row as usize;
    let width = winsize.ws_col as usize;
        return (width, height);
        }


```

**Comment by flipchan** [comment]
tried with gimmesize function and works will push to dev branch
![tari with better ui](https://i.imgur.com/uZwMX8o.png)

upper one is with the update and lower one is regular

**Comment by StriderDM** [comment]
@flipchan Looks good, mind submitting a PR for this and then we can review it?

**Comment by zhangcheng** [comment]
The above code snippets from @flipchan can only determine the size of the current terminal, but lack of a way to resize it.
Nonetheless, the knowledge in it leads me to discover the [crossterm](https://github.com/crossterm-rs/crossterm) crate, which solves the problem nicely. Hence PR #3827.
