### ISSUE TITLE
[Feature] Ability to include default amount and note in deep link

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1742]
**Acceptance Criteria**

- In deep link, we should be able to include not just the recipient, but also the parameters that autofill the amount and the note, e.g. "?amount=32.1" and "note='thanks!!!'
- When user opens app to deep link, they should still land on the Recipient screen they way they do now, and be able to tap through the rest of the transaction screens and make changes to the amount and the note if they wish

**Comment by Tas4tari** [comment]
@talmahaj Closing off this ticket as component tickets have been released, tested and closed off
