### ISSUE TITLE
[Feature] Ability to cancel transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1743]
Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5eaba80ec87c72af43ef0dfb

**Acceptance Criteria**

- Cancel Transaction button should appear to Sender as soon as transaction is initially sent, and only disappear once transaction is broadcast to mempool

- When user hits Cancel Transaction button, a standard alert should appear reading:
“Are you sure?”
“You will have to start a new transaction if you change your mind.”
“Not now” “Yes, Cancel”

**Comment by Tas4tari** [comment]
Closing as this has been released
