### ISSUE TITLE
[Feature] Store & Forward - Addl UX improvements

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1750]
We've gotten approval on some improvements to help address the mobile team's concerns about not providing the user enough feedback as to the transaction's status, and confusion by internal testers. Yay!

**Acceptance Criteria**

1. Remove animation on top right of In Progress section on transactions list screen. It makes sense for transactions that are only in progress for a few minutes due to being mined, but not for ones that are being stored and forwarded.

2. Transaction detail page should show similar element to status bar:
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ea140123e3c6e8753894e7c
Depending on status, copy should read:
"Waiting for recipient to accept transaction" (not accepted)
"Waiting for sender to complete transaction" (accepted, not broadcasted)
"Completing final processing…" (broadcast)

(do you guys have ideas for better wording for the last one, btw? I don't love "completing final processing..." but I wanted to indicate to the user that they were at the finish line)

@karim-tari is also going to spend more time exploring Kutsal's idea when possible too!

**Comment by kukabi** [comment]
Final step name ideas: just "Final processing...", "Registering transaction...", "Publishing transaction..." (it isn't actually publishing, but trying to think what would make sense from a non-tech user's point of view). @talmahaj @Karim-tari @CjS77 @Jasonvdb

**Comment by talmahaj** [comment]
@kukabi the latter two would mean nothing to me as a non-tech user, but I wanted to make it clear something is currently happening which is why I had it as "Completing final processing..." instead of just "Final processing"

**Comment by Tas4tari** [comment]
@talmahaj Closing this this ticket off as the related component tickets have been tested and closed off
