### ISSUE TITLE
error: failed to run custom build command for `prost-build v0.6.1`

### ISSUE THREAD

**Issue by LukasRada** [tari-project/tari#1781]
**Describe the bug**
Running `cargo build --release` command ends with error:
```
error: failed to run custom build command for `prost-build v0.6.1`

Caused by:
  process didn't exit successfully: `/root/tari/target/release/build/prost-build-567322a74cee75bf/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To Reproduce**
1. Clone default branch (development)
2. Run command `cargo build --release`

**Expected behavior**
Successfully build app

**Machine:**
```
lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A7
Stepping:            r0p3
CPU max MHz:         2000.0000
CPU min MHz:         200.0000
BogoMIPS:            12.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae
```

OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

**Comment by CjS77** [comment]
@sdbondi - Is this fixed by #1790 ?

**Comment by sdbondi** [comment]
@CjS77  Nope - this error is because the protoc binary is not installed. Instructions for apt were PRd here: https://github.com/tari-project/tari/pull/1800 

@LukasRada try 
```
apt install libprotobuf-dev protobuf-compiler
```

**Comment by CjS77** [comment]
Ok, thanks @sdbondi. 

I'm going to close this since the solution is already present.

**Comment by dominick2088** [comment]
@LukasRada cool！just ：apt install libprotobuf-dev protobuf-compiler  thank you ，bro

**Comment by dominick2088** [comment]
@sdbondi cool！just ：apt install libprotobuf-dev protobuf-compiler thank you ，bro

**Comment by Zeus-Adin** [comment]
thanks @sdbondi, very helpful

**Comment by ekomic** [comment]
> ```
> apt install libprotobuf-dev protobuf-compiler
> ```

this did not work for me

**Comment by delta1** [comment]
@ekomic make a new issue posting the error message you are getting

**Comment by Kartos102** [comment]
sudo apt install libprotobuf-dev protobuf-compiler

it works for me

**Comment by ashWhiteHat** [comment]
I use alpine and fix with.
```
apk add protoc
```

**Comment by ppdouble** [comment]
> [@CjS77](https://github.com/CjS77) Nope - this error is because the protoc binary is not installed. Instructions for apt were PRd here: [#1800](https://github.com/tari-project/tari/pull/1800)
> 
> [@LukasRada](https://github.com/LukasRada) try
> 
> ```
> apt install libprotobuf-dev protobuf-compiler
> ```

Try ` dnf install protobuf-devel` for Fedora 41.
