### ISSUE TITLE
Launch QA : When a user receives Tari, the fee seems to be deducted from the receiver on Android

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1782]
**Description**
When a user receives Tari, it seems like the fee is being deducted from the Recipient as the transferred amount is short

**Expected behavior**
Fee should be deducted from Sender only

**Screenshots**
![Screenshot_20200428-111710](https://user-images.githubusercontent.com/50987039/80581542-94919c00-8a0d-11ea-9a3c-d769a877c39d.jpg)
![IMG_3650](https://user-images.githubusercontent.com/50987039/80581557-9b201380-8a0d-11ea-9a4d-441b7dc0cdfd.PNG)

 **Logs**
[ffi_logs_E00EB1939AA9F2C7289DBD04A2D97D1BC22DDA720533ABEA8C0BDF156213F773.zip](https://github.com/tari-project/tari/files/4550858/ffi_logs_E00EB1939AA9F2C7289DBD04A2D97D1BC22DDA720533ABEA8C0BDF156213F773.zip)

**Comment by Tas4tari** [comment]
Logs received from John Davies via Telegram, he is experiencing the same issue as above:
[ffi_logs_405287D508E21BC6C1DA659DE2D5A963A375E0E496C586B59718BC14B5EADD04.zip](https://github.com/tari-project/tari/files/4553994/ffi_logs_405287D508E21BC6C1DA659DE2D5A963A375E0E496C586B59718BC14B5EADD04.zip)

**Comment by Tas4tari** [comment]
Users on Telegram reporting that their balances have dropped to 0

**Comment by CjS77** [comment]
My immediate reaction is that this is some rounding error issue, because senders definitely pay fees.

The logs should tell us the actual amounts that were used in the transaction.

**Comment by StriderDM** [comment]
Have had a look at the logs, amount received was `8999.999488`
```
2020-04-28 11:09:36.176553629] wallet::transaction_service::service] INFO  Transaction (TX_ID: 11544006460190926997) - Amount: 8999.999488 T - Message: Tari-1017
```

However I think there may be a problem with this issue:
The first screenshot shows the transaction was received at April 28 2020, 11:09 AM
The second screenshot shows the transaction was sent at April 28 2020, 1:09 PM

False positive?

**Comment by Tas4tari** [comment]
@StriderDM Will verify with the initial reporters and provide more information

**Comment by StriderDM** [comment]
Should be fixed by https://github.com/tari-project/wallet-android/pull/337

**Comment by Tas4tari** [comment]
@StriderDM Both Robin and Leland were in different timezones at the time the transaction took place:
Robin was in CT (St. Louis) and Leland was in PT (Oakland)

**Comment by philipr-za** [comment]
Can this be closed?

**Comment by Tas4tari** [comment]
@philipr-za Will test this today before closing to ensure we don't see this error again

**Comment by Tas4tari** [comment]
Tested, works as expected. Screenshots attached.
**Payment Sent:**
![Screenshot_20200518_100811_com tari android wallet](https://user-images.githubusercontent.com/50987039/82189501-ca7cbe80-98ef-11ea-9529-5d39211fe504.jpg)

**Payment Received:**
<img width="324" alt="Screen Shot 2020-05-18 at 10 08 37 AM" src="https://user-images.githubusercontent.com/50987039/82189457-b638c180-98ef-11ea-8b78-f4896ae6e44c.png">
