### ISSUE TITLE
Launch QA : Transactions still in progress on App and some users are unable to send transactions whilst in this state

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1783]
**Description**
Txns still in progress

**Reporter**
Jason Lau

**Smartphone:**
Network: rincewind
Phone: iPhone 11 Pro Max
iOS: 13.4
App version: 0.1.0
App build: 64
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-04-28_12-15-13-bug-report.zip](https://github.com/tari-project/tari/files/4550894/2020-04-28_12-15-13-bug-report.zip)

**Comment by Tas4tari** [comment]
**Additional Feedback**
Another user seems to be having a similar issue whereby Sending transactions are stuck in a processing state.

**Reporter**
Brent Parks

**Smartphone:**
Network: rincewind
Phone: iPhone X
iOS: 13.4.1
App version: 0.1.0
App build: 64
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-04-28_21-36-40-bug-report.zip](https://github.com/tari-project/tari/files/4550909/2020-04-28_21-36-40-bug-report.zip)

**Comment by Anziskavds** [comment]
I have the same issue. I've sent tXTR from my Android device to my iOS device. The payment stays in progress and this is been in progress for almost 2 hours now. I still haven't received any notification on my iOS device that a payment was sent to me but on my Android device it says it's waiting for the recipient to accept the transaction. Because of this, I am unable to do any other payments.

**Comment by Tas4tari** [comment]
Issue reported by Jessi as well:
**What happened? (Crash/strange behavior)**
Can’t send any amount of txtr because I have one pending transaction that’s been hanging since yesterday afternoon. 

**What did you expect to happen?**
Include cancel transaction option for pending transfers that haven’t been accepted by recipient so that other transactions can occur

**Device:**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.4.1
App version: 0.1.0
App build: 64
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Screenshot:**
![image1](https://user-images.githubusercontent.com/50987039/80679730-bb0f1000-8abd-11ea-83a0-0206d8cfc393.png)
![image0](https://user-images.githubusercontent.com/50987039/80679741-c2ceb480-8abd-11ea-811b-c38c9f6054dd.png)

**Logs:**
[2020-04-29_09-25-37-bug-report.zip](https://github.com/tari-project/tari/files/4556500/2020-04-29_09-25-37-bug-report.zip)

**Comment by Tas4tari** [comment]
Reported by Naveen:

**Description:**
Transactions stuck in progress

**Smartphone:**
Network: rincewind
Phone: iPhone XS Max
iOS: 13.4.1
App version: 0.1.0
App build: 64
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-04-30_22-42-11-bug-report.zip](https://github.com/tari-project/tari/files/4571031/2020-04-30_22-42-11-bug-report.zip)

**Comment by Tas4tari** [comment]
**Reported by: **
Scott Hamilton

**Description:**
Transaction “in progress” for like 20 hours*Smartphone:**

**Smartphone:**
Network: rincewind
Phone: iPhone 8 Plus
iOS: 13.4.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-04-30_18-58-42-bug-report.zip](https://github.com/tari-project/tari/files/4571053/2020-04-30_18-58-42-bug-report.zip)

**Comment by CjS77** [comment]
Related to #1804; Closing in favour of that proposal.
