### ISSUE TITLE
Launch QA: Transaction took more than 8 hours to go through to recipient

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1784]
**Description**
Sent Tash (🎧💎🎢🙄🦄🔭🐒🏠🚒😛🚧🧣🤑💙🎧🥜🐸⛳🚢⏰🍞🤪👐🦄🎻🐮🍖🍉😀🐚📖👨😷) some tXTR yesterday and it's still in progress today. She finally received it more than 8 hours after I had initiated the transaction

**Expected behavior**
Expected her to get the tXTR soonish after I sent it

**Reporter:**
Shannon Tenner

**Screenshots**
![image0](https://user-images.githubusercontent.com/50987039/80582883-c3107680-8a0f-11ea-8d26-4551fc56a131.png)

**Smartphone:**
Network: rincewind
Phone: iPhone 8
iOS: 13.3.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-04-29_09-00-47-bug-report.zip](https://github.com/tari-project/tari/files/4550948/2020-04-29_09-00-47-bug-report.zip)

**Comment by CjS77** [comment]
Possibly related to #1804 - S&F retrieval also looks unreliable.

**Comment by Tas4tari** [comment]
Re-tested this with Shannon and Payment received within 15 minutes of the transaction occurring, @philipr-za can this be closed or is there anymore work being completed on this?
