### ISSUE TITLE
Launch QA: user is unable to build valid blocks

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1786]
**Description**
Seth Simmons, [Apr 28, 2020 at 9:59:53 PM]:
Weird, looks like I can’t build valid blocks: Block validation failed because the block has invalid input: 324ae264d5e80b0aea8d05eb9a68a4f0fe367ee234ba16aaace024da601ed55c

Get that for every block I mine

But I can’t cancel that input, and don’t see it in mempool either

**Expected behavior**
User should be able to build valid blocks

**Reporter:**
Seth Simmons

**Source**
Telegram

**Additional Notes:**
Logs received

**Logs:**
[base_layer_invalid_blocks.zip](https://github.com/tari-project/tari/files/4552330/base_layer_invalid_blocks.zip)

**Comment by clemperorpenguin** [comment]
I am also experiencing this issue. Logs are attached.
[base_layer_logs.zip](https://github.com/tari-project/tari/files/4554624/base_layer_logs.zip)
