### ISSUE TITLE
Launch QA: Critical error in back-end

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1788]
**Description**
There appears to be a critical error on the back end:Could not create LMDB store:An LMDB error occurred:There is not enough space on the disk.

**Reporter**
@pussinboots

**Source:**
Telegram

**Comment by CjS77** [comment]
Assuming this is a Windows install; since it's a know issue that LMDB wants to allocate the entire DB page space on disk at start-up, which is set at 50GB.
