### ISSUE TITLE
Launch QA: Tari Wallet balance is incorrect

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1789]
**Describe the bug**
My balance is not correct. I should have a few thousand but only have ~200 now? 

**Additional Info:**
just added up all my transactions. I should have like 19000 but it's only on 796

**Expected behavior**
User should have more tari

**Reporter:**
Shannon Tenner

**Screenshots**
![IMG_9862](https://user-images.githubusercontent.com/50987039/80605640-a0905480-8a33-11ea-8345-96b37b173ca4.PNG)
![IMG_9861](https://user-images.githubusercontent.com/50987039/80605666-a8e88f80-8a33-11ea-877d-9d213f40f031.PNG)
![IMG_9859](https://user-images.githubusercontent.com/50987039/80605694-b271f780-8a33-11ea-8d2d-4f0e7bffd8e9.PNG)
![IMG_9860](https://user-images.githubusercontent.com/50987039/80605713-b7cf4200-8a33-11ea-89ff-bbcb612b2487.PNG)

**Smartphone:**
Network: rincewind
Phone: iPhone 8
iOS: 13.3.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-04-29_15-52-47-bug-report.zip](https://github.com/tari-project/tari/files/4552144/2020-04-29_15-52-47-bug-report.zip)

**Comment by Tas4tari** [comment]
@philipr-za More information:
Something similar seems to be occurring with an Android user from Telegram though on a much smaller scale.
The user says that his balance displays as 10 Tari, however he has 30 and can still send more than 10, no screenshots or logs were posted and neither was a bug logged by him

**Comment by Tas4tari** [comment]
Reported by Jason Lau:
**What happened? (Crash/strange behavior)**
Balance is zero
**What did you expect to happen?**
Balance was 10k last time I logged in 

**Smartphone:**
Network: rincewind
Phone: iPhone 11 Pro Max
iOS: 13.4.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-05-04_00-34-59-bug-report.zip](https://github.com/tari-project/tari/files/4574205/2020-05-04_00-34-59-bug-report.zip)

**Comment by Tas4tari** [comment]
Had another report of this by a user where their balance is incorrect:

**What did you expect to happen?**
Sent 3000 tXTR, it took off 6000. All transaction history is in this screenshot:

**Reporte:**
Aaron M

**Device:**
Network: rincewind
Phone: iPhone 7
iOS: 13.5
App version: 0.1.14
App build: 93
App environment: production
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Screenshot:**
![24a5d3c3-c004-4634-988d-0079a620ca8f](https://user-images.githubusercontent.com/50987039/83996697-0b9b4800-a95d-11ea-84ca-f036a092fa35.png)

**Comment by philipr-za** [comment]
Has this been reproduced recently? If not I think we can consider this resolved with recent app updates.

**Comment by Tas4tari** [comment]
@philipr-za Haven't seen another instance of this so will close for now
