### ISSUE TITLE
Launch QA: Sync Status feedback

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1792]
Due to the feedback we've from users on Telegram it would be good to provide feedback for users on the Sync status

From Lee: sync status would be like X blocks to go or percent would be a big winner

**Comment by SWvheerden** [comment]
#1815

**Comment by SWvheerden** [comment]
#1880 address this

**Comment by Tas4tari** [comment]
@SWvheerden Can I close this off?

**Comment by SWvheerden** [comment]
yes I think so
