### ISSUE TITLE
Can initiate transfer of XTR to base node public key from CLI

### ISSUE THREAD

**Issue by philkode** [tari-project/tari#1799]
**Describe the bug**
Currently it's possible to initiate an XTR transaction to a base node public key in the CLI using the "send-tari" command. As there's no wallet on the other end, the transaction gets stuck on the sending wallet.

**Expected behavior**
Would expect the sending wallet to cancel the transaction if it discovers the recieving address as a base node. A stopgap measure would be the ability to cancel the pending transaction, which seems to be coming in a future version.

**Comment by CjS77** [comment]
In the CLI, the `cancel-transaction` command exists as a workaround, 
but agree that this is undesirable behaviour

**Comment by philipr-za** [comment]
Once the connectivity manager is in it might be possible to for the wallet to know it has made a direct connection and the Transaction has been sent but the recipient, which we are sure received the initial send-tari message, did not respond.

**Comment by SWvheerden** [comment]
connectivity manager is merged in, this will also not be an issue anymore because sending wallets will cancel stale transactions after a whole if the receiver does not respond
