### ISSUE TITLE
Launch QA: Mining: User tried to send tXTR for payment from the node but was unsuccessful

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1801]
**Describe the bug**
Have been trying to send tXTR that I mined since the moment I made this order (TTL Store order), but have been unable to get them to go through despite many attempts. All Tx get stuck at “CollectingSingleSignature” and never are visible in my Aurora wallet from my node.

Let me know how I can help test/resolve this, happy to help in any way!

**Reporter:**
Seth Simmons

**Logs**
[failed_to_send_1.zip](https://github.com/tari-project/tari/files/4571098/failed_to_send_1.zip)
[failed_to_send_2.zip](https://github.com/tari-project/tari/files/4571102/failed_to_send_2.zip)

**Additional Info from reporter**
Just another follow up — after sending those logs, I purged out all of .tari and rebuilt after a git pull, then let my base node sync up again from scratch.

Once I got synced up, I was finally able to mine perfectly (already 80+ blocks mined successfully), and was able to send out those funds perfectly, no issues or delays at all.

Thanks for all you guys hard work on this, can’t wait to see Tari continue to grow!

**Comment by CjS77** [comment]
The initial issue is indicative of not being able to reach the wallet; or the return message got lost.

#1804 is designed to help with this. So closing in favour of that issue.
