### ISSUE TITLE
Same recipient, multiple transactions in pending state (24+ hours)

### ISSUE THREAD

**Issue by mfoolb** [tari-project/tari#1803]
I've been able to mine/send/receive transaction, and I still am, but three different transactions to the same recipient (TTL store) have been in pending state for a while.

Transaction ID: 15045252419189997262, 10410759071074328996 and 9196655905677161753.
Status for all three: Pending
Sender state for all three: CollectingSingleSignature(11 input(s), 1 output(s))
Timestamp: 2020-05-02 10:25:24, 2020-05-02 10:32:08 and 2020-05-02 10:23:38.

Balance has a Pending outgoing balance of 182601.494371 T (more than the total pending transaction value plus showed fees).

Let me know if it could be useful to investigate.

Keep up the good work.

Tari base node Version 0.2.1-ecfe782-release on Ubuntu.

15045252419189997262 | e00eb1939aa9f2c7289dbd04a2d97d1bc22dda720533abea8c0bdf156213f773 | 60000.000000 T | 1000 µT | Pending | CollectingSingleSignature(11 input(s), 1 output(s)) | 2020-05-02 10:25:24 | TARI-1093 
10410759071074328996 | e00eb1939aa9f2c7289dbd04a2d97d1bc22dda720533abea8c0bdf156213f773 | 60000.000000 T | 1000 µT | Pending | CollectingSingleSignature(11 input(s), 1 output(s)) | 2020-05-02 10:32:08 | TARI-1093 
9196655905677161753  | e00eb1939aa9f2c7289dbd04a2d97d1bc22dda720533abea8c0bdf156213f773 | 60000.000000 T | 1000 µT | Pending | CollectingSingleSignature(11 input(s), 1 output(s)) | 2020-05-02 10:23:38 | TARI-1093

**Comment by CjS77** [comment]
Similar to #1804 - Will close in favour of that issue
