### ISSUE TITLE
Monitor transaction counterparties with Liveness service and resend Tx Replies and Tx Finalized messages

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1804]
Currently a Wallet that is a Transaction Sender that sends a transaction but has not received a Reply will monitor the Recipient for liveness using the Liveness service (PR https://github.com/tari-project/tari/pull/1777). If the Recipient comes online and hasn't sent a reply yet the transaction will be sent again.

However, a wallet that is the Recipient of a Transaction will only send the Transaction Reply once via Store and Forward and attempt to send it once directly. 

It would be more robust if the Recipient wallet uses the Liveness service to monitor if their transaction counterparty's come online. If they do come online and they have not yet sent the Transaction Finalized messages then the Recipient wallet should resend the Tx Reply to have the Sender wallet complete the transactions.

It is also possible that that the Transaction Finalized message did not make it back to the Tx Recipient wallet so if a Transaction Sender wallet receives a Tx Reply for a completed transaction it should still send the Tx Finalized message so that the Recipient can close out the transaction.

**Comment by CjS77** [comment]
Sounds like a decent strategy
