### ISSUE TITLE
Add support for detecting and manage re-orgs to the wallet

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#1807]
Currently the wallet does not monitor or handle reorgs at all except to invalidate outputs that are no longer in the chain.

The wallet should be able to detect that a re-org has occurred and figure out which transactions and outputs were affected and update its state to reflect the new chain state. Features required for this:
- Detect which transactions have been lost from the blockchain using their Kernels.
- If a transaction has been reorged out of the chain is it in the Reorg pool to be included in a later block or is it gone forever?
- Update all transaction lists accordingly
- Detect if outputs have become spendable again and update the wallet balance accordingly

**Comment by philipr-za** [comment]
https://github.com/tari-project/tari/issues/2208 is a sub issues of this issue. By validating STXO's we will make funds that are erroneously flagged as spent spendable again but there is still value in marking Transactions that were reorged with some sort of status to indicate what happened to them.

**Comment by stringhandler** [comment]
This is solved by tracking the mined height and hash in the wallet
