### ISSUE TITLE
[Bug] illegal instruction

### ISSUE THREAD

**Issue by leet4tari** [tari-project/tari#1811]
When running the ```tari_base_node```, all that is returned is ```Illegal instruction: 4```

**To Reproduce**
1. On OSX 10.10.5 (Yosemite), download the pkg and install
2. Run ```tari_base_node``` in a terminal ...
```Illegal instruction: 4```  
  
**Expected behavior**
Generally expect the tari_base_node to start.

**Screenshots**

**Desktop:**
 - OSX 10.10.5 (Yosemite)
 - tari_base_node-osx-10.15-0.2.1.pkg - https://www.tari.com/binaries/tari_base_node-osx-10.15-0.2.1.pkg

**Comment by LeeNX** [comment]
Checking if Hardware is 64bit ...
```
CLees-MacBook-Pro:~ leet$ sysctl machdep.cpu
machdep.cpu.max_basic: 13
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz
machdep.cpu.family: 6
machdep.cpu.model: 23
machdep.cpu.extmodel: 1
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 10
machdep.cpu.feature_bits: 290732854951541759
machdep.cpu.extfeature_bits: 4832888832
machdep.cpu.signature: 67194
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 XSAVE
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF
machdep.cpu.logical_per_package: 2
machdep.cpu.cores_per_package: 2
machdep.cpu.microcode_version: 2571
machdep.cpu.processor_flag: 7
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 51520032
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 0
machdep.cpu.thermal.invariant_APIC_timer: 0
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 0
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 0
machdep.cpu.thermal.hardware_feedback: 1
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.xsave.extended_state: 3 576 576 0
machdep.cpu.arch_perf.version: 2
machdep.cpu.arch_perf.number: 2
machdep.cpu.arch_perf.width: 40
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.events: 0
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 40
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 12
machdep.cpu.cache.size: 3072
machdep.cpu.tlb.inst.small: 128
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.data.small: 16
machdep.cpu.tlb.data.small_level1: 256
machdep.cpu.tlb.data.large: 16
machdep.cpu.tlb.data.large_level1: 32
machdep.cpu.address_bits.physical: 36
machdep.cpu.address_bits.virtual: 48
machdep.cpu.core_count: 2
machdep.cpu.thread_count: 2
```
Checking if OS is 64bit ...
```
CLees-MacBook-Pro:~ leet$ uname -a
Darwin CLees-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
```

**Comment by LeeNX** [comment]
Checking brew installed components, need the following packages: 
 - sqlite
 - tor  
  
Good to have:
 - torsocks
 - wget  
  
Seems there is a problem with brew
```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `source' for nil:NilClass
```
Looking too resolve before moving forward, if it's possible to resolve on this old Mac Book Pro.

**Comment by LeeNX** [comment]
Some how, XCode did not install?  
```
CLees-MacBook-Pro:~ leet$  brew config
HOMEBREW_VERSION: 2.2.14-72-ge1f3b0b
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1f3b0b971dccb72780b2ef33fafde158cb3909e
Last commit: 12 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 012da54a8e6783595e26a87d87e5b12cffea6a42
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 2
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 7.0 build 700
Git: 2.21.0 => /usr/local/opt/git/bin/git
Curl: 7.43.0 => /usr/bin/curl
macOS: 10.10.5-x86_64
CLT: 7.2.0.0.1.1447826929
Xcode: N/A
```

**Comment by leet4tari** [comment]
Had to track down an old XCode that works with this version of OSX - https://xcodereleases.com/  
  
XCode v7.2.1 4.5GB download and install, now can do brew install openssl, see if this helps with my issue and move forward from there.

**Comment by CjS77** [comment]
This issue has cropped up a few times when running `tari_base_node` binaries (compiled on Catalina) on earlier OSX version.

Out of curiosity, Can you build from source and run on Yosemite?

We might have to 
a) look for a way to build binaries for different OSX versions
b) Mark the binaries as unsupported for incompatible versions and leave the build from source option (to be fair, it's not that more complicated -- install deps & rust and `cargo install tari_base_node`)

**Comment by leet4tari** [comment]
Way too much compiling and on this little old and slow MacBookPro, I think we limit binary archive support to what Apple/Brew supports for OSX - https://docs.brew.sh/Installation#macos-requirements  
```
macOS Requirements:
    A 64-bit Intel CPU 1
    macOS High Sierra (10.13) (or higher) 2
    Command Line Tools (CLT) for Xcode: xcode-select --install, developer.apple.com/downloads or Xcode 3
    A Bourne-compatible shell for installation (e.g. bash or zsh) 4
```
Half the day yesterday was used on brew downloading and compiling all packages needed to support the tari_base_node.  
  
On better supported OSX releases, these libraries and tools, like tor, come down as pre-compiled binary packages.

**Comment by leet4tari** [comment]
Backtrace by @Krakaw , shows randomx references, could be the lack of AES instructions set in the older Mac, compared to a new i7 with - ```sysctl machdep.cpu.features```:
```
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
```

**Comment by CjS77** [comment]
https://github.com/tari-project/randomx-rs/pull/23 helps

**Comment by CjS77** [comment]
RandomX won't compile with certain optimisations on by default now; If you're a miner and need this, you'll want to BYO

**Comment by leet4tari** [comment]
Build a VM without AVX/AVX2 ...

cat /proc/cpuinfo
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
```
vs feauture fill on my native CPU support
cat /proc/cpuinfo
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
```
Running for about 30min or so, we see the ```Illegal instruction``` ...
```
>> get-chain-metadata
Height of longest chain : 463
Geometric mean of longest chain : 2120971
Best_block : 0a1e799ae6724c5ffe6738325c6347c05a63f71816ab0532c961f78c6f645243
Pruning horizon : 0

>> Illegal instruction (core dumped)
```
Re-run and get the ```Illegal instruction``` in 5min. I think we have a reproducible environment.
[Vagrantfile.zip](https://github.com/tari-project/tari/files/4661612/Vagrantfile.zip)

**Comment by leet4tari** [comment]
Feature fill VM ran beyond chain 463
```
>> get-chain-metadata
Height of longest chain : 1150
Geometric mean of longest chain : 2545975
Best_block : 0a00e76608042125a76e662078fa67ca4395a469a4d5b583d3a1c28e4466594a
Pruning horizon : 0
```

**Comment by leet4tari** [comment]
With ```RandomX``` disabled for now, we have tracked down another culprit - ```croaring-rs``` https://github.com/saulius/croaring-rs/blob/master/croaring-sys/build.rs#L10  
  
Basically croaring-rs builds with native CPU instruction set support, which can be a problem when compiled on faster machines and then run on older and less feature rich CPU instructions.  
  
Tested with branch https://github.com/tari-project/tari/tree/croaring-remove-march-native  
  
Need to make a PR that supports passing CPU build flag, thinking creating a build feature?

**Comment by leet4tari** [comment]
Just as a note - https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html  
  
Are options, if supported on the platform.

**Comment by leet4tari** [comment]
Since https://github.com/tari-project/tari/pull/2020 source code builds can target CPU instruction sets

 ```
export RUSTFLAGS="-C target_cpu=x86-64"
export ROARING_ARCH="x86-64"
cd applications/tari_base_node
cargo build --bin tari_base_node --release --features safe
 ```
  
As of release v0.5.4, some basic binary builds can be found at https://www.tari.com/downloads/
 - minimum set  ```x86-64/safe```
 - medium set  ```ivybridge/safe```
 - higher set ```ivybridge/avx2```
