### ISSUE TITLE
start_tor.sh not included in Ubuntu ZIP

### ISSUE THREAD

**Issue by yidakee** [tari-project/tari#1819]
Apparently, there is a missing .sh file in the Ubuntu ZIP file, with the following

`tor --allow-missing-torrc --ignore-missing-torrc --clientonly 1 --socksport 9050 --controlport 127.0.0.1:9051 --log "notice stdout" --clientuseipv6 1`

Using the URL - https://www.tari.com/binaries/tari_base_node-ubuntu-0.2.1-23677a7.zip

.

**Comment by leet4tari** [comment]
Fixed with https://github.com/tari-project/tari/pull/1838 and should be included since v0.2.3.

**Comment by Tas4tari** [comment]
@leet4tari Since the fix went in can this issue be closed off?

**Comment by Tas4tari** [comment]
As per @leet4tari comment, closing this issue off as I see the corresponding ticket was merged
