### ISSUE TITLE
[Feature] Open TTL Store in in-app browser

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1843]
To keep the users in the Tari Aurora app, we'd like to open the TTL store in an in-app browser instead of linking out to an external browser

Specs and Assets: http://zpl.io/bzEMWAG (toggle to Assets tab to get icons)

Animation: See in-app browser in Instagram: https://app.asana.com/app/asana/-/get_asset?asset_id=1169169367013234&amp;force_download

**Acceptance Criteria**
- When tapping to open the TTL store from the modal in the app, an in-app browser should slide up from the bottom of the screen (like in Instagram or Pinterest) rather than opening the link in the user's default browser
- Users should be able to hit the X icon on the top left or swipe down on the drawer to close the browser
- Users should be able to navigate forward and back with the arrows at the bottom of the in-app browser
- Back and/or forward arrow should be color #B8B8B8 when disabled (that is, when user cannot navigate forward or back)
- Users should be able to hit the Share icon to open their OS's default sharesheet (android) or share extension (ios) to share the store, get the link, or open it in their browser

**Open Questions**

What are the default options that appear when implementing the sharesheet on Android and share extension on iOS? I looked through the documentation but it still wasn't clear to me. E.g. not sure if the "Open in Safari" option seen in the Instagram share extension (below) appears by default in all in-app browsers in iOS, but since the designers didn't include a separate button to pop out the browser if the user wants to I'm hoping we get that by default...

![androidsharesheet.jpg](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/068b526b-4b85-4feb-aba1-43a717d0f437)![androidsharesheetcollapsed.jpg](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/70240f06-0bcc-4ac6-9287-6a61d76b980d)

![Screen Shot 2020-05-12 at 12.50.19 AM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/8e246dec-99a7-4831-ba88-d381014e84f2)

**Comment by Tas4tari** [comment]
@talmahaj Closing of this ticket as the component tickets have been tested and closed
