### ISSUE TITLE
Implement Coin Split to address issue of user being unable to transact when a transaction remains In Progress

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1854]
**To address:**
Transactions to TariBot have been In Progress for more than a day and users are unable to transact as they receive the "Hold your horses" error on the wallet.

**Possible solution identified:**
Implementation of a coin-split that will address this issue

**Comment by philipr-za** [comment]
The coin split functionality exists in the Output Manager service. To allow the mobile apps to use this that function should be exposed via the FFI interface.
