### ISSUE TITLE
Wallet: Cancel Transaction: User is unable to cancel a transaction when they select to Cancel

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1891]
**Describe the bug**
User can’t cancel a transaction when hitting the cancel button, an error is received

**Device Info:**
Network: rincewind
Phone: iPhone X
iOS: 13.4.1
App version: 0.1.3
App build: 79
App environment: production
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Screenshot:**
![IMG_3832](https://user-images.githubusercontent.com/50987039/82342297-bd47f880-99f1-11ea-9768-f55e918caf74.PNG)

**Logs:**
[2020-05-19_09-38-56-bug-report.zip](https://github.com/tari-project/tari/files/4651244/2020-05-19_09-38-56-bug-report.zip)

**Comment by talmahaj** [comment]
@Tas4tari Is this meant for the FFI team? I see it's in the main tari repo

**Comment by Tas4tari** [comment]
@talmahaj Logged in the Tari repo because @philipr-za  said there was an issue with the TariBot and that he is investigating, he requested the logs that I had added to the issue as well

**Comment by philipr-za** [comment]
I have been through the logs and don't see anything to explain the behaviour. We haven't been able to reproduce so chalking this up to the malfunctioning  TariBot at the time.
