### ISSUE TITLE
QA: User keeps receiving Network error when on the Tari Wallet 

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1902]
**Description**
As a user I keep receiving the "Its not you, it's the network" error

**Screenshots**
![Screenshot_20200525_141713_com tari android wallet](https://user-images.githubusercontent.com/50987039/82813783-0f779680-9e96-11ea-81da-1ac8534d567b.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P30 lite
 - OS: 10
 - Wallet version: v0.1.13-jnilib-0.10.3

**Logs:**
[ffi_logs_6CD682CB8768ABA5C880B1F7A48D13003DEE515C9E77683A86E2B2D33A932F3C.zip](https://github.com/tari-project/tari/files/4677208/ffi_logs_6CD682CB8768ABA5C880B1F7A48D13003DEE515C9E77683A86E2B2D33A932F3C.zip)

**Comment by talmahaj** [comment]
@Tas4tari I see this is still in awaiting triage under the tari repo, how often do these get triaged? @CjS77 not sure if someone on the team can take a look at these and filter every day

**Comment by Tas4tari** [comment]
@talmahaj Currently working on these issues to establish them to the correct columns/repos

**Comment by Tas4tari** [comment]
@philipr-za I've tested and have not received the network error again, closing this issue, will re-open if i ever experience the issue again

**Comment by Tas4tari** [comment]
@philipr-za I've re-opened this I know this is related to the node issues from Friday, I have confirmed I'm still receiving the error, as has Keith and a Telegram user. It's in the backlog for now, please let me know of there is a more appropriate column I should move this to

**Comment by Tas4tari** [comment]
@philipr-za 
@Anziskavds Has reported seeing this issue pop up again. Below are the logs received:

**Description:**
I'm getting the network error message.

**Public Key:**
9C102DA1A0304A97564914CD7244E2597749F7558A878B17C129A6FE83A72F14

**Logs:**
[ffi_logs_9C102DA1A0304A97564914CD7244E2597749F7558A878B17C129A6FE83A72F14.zip](https://github.com/tari-project/tari/files/4878406/ffi_logs_9C102DA1A0304A97564914CD7244E2597749F7558A878B17C129A6FE83A72F14.zip)

**Comment by philipr-za** [comment]
These logs show that the tested lib seems out of date, there has been a lib update since this issue though I am not sure how it has been deployed.

**Comment by Tas4tari** [comment]
@philipr-za I will confirm with Anziska if she has updated her app

**Comment by philipr-za** [comment]
There is a small issue that would also give this symptom if you have no spentable UTXOs left that should be resolved by this PR: https://github.com/tari-project/tari/pull/2048 but not what these logs show.

**Comment by Tas4tari** [comment]
@philipr-za Anziska has confirmed that she is on the latest version of the wallet app that is on Prod. We can wait for the above PR to be merged and then verify if the error is still being received and go from there

**Comment by Tas4tari** [comment]
Update: Users still intermittently receive network errors on Android until a node has synced

**Comment by Tas4tari** [comment]
@philipr-za @mikethetike This issue seems to have gotten worse on the iOS build whilst @Anziskavds was testing as we have struggled to sync to a base node as well.
User on Telegram has also reported on the issue: Dank Engine
