### ISSUE TITLE
[Mobile Feature] Forced upgrade for breaking changes

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1904]
@jasonvdb @kukabi I can't remember exactly what you had in mind for this, so feel free to fill in the gaps.

**Acceptance Criteria**
- We should have a mechanism that we can enable when making breaking changes, like a network restart, that forces users on earlier versions of the app to upgrade
- The mechanism should pop an alert or screen that informs the user that they must upgrade the app for it to be usable, and ideally the user should not be able to close it
- Ideally the mechanism above can differentiate between breaking changes that *do* require a user to create a new wallet vs. those that don't, so we can show more helpful copy
    - Same wallet: "Update Required" "Please upgrade to the latest version of Tari Aurora to continue using the app."
    - New wallet: "Update required due to reset" "We had to reset the testnet, which means you'll need to upgrade to the latest version of Tari Aurora and create a new wallet to continue using the app."
- We should also ensure that we can restart the onboarding flow in cases like a network restart where the user has to generate a new wallet.

**Comment by Jasonvdb** [comment]
So what we were thinking is maybe passing in the lib version when doing a base node sync and if the base node we're connecting to no longer supports the mobile lib version it would return a specific error code and we could use that to tell the user to update. @philipr-za what do you think? Is there a better way or does this make sense?

**Comment by philipr-za** [comment]
This is possible though it does imply keeping some sort of map of what base node versions are supported by what lib versions.

I am not sure there is a way to ask a base node what version it is running yet but there was talk of it at some stage.
