### ISSUE TITLE
QA: Transaction still in progress

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1909]
**Describe the bug**
a tx will not complete

**Expected behavior**
my subsequent tx to the sender (where I sent them tari) completed, while the original tx remains ‘in progress

**Smartphone (please complete the following information):**
Network: rincewind
Phone: iPhone 8
iOS: 13.4.1
App version: 0.1.3
App build: 79
App environment: production
Reachability: Offline ❌
Base node: Sync failed ❌
Tor ports: Open ✅
Tor status: Connecting ⌛
Tor bootstrap progress: 0%

**Reporter:**
Chris Dohm

**Logs**
[2020-05-22_16-47-39-bug-report.zip](https://github.com/tari-project/tari/files/4681536/2020-05-22_16-47-39-bug-report.zip)

**Comment by CjS77** [comment]
Several improvements to this have been implemented in both FFI and wallet to reduce stuck txs. Empirically this issue is a lot better, so closing for now. Can re-open if issue re-emerges, or more specific details as to cause can be provided.

**Comment by Tas4tari** [comment]
Received another bug report on this:

**User:**
Bernhard Pluess

**Platform:**
- Bug Report

**What happened? (Crash/strange behavior)**
- Transactions stay stuck. Either with message „waiting for sender to complete transaction“ or „completing final processing“

**What did you expect to happen?**
- Transactions to complete

**Smartphone Information:**
Network: rincewind
Phone: iPhone 7
iOS: 13.5.1
App version: 0.3.0
App build: 123
App environment: production
Reachability: WiFi ✅
Base node (t-tbn-nvir): Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-08-05_08-18-30-bug-report.zip](https://github.com/tari-project/tari/files/5026609/2020-08-05_08-18-30-bug-report.zip)


**Image:**
![image0](https://user-images.githubusercontent.com/50987039/89379664-761afb00-d6f6-11ea-8f1b-9a95d39170ba.png)
