### ISSUE TITLE
Allow transaction message to be sent to a peer

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#191]
Send, receive and broadcast a transaction.

1. Initiator creates a new transaction message.
1. Initiator sends encrypted message(s) to recipients.
1. Recipients receive and decrypt the message.
1. Recipients add their data and signatures to the transaction and send a message back to the initiator.
1. Initiator completes transaction and sends the completed transaction message to a full node peer(s).

Child of #183

**Comment by philipr-za** [comment]
Connected to https://github.com/tari-project/tari/issues/291

**Comment by philipr-za** [comment]
Closed by https://github.com/tari-project/tari/pull/638
