### ISSUE TITLE
QA: Sending tXTR from base node to wallet resulted in a bug

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#1911]
**Describe the bug**
Sending tTrx From my base node to my Aurora wallet resulted in a bug
“ hs_client609 send_introduce1” nit sure if this is a base node issue or wallet issue? Heres a photo with the bug log

**Expected behavior**
Expected to send and receive tari from base node wallet 

**Smartphone (please complete the following information):**
Network: rincewind
Phone: iPhone XS
iOS: 13.4.1
App version: 0.1.3
App build: 79
App environment: production
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs**
[2020-05-23_09-01-05-bug-report.zip](https://github.com/tari-project/tari/files/4681573/2020-05-23_09-01-05-bug-report.zip)

**Screenshot**
![image0](https://user-images.githubusercontent.com/50987039/82891554-3b565300-9f4e-11ea-8f85-28af9eb15e58.jpeg)

**Comment by sdbondi** [comment]
Unfortunately there is no detail on the actual assertion in tor that failed. However having taken a peek at the tor code it appears that this bug notification has been removed from tor in this commit https://github.com/torproject/tor/commit/40a321659a6537131566442ab3c2afd6f58019c9

Closing this issue as this was likely some intermittent connection reliability issue
