### ISSUE TITLE
Blockchain DB migrations

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#1920]
## Background

The blockchain DB is an LMDB key value store that stores bincode serialised structs. Bincode does not tolerate any changes to the data structure.

## Description

Implement a blockchain database migration that runs if necessary on startup. 

The requirements of this component are as follows:

1. Each migration MUST only be run once and only when required
1. Migrations MAY use library code (e.g. compute values etc) as needed
1. A new node with an empty database SHOULD NOT need to run migrations. i.e The migration counter should be set to the most recent migration 
1. Migration MUST run in order
1. If a migration is interrupted, it MUST safely revert to the state before the migration was run.
1. Migrations need not be reversible
1. If a migration errors, the migration counter MUST NOT be incremented and the migration should terminate. 

## Implementation Notes

1. The existing metadata database may be a good candidate for keeping track of a migration counter. This should be the easiest approach, though creates a coupling to the metadata db. 
1. Alternatively, a separate db could be used to track the migrations. 
1. Migrations would read from the source db and migrate to a new temporary db. Once the temporary db is fully migrated, the old database can be overwritten (this is at the devs discretion, it is simpler to overwrite values in the current database which is fine).

Perhaps, something along the lines of:

```rust
BlockchainMigrations::new(metadata_db, /* temporary path? etc */)
   .add(1, FirstMigration::new())
   .add(2, SecondMigration::new())
   .migrate();

// Migrations Implement this trait
trait LmdbMigration {
  fn migrate(&mut self, old_db: LMDBStore, new_db: LMDBStore) -> Result<(), MigrationError>;
}
```

**Comment by jorgeantonio21** [comment]
Hello guys, 

I am interested in tackle this issue. I see that some time has passed since the last time this was updated, is this still on hold? Moreover, it seems that some of the code has been deprecated. Could you please provide some update info to start working on this issue?

Thank you for the help

**Comment by sdbondi** [comment]
Hey @jorgeantonio21 Thanks for your interest in helping with this. This is a nice-to-have feature as currently any change to the blockchain database requires a full resync. 

If you'd like to take a crack at it, feel free to ask myself or anyone else on discord #dev channel - happy to help! 

There is already example of this for the LMDB peer database. [Peer DB Migrations](https://github.com/tari-project/tari/blob/development/comms/core/src/peer_manager/migrations.rs#L33)

**Comment by willyrgf** [comment]
Hi @sdbondi, I'm interested in try to solve this issue. There's someone working on it? There's some updates to this issue? Thanks.

**Comment by stringhandler** [comment]
No one is working on this at the moment. I'm not convinced it's necessary at the moment, and might only be more clear when it's actually needed. I'm going to close the issue for now, and will reopen it when it's more relevant

**Comment by sdbondi** [comment]
Agreed, this isn't particularly necessary at the moment. @willyrgf  thanks for your interest in contributing! If you're interested, perhaps this is a good one to tackle https://github.com/tari-project/tari/issues/4568

**Comment by willyrgf** [comment]
> Agreed, this isn't particularly necessary at the moment. @willyrgf  thanks for your interest in contributing! If you're interested, perhaps this is a good one to tackle https://github.com/tari-project/tari/issues/4568

Thanks @sdbondi, I'll check this one.
