### ISSUE TITLE
Live connections (Messaging)

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#195]
The set of live connections to peers is managed by `ConnectionManager`. 

`ConnectionManager` is a fairly heavyweight container that consists of:
* A list of active peer connections
* A control port listener
* A controller that receives and sends messages from/to other parts of the system

`PeerConnection` represents a live, direct P2P connection with another node. 
`PeerConnection` has a few important functions:
1. Manage the underlying network connection; with automatic reconnection if necessary.
1. Listen for messages from its peer and pass the messages onto the `MessageHandlerService`
1. Receive messages from a `MessageBroadcastService` and send them to the peer.

Peer connection should also manages an internal queue if the MessageHandlerService is slow; up to a configured high-water mark, after which it drops messages (after optionally logging them); Peer connection relays messages to `MessageHandlerService` without blocking.

`PeerConnection` will send messages to the peer in a non-blocking, asynchronous manner as long as the connection is maintained. It maintains an outbound queue if the connection is temporarily down.

`ConnectionManager` also contains exactly one `ControlPort`. The `ControlPort`  listens for connections on a predefined CONTROL PORT. Any clients can try connect to this port and deliver a control message, usually an `ESTABLISH_CONNECTION` message.

Before allowing a connection, the control port MAY consult a black list and silently drop the connection if the peer is on the list.

If the connection is established, the control port passes the control message onto the `ConnectionManager` and waits for a reply to give to the peer. This can be repeated (depending on the type of message being received). Eventually, the `ConnectionManager` will respond with a `TERMINATE_CONNECTION` message which the control port can pass to the peer before closing the connection.

Child of #183

**Comment by sdbondi** [comment]
Closed by #277
