### ISSUE TITLE
[Feature] Encrypted cloud backup (password)

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#1973]
**Design**

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5ef40c39f47783a0be5cc238

**Open Qs:**
Can you change the password after you set it?

**Acceptance Criteria**

Wallet Backups Screen
- If iCloud backups are enabled AND the user has not yet encrypted their wallet, item below iCloud Backups should read “Secure your iCloud backup”
- If iCloud backups are enabled AND If the user *has* already encrypted their wallet, the item should instead read “Change your secure password”
- If iCloud backups are disabled, no item should appear at all below it

Select Password Screen
- There will be no password validation here -- all passwords should be accepted as long as the two match. Design will come up with a password strength UI within the next few weeks to add.

Other:
- Password field should support copying and pasting in case you use apps like lastpass
- After user first sets password or changes password, wallet should immediately back up

Added Requirement:
**Password Error message:**

- Error should only appear once first password field is no longer in focus (that is, once user taps out of it, usually in order to enter it again in the pw confirmation field)
- Design: http://zpl.io/VxzWw4X

**Comment by kukabi** [comment]
`Can you change the password after you set it?`

I think it's possible to change the password but it will only be effective for the first backup after the change.

**Comment by stringhandler** [comment]
@Tas4tari I think this can be closed?
