### ISSUE TITLE
Clear secret keys from memory

### ISSUE THREAD

**Issue by neonknight64** [tari-project/tari#198]
Secret keys need to be cleared from memory after we have used them, especially in between copying to byte arrays.

**Comment by CjS77** [comment]
Good thinking, but this is already being done.
ref: 
* https://crates.io/crates/clear_on_drop
* curve25519-dalek-1.1.3/src/scalar.rs:741

But a more thorough investigation is required and perhaps doing some diagnostic tests / memory poking

**Comment by CjS77** [comment]
This issue may have some merit. `RistrettoSecretKey` currently implements `Copy` which may not be wise.

**Comment by CjS77** [comment]
I've also added a test in https://github.com/tari-project/tari/pull/200 that currently fails, suggesting that the secret key is in facto not cleared

**Comment by CjS77** [comment]
One possible approach here is:
* Remove the Copy trait from `RistrettoSecretKey`
  * This will require some refactoring in a few places like MuSig and transaction
* Implement `Drop` on SecretKey that explicitly clears the memory the scalar value points to.
