### ISSUE TITLE
LMDB database gets corrupted if an invalid block is mined

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#1990]
**Describe the bug**

A block my node had deemed invalid was rejected. Later my node mined a block, but could not insert it into the DB because there appears to be some residual data in the database from that failed insert attempt.

This issue is not about whether the original block should have been invalidated or not; but that the validation failure did not clean up after itself properly.

```text
2020-06-11 21:26:32.681788518 [c::bn::comms_interface::inbound_handler] DEBUG Block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb) received from local servi│
│2020-06-11 21:26:32.681879657 [c::val::block_validators] DEBUG block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb) has PASSED stateless VALIDATION check.  │
│2020-06-11 21:26:32.701672739 [c::cs::database] DEBUG Added candidate block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb) to the orphan database. Best heig│
│2020-06-11 21:26:32.701701471 [c::cs::database] DEBUG Checking if block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb) is connected to the main chain.      │
│2020-06-11 21:26:32.701726252 [c::cs::database] DEBUG Connection with main chain found at block #31449 (09e2de5779b1a43b884bd1f86440d96376190153c3c27d64329c7e407258ad09) from block #3│
│2020-06-11 21:26:32.740611082 [c::cs::database] DEBUG Comparing candidate block #31450 (accum_diff:12857169, hash:5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb) to │
│2020-06-11 21:26:32.740714872 [c::cs::database] DEBUG Validate and add 1 chain blocks from height 31449.                                                                               │
│2020-06-11 21:26:32.833871154 [c::val::block_validators] DEBUG Block validation: Block is VALID for block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb)    ┤
│2020-06-11 21:26:32.833980721 [c::cs::lmdb_db::lmdb] ERROR Could not add insert value into lmdb transaction: Error::Code(-30799, 'MDB_KEYEXIST: Key/data pair already exists')         │
│2020-06-11 21:26:33.452825869 [c::bn::comms_interface::inbound_handler] WARN  Block validation failed: AccessError("MDB_KEYEXIST: Key/data pair already exists")                       │
│2020-06-11 21:26:33.452879890 [c::m::miner] ERROR Miner submitted invalid block. AccessError("MDB_KEYEXIST: Key/data pair already exists").                                            │
│2020-06-11 21:26:33.502312283 [c::bn::initialization] INFO  🤑💰🤑 Newly mined coinbase output added to wallet 🤑💰🤑 
```

**To Reproduce**
1. Try and introduce an invalid block (I'm unsure as to what should be invalid, but my suspicion is that it's a double spend or otherwise spending an invalid input) to the chain. It is rejected.
2. Try and add a new block at the same height.

**Expected behavior**
LMDB cleans up properly after trying to add an invalid block

**Desktop (please complete the following information):**
 - OS & Version: Ubuntu 18.04
 - Git commit hash: c856c516

**Comment by SWvheerden** [comment]
Some more info on this error having delved deeply into it before:

- The mined block is valid if you look at the log
`│2020-06-11 21:26:32.833871154 [c::val::block_validators] DEBUG Block validation: Block is VALID for block #31450 (5b1434b92232ec0837c122522183f41eb00be1d187cf054349b02b4a384c5ebb)` 

- The inserting of the block into the lmdb fails, this is after all the reorg logic. 

- Previous times I have seen this failed, it failed at the marking of utxo's as spend section of adding a block. 


Notes:
- I strongly suspect this is not linked to the mining of an own block, but more of a block coming in. I suspect your node is mining % wise more blocks than everyone else. Thats why this keep happing on submitting a block. 

- Also think the theory about it not resetting correctly might be correct. As I have seen it complain about spent index keys/and or utxo not found, and now this time of a duplicate entry. So it look like it either leaves too much or does not delete enough.

**Comment by sdbondi** [comment]
I believe that the incorrect cleanup is a symptom of some other issue that causes the `utxo_db` and `txos_hash_to_index_db` to go out of sync. 

The `UnspendableInput` validation error is, in fact, not coming from the block validation but coming from the lmdb_db [here](https://github.com/tari-project/tari/blob/946068a072e47bb85676b7b621e3a7550b36fa5b/base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs#L423). The block validator only verifies that the UTXO exists in the `utxo_db` and not in the `txos_hash_to_index_db`. This is fine as they should always be in sync.

However, if they are not in sync, `store_new_block` will fail to spend inputs (`UnspendableInput`) and the operations that have already run will not be undone. [See here](https://github.com/tari-project/tari/blob/946068a072e47bb85676b7b621e3a7550b36fa5b/base_layer/core/src/chain_storage/blockchain_database.rs#L734).

The "gaps" are a result of the updated metadata and header being persisted and the `Spend(UnspentOutput)` operation subsequently failing.

These are the possible causes for this that I can think of:
1. The node happened to crash/terminate at some point between writing the utxo and the txn hash index (consistency between dbs is not guaranteed by the blockchain db in this case)
1. Some mysterious LMDB bug causes the write to `txos_hash_to_index_db` to silently fail (we've looked into this and it seems unlikely UNLESS the database file is opened more than once, in which case, this has been confirmed)
1. A bug where the `txos_hash_to_index_db` is not kept in sync with the `(utxo|stxo)_db`. I don't see this possibility anywhere in the code (except in the case of an unlucky crash)

**Comment by stringhandler** [comment]
Stale due to new DB structure
