### ISSUE TITLE
Chain Metadata effective vs configured pruning horizon

### ISSUE THREAD

**Issue by neonknight64** [tari-project/tari#2005]
The base node shares its pruning horizon with other nodes by sharing metadata. Currently the pruning horizon is the configured pruning horizon and not the effective pruning horizon. This mismatch can result in remote nodes incorrectly calculating the nodes horizon block height and thus request chain data that the node does not have.
- The effective and configure can be different when a node is performing pruned mode syncing or when a different pruning horizon was selected in the base node config.
- A possible solution is to share the horizon block height rather than the pruning horizon.
- Or the effective pruning horizon can be shared instead of the configured.

**Comment by stringhandler** [comment]
I think if the sync node is asked for chain data it doesn't have it should respond with `CommsInterfaceError::UnableToProvideData` or something like that, at which point the requesting node asks another peer. There are a number of cases where the node might not be able to provide data in future.

@sdbondi what do you think?

But in concept I agree that this value should be more meaningful. Perhaps we should call it `pruned_at` and specify first block height after the horizon.

**Comment by sdbondi** [comment]
It's currently difficult to respond with an error. It will require adding support for that in the message type itself.

I've started on this and called it `effective_pruned_height` but not married to that name. 

Current thoughts:
- It indicates the actual pruned height (i.e  `effective_pruned_height + 1` is the first block that the node can provide)
- An archival node will always have `effective_pruned_height == 0`
- I think that if the node cannot provide any blocks temporarily it makes sense to have block_height=0. 
- After pruned sync, the pruning_horizon field doesn't actually give you anything too useful, though it does indicate that a node is in pruned mode but I don't think any node should care about that. Also `effective_pruned_height > 0` means a node is pruned. Maybe we can remove it.
- The effective pruned height would be updated (1) after pruned sync (it would equal the block_height which indicates that no blocks can be fetched from this node) and (2) when the blockchain database is pruned every `n` intervals.

**Comment by stringhandler** [comment]
I think `effective` is not really necessary, and `pruned_at` is more clear (IMHO). I also don't really see the need to have it as part of the chain_meta_data, but I don't think there is currently another way of telling whether a node is pruned or not. 

So with your points 
1. Agree, maybe just the name change
2. Yep, `pruned_at==0`
3. Assuming `block_height` is the field in chain_metadata, agree
4. Agree that we should be able to remove it, but maybe safer to keep it for debugging purposes right now
5. True
