### ISSUE TITLE
Backend wallet backup and restore through CSV formatted data

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#2009]
The current method for wallet backup and restoration is for the mobile clients to do a full backup of the wallet sqlite db

When you backup the full sqlite db you backup the following:
- Comms private key
- Full transaction history (including pending transactions)
- All outputs (including invalid ones)
- Contacts

So the goal of producing a CSV export of the wallet is to try backup a minimal set of data that is compact as possible and then also be able to do backups as a series of diffs i.e. an initial backup which includes the once of Comms Private Key and then on subsequent request just what has changed.

## What is backed up

Can we confirm exactly what is going to go into the CSV formatted backup data:
- Optional Comms private key: This is optional to allow for unencrypted backups that only expose funds not identity.
- All completed transactions
- All valid outputs
- Contacts?

Do we want to include pending transactions?
Do we want to include invalid outputs that might become valid again? It is unlikely that this will happen ever but just checking.

## How the backup functionality will be used by the mobile client
The backup function can be called in two ways: 
1. A full backup will provide all the backup data in CSV form and will record the time at which the backup was made in the sqlite db.
2. A diff backup will provide only the data that is new since the last recorded backup call. If this is called with no initial full backup this will return the initial full backup

The restore function will accept multiple CSV formatted backup data batches which must include at least 1 initial full backup. The timestamps in the CSV data batches will be used to apply the initial backup and subsequent diffs in order.

If a restoration is done on a wallet that has existing data the backend will construct the DB view provided by the initial backup + subsequent diffs and then try merge that with the data that is currently in the sqlitedb.

**Comment by philipr-za** [comment]
Actually with a little more thought if we are dealing with multiple tables CSV is not the best format. Sql files are probably better? Or else just multiple sets of CSV.

**Comment by CjS77** [comment]
The benefit of CSV is that it's schema agnostic. 

One CSV file per table should work ok.

The staged security model is what drives the particular backup scheme.

For reference:
Under a certain value in the wallet:
 - Wallet is stored unencrypted on the Cloud (but protected by the user's cloud credientials)
- Access to user's cloud account => access to funds
- Simple. User interaction not required in UI beyond authorising use of the cloud account.

Above a certain value:
- Wallet is encrypted with a passphrase
- User must be prompted to enter (a good) encryption passphrase.

Switching between the two modes should ideally _not require a wallet sweep_. So this means that we should not backup the seed phrase in unencrypted form, for example. 

If a wallet is now encrypted and an old backup is compromised, at worst, the user loses the (small amount of) funds that were backed up at that time.

In an encrypted wallet, we are free to back up the master seed phrase as well.

**Comment by CjS77** [comment]
Backing up UTXOs and Transactions leads to better UX, so best to back up both.

Backing up contacts? I don't feel strongly either way; probably yes?

> Do we want to include pending transactions? 

Yes, or just the UTXOs that will be scanned on a restore.

> Do we want to include invalid outputs that might become valid again? It is unlikely that this will happen ever but just checking.

Invalid, as in spent? or due to cancelled txs?

Maybe it's safer to back it all up.

**Comment by philipr-za** [comment]
Invalid means it is a UTXO that was Unspent in our db but when we asked a Base Node about they said it is not in the UTXO set. This can be due to a reorg or it was spent by another wallet.

**Comment by philipr-za** [comment]
> Yes, or just the UTXOs that will be scanned on a restore.

So pending transaction will involve also keeping track of pending inbound UTXO's that could become spendable if the transaction is mined. For outbound transactions it also means keeping track of encumbered outputs that will become spent. We also need to keep the transaction protocol state depending on which stage we are at. So it is quite a bit more than just UTXOs when we are talking Pending transactions.

**Comment by CjS77** [comment]
In that case it's definitely a better UX to be able to import a pending transaction into the db

**Comment by Jasonvdb** [comment]
Can we do a test on the zipped file size of all the exported CSVs before doing the work on the diff? To get an idea of the bandwidth usage from doing a full backup of zipped CSVs instead of zipped SQLite files after each TX sent/received? Add a few contacts, use make-it-rain to send a few hundred txs, export and zip.

Just a thought, if the full backup size was manageable for now. When the seed phrase is ready we could eventually backup the seed phrase once, while tx history and contacts get a daily backup. Then a user could always safely recover all funds with the worst case scenario being they lose some history. 

Unless exported CSV files are not much smaller than the SQLite file, in which case ignore this ☝️

**Comment by philipr-za** [comment]
So a quick test shows my base node wallet.dat = 16mb and a CSV backup = 14mb so it doesn't seem like a huge space saving.

So the incremental backup was floated to try reduce bandwidth required to upload to the cloud but incremental backup is very complex so will take a lot of time to implement. I agree with @Jasonvdb 's comment that in the near future we will have Seed Phrase restoration so we can backup the db less often which makes incremental backup unnecessary. 

So after our discussion here it sounds like we have two modes of backup which are:
1. Partial unencrypted backup when balance is below the threshold for encryption which will backup:
a. Outputs
b. Transactions (pending and completed)
c. Exclude Comms Private Key
d. Exclude Contacts
2. A full backup when the balance is above a threshold that backs up everything. This might as well just be a full backup of the Sqlite3 file.

So to confirm that means the only functionality that needs to be added to the backend at the moment is a function to produce the partial backup file which only includes funds and transaction history?

Thoughts? @CjS77 @Jasonvdb @kukabi

**Comment by philipr-za** [comment]
Just capturing the outcome of our discussion but the partial backup that will be stored unencrypted will include the full db without the comms private key but will include the Comms Public Key so that we can tell the direction of the transaction history.

**Comment by CjS77** [comment]
Yup, I think we can export the contact list too, in unencrypted form since the pubkeys are already exposed. Only aliases are additional info.
