### ISSUE TITLE
Display correct fee estimate in Mobile Apps

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#2025]
Currently the fee estimate in the mobile apps is based on one input and 2 outputs.

In reality, this is only a (often reasonable) guess.

A more accurate estimate requires communication with the wallet to find out exactly how many inputs will be in the transaction.

To implement this feature, we need the following

[ ] FFI function that returns the fee (taking into account the number of inputs and outputs) that would be used in a transaction of a given size: `calclulate_fee_estimate(value) -> value`
[ ] Update Send Amount screen to make use of this function

**Comment by stringhandler** [comment]
Closed in v0.8.5
