### ISSUE TITLE
Checking for updates animation and Pull to Refresh updates never complete

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#2060]
**Describe the bug**
“Checking for updates” takes forever. Never finishes actually. 
Tried restarting the app. 

I have “in progress” transactions for 2 days now. Also some of my previously confirmed transactions have been cancelled. I’m almost certain the amounts went through but the status is as mentioned above. 

**Smartphone:**
Network: rincewind
Phone: iPhone 11 Pro
iOS: 13.5.1
App version: 0.2.1
App build: 101
App environment: production
Reachability: Cellular ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-07-09_15-36-33-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4897404/2020-07-09_15-36-33-bug-report.zip)

**Reporter:**
Giannis Bakopoulos

**Additional Information:
@Anziskavds has reported seeing this on the current TestFlight build as well. The pull to refresh animation also remains in progress and does not complete
[2020-07-10_08-41-12-bug-report.zip](https://github.com/tari-project/tari/files/4901451/2020-07-10_08-41-12-bug-report.zip)

**Comment by Tas4tari** [comment]
Received another Bug report from Seth Simmons:
**Description:**
Cannot use wallet as all BNs show “pending first sync

**Logs:**
[2020-07-09_10-47-39-bug-report.zip](https://github.com/tari-project/tari/files/4897930/2020-07-09_10-47-39-bug-report.zip)

**Comment by Tas4tari** [comment]
**Another Bug report reported by Seth Simmons:**
Seems I’m unable to get a connection to a BN at all today, with each time I open my wallet the sync failing at 6 attempts and not being able to find a good peer.

**Logs:**

[2020-07-10_12-50-31-bug-report.zip](https://github.com/tari-project/tari/files/4910940/2020-07-10_12-50-31-bug-report.zip)

**Comment by philipr-za** [comment]
I think this was due to the user's running older versions of the app and some issues we had with the seed nodes on friday 10 July. I think this issue can be closed.

**Comment by Tas4tari** [comment]
@philipr-za Anziska was running the TestFlight build at the time, was this issues with the seed nodes as well?

**Comment by philipr-za** [comment]
I believe so, I was unable to create a failure when test yesterday.

**Comment by Tas4tari** [comment]
@philipr-za Ok, Anziska has access to the TestFlight build, v0.2.2 of the wallet app, I can ask her to try and see if the issue persists, if not then we can close this

**Comment by Anziskavds** [comment]
Tested again on iOS version 0.2.2 and the issue still persists. @Tas4tari @philipr-za 


![IMG_FEE2A5E67266-1](https://user-images.githubusercontent.com/50451670/87415003-d83b8100-c5cc-11ea-9fe1-21555053e08f.jpeg)
