### ISSUE TITLE
Consensus breaking changes for Tari testnet

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2068]
This proposal is (tick applicable):

* [X] A new feature
* [X] An extension to an existing RFC/proposal <LINK>
* [X] An alternative approach to an existing RFC or proposal <LINK>

### Change log

| Date | Changes |
|:-----|:--------|
|      |         |

### Goals
We have a potential upcoming consensus breaking change for testnet, for example to introduce multi-POW with merge mining; this issue is to collect and consolidate these ideas. The body of the issue will be populated and/or changed as the discussion unfolds.

### Assumptions
_These proposals seldom live in a vacuum. The proposal might presuppose that some other feature has been implemented, or
that a certain ECC curve is used etc. List those assumptions here._

### Abstract
_A short summary of how the solution in this proposal works._

## Description

_Type out the body of the proposal here_

### Assumptions
_These proposals seldom live in a vacuum. The proposal might presuppose that some other feature has been implemented, or
that a certain ECC curve is used etc. List those assumptions here._

### Abstract
_A short summary of how the solution in this proposal works._

## Description

_Type out the body of the proposal here_

### Assumptions
~~_These proposals seldom live in a vacuum. The proposal might presuppose that some other feature has been implemented, or that a certain ECC curve is used etc. List those assumptions here._~~

### Assumptions
_These proposals seldom live in a vacuum. The proposal might presuppose that some other feature has been implemented, or
that a certain ECC curve is used etc. List those assumptions here._

### Abstract
_A short summary of how the solution in this proposal works._

## Description

_Type out the body of the proposal here_

**Comment by CjS77** [comment]
Here's my list:

* Merge mining implementation with Monero (ongoing)
* Pruned mode syncing  (#2040) 
* Protocol versioning
* An integer-math based emission curve (#2082)
