### ISSUE TITLE
Maintain a denylist of IP addresses and enforce ban at the lowest connection level

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2080]
## Description

When a peer is banned, the peer's public IP address should be added to a denylist when is checked before the noise handshake.

## Considerations

- This should be maintained for base node's only as wallets could be connecting from the same tor exit node.

**Comment by stringhandler** [comment]
@sdbondi is this still a concern?

**Comment by sdbondi** [comment]
@mikethetike Short answer: yes 

Peers are allowed to advertise public IP addresses. The current strategy bans the node identity, however since new identities are free, an attacker could simply create a new identity to 'bypass' the ban. When we ban a peer, we should be banning their network address. Of course, tor addresses are free identities so in tor's case this doesn't make any difference.

**Comment by stringhandler** [comment]
Thinking about this many months later, I don't think it is wise, since common workspaces and buildings often share a single IP address
