### ISSUE TITLE
Authentication is bypassed when opening the application via deeplink

### ISSUE THREAD

**Issue by nyarian** [tari-project/tari#2085]
Video journey: https://drive.google.com/file/d/19H91GEIcYzhD8NhY9FHnoG-smabvH5zL/view?usp=sharing

**Comment by sdbondi** [comment]
@nyarian Thanks for the bug report! Great find! 🥇  I've created an issue on the Aurora Android repo (https://github.com/tari-project/wallet-android/issues/508)

Closing here
