### ISSUE TITLE
Delay between serializing and buffering in the comms stack

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2111]
**Describe the bug**

---
_**Edit 2020-08-12**_
It has been found that the delay corresponds to `inactivity_timeout: Some(Duration::from_secs(5 * 60))` in `comms\src\protocol\messaging\config.rs`
- Windows to Ubuntu Linux:
  - set at 1 minute: Serializing to Buffering multiple instances at 1 minute, also evident in Linux
- Windows to Windows:
  - set at 5 minutes: Serializing to Buffering multiple instances at 5 minutes
  - set at 30 minutes: Serializing to Buffering multiple instances at 30 minutes [with & without branch `sb-comms-remove-messaging-events`]
  - None: Many many Serializing not making it to Buffering
- Windows to MacOS
  - set at 5 minutes: Serializing to Buffering multiple instances at 5 minutes, also evident in MacOS [with branch `sb-comms-remove-messaging-events`]
---

The time that is taken between `[comms::dht::serialize] TRACE Serializing outbound message` and `[comms::protocol::messaging::outbound] DEBUG Buffering outbound message` in the comms stack shows big delays. See the example below where two messages have been traced.

```
2020-08-05 12:57:09.692740400 [comms::dht::serialize] TRACE Serializing outbound message MessageTag(9612750584833995996) for peer `9bd99c67213815c9`
2020-08-05 13:21:11.929191600 [comms::protocol::messaging::outbound] DEBUG Buffering outbound message (tag = Tag#9612750584833995996, 170054 bytes) for peer `9bd99c67213815c9`
```
```
2020-08-05 12:55:09.689771800 [comms::dht::serialize] TRACE Serializing outbound message MessageTag(8548633173114369625) for peer `9bd99c67213815c9`
2020-08-05 13:21:11.929191600 [comms::protocol::messaging::outbound] DEBUG Buffering outbound message (tag = Tag#8548633173114369625, 134353 bytes) for peer `9bd99c67213815c9`
```

When tracking this at node startup, with a big wallet, and some pending transactions that need to be sent, it is evident that these two services are not running optimally in an asynchronous manner, as if there is something that holds them up. The order of events in this example was:
- UTXO query from wallet to base node
- Re-sending all pending Txs after UTXO queries were successful

[serializing-buffering-delay-01.log](https://github.com/tari-project/tari/files/5028918/serializing-buffering-delay-01.log)
[serializing-buffering-delay-02.log](https://github.com/tari-project/tari/files/5028920/serializing-buffering-delay-02.log)
[serializing-buffering-delay-query.log](https://github.com/tari-project/tari/files/5028944/serializing-buffering-delay-query.log)

**To Reproduce**

This happened at node startup and during Tx stress testing.

**Expected behavior**

The time taken between `[comms::dht::serialize] TRACE Serializing outbound message` and `[comms::protocol::messaging::outbound] DEBUG Buffering outbound message` in the comms stack should be very very quick.

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by sdbondi** [comment]
Think this is fixed in #2127 and #2132. Closing
