### ISSUE TITLE
QA: Sending Transactions: App drains battery

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#2128]
When I started sending and receiving transactions, it became really power hungry and drains the battery fast.

Device Details: Android 9

**Comment by kukabi** [comment]
thanks @Tas4tari !

**Comment by Tas4tari** [comment]
Just a note:

Opened the Tari app less than 30 minutes ago on my Huawei P30 Lite and received the power intensive app pop up on version 0.4.0-jnLibs-0.16.0

**Logs:** 
[ffi_logs_C8068FB342406B6F8C033ADEB5050495C068B82B1ADFE9B4349FFC602A3C555B.zip](https://github.com/tari-project/tari/files/5075179/ffi_logs_C8068FB342406B6F8C033ADEB5050495C068B82B1ADFE9B4349FFC602A3C555B.zip)

**Screenshot:**
[photo_2020-08-14 16 41 33](https://user-images.githubusercontent.com/50987039/90261303-0f5fb500-de4d-11ea-9596-28e10184d024.jpeg)

**Comment by Tas4tari** [comment]
@philipr-za @mikethetike @kukabi DankEngine from telegram  reported battery usage issues whilst using the Android app privacy apk.

**Logs:**
[ffi_logs_E044F69EEBFC3A8E0299F2085BE2AA7CD236149E39F46A38AE35C3DC9D9BAF21.zip](https://github.com/tari-project/tari/files/5095187/ffi_logs_E044F69EEBFC3A8E0299F2085BE2AA7CD236149E39F46A38AE35C3DC9D9BAF21.zip)

**Telegram Conversation:**
Big battery drain from Aurora privacy apk

Mike, [Aug 19, 2020 at 1:26:15 AM]:
Wow, that's pretty bad

Dank Engine, [Aug 19, 2020 at 1:26:35 AM]:
Was fine yesterday so not really sure what changed

Yesterday it used like 5%

Mike, [Aug 19, 2020 at 1:27:41 AM]:
Please send your logs. It really helps debug these situations

Dank Engine, [Aug 19, 2020 at 1:28:49 AM]:
I force stopped the app to conserve battery. Will the logs still be useful after I relaunch the app?

Mike, [Aug 19, 2020 at 1:29:11 AM]:
Yeah they will be

Dank Engine, [Aug 19, 2020 at 1:29:14 AM]:
Otherwise I'll just make sure to send them if it happens again

Sent



**Screenshot:**
![photo_2020-08-19 10 54 24](https://user-images.githubusercontent.com/50987039/90614130-8ceb4280-e20a-11ea-9412-d541584d7cc2.jpeg)
