### ISSUE TITLE
Running tari_base_node in screen session

### ISSUE THREAD

**Issue by trasherdk** [tari-project/tari#2146]
**Describe the bug**
When launching the tari_base_node in a screen session.

**Expected behavior**
It would be nice if output fitted on standard terminal.

**Screenshots**
Screen session
![image](https://user-images.githubusercontent.com/5003891/90600964-a21f9b80-e221-11ea-9e4b-0b84803821e0.png)

Non screen session
![image](https://user-images.githubusercontent.com/5003891/90601658-c039cb80-e222-11ea-882a-ab4791a51e5a.png)

**Desktop (please complete the following information):**
Debian (Buster) 10.5 (Headless)

**Comment by stringhandler** [comment]
I'm also experiencing this on macos zsh and iterm Build 3.3.9

**Comment by boldsuck** [comment]
I don't have this problem on my 3 server. Also Debian Buster. on bare metal.

KDE Konsole: remote SSH login
Terminal Size
Columns: 80 ; Rows: 40

```
.bashrc
# Run Tari base node in background
alias tari='screen -mdS tari /home/user/tari/tari_base_node'
# reattach Tari base node
alias ttr='screen -r'
```

**Comment by leet4tari** [comment]
I think https://github.com/tari-project/tari/issues/1728 is related?

**Comment by SWvheerden** [comment]
Thanks for logging this issue, we have made a multitude of improvements during the past 2 years. If this issue is still present, please reopen it.

**Comment by trasherdk** [comment]
I deleted my fork a long time ago :laughing:
