### ISSUE TITLE
Base node/wallet should emit an error if the LMDB/SQLite databases are in use by another process

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2153]
A lockfile or (database agnotic) lock "flag" should be investigated. This crate looks promising: https://docs.rs/lockfile/0.2.2/lockfile/

The important part of this functionality is the user being made aware of the fact that two base nodes are accessing the same database not to actually enforce exclusive access. The best strategy may be to lock the data directory with a crate like `lockfile`.

**Comment by stringhandler** [comment]
This has been implemented
