### ISSUE TITLE
Add a database transaction to the Output Manager Service when encumbering a received output

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#2172]
We have seen some occurence of an intermittent bug where if the direct and propagated transaction messages arrive at a receiver in rapid succession we can have clashes in the Output Manager database because receiving a transaction requires multiple database operations. When they operations are interleaved and cause an error it breaks the inbound transaction.

The operations in the transaction and output manager services for receiving a transaction should be encapsulated in a database transaction somehow to be completely atomic to avoid this.

**Comment by hansieodendaal** [comment]
Closed by:
- #4775
- #4716 
- #4689 
- #4663
