### ISSUE TITLE
LMDB `mapsize` (environment size) does not increase as the database is filling up.

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2181]
**Describe the bug**

LMDB `mapsize` (environment size) does not increase as the database is filling up. This results in db write failures when syncing from scratch at ~76,000 block height, when the db size reaches 1GiB. (_#1817 changed the 50GiB initial size down to 1GiB for reasons discussed there._)

**To Reproduce**

Sync from scratch on a blockchain that is larger than 1 GiB, without restarting the basenode.

**Expected behavior**

- LMDB environment size should increase automatically. See related sizing logic in #1817.
- A unit test should be added to test automatic resizing if the limits are approached.

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows 10, Ubuntu Linux

**Smartphone (please complete the following information):**

n/a

**Additional context**

See related issues

**Comment by delta1** [comment]
closed by #2193
