### ISSUE TITLE
Expose kernel excess and excess signature via FFI

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#2201]
Currently, the Aurora wallet doesn't show any details about the transaction in the transaction details view. It would be useful to have a link to a block explorer or the excess or excess signature in order to prove to the receiver that I have sent it. 

The FFI currently doesn't expose these fields (AFAIK)

**Comment by philipr-za** [comment]
Just a note this will only be possible on a CompletedTransaction that has a TransactionStatus other than Pending. In the FFI we convert InboundTransaction and OutboundTransaction to CompletedTransactions for presentation by the frontend but if they are converted they will not have a fully formed Transaction field.

**Comment by delta1** [comment]
PR ready at #2230
