### ISSUE TITLE
Default wallet timeout configuration

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2233]
Regarding tari-project/tari#2220 default wallet config can I please have your feedback @philipr-za @hansieodendaal @mikethetike  

Previously suggested were: 

```
[wallet]

base_node_query_timeout = 300
transaction_broadcast_monitoring_timeout = 300
transaction_chain_monitoring_timeout = 30
transaction_direct_send_timeout = 300
transaction_broadcast_send_timeout = 300
```

What should we default to?

**Comment by philipr-za** [comment]
base_node_query_timeout is not a thing anymore. 
I have the following in the code:
```Rust
impl Default for TransactionServiceConfig {
    fn default() -> Self {
        Self {
            broadcast_monitoring_timeout: Duration::from_secs(30),
            chain_monitoring_timeout: Duration::from_secs(30),
            direct_send_timeout: Duration::from_secs(20),
            broadcast_send_timeout: Duration::from_secs(30),
            low_power_polling_timeout: Duration::from_secs(300),
        }
    }
}
```

**Comment by delta1** [comment]
Thanks @philipr-za are those the current defaults? Do you suggest they remain the same?

**Comment by philipr-za** [comment]
I think so, unless there are arguments otherwise these have been what we have been using up till now.

**Comment by hansieodendaal** [comment]
The config source code defaults are here, same as the code snippet above,  should be reverted to the original values:
https://github.com/tari-project/tari/pull/2220/files

These values must be defaults in the config files (`tari_config_sample.toml` and `windows.toml`), not in the code:
```
[common]

buffer_size_base_node = 1000
buffer_size_base_node_wallet = 25000
buffer_rate_limit_base_node = 100
buffer_rate_limit_base_node_wallet = 100

[wallet]

base_node_query_timeout = 300
transaction_broadcast_monitoring_timeout = 300
transaction_chain_monitoring_timeout = 30
transaction_direct_send_timeout = 300
transaction_broadcast_send_timeout = 300
```
