### ISSUE TITLE
Initial mempool sync should only start if the blockchain is synced

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2237]
```
│2020-09-17 08:42:56.798250000 [c::mempool::sync_protocol] DEBUG Inserted transaction `7906099e064c9bc9c6ec4f9f5bd6fe0a8ed3daef5e4a8352464e6898d804eb08` from peer `391ef20a801cd35f`                            │
│2020-09-17 08:42:56.798690000 [c::mempool::sync_protocol] DEBUG Received transaction `17c05f99f107f01c1523647eca14ce375f932af5a729519b9e22e4862c3f0903` from peer `391ef20a801cd35f`                            │
│2020-09-17 08:42:56.798871000 [c::mp::mempool] DEBUG Inserting tx into mempool: 17c05f99f107f01c1523647eca14ce375f932af5a729519b9e22e4862c3f0903                                                                │
│2020-09-17 08:42:56.843540000 [c::val::transaction_validators] DEBUG Transaction validation failed due to already spent input: 7884c6530a43c6a0fde4a776c56418a46a232e87cb3e8e4505fbbfda9ab3ba7b [OutputFeatures │
```

Additionally, we may want to put some rules and limits in place for max number of transaction synced, timeouts, and handling transaction validation failures.

```
Mempool stats: Total transactions: 2668, Unconfirmed: 436, Orphaned: 0, Time locked: 0, Published: 2232, Total Weight: 107340
```

**Comment by stringhandler** [comment]
Maybe there can be an unvalidated pool, and it syncs, but doesn't validate them until the block chain is synced? I think doing the two network requests can be done in parallel

**Comment by sdbondi** [comment]
The "problem" that led me to create this issue was that I had a peer with ~3000 + transactions in their mempool. The mempool sync is probably the most efficient protocol we have and was downloading and validating at the maximum rate (for the network connection, txn validation (debug)). This was using a ton of CPU and network just to put transactions in the published pool. I think your suggestion is solid, we can then trigger a validation once the block sync is done but allow transaction downloading to continue as it is now. I'll close this as the current behaviour is more of an annoyance than a bug.
