### ISSUE TITLE
`find_orphan_chain_tips` in BlockchainDatabase is very inefficient

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#2247]
`find_orphan_chain_tips` requires searching though all orphans recursively. This causes large reorgs (+1000 block) to take hours.

Additionally, it is likely possible to slow a node to a crawl by pushing many large orphan blocks to it. These dummy blocks do not need to be mined because the difficulty is not checked before adding into the orphan block pool.

**Comment by SWvheerden** [comment]
I think the biggest culprit inside there is the iterator over the orphans. Iterating over 1000 items should not take seconds.

**Comment by sdbondi** [comment]
@SWvheerden Each iteration has to deserialise an entire block, which involves [decompression for every public key](https://github.com/tari-project/tari-crypto/blob/7ee2dfb24595e8a858ddd3f2f8de15793fa466a2/src/ristretto/ristretto_keys.rs#L340) and [other operations](https://github.com/dalek-cryptography/curve25519-dalek/blob/master/src/scalar.rs#L210) per input/output/kernel.

I suspect there is no perf issue with the iterator implementation itself. I think a better strategy is needed to remove the need to load and deserialise in the first place. Maybe tip tracking and/or only keeping the headers in the orphan db and only downloading the full blocks if needed for a reorg.

EDIT:
I have seen ~900 blocks take as long as 22 seconds on my macbook after a stress test. I suspect that is because there are many more expensive "crypto operations" for each full block. The problem isn't the "crypto operations", it's that we have to iterate over the whole orphan db when adding a block in the first place

**Comment by hansieodendaal** [comment]
Some stats:

The log entries below shows measured time for each block to be added during a fairly large block sync. This can happen if a base node is started up when it last synced a couple of days ago or if a large chain reorg is happening.
``` rust
2020-10-09 07:15:19.044207800 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:23.087208500 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:27.297718300 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:32.445717800 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:36.493718400 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:40.719718700 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:44.851719100 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:48.913227100 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:53.902735900 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:15:58.066735500 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:16:02.222735400 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
2020-10-09 07:16:06.221737100 [c::cs::database] DEBUG Searched 1031 orphan(s) in 4s
etc.
```

**Comment by SWvheerden** [comment]
@sdbondi I think you are right. I dont think its necessary the iterator itself thats the problem. Its how we use the iterator. Looking into other databases etc, I think that function is too dependant on how LMDB works. I think we need to replace it with a call that only returns the previous block. Perhaps we should keep a reserve index inside LMDB like <previous block hash,(block hash, height)> , because we are essentially doing a search on the previous block hash. 

I were to write this in a postgres sql query, I would write this: `SELECT height, hash FROM orphans WHERE previous_hash={}`
I dont see this taking very long. The height and hashes is not very large, and we dont need to deserialise a block here.

**Comment by sdbondi** [comment]
@SWvheerden I like the index idea. In postgres, you would speed up that query by adding an index. Maintaining the index should be no more difficult than the existing indexes we have and I'm confident that will speed things up greatly. Nice idea!

**Comment by stringhandler** [comment]
This implementation has been rewritten
