### ISSUE TITLE
Improve revalidation of invalid and spent outputs in the wallet

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#2268]
The wallet does three types of validation:
1. Validate Unspent outputs are still spendable
2. Revalidate outputs that have been marked as invalid by previous runs of 1.
3. Check that spent outputs have not become spendable again due to reorg (https://github.com/tari-project/tari/pull/2264)

Validation 1 needs to be done often but validations 2 and 3 are much less likely to be needed and as the wallet becomes full of spent and invalid outputs can represent a large amount of effort.

A more intelligent scheme for choosing how often validations 2 and 3 are performed and which outputs are included in the validation because as time goes on it becomes more and more unlikely that outputs will be recovered by these validations.

**Comment by stringhandler** [comment]
This has been implemented
