### ISSUE TITLE
Base node and base node wallet not communicating

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2295]
**Describe the bug**

The base node and its wallet (development branch commit `69380e0` of 2020/10/02) not communicating for many hours while other connections are working via Tor.

**To Reproduce**

Started a base node

**Expected behavior**

The base node and its wallet should not have problems connecting.

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

See the initial portion of the network trace log below:

[network.zip](https://github.com/tari-project/tari/files/5325855/network.zip)

**Comment by delta1** [comment]
can this be closed @hansieodendaal ?

**Comment by hansieodendaal** [comment]
I do not think we have fixed the issue, but this functionality (base node with base node wallet) will be deprecated soon.
