### ISSUE TITLE
78 coinbase kernels in block 110102

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2299]
**Describe the bug**

78 coinbase kernels are present in block 110102. A portion of the network accepted this block as valid.
block #110102 `8f8adc1d36a69b2961a00798ca46fecb5d7db1bf0b5f4e68ff0efffff30413c2`

**To Reproduce**

This is probably due to a reorg.

**Expected behavior**

Only one coinbase kernel should be accepted in a block.

**Screenshots**

n/a

**Desktop (please complete the following information):**

Linux, Windows

**Smartphone (please complete the following information):**

n/a

**Additional context**

1. Block 110102 contents:

  [block-110102-to-many-coinbases.log](https://github.com/tari-project/tari/files/5326875/block-110102-to-many-coinbases.log)
  [block-110102-to-many-coinbases(json).log](https://github.com/tari-project/tari/files/5326874/block-110102-to-many-coinbases.json.log)

2. Logfile from a node where this block was accepted as part of a reorg:

  [core_node_03.zip](https://github.com/tari-project/tari/files/5326904/core_node_03.zip)

3. Logfile from a node where this block was rejected as part of block sync:

  [core_reject_110102.zip](https://github.com/tari-project/tari/files/5326908/core_reject_110102.zip)

4. The block explorer listed the same faulty block: https://explore.tari.com/block/110102

  ![image](https://user-images.githubusercontent.com/39146854/95070965-3b8b0a00-0709-11eb-83b5-3f4a3bf09d2c.png)

**Comment by stringhandler** [comment]
Fixed with Ridcully testnet reset
