### ISSUE TITLE
Base node crash with many repetitive large UTXO queries

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2342]
**Describe the bug**

Base node crash with many repetitive large UTXO queries.

Console error message (with full trace enabled):
```
memory allocation of 3580034 bytes failed
Press any key to continue . . .
```

**To Reproduce**

See UTXO queries in attached `base_layer.log`

**Expected behaviour**

The base node should not crash

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

Log files from 4x independent cases, the most recent on from 2020-10-13 below. The most informative is the console error message and the fact that many UTXO queries were repeated and timed out.

[base_node_crash_memory_allocation-01.zip](https://github.com/tari-project/tari/files/5382816/base_node_crash_memory_allocation-01.zip)
[base_node_crash_memory_allocation-02.zip](https://github.com/tari-project/tari/files/5382818/base_node_crash_memory_allocation-02.zip)
[base_node_crash_memory_allocation-03.zip](https://github.com/tari-project/tari/files/5382823/base_node_crash_memory_allocation-03.zip)
[base_node_crash_memory_allocation-04.zip](https://github.com/tari-project/tari/files/5382826/base_node_crash_memory_allocation-04.zip)

**Comment by stringhandler** [comment]
The wallet uses a different process now, so can be closed. Please reopen and add details if not the case
