### ISSUE TITLE
Tokio panic on v0.6

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#2385]
>> thread 'tokio-runtime-worker' panicked at 'index 16 out of range for slice of length 7', base_layer/core/src/base_node/proto/chain_metadata.rs:30:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When running 0.6

# To reproduce
- run `cargo run --release --bin tari_base_node` on v0.6

**Comment by SWvheerden** [comment]
#2387
