### ISSUE TITLE
Transactions being invalidated and cancelled after base node restart

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#2401]
**Describe the bug**

Currently, if a base node has multiple transactions in its mempool unconfirmed pool, with a wallet connected to it and relying on status updates, those transactions will be cancelled in the wallet if a request is sent to the base node and the transaction is no longer in the mempool after a base node restart, but before it is being mined. If mempool sync works as designed after startup, and the wallet's query is returned after sync, all is good, but this is not always the case.

**To Reproduce**

Steps to reproduce the behaviour:
1. Broadcast finalized transactions to a base node, wait for confirmation that it is in the mempool unconfirmed pool
2. Shut down the base node straight after
3. Restart the base node (and wallet connecting to the same base node)

**Expected behavior**

A wallet should not merely cancel legitimate transactions based on that transaction not being in its connected base node's mempool anymore and not detected as mined. Some knowledge of how long the base node has been up is required. If the wallet determines the base node has been restarted after the transaction broadcast time, the transaction can be re-broadcasted. If the base node returns the status of the transaction to be in the reorg pool, the transaction can be cancelled in the wallet, or it can wait for the transaction to leave the reorg pool and then cancel the transaction.

**Screenshots**

n/a

**Desktop (please complete the following information):**

Windows, OSX, Linux

**Smartphone (please complete the following information):**

 n/a

**Additional context**

This happened on 5 base node + base node connected wallets after those base nodes were restarted just after the transactions were successfully broadcast to the mempool unconfirmed pool.

**Comment by SWvheerden** [comment]
I think a good look about this should be who is responsible for the tx getting into the blocks. 
From my opinion I would say the wallet is the responsible party here. The Base_node it self does not really care about this individual tx. 
We could potentially look at 2 ways here:
1: Wallet retransmits tx's 
2: Wallet sends out tx to more than one base_node. 

I believe  grin uses a combination of the two(I might be wrong). But with dandelion I think they look if its retransmitted. If not it resends it out to a different node. I dont they they flood it out first time. This should help with utxo linking.

**Comment by hansieodendaal** [comment]
Startup and transaction protocol logic has been reworked since
