### ISSUE TITLE
list-headers n lists n+1 headers

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2426]
**Describe the bug**
Using `list-headers 1` shows 2 headers

**To Reproduce**
1. run tari base node
2. run command `list-headers 1`
3. output is last 2 headers instead of last 1

**Expected behavior**
Running `list-headers [n]` should only show *n* headers 

**current output example**

```
>> list-headers 1

Header hash: 106fe98c85348eb3bd6ff1604e7ea4b9c1d2ba1fd20bf5e6cabac2870aa22b2b
Version: 1
Block height: 2673
...

Header hash: b121130a967a2401507219ad97f920b67ba27a028b664639e5b56d598e04e61e
Version: 1
Block height: 2672
...

```

**Desktop (please complete the following information):**
 - OS & Version: all OS versions, TBN 0.6

**Comment by sdbondi** [comment]
I've assigned myself, since I had to fix this to check headers in the upcoming block sync PR. Will reference this issue when that is ready to PR (ref #2428)

**Comment by delta1** [comment]
nice one @sdbondi 👍
