### ISSUE TITLE
User tried sending Tari but was unable to

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#2437]
**Describe the bug**
I'm trying send tXTR but did not send

**Expected behavior**
User should be able to successfully send tXTR

**Device:**
Android

**Date received:**
13 November 2020

**User:**
Bendito Silva

**Platform:**
Telegram Tari Channel

**Logs**
[ffi_logs_D29AC867B0D1B626C903678800AAF2C3F1D8B6A8138534D7FED6CC16CB45032E.zip](https://github.com/tari-project/tari/files/5554726/ffi_logs_D29AC867B0D1B626C903678800AAF2C3F1D8B6A8138534D7FED6CC16CB45032E.zip)

**Comment by delta1** [comment]
Resolved earlier this week on telegram 

![62EF240E-F65C-407B-80DF-67B0F9544F5B](https://user-images.githubusercontent.com/351403/99689313-84b3d500-2a8f-11eb-8f2c-9a52a8a5ba3e.jpeg)
