### ISSUE TITLE
BroadcastStrategy

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#246]
# BroadcastStrategy 

From RFC-0172:

Determines how a set of peer nodes will be selected and can be one of:

* Direct - send to a particular peer matching the given node ID
* Flood - send to all known peers who are not [communication clients]
* Closest - send to n closest peers who are not [communication clients]
* Random - send to a random set of peers of size n who are not [communication clients]

**Comment by philipr-za** [comment]
Closed by https://github.com/tari-project/tari/pull/352
