### ISSUE TITLE
Transaction Messaging

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#249]
The goal is to have peers constructing, signing and passing valid Tari transactions across the Wire.

Requirements:

1. Sender builds a new transaction (incl Range proofs). Parent of #239. Parent of #61. Requires #42.
1. Sender send message over wire to recipient
  1. Transaction can be serialized into `TariMessage`. Parent of #243
  1. Create a `PeerConnection` with peer. Parent of #232.
  1. Wrap the transaction message into a `MessageEnvelope` and send it to the peer. Parent of #223. Parent of #245. Parent of #246.
1. Recipient receives, deserializes, and dispatches message to the appropriate `MessageHandler`.
  1. InboundMessageService get message. Parent of #247.
  1. The appropriate `MessageHandler` passes the message onto `TransactionManager`. Parent of #248. Parent of #196.
  1. Recipient signs transaction. Parent of #42
  1. Recipient uses OutboundMessageService to return response.
1. Sender receives response, dispatches it to the relevant FSM via `InboundMessageServe` and `TransactionManager` and 
  1. Finalizes the message. Parent of #42.
1. Sender then prepare a broadcast message for the new transaction

**Comment by sdbondi** [comment]
Related epic: #195

**Comment by CjS77** [comment]
Closed in favour of Zenhub Epic
