### ISSUE TITLE
Tari config file

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#250]
Design and build an easy to use and configure ConfigurationFile.

Maybe there's a crate that can do this for us?

TOML, YAML, JSON? Discuss

**Comment by SWvheerden** [comment]
It looks like config-rs does exactly what we want. 
We can post pone the decision of  config type till the last minute before we ship production version 1.0 out. 

Even then it supports usage of (JSON, TOML, YAML, HJSON, INI) at the same time. Not that I think its that great idea. But its doable.

**Comment by CjS77** [comment]
There are 2 ways to go about this:

A) A global `ConfigService` that provides access to a single `Config` instance. 
This service will read from a set of defaults, config file, envars and command lines (in increasing priority) and populate the static Config struct.

Things that need config vars use the service to query for those vars as necessary.

Essentially, all configuration for the entire Tari ecosystem is kept in a centralised place.

B) Similar to A, but everything that needs configuration creates their own local `ThingConfig` struct that can populate itself with a `set_from_global(&Config)` function. This could have settings that aren't present in the global config; have different defaults (which might not be a good thing) etc, and is generally more decentralised.
