### ISSUE TITLE
Tari Logging Framework

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#251]
Implement a unified logging framework for the Tari ecosystem.

The framework should be configurable to allow
* Writing to stdout
* Writing to file
* Writing to syslog
* Writing to S3 or similar

Specific logging destinations should preferably be included via plugins and shouldn't really be explicit dependencies (e.g. Writing to S3 code shouldn't be compiled and linked in by default. -- enabling should perhaps be done with compile features).

Writing log messages should preferable be done through standard debug/logging macros.

Log messages should have a level (DEBUG, INFO, WARN, ERROR) and users should be able to decide on the level of verbosity.

Possibly there can be multiple backends, e.g. WARN and ERROR to stdout while everything gets stored to file.

Compilation / running should not fail if no logging backend has been configured. Logs should either be suppressed or written to stdout in this case.

**Comment by SWvheerden** [comment]
slog looks nice: https://github.com/slog-rs/slog

**Comment by CjS77** [comment]
SLog looks like the thing.

The overall approach is:

1. Build a `LoggingService` that acts as a centralised logging service implementing a MPSC channel. `LoggingService` is exposed as a singleton, and any thread can send log messages to the service from any thread. The data it sends is
   * Log Level
   * Process
   * Message
   * Metadata
1. `LoggingService` writes logs it receives to whichever output is configured in the Configuration file. This could be syslog, console, S3 etc. etc. Other config options include:
   1. LogLevel filtering
   1. Process filtering

**Comment by CjS77** [comment]
Fixed in #307
