### ISSUE TITLE
dyld: Library not loaded (openssl) 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2515]
`dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib` 

Replicated this issue by uninstalling openssl and trying to run a base node binary. (`brew uninstall --ignore-dependencies openssl`) 

Resolved by reinstalling openssl - `brew reinstall openssl@1.1`

**Comment by leet4tari** [comment]
My problem is not that the dylib can't be found, but that it is unsigned
```
leet-mbp:~ leet$ tari_base_node
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: /usr/local/bin/tari_base_node
  Reason: no suitable image found.  Did find:
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib: code signature in (/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib: stat() failed with errno=1
Abort trap: 6
```
Re-installing openssl did not change the error.  
  
Code signing the openssl libs solved this problem
```
codesign -f -s "Developer ID YourDevID (XXXXXXXXXX)" /usr/local/opt/openssl@1.1/lib/*.dylib
```
Could also disabled code signing verification, but I don't think that is an option. I will have to test a clean install of OSX and see if it's just me.

**Comment by delta1** [comment]
Awesome thanks @leet4tari

**Comment by xuxucode** [comment]
@leet4tari I faced same issue, how to fix that?
I have no Apple Developer Account and Self-Signed certificate dose not work

**Comment by leet4tari** [comment]
@xuxucode I currently don't know of a quick fix that does not have security concerns. We are investigating other options and will post updates here.

**Comment by futurepr0n** [comment]
I have the same issue - I don't have a developer account (paid), is there a way to disable the check on the file?

**Comment by delta1** [comment]
> I have the same issue - I don't have a developer account (paid), is there a way to disable the check on the file?

Is it not possible with the free developer account? (sign in with apple id) 

https://developer.apple.com/support/compare-memberships/

**Comment by delta1** [comment]
We are looking for a better way to solve this issue. Reopened.

**Comment by delta1** [comment]
@xuxucode @futurepr0n what version of macOS?

**Comment by xuxucode** [comment]
@delta1 
```
macOS Big Sur
Version 11.0.1
MacBook Pro (Retina, 15-inch, Mid 2015)
```

**Comment by leet4tari** [comment]
JFYI - my brew just updated my openssl 
```
Upgrading openssl@1.1 1.1.1j -> 1.1.1k
```
I did not re-sign the openssl libs and ```tari_base_node``` run without problems. I don't know if this adds any useful info.

**Comment by delta1** [comment]
Nice one @leet4tari thanks!

 @xuxucode @futurepr0n @cczufish could you try upgrading OpenSSL and let us know please?

`brew upgrade openssl`

**Comment by leet4tari** [comment]
Just to be clear, I have not done anything, just making a note 
```
leet-mbp:~ leet$ cd /usr/local/Cellar/openssl@1.1/1.1.1k/lib
leet-mbp:lib leet$ ls
engines-1.1		libcrypto.dylib		libssl.dylib
libcrypto.1.1.dylib	libssl.1.1.dylib	pkgconfig
libcrypto.a		libssl.a
leet-mbp:lib leet$ codesign -d -vv libcrypto.1.1.dylib
libcrypto.1.1.dylib: code object is not signed at all
leet-mbp:lib leet$ codesign -d -vv libssl.1.1.dylib
libssl.1.1.dylib: code object is not signed at all
leet-mbp:lib leet$ which tari_base_node
/usr/local/bin/tari_base_node
leet-mbp:lib leet$ /usr/local/bin/tari_base_node
Initializing logging according to "/Users/leet/.tari/config/log4rs_base_node.yml"
2021-03-29 11:29:35.552077000 [tari_app_utilities::identity_management] INFO  Node ID loaded with public key
```
These libs are not signed, but were and ```tari_base_node``` loads and seems to run without any errors on my Mac.
