### ISSUE TITLE
Improve Docstrings for `extend_bytes`

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#252]

**Comment by zhangcheng** [comment]
@CjS77 would you pls take a look at above linked PR and comment? like to make sure I am in the right direction first.

**Comment by CjS77** [comment]
I see that you wrote that things feel "clumsy" in the test.

Is it because you feel that the API for this trait is a bit weird? I opened this issue a long time ago, but I suspect it's because I felt that the trait was not very ergonomic and that some clear docs would help indicate how it should be used.

@mikethetike -- I did a very quick scan and looks like this trait is never used in tari_core. Maybe the best route is to deprecate it?

**Comment by CjS77** [comment]
A more detailed grep suggests it's only really used in the `Hashable` trait, so we could just bundle it up into there and remove `ExtendBytes` from tari_utilities

**Comment by zhangcheng** [comment]
> I see that you wrote that things feel "clumsy" in the test.
> 
> Is it because you feel that the API for this trait is a bit weird?

The impl part feels a bit weird to a person like me coming from Python background, seeing that literally same piece of code repeated for each similar type.

**Comment by zhangcheng** [comment]
> A more detailed grep suggests it's only really used in the `Hashable` trait, so we could just bundle it up into there and remove `ExtendBytes` from tari_utilities

I see that #215 is about the `Hashable` trait, so I will consider how to combine these two.

**Comment by zhangcheng** [comment]
> > I see that you wrote that things feel "clumsy" in the test.
> > Is it because you feel that the API for this trait is a bit weird?
> 
> The impl part feels a bit weird to a person like me coming from Python background, seeing that literally same piece of code repeated for each similar type.

I applied my newbie knowledge of macro to improve the impl part (hopefully).

Also looked into `infrastructure/derive/src/hashable.rs`, the code is way out of my league now. Is it really qualified as "good first issue", I have to wonder. 😅

**Comment by zhangcheng** [comment]
Just updated my PR, that's all I can do given my current understanding. 😺 

Small side note: i64 wasn't implemented previously, but probably just as @CjS77 checked that this piece of code is not really in use.

**Comment by zhangcheng** [comment]
Update the PR to include more general clean-up.
@CjS77 pls take a look when you have time, and there is a typo fix pending your confirmation.

**Comment by zhangcheng** [comment]
@CjS77 just want to remind you take a look at the linked PR. 😄
