### ISSUE TITLE
#[derive(Hashable)] should not automatically implement `ExtendBytes`

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#255]
`ExtendBytes` and `Hashable` are not mutually dependent, so there's no reason to automatically implement `ExtendBytes` when using `derive(Hashable)`:

`infrastructure/derive/src/hashable.rs`

**Comment by SWvheerden** [comment]
This should be relatively easy.
`Hasable` requires `ExtendBytes`. `ExtendBytes` already has it own macro. The solution to this is one of the following design choices:
* `Hashable` could search for a feature flag for `ExtendBytes` which implements it as well, but this should be an opt-in flag, not as currently opt-in by default
*  `ExtendBytes` and `Hashable` should be kept completely separate and no link between them should exist, just delete the `ExtendBytes` call in the `Hasable` macro fn

**Comment by SWvheerden** [comment]
`Hashable` creates the following function:
```
fn hash(&self) -> Vec<u8> {
                let mut hasher = <#varname>::new();
                let mut buf:Vec<u8> = Vec::new();
                #fields_text
                hasher.input(&buf);
                hasher.result().to_vec()
            }
```
#fields_text is replaced by `field.append_raw_bytes(&mut buf)` for each field. 
This function comes from `ExtendBytes` macro. As far as I know doing this double copy is the only way to generalise a copy over bytes for all types. 

Closing this issue for now
