### ISSUE TITLE
QR code not completely visible in console wallet.

### ISSUE THREAD

**Issue by artfulplonker** [tari-project/tari#2552]
When using the console wallet as normal the QR code is cropped out of the page.

This occurs for me even at full screen. The only way to view it in full is by zooming out.

My laptop has a resolution of 1366x768
OS: Ubuntu 20..04.1

![signal-2021-01-23-123728](https://user-images.githubusercontent.com/77884629/105578399-cb67c900-5d77-11eb-968c-6a1cbcf0ceec.jpeg)

**Comment by delta1** [comment]
Hey @artfulplonker ! Thanks for the report - looks like the wallet is expecting a larger vertical height to fit this in.. we'll take a look at solutions to this 

I'll comment here again once we've got a plan/fix 

Cheers!

**Comment by artfulplonker** [comment]
You're welcome. 
I know it's nothing major, but I thought it might help in some way.

**Comment by artfulplonker** [comment]
looking again, it seems like I have a similar problem with 'connected peers' on the Network tab.
I am unable to scroll to view them, the only way is by zooming out.
Is it possible that this is a problem with the way my terminal is set up, rather than an issue with the wallet?

FYI, I am using gnome version 3.36.2

**Comment by delta1** [comment]
Maybe there's some kind of zoom options in your OS/DE settings?

**Comment by artfulplonker** [comment]
There are zoom settings in the gnome terminal and I am able to view the whole qr code if i zoom out. It's just a bit inconvenient and the text gets rather small.

![Screenshot from 2021-01-26 17-49-19](https://user-images.githubusercontent.com/77884629/105883644-fd3e9100-5ffe-11eb-9c71-46968c308ea1.png)

**Comment by delta1** [comment]
Thanks for that feedback @artfulplonker will let you know how it goes!

**Comment by SWvheerden** [comment]
@artfulplonker 

This PR will should allow you to view the QR. It will be great if you can test it.

**Comment by delta1** [comment]
hey @artfulplonker, #2610 was merged so if you're building from source you could test it again. Otherwise there should be a release shortly! Thanks again

**Comment by artfulplonker** [comment]
you're welcome, i'll check the new release when it is available, thanks
