### ISSUE TITLE
Compile error when try to compile tari_comms

### ISSUE THREAD

**Issue by jont4** [tari-project/tari#2579]
**Describe the bug**
When trying to compile tari_comms, tari_app_grpc, tari_core and maybe other related, I got the following error:

tari_comms v0.8.0 (/root/tari/comms)                                     Caused by: process didn't exit successfully: 
`/root/tari/target/release/build/tari_comms-72d5d76e61bf6005/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'status: exit code: 1 - Operation not permitted (os error 1)      ', common/src/protobuf_build.rs:28:13
stack backtrace:
0: rust_begin_unwind   at / rustc/576d27c5a6c80cd39ef57d7398831d8e177573cc/library/std/src/panicking.rs:475                                             1: std::panicking::begin_panic_fmt  at /rustc/576d27c5a6c80cd39ef57d7398831d8e177573cc/library/std/src/panicking.rs:429                                             2: tari_common::protobuf_build::fmt
3: tari_common::protobuf_build::ProtoCompiler::compile
4: build_script_build::main
5: core::ops::function::FnOnce::call_once

**To Reproduce**
1. Just compile: cargo build --release

**Smartphone (please complete the following information):**
 - Device: Lenovo Z5 Pro GT, Snapdragon 855
 - OS: Android 10 (BlissROM), running Ubuntu 20.04 on termux via chroot (configured via Andronix)

**Comment by delta1** [comment]
Hey @jontaix, thanks for reporting! From what I can find, this seems to be a file permissions issue ([link](https://stackoverflow.com/questions/10937806/oserror-error-1-operation-not-permitted)) 

`profobuf_build.rs` is trying to a write a file and doesn't have permissions to do so, please can you check the permissions on all files and folders in your source code folder? 

You can use `chown` to set ownership of the files to your user/group, and `chmod` to enable write permissions. 

https://www.baeldung.com/linux/chown-chmod-permissions

**Comment by sdbondi** [comment]
@jontaix During build, code is generated from protobuf files and written to the file system. It appears that your environment does not have write permissions.

**Comment by jont4** [comment]
> Hey @jontaix, thanks for reporting! From what I can find, this seems to be a file permissions issue ([link](https://stackoverflow.com/questions/10937806/oserror-error-1-operation-not-permitted))
> 
> `profobuf_build.rs` is trying to a write a file and doesn't have permissions to do so, please can you check the permissions on all files and folders in your source code folder?
> 
> You can use `chown` to set ownership of the files to your user/group, and `chmod` to enable write permissions.
> 
> https://www.baeldung.com/linux/chown-chmod-permissions

Thanks for reply. 
I checked several times the permissions and ownership in the tari folder, and seem to be ok, all root:root with permissions to write.

**Comment by delta1** [comment]
Could you try with the latest code please

**Comment by jont4** [comment]
> Could you try with the latest code please

I tried, same error.

**Comment by sdbondi** [comment]
@jontaix The part that's failing runs `cargo fmt` - could you try running `cargo fmt --all` in your terminal?

If that works, try applying this patch to the code
[disable_fmt.patch.txt](https://github.com/tari-project/tari/files/5894349/disable_fmt.patch.txt)

**Comment by jont4** [comment]
@sdbondi I tried
`root@localhost:~/tari# cargo fmt --all
Operation not permitted (os error 1)`
and got this error.

So I applied the patch anyway and got this error:
```
error[E0599]: no method named compile found for unit type () in the current scope
  --> comms/build.rs:28:10
   |
28 |         .compile()
   |          ^^^^^^^ method not found in ()

error: aborting due to previous error

For more information about this error, try rustc --explain E0599.
error: could not compile tari_comms.
```

**Comment by sdbondi** [comment]
@jontaix Fixed the mistake in the patch file (whoops)

[disable_fmt.patch.txt](https://github.com/tari-project/tari/files/5899602/disable_fmt.patch.txt)

The patch essentially skips running `cargo fmt` for all builds. You may want to look at why your setup 
does not allow cargo fmt to be run.  

EDIT: I'm going to turn off rustfmt on build by default because the reason we needed to run rustfmt on build no longer exists.

**Comment by jont4** [comment]
@sdbondi Thanks. No errors now.
