### ISSUE TITLE
Transactions cancelled almost immediately 

### ISSUE THREAD

**Issue by artfulplonker** [tari-project/tari#2580]
Tried sending a few transactions from the base_node. Log attached.

Can someone help me understand what is going on?

[error.log](https://github.com/tari-project/tari/files/5889591/error.log)

**Comment by delta1** [comment]
hey @artfulplonker , are you running v0.8 base node? And are you trying to send to an Aurora wallet? If so, Aurora is still being updated on ios/android and won't be able to accept funds from the new `stibbons` testnet yet

**Comment by delta1** [comment]
Apologies, just spotted this in your log: 

```
2021-01-28 19:21:07.305575178 [c::mp::mempool] WARN  Validation failed due to maturity error
2021-01-28 19:21:07.564904055 [wallet::transaction_service::protocols::broadcast_protocol] ERROR Transaction (TxId: 15070699147182574379) rejected by Base Node for reason: Time Locked
``` 

I take it you mined some Tari and then tried to spend it? [Coinbase/mined outputs are now timelocked for 60 blocks](https://github.com/tari-project/tari/pull/2555/files) before they can be spent (approx 2 hours). This information still needs to be shown in the wallet UI and we're working on a few issues where those outputs should not be selected for transactions if they can't be spent.

**Comment by artfulplonker** [comment]
That's exactly right. I was sending it to a console wallet after updating to the newest version.

Glad to know there's no bug, thanks for the info :) +1:

**Comment by delta1** [comment]
Thank you for reporting and providing logs!

**Comment by delta1** [comment]
I'd like to reopen the issue until we've investigated and present this information better if that's okay!

**Comment by artfulplonker** [comment]
Sure :) let me know if I can help

edit: interesting to see that the console wallet still considers it pending income, even though there are no active transactions in the base node.

**Comment by jont4** [comment]
The same happened with a tx I sent from base_node to aurora's wallet. The utxos were mature. The tx was automatically displayed as canceled in Aurora. Minutes after an identical to canceled tx appeared as "waiting for sender to complete transaction" and does not change status. The taris I sent don't appear in the wallet. Disappeared. The base_node shows as a complete transaction.

Aurora:
![20210204-204110_Tari_Aurora](https://user-images.githubusercontent.com/31804298/106969398-7e95d200-6729-11eb-9f51-92c5b80f5f09.jpg)

**Comment by delta1** [comment]
Which Aurora version are you on?

**Comment by jont4** [comment]
> Which Aurora version are you on?

0.6.0-libwallet-0.16.17 b149

**Comment by delta1** [comment]
Thanks, could you please try to reproduce and then send logs?

**Comment by jont4** [comment]
> Thanks, could you please try to reproduce and then send logs?

Aurora and base_node logs:

[ffi_logs_20ADF66D691DE0304BF0A8CEDCB379B43B0D71C2282C077CF5EE0C6442FD6121.zip](https://github.com/tari-project/tari/files/5936228/ffi_logs_20ADF66D691DE0304BF0A8CEDCB379B43B0D71C2282C077CF5EE0C6442FD6121.zip)

[base_node.log](https://github.com/tari-project/tari/files/5936229/base_node.log)

**Comment by SWvheerden** [comment]
Thanks for the effort in logging this bug. We have made many improvements over the last year. If this issue is still present in the current version of Tari, will you please reopen the issue, and we will have a careful look into the cause?
