### ISSUE TITLE
Build failed when compiling randomx-rs v0.5.0

### ISSUE THREAD

**Issue by jont4** [tari-project/tari#2606]
**Describe the bug**

When compiling randomx-rs v0.5.0 this error happened:

``error: failed to run custom build command for randomx-rs v0.5.0 Caused by: process didn't exit successfully: /root/tari/target/release/build/randomx-rs-95b390e1c0f11a64/build-script-build (exit code: 101)
--- stderr
thread main panicked at failed to execute CMake: Os { code: 2, kind: NotFound, message: "No such file or directory" }, /root/.cargo/registry/src/github.com-1ecc6299db9ec823/randomx-rs-0.5.0/build.rs:92:14``

**Smartphone (please complete the following information):**
 - Device: Lenovo Z5 Pro GT, Snapdragon 855
 - OS: Android 10 (BlissROM), running Ubuntu 18.04 on termux via chroot

**Comment by delta1** [comment]
> failed to execute CMake 

You don't have [cmake](https://cmake.org) installed. 

Please see the build prerequisites: https://github.com/tari-project/tari#ubuntu-1804-including-wsl-2-on-windows

**Comment by stringhandler** [comment]
I think this could be a different issue. AFAIK this did compile previously?

**Comment by jont4** [comment]
@mikethetike all prerequisites was installed. And yes, I previously builded.

Edit: Sorry my mistake. I just check and CMake was not installed, I don't know why it was uninstalled. Sorry for taking your time.

**Comment by delta1** [comment]
No worries @jontaix !
