### ISSUE TITLE
`generate_wallet_test_data` is failing 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2621]
#2590 broke some tests, specifically breaking the `generate_wallet_test_data` function which is used in a number of wallet and FFI tests @SWvheerden  

to reproduce: `cargo test test_data_generation` 

file `base_layer/wallet/tests/wallet/mod.rs` [line 688 ](https://github.com/tari-project/tari/blob/development/base_layer/wallet/tests/wallet/mod.rs#L688)

**Comment by SWvheerden** [comment]
PR #2613 fixes this

**Comment by delta1** [comment]
Thanks @SWvheerden will take a look
