### ISSUE TITLE
Wallet reporting not enough funds

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#2622]
From the console output when trying to send a transaction

```
Available balance: 49808.254941 T
Pending incoming balance: 209067.645138 T
Pending outgoing balance: 212067.729613 T
 send-tari 1000000000 1ac2c7968db90f08e309b259a4edf31d225ccaa3bf13b544f0b1ee6d1a75e21c
 Not enough funds to fulfill the transaction.
```

From looking at my wallet, there should be enough funds to process that transaction.

**Comment by SWvheerden** [comment]
@hansieodendaal @philipr-za 

I dont know if any of you have seen this before and can comment as to why this could be happening.

**Comment by philipr-za** [comment]
I have not seen this in all my testing I did on friday. What branch are you running because I would posit it has to do with your latest update to UTXO selection.

What do the logs say?

**Comment by SWvheerden** [comment]
that might be it

**Comment by hansieodendaal** [comment]
Have not seen this before either
