### ISSUE TITLE
Error while syncing horizon states

### ISSUE THREAD

**Issue by jont4** [tari-project/tari#2642]
**Describe the bug**

I'm getting this error msg continuously while syncing:

`[c::bn::state_machine_service::states::horizon_state_sync] WARN  Error during sync:Final state validation failed: Final state validation failed: The UTXO set did not balance with the expected emission at height 2157`

**To Reproduce**
Sync from scratch using prune_horizon = 1000.
base_node version: 0.8.2-84fa05a-release

**OS**
Ubuntu 20.10

**Logs**
[base_layer.log.txt](https://github.com/tari-project/tari/files/5972562/base_layer.log.txt)

**Comment by delta1** [comment]
Thanks @jontaix - what is your `pruning_horizon` set to in `config.toml` ? 

If you want to remove that line from your config, you can then delete the stibbons folder and resync running a full archival node and won't have this issue (while we fix it)

**Comment by jont4** [comment]
> Thanks @jontaix - what is your `pruning_horizon` set to in `config.toml` ?

1000

> If you want to remove that line from your config, you can then delete the stibbons folder and resync running a full archival node and won't have this issue (while we fix it)

Okay, I've already done that. Thanks

**Comment by stringhandler** [comment]
Should be fixed in  #2677
