### ISSUE TITLE
error  compiling in 20.04

### ISSUE THREAD

**Issue by Donneur2lumiere** [tari-project/tari#2750]
Hello
Waiting  for compile in 20.04  take a beer but suddenly compiling stuck and leave 
"error: could not compile unsigned-varint"

Now my beer is hot, what a shame

**Comment by delta1** [comment]
Please could you post the error log

**Comment by Donneur2lumiere** [comment]
Did you update the repo ?
Friday i reproduce the crash twice, but forget to save the log. This morning i run a another build with absolutely same command and .... Miracle happens

Sorry for lost of your time you can close with comment :+1: /Dev use his magical power for resolve the bug
Thank for response Have a nice day

**Comment by delta1** [comment]
Hey @Donneur2lumiere! There were some updates, but nothing specific for this issue. Glad to hear it's working - thanks for getting involved! Let us know if you have any questions 😃
