### ISSUE TITLE
[Thanks for making Tari better] I hope you can see everything on the pic

### ISSUE THREAD

**Issue by ghost** [tari-project/tari#2766]
![Screenshot_20210318_011702_com tari android wallet](https://user-images.githubusercontent.com/75277623/111555106-fa068c80-8787-11eb-8748-32393a8f68e0.jpg)

0.6.2

**Comment by delta1** [comment]
Thanks for testing the Aurora app! 

@kukabi should that copy say "write these **24** words in order (**of their number**)" instead?

**Comment by kukabi** [comment]
Thanks @offordelete. Yes @delta1, will fix 👍🏼

**Comment by delta1** [comment]
Nice! Thanks @offordelete let us know if you have any more feedback 🙏
