### ISSUE TITLE
When a node has been running at the tip for a long time, it calculates TargetDifficulty for blocks differently to a newly synced node

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#2770]
Steps to reproduce:
1. Sync a node to tip
2. Leave it for a few days
3. Sync a new node from scratch
4. Run `list-headers 1`

Expected:
Target difficulty matches on both nodes

Actual:
Node that has been running for a few days has a higher target difficulty than newly synced node. 

This problem usually present when a block that has an achieved difficulty is close to the target difficulty, resulting in a block that is accepted by one node and not the other.

**Comment by SWvheerden** [comment]
"Period-stats [start height] [end height]" should print this out in a csv, so excel can be used to compare the results

**Comment by HandilyStop** [comment]
View #2801

**Comment by mitralwangle679** [comment]
See #2803

**Comment by Unfirmgrivet81** [comment]
Have a look at #2805

**Comment by upstagebuild585** [comment]
Have a look at #2809

**Comment by JuicyReferral136** [comment]
View #2811

**Comment by luridRegion43** [comment]
Check out #2831

**Comment by radialpartita858** [comment]
Have a look at #2860

**Comment by SWvheerden** [comment]
Test if this is still an issue on the new Esmeralda

**Comment by stringhandler** [comment]
I'm sure this has been fixed
