### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

### ISSUE THREAD

**Issue by cczufish** [tari-project/tari#2772]
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/bin/tari_base_node
  Reason: no suitable image found.  Did find:
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib: code signature in (/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib: stat() failed with errno=1
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by stringhandler** [comment]
Is this when building from source?

**Comment by delta1** [comment]
Hi @cczufish please see #2515 for two possible fixes and let us know if that helps

**Comment by delta1** [comment]
https://stackoverflow.com/questions/59214424/macos-homebrew-dylib-formula-all-hit-code-sign-errors/59245396#59245396

**Comment by cczufish** [comment]
> https://stackoverflow.com/questions/59214424/macos-homebrew-dylib-formula-all-hit-code-sign-errors/59245396#59245396

thanks ,but it not works for me .

when I excute on terminal ,and then 

codesign -f -s "Apple Development: my account" /usr/local/opt/openssl@1.1/lib/*.dylib
/usr/local/opt/openssl@1.1/lib/libcrypto.dylib: replacing existing signature
/usr/local/opt/openssl@1.1/lib/libssl.dylib: replacing existing signature

**Comment by delta1** [comment]
Will investigate further. Are you using a binary downloaded from the website?

**Comment by delta1** [comment]
@cczufish what version of macOS?

**Comment by cczufish** [comment]
> @cczufish what version of macOS?

m1 & Mac os Big Sur

**Comment by cczufish** [comment]
> downloaded

I  downloaded tari_base_node-0.8.5-aeba436-release.pkg from the website

**Comment by HandilyStop** [comment]
Take a look #2801

**Comment by mitralwangle679** [comment]
Have a look at #2803

**Comment by Unfirmgrivet81** [comment]
See #2805

**Comment by delta1** [comment]
@cczufish closing this issue for #2515 to continue there 🙏

Please try https://github.com/tari-project/tari/issues/2515#issuecomment-809132161
