### ISSUE TITLE
Clean up cucumber tests

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2776]
Improve the [cucumber tests](https://github.com/tari-project/tari/tree/development/integration_tests) by grouping logical steps into convenience functions where they can be reused across features

**Comment by HandilyStop** [comment]
#2801

**Comment by mitralwangle679** [comment]
See #2803

**Comment by Unfirmgrivet81** [comment]
Check out #2805

**Comment by upstagebuild585** [comment]
Take a look #2809

**Comment by JuicyReferral136** [comment]
Check out #2811

**Comment by luridRegion43** [comment]
Have a look at #2831

**Comment by radialpartita858** [comment]
View #2860

**Comment by brianp** [comment]
Closing. Only because we have like 3-4 "Fix cucumber" issues and since this issue was created we've refactored the entire suite (not to say it improved this particular issue) 🙃
