### ISSUE TITLE
[base-node] Implement AllowList for peers 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2777]
Implement a configurable AllowList of peers that should never be banned from communications 

- [ ] `config.toml` should accept a new key for an array of allowed peers 
- [ ] in the banning function, the peer being banned should be checked first to see if it is in the list of allowed peers, and if so **do not** ban it. An info/debug log should be added to make note of this

**Comment by HandilyStop** [comment]
See #2801

**Comment by mitralwangle679** [comment]
See #2803

**Comment by Unfirmgrivet81** [comment]
Check out #2805

**Comment by upstagebuild585** [comment]
Have a look at #2809

**Comment by JuicyReferral136** [comment]
#2811

**Comment by luridRegion43** [comment]
Have a look at #2831

**Comment by radialpartita858** [comment]
#2860

**Comment by sdbondi** [comment]
Closing because this was implemented in #3642

**Comment by delta1** [comment]
Naas
