### ISSUE TITLE
[console-wallet] Red spent text for transactions look like errors

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2778]
Propose an improvement for the console-wallet, maybe the red spend amounts should be a different color? How should spent vs received transactions be displayed? 

![image](https://user-images.githubusercontent.com/351403/112129158-cab0af00-8bcf-11eb-8606-21a860d2e979.png)

Maybe spent transactions should be displayed with a minus sign?

**Comment by HandilyStop** [comment]
Take a look #2801

**Comment by mitralwangle679** [comment]
See #2803

**Comment by Unfirmgrivet81** [comment]
#2805

**Comment by upstagebuild585** [comment]
See #2809

**Comment by JuicyReferral136** [comment]
See #2811

**Comment by luridRegion43** [comment]
Take a look #2831

**Comment by radialpartita858** [comment]
#2860

**Comment by Closelyopen12** [comment]
Have a look at #2917

**Comment by QueasilyMacerate286** [comment]
Have a look at #2919
