### ISSUE TITLE
Write versioning RFC 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2779]
Write a new [Tari RFC document](https://rfc.tari.com) describing how proposed soft/hard forks are versioned - what aspects of the consensus rules determine when a new version number should be implemented?

**Comment by HandilyStop** [comment]
Have a look at #2801

**Comment by mitralwangle679** [comment]
See #2803

**Comment by Unfirmgrivet81** [comment]
Check out #2805

**Comment by upstagebuild585** [comment]
Have a look at #2809

**Comment by JuicyReferral136** [comment]
View #2811

**Comment by luridRegion43** [comment]
Have a look at #2831

**Comment by radialpartita858** [comment]
#2860

**Comment by Closelyopen12** [comment]
#2917

**Comment by QueasilyMacerate286** [comment]
Have a look at #2919

**Comment by BadRoper98** [comment]
#2921

**Comment by Nastilydaub** [comment]
Take a look #3021
