### ISSUE TITLE
Investigate Tor issue: "No more HSDir available to query"

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#2780]
While running the Tari base node over Tor, the following notice log is logged repeatedly by Tor: 

`[notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.` 

Investigate the cause of this issue and find a fix for it (or suggest a way to fix it). 

From previous investigation into the [Tor source code](https://github.com/torproject/tor/): 

Here is the log context: 

```
Mar 03 12:51:09.000 [info] handle_response_fetch_hsdesc_v3(): Received v3 hsdesc (body size 0, status 404 ("Not found"))
Mar 03 12:51:09.000 [info] client_dir_fetch_404(): Fetching hidden service v3 descriptor not found: Retrying at another directory.
Mar 03 12:51:09.000 [debug] conn_close_if_marked(): Cleaning up connection (fd 18446744073709551615).
Mar 03 12:51:09.000 [debug] pick_hsdir_v3(): Found 6 responsible HSDirs and about to pick one.
Mar 03 12:51:09.000 [info] hs_pick_hsdir(): Could not pick one of the responsible hidden service directories, because we are rate limited..
Mar 03 12:51:09.000 [info] fetch_v3_desc(): Couldn't pick a v3 hsdir.
Mar 03 12:51:09.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
``` 

The above logs seem to indicate the notice is logged when we are unable to look up a hidden service because of rate limiting.. but the underlying cause must be ascertained.

**Comment by HandilyStop** [comment]
See #2801

**Comment by mitralwangle679** [comment]
Have a look at #2803

**Comment by Unfirmgrivet81** [comment]
See #2805

**Comment by upstagebuild585** [comment]
Check out #2809

**Comment by JuicyReferral136** [comment]
See #2811

**Comment by luridRegion43** [comment]
#2831

**Comment by radialpartita858** [comment]
Have a look at #2860

**Comment by Closelyopen12** [comment]
Take a look #2917

**Comment by QueasilyMacerate286** [comment]
Check out #2919

**Comment by BadRoper98** [comment]
Take a look #2921

**Comment by ZambianJigsaw96** [comment]
Check out #2923

**Comment by Nastilydaub** [comment]
View #3021
