### ISSUE TITLE
Are you here to help Riccardo Spagni steal some more money?

### ISSUE THREAD

**Issue by visiblyDock78** [tari-project/tari#2783]
https://www.reddit.com/r/Monero/comments/6d5yt5/what_fluffypony_just_did_is_not_ok/

Monero: BUT HE APOLOGISED TO SOME OF THEM AFTER LAUGHING AT THOSE IDIOTS!

----

Spam or truth? There is only one way to find out. Look into the sources yourself.

#2781 #2780 #2779 #2778 #2777 #2776 #2772 #2770 #2714 #2633 #2620 #2617 #2580 #2515 #2479 #2442 #2389 #2346 #2342 #2315 #2268 #2228 #2210 #2209 #2206

**Comment by delta1** [comment]
We're here to write code, take your political/philosophical issues elsewhere.
