### ISSUE TITLE
Tor error: No more HSDir available to query  &  Merge minig proxy  initial base node not achieved

### ISSUE THREAD

**Issue by Rsimoca** [tari-project/tari#2859]
**Describe the bug**
 my merge mining proxy says initial base node not achieved, current hight at #35854... (waiting = true)

**To Reproduce**
1. I installed the tari.exe
2. After the  installation was done, and the node got synced.  I modified xmrig conf.json  with my node 127.0.0.1:18081 and wallet 
3. I run Tari all as admin 
4. And i get 2 kind of errors:

  * Tor service gives me this error :
  [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.

  * Merge mining proxy:
    Initializing logging according to "C:\\Users\\0\\.tari-testnet\\runtime\\..\\config\\log4rs_merge_mining_proxy.yml"
Solo mining configuration detected, configured to submit to Monero daemon.
Connections:
- monerod (http://18.133.55.120:38081)... ✅ (v196613)
- Tari base node GRPC (127.0.0.1:18142)... ✅
- Tari wallet GRPC (127.0.0.1:18143)... ✅
Listening on 127.0.0.1:7878...
Initial base node sync not achieved, current height at #35869 ... (waiting = true)
  

**Desktop_base_node-Windows-0.8.8-55cd2eb-release

**Comment by delta1** [comment]
Hi @Rsimoca thanks for the report! 

Regarding the "no more hsdir available", no need to worry about that it doesn't affect normal operation. We have an issue tracking that at #2780. 

As for the base node sync, could you please zip up your `log/base-node` folder and post that here? Alternatively you can email it to [bug_reports@tari.com](mailto:bug_reports@tari.com) if that's easier.

**Comment by radialpartita858** [comment]
Take a look #2860

**Comment by Rsimoca** [comment]
> Hi @Rsimoca thanks for the report!
> 
> Regarding the "no more hsdir available", no need to worry about that it doesn't affect normal operation. We have an issue tracking that at #2780.
> 
> As for the base node sync, could you please zip up your `log/base-node` folder and post that here? Alternatively you can email it to [bug_reports@tari.com](mailto:bug_reports@tari.com) if that's easier.


[mining-node.zip](https://github.com/tari-project/tari/files/6335852/mining-node.zip)

**Comment by Closelyopen12** [comment]
See #2917

**Comment by QueasilyMacerate286** [comment]
Take a look #2919

**Comment by BadRoper98** [comment]
Check out #2921

**Comment by ZambianJigsaw96** [comment]
View #2923

**Comment by indigoPreserve55** [comment]
Have a look at #2927

**Comment by PurulentAcinonyx** [comment]
#2933

**Comment by veryshroud** [comment]
#2937

**Comment by Onstagethink42** [comment]
View #2939

**Comment by Nastilydaub** [comment]
Take a look #3021

**Comment by SWvheerden** [comment]
Thanks for the effort in logging this bug, We have made many improvements over the last year. If this issue is still present in the current version of Tari, will you please reopen the issue, and we will have a careful look into the cause?
