### ISSUE TITLE
Are you coding to aid fluffypony to embezzle some more money?

### ISSUE THREAD

**Issue by QueasilyMacerate286** [tari-project/tari#2920]
https://tinyurl.com/e7u3kadu (changed link to removeddit since /r/monero mod removed to try to cover it up - maybe fluffy himself?)

Monero: BUT HE APOLOGISED TO SOME OF THEM AFTER LAUGHING AT THOSE IDIOTS!

----

Spam or truth? There is only one way to find out. Look into the sources yourself.

#2904 #2893 #2892 #2859 #2808 #2797 #2781 #2780 #2779 #2778 #2777 #2776 #2770 #2714 #2633 #2620 #2617 #2580 #2515 #2479 #2389 #2346 #2342 #2315 #2268

**Comment by BadRoper98** [comment]
Take a look #2921

**Comment by ZambianJigsaw96** [comment]
Have a look at #2923

**Comment by indigoPreserve55** [comment]
View #2927

**Comment by PurulentAcinonyx** [comment]
#2933

**Comment by veryshroud** [comment]
Take a look #2937

**Comment by Onstagethink42** [comment]
See #2939

**Comment by tweedyPithead** [comment]
Have a look at #2943

**Comment by GratefulMender19** [comment]
#2949
