### ISSUE TITLE
Did fluffypony change his mind after admitting he wants to pump and dump XMR?

### ISSUE THREAD

**Issue by BadRoper98** [tari-project/tari#2922]
“I thought, ‘I’m going to pump it and dump it,’ because I was interested and taking the ideas
and implementing them in bitcoin. The bitcoin code base was far more interesting to me than monero,
and I thought, ‘I’m not going to work on this codebase, it’s terrible” he recalls.
- fluffypony on Monero

----

https://www.coindesk.com/drugs-code-icos-moneros-long-road-blockchain-mainstream

----

Spam or truth? There is only one way to find out. Look into the sources yourself.

#2920 #2904 #2893 #2892 #2859 #2808 #2797 #2781 #2780 #2779 #2778 #2777 #2776 #2770 #2714 #2633 #2620 #2617 #2580 #2515 #2479 #2389 #2346 #2342 #2315

**Comment by ZambianJigsaw96** [comment]
Check out #2923

**Comment by indigoPreserve55** [comment]
View #2927

**Comment by PurulentAcinonyx** [comment]
#2933

**Comment by veryshroud** [comment]
Have a look at #2937

**Comment by Onstagethink42** [comment]
Check out #2939

**Comment by tweedyPithead** [comment]
Check out #2943

**Comment by GratefulMender19** [comment]
Take a look #2949
