### ISSUE TITLE
Blockchain storage

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#300]
Implement persistent storage of the Tari blockchain on LMDB.

Support the following features:
* Retrieval of a given block (if it exists)
* Retrieval of a given header
* Pruning of block data beyond the pruning horizon
* Saving of newly validated blocks & headers to storage
* Re-org handling

**Comment by SWvheerden** [comment]
This will be mostly solved by #287

**Comment by SWvheerden** [comment]
MMR now has all the following, we just need to store the Tari blockchain in the MMR

**Comment by SWvheerden** [comment]
The code for this is all done, It just needs tests which should be covered by #388
