### ISSUE TITLE
Mobile wallets should have a button to trigger a scan of outputs for balance changes

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#3051]
This idea was proposed by John Davies on tari telegram. 

Basically have a button to trigger the wallet to scan the blockchain for balance changes, in addition to the normal wallet method of saving what it knows about. It will help reassure new users if something goes wrong with the standard method and will be something they are familiar with on other wallets. This was missing from Beam and Grin's wallet at launch and was added later

**Comment by SWvheerden** [comment]
has been fixed
