### ISSUE TITLE
`search-kernel` not reflecting pruned status correctly in base node

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#3120]
**Describe the bug**
With a recent stress test and multiple reorgs, `search-kernel` was not reflecting pruned status correctly in the base node CLI.

This node was an archival node, but the CLI message indicated otherwise.
Should the kernel of a deleted block be kept around?

See below:
```
>> search-kernel a43ece75e67a2aa3a0a8192704339b66f1db659622a5998f794c3634f782e752 
       cd1ea22f5a1e92d1022fd56bb189976c125796550fcb6b811183352dd8aa3400
>> Pruned node: kernel found, but block not found for kernel signature 
       cd1ea22f5a1e92d1022fd56bb189976c125796550fcb6b811183352dd8aa3400
>>
>> get-chain-metadata`
>> Height of longest chain : 6223
Geometric mean of longest chain : 28227596133895283198760
Best block : 90bc81253e4ec32fc0318f8b373edccad7ee1b431a869d079005f0dd998d507d
Pruning horizon : 0
Effective pruned height : 0
```

**To Reproduce**
1. Run a 36,000 transaction stress test from 6 sending wallets to 10 receiving wallets, with each wallet connected to its own base node.

**Expected behavior**
- `search-kernel` should always reflect pruned status correctly in the base node CLI.
- Kernels of a deleted blocks should not be kept in the blockchain database.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OSX, Windows

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by SWvheerden** [comment]
This code has been refactored quite intensively, it is not possible to get this error anymore. 
We can reopen this if we find more information that something similar can still happen.
