### ISSUE TITLE
Force node to always be in syncing mode

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#3277]
Currently, nodes decide on their status on received ping and pong messages. These messages contain the sender's ChainMetaData. 

Currently, its possible to change increase the `accumulated_difficulty` field, and then broadcast this out to every connected node. The following then happens:

- The connected node then thinks it needs to sync to you. 
- It searches for a fork and "finds" on 0 blocks back. 
- It thinks you are both in sync, and exit out of syncing mode

By the current defaults of 10_000 messages/ 100s, it means you can force the node into syncing mode every 10ms. Doing this whole dance takes longer than that. 
The older flood of 1000 messages /100s means you can send one every 100ms which is also not sufficient.

**Comment by sdbondi** [comment]
Closed in #3478
