### ISSUE TITLE
Logger configurations can't be found

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#328]
**Describe the bug**
The function `initialize_logger` in the common crate will not work in any other crate
because the path is relative to where it is being run. It will only work if run from the common crate directory.

Simple workaround: Put the configs in the repo root and make the path `../log4rs*` 

Suggestion: Allow the path to a logger config to be specified as an argument to initialize_logger. Logger should perhaps error (not panic) if it's been initialized before, but no strong opinions on that. This implies that each binary using it should be responsible for initializing it (from e.g. a command line arg which defaults to the CWD)

**To Reproduce**
1. Use initialize_logger in any crate other than common.
2.Run and observe panic from not being able to find the configurations contained in the common crate

**Expected behavior**
Logs should be able to initialize in any crate

Related to #307

**Comment by CjS77** [comment]
The intention is that applications place a `log4rs.yml` file in the same directory as the binary, so this is a borderline feature, not bug situation :)

However, I agree that the path should be configurable; as written though I'd suggest that an ENVAR  is less problematic. Right now passing a path to `initialize_logger` will cause a panic if it's called twice with different paths (in my limited experiments on this). 

If an ENVAR is changed, a subsequent call with have no effect.

**Comment by CjS77** [comment]
Closing in favour of #396
