### ISSUE TITLE
Wallet reconnect does not seem to always work

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#3288]
When a wallet tries to connect to a node that has a full amount of RPC connections, the wallet will say waiting to connect. When the base node has space available again for connections, the wallet will not reconnect and needs to restart. 

** To reproduce **

- Fill up a base node's RPC connections till it cant accept more. 
- Connect wallet to the base node
- Clear up RPC connections to base_node
- Wallet will not reconnect.

**Comment by stringhandler** [comment]
@SWvheerden is this still reproducible?

**Comment by SWvheerden** [comment]
It does not look like it is, closing this
