### ISSUE TITLE
RPC session count needs to be more intelligent 

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#3294]
Currently, the MAX RPC session count is just, a max count. We need to look at limiting the max per node. The nodes can handle quite a big load of RPC sessions, but we need to rethink the sessions to be only per node as having a broad limit makes it very easy to play shenanigans and open up loads of connections. Theoretically, a node only needs a single session.

**Comment by sdbondi** [comment]
Resolved in #4549
