### ISSUE TITLE
Node should validate incoming SAF messages

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#3410]
A node should verify all incoming SAF messages if they are legit by either, or:

- Checking if they come from a nearby neighbor and request others
- OR preferably only accepting incoming SAF messages if it requested such messages.

By not checking these messages, it allows a malicious actor to control what the node downloads by preemptively forwarding messages to it. If SAF message can be used to "break" the node, it allows an attacker to kill a node by simply sending a message to it.

**Comment by sdbondi** [comment]
Fixed in #3444 - only requested SAF responses are accepted
