### ISSUE TITLE
TransactionValidationService

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#35]
Validate new transactions when nodes receive them.

`Transaction` already has internal consistency code (commitments sum to the excess, range proofs hold, signatures are valid etc).

This issue requires blockchain validation:
* All inputs are in the current UTXO set.
* Spending locks are satisfied
* Any other feature checks

**Comment by SWvheerden** [comment]
All inputs are in the current UTXO is already verified by the MMR's in the chain
