### ISSUE TITLE
Allow OMS, IMS and OMP to shutdown cleanly

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#374]
The CommsBuilder must have a way to block program execution for the lifetime of the comms layer and be able to cleanly shutdown all comms services. (some background: https://github.com/rust-lang/rust/issues/48820) This is currently not possible as there is no way for IMS, OMS and OMP to cleanly exit their threads.

**Comment by CjS77** [comment]
Don't you collect the vector of JoinHandles and then call 'join' in your
master shutdown function?

You obv need a way to let the individual threads know that they should
terminate too.

**Comment by sdbondi** [comment]
I do in peer connection and control service - but the IMS, OMP and OMS don't
