### ISSUE TITLE
Investigate benefits of converting Inbound Message Broker + DomainConnector's to use a Pub-Sub model

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#382]
Currently for n message types registered by Domain Layer managers the IMB will create n separate dealer sockets. This means that for each new message type that can be passed on to the domain layer a new dealer-router connection is maintained.

A pub-sub model could achieve this and provide a bit more flexibility in that you can have multiple Domain layer entities receiving a given message.

**Comment by CjS77** [comment]
This is the model we will move to eventually since it offer many benefits:
* Decoupling,
* Multiple responders
* Inter-service communication
