### ISSUE TITLE
Create a gRPC interface in console wallet to set the connected base node

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#3821]
Address the following TODO in the code:

// TODO gRPC interfaces for setting base node 

clear TODO comment when completed

**Comment by zhangcheng** [comment]
I just took a crack on this.
@philipr-za pls take a look at the attached PR (#3828), does this align with your idea for this ticket?
I am new to Tari, gRPC and Rust, feedback is very welcome.

Also, I don't know how to write a proper unit test for this yet.
