### ISSUE TITLE
Add Mnemonic language Autodetection for ChineseTraditional and ChineseSimplified

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#3823]
// TODO: Develop a language autodetection mechanism to distinguish between ChineseTraditional and ChineseSimplified

remove TODO from code when done

**Comment by delta1** [comment]
This todo is in the file: `base_layer/key_manager/src/mnemonic.rs`  

Some notes: 

- [ ] Add a new variant for `ChineseTraditional` to the `MnemonicLanguage` enum
- [ ] Create a new word list in `mnemonic_wordlists` for `MNEMONIC_CHINESE_TRADITIONAL_WORDS` using the [BIP word list ](https://github.com/bitcoin/bips/blob/master/bip-0039/chinese_traditional.txt)
- [ ] Add or update tests to detect the ChineseTraditional language

**Comment by SWvheerden** [comment]
Will do this when there is a demand for this.
