### ISSUE TITLE
Implement a Thread Pool for the PeerConnection threads

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#385]
A potential DoS attack is for an attacker to request many connections and eat up the local nodes memory. 

Implement a Thread Pool so that PeerConnections can't just spin up threads indefinitely.

**Comment by sdbondi** [comment]
There are two ways this can be achieved. A shared thread pool is one, however it's quite a big change.
Another way is if connection manager, which is aware of all the connections, checks the number of active peer connections and prevents more from being created over that threshold - this would be a quick change. I'll go with the latter as that will be an hour or two to get done.

**Comment by CjS77** [comment]
Will be resolved by #549 and #543 cumulatively.
