### ISSUE TITLE
Estimated hashrate calculation is incorrect

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#3921]
The [estimated hash rate calculation](https://github.com/tari-project/tari/blob/c0750b7496d62efdde43d9d053c3f49c51299c83/applications/tari_base_node/src/grpc/base_node_grpc_server.rs#L185) is using this formula:

`t_i / (t_{i+1} - t_i)`

where `t_i` is the timestamp of the ith block.

This is not correct. It is dimensionless for one thing, whereas we expect H/s as units at the very least.

This was possibly meant to be ` (D_{i+1} - D_i)/(t_{i+1} - t_i)`

where `D_i` is the accumulated difficulty at block I.

But even though this formula would be correct in some sense, it is not very useful, because the time between blocks follows a Poisson distribution and would thus give very noisy hash rate estimates.

A smoother, and thus, more useful estimate would be to take the moving average of the difficulty divided by the target block time:

`sum(d_i)/n / t_t` carried out FOR EACH POW ALGO INDEPEDENTLY.

Thus we'll have a separate hash rate estimate for SHA3 and RandomX.

A 60 minute time window feels reasonable for the moving average, so using the last 12 SHA3 blocks for SHA3 and 18 RandomX blocks. Or just use 15 for both.

**Comment by jorgeantonio21** [comment]
Is this issue still on hold ? It looks like a very interesting issue to tackle. 

However, after looking at the current code it seems that this might have already been refactored accordingly. Indeed there is a file `hash_rate.rs` in the same parent folder as the code mentioned here, which implements the necessary logic to compute the required hash rate moving average.

**Comment by CjS77** [comment]
Yes it looks like this was fixed in #3996
