### ISSUE TITLE
Downcasting in difficulty calculation can lead to overflow 

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#3923]
The [difficulty calculation](https://github.com/tari-project/tari/blob/c0750b7496d62efdde43d9d053c3f49c51299c83/base_layer/core/src/proof_of_work/difficulty.rs#L119) has an overflow issue:

```rust 
pub(crate) fn big_endian_difficulty(hash: &[u8]) -> Difficulty {
        let scalar = U256::from_big_endian(hash); // Big endian so the hash has leading zeroes
        let result = U256::MAX / scalar;
        result.low_u64().into()
    }
```

Here, `scalar` is the target for the mining algorithm. The smaller the target, the more difficult it is to find a hash with the requisite number of leading zeroes.

The definition of difficulty is `TARGET_MAX / target`. Once target falls below 2^192, the difficulty will overflow to zero, since we downcast to 64 bits by truncating the highest portion of the actual difficulty.

Now, this is possibly only a theoretical problem since we need a ridiculous hashrate before this become an eventuality. We will certainly have native 256-bit integers long before this happens. 

However, to protect against weird things happening, it might be better to prevent the overflow anyway by returning `u64::max` if scalar <= 2^192.

**Comment by jorgeantonio21** [comment]
Hello, I am interested in tackling this issue. I included the suggested code change in a newly created PR:

https://github.com/tari-project/tari/pull/4090

 I also want to add test coverage for this new functionality, but I am having some difficulty with it, which I describe in the PR. Any help is highly appreciate it.
