### ISSUE TITLE
`CipherSeed` MAC is keyed directly with low-entropy passphrase

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4182]
The MAC used in the `CipherSeed` construction is [keyed](https://github.com/tari-project/tari/blob/development/base_layer/key_manager/src/cipher_seed.rs#L214) (via `Blake2b` input concatenation) with the user-supplied passphrase, which should be assumed to be of low entropy.

A straightforward improvement is to extend the associated `Argon2` output and split it to generate two keys: one for the `ChaCha20` encryption, and the other for the MAC. While the MAC is very short (only 5 bytes in the current design), this approach can take some advantage of any key stretching provided by `Argon2`, in addition to preventing an attacker from performing any kind of precomputation on the MAC prior to deriving the key.

Additionally, the use of `Blake2b` for this MAC construction should use proper domain separation. Any future hashing API should be strongly considered for this.

**Comment by hansieodendaal** [comment]
Wow, the pitfalls...

**Comment by jorgeantonio21** [comment]
I tried to tackle this issue, the PR can be found [here](https://github.com/tari-project/tari/pull/4296).

**Comment by AaronFeickert** [comment]
Another recommendation that came up recently in a discussion with @jorgeantonio21 was to use separate hash operations for turning the [primary salt](https://github.com/tari-project/tari/blob/development/base_layer/key_manager/src/cipher_seed.rs#L116) into the `Argon2` [salt](https://github.com/tari-project/tari/blob/development/base_layer/key_manager/src/cipher_seed.rs#L245) and `ChaCha20` [nonce](https://github.com/tari-project/tari/blob/development/base_layer/key_manager/src/cipher_seed.rs#L241). This follows the best practice of not reusing key- or nonce-type material across different cryptographic primitives. The primary salt should continue to be used directly when [computing the MAC](https://github.com/tari-project/tari/blob/development/base_layer/key_manager/src/cipher_seed.rs#L140), as there it serves as something akin to authenticated associated data.
