### ISSUE TITLE
Move power-of-two chunking logic for range proofs batch verification into the the Bulletproofs+ crate

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4279]
This function should be in the bulletproofs+ crate. Think about it - Verifying batches of non power-of-two sets is something you'd be writing over and over if its not there.

_Originally posted by @CjS77 in https://github.com/tari-project/tari/pull/4260#discussion_r913607007_

**Comment by stringhandler** [comment]
Given that this is optimization and not a requirement for processing, it does not need to be in the BP+ crate. It may be removed at some point from the Tari code base in favour of some other optimization
