### ISSUE TITLE
Examine peer banning logic

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4339]
Since #4336 introduces a new message decryption failure mode, this is a good opportunity to review peer banning logic more broadly. Here are some hypothetical scenarios that should not occur:

1. A node attempts to decrypt a message not intended for it, so the message signature authenticated decryption fails, which does not represent malicious behavior. The node bans the peer that forwarded the message.
2. A sender crafts a message maliciously in such a way that only the recipient can detect the manipulation. The recipient bans the forwarding peer, but not the sender.
3. A forwarding node manipulates a message it receives in a way that only the recipient can detect, and then passes it to an honest forwarding node before delivery to its recipient. The recipient bans the honest forwarding node, but not the malicious forwarding node.

The first scenario would presumably result in mass bans even in the absence of active adversaries. The second and third scenarios could be easily abused by an active adversary to result in a denial-of-service attack on the network.

In general, encryption-related failures should only result in a peer ban if the following are true:
- The failure mode represents malicious behavior.
- The banning node knows definitively that its forwarding peer performed the malicious behavior. Note that identifying a message as malicious and forwarding it anyway is itself malicious behavior.

**Comment by SWvheerden** [comment]
| Method                                                                             | Link                                                                                                                                                                                                                                                                                                                       | Where? (context)                                           | Reason to ban                                                                               | Who?                                | Cause | Ban duration       | Is this correct?                 |
| ---------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- | ------------------------------------------------------------------------------------------- | ----------------------------------- | ----- | ------------------ | -------------------------------- |
| base\_node::comms\_interface::inbounds\_handlers::request\_full\_block\_from\_peer | [https://github.com/tari-project/tari/blob/9aed188ccd7b2caffa10e061ba0d0c3253fb0b16/base\_layer/core/src/base\_node/comms\_interface/inbound\_handlers.rs#L612](https://github.com/tari-project/tari/blob/9aed188ccd7b2caffa10e061ba0d0c3253fb0b16/base_layer/core/src/base_node/comms_interface/inbound_handlers.rs#L612) | Received block header with pow                             | Peer sent block header with valid pow, but when asked for the full block did not provide it | peer who could not privde the block |       | CUSTOM: 100 Secs   | Y                                |
| base\_node::comms\_interface::inbounds\_handlers::handle\_block                    | [https://github.com/tari-project/tari/blob/9aed188ccd7b2caffa10e061ba0d0c3253fb0b16/base\_layer/core/src/base\_node/comms\_interface/inbound\_handlers.rs#L710](https://github.com/tari-project/tari/blob/9aed188ccd7b2caffa10e061ba0d0c3253fb0b16/base_layer/core/src/base_node/comms_interface/inbound_handlers.rs#L710) | handle incoming block received from peer                   | Peer provided an invalid block                                                              | peer who provided the block         |       | Permanent          | Y                                |
| Base\_node::sync::block\_sync::Synchroniser                                        | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/block\_sync/synchronizer.rs#L178](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/block_sync/synchronizer.rs#L178)          | base node is busy downloading blocks from peer during sync | Peer provided an invalid block                                                              | The peer who provided the bad block |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::block\_sync::Synchroniser                                        | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/block\_sync/synchronizer.rs#L191](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/block_sync/synchronizer.rs#L178)          | base node is busy downloading blocks from peer during sync | Peer sent incomplete data                                                                   | The peer who provided the data      |       | Ban\_period        | Y                                |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L179](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L179)        | Base node is busy download headers                         | rpc connection timeout                                                                      | peer who timeout                    |       | Ban\_period\_short | Y                                |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L183](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L179)        | Base node is busy download headers                         | Peer provided in invalid header                                                             | peer who provided the header        |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L187](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L179)        | Base node is busy download headers                         | Base\_node and peer dont have a common block                                                | peer who provided the header        |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L191](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L179)        | Base node is busy download headers                         | Peer lied about the Pow of its chain                                                        | Peer who provided the header        |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L209](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L179)        | Base node is busy download headers                         | Headers peer sent does not form a chain on hashes                                           | Peer who provided the headers       |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L213](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L213)        | Base node is busy download headers                         | Peer lied about the Pow of its chain                                                        | Peer who provided the header        |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L222](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L213)        | Base node is busy download headers                         | Headers peer sent does not form a chain on heights                                          | Peer who provided the header        |       | Ban\_period        | Perhaps this should be permanent |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L445](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L213)        | Base node is busy determining where chains diverge         | Peer sent too many headers                                                                  | Peer who provided the header        |       | Ban\_period        | Y                                |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L470](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L213)        | Base node is busy determining where chains diverge         | Peer sent bad data on where split is                                                        | Peer who provided the header        |       | Ban\_period        | Y                                |
| Base\_node::sync::header\_sync::Synchroniser                                       | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base\_layer/core/src/base\_node/sync/header\_sync/synchronizer.rs#L530](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/base_layer/core/src/base_node/sync/header_sync/synchronizer.rs#L213)        | Base node is busy determining sync status                  | Peer has a tip hiehgt less that the chain diverge height                                    | Peer who provided the header        |       | Ban\_period\_short | Y                                |
| comms::dht::src::connectivity::mod                                                 | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/connectivity/mod.rs#L320](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/connectivity/mod.rs#L320)                                                                     | Base\_node checkis message rate                            | peer send more than messages than allowed                                                   | Peer who spammed                    |       | Ban\_period\_short | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | source msg did not contain a signature                                                      | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | source msg is encrypted and did not contain a n ephemeral public key                        | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | source msg is unencrypted and did not contain a valid signature                             | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | source msg did not contain a valid signature                                                | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | Source msg is encrypted but has no destination                                              | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::inbound::decryption                                               | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/inbound/decryption.rs#L202)                                                                 | Node is decryption messages                                | source msg did not contain a valid signature                                                | Source                              |       | Ban\_period        | Y                                |
| comms::dht::src::network\_discovery::discovering                                   | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/network\_discovery/discovering.rs#L225](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/network_discovery/discovering.rs#L225)                                          | Node received a peer from peer                             | source sent an invalid peer                                                                 | source                              |       | Ban\_period        | Y                                |
| comms::dht::src::network\_discovery::on\_connect                                   | [https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/network\_discovery/on\_connect.rs#L86](https://github.com/tari-project/tari/blob/5703d02d419b1a5f49f4523707f7f689c01eb1b5/comms/dht/src/network_discovery/on_connect.rs#L86)                                             | Busy connecting to a new peer                              | Peer has invalid address or signature                                                       | peer                                |       | Ban\_period        | Y                                |
