### ISSUE TITLE
Delete Seed words commands from GRPC

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4363]
~~Seed word command is broken on GRPC~~

` thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', applications/tari_console_wallet/src/grpc/wallet_grpc_server.rs:1210:50`
~~

Delete the two seed words commands from GRPC

**Comment by delta1** [comment]
Fixed in #4370

**Comment by SWvheerden** [comment]
This is still broken

**Comment by SWvheerden** [comment]
GRPC just returns file path is empty

**Comment by SWvheerden** [comment]
We need to remove this from GRPC service, this is a dangerous call.

**Comment by stringhandler** [comment]
waiting on ci
