### ISSUE TITLE
fix cucumber transaction builder

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4390]
Since the new hasing api, the signatures of the cucumber tests are not working correctly. 
We need to fix the signatures in transactionBuilder.js

**Comment by stringhandler** [comment]
This Js class might be useful
![image](https://user-images.githubusercontent.com/4200336/183021693-fe014d92-9383-4a13-abc1-8b6299ddba8a.png)

**Comment by SWvheerden** [comment]
That's the reason it's not working, 
We have some disconnect between the JS Domain hasher and the Rust Domain hasher.

**Comment by SWvheerden** [comment]
fixed in: https://github.com/tari-project/tari/pull/4420
