### ISSUE TITLE
Implement tari_crypto hashing API: Comms

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4393]
|      | Effective  GitHub hash: d25d726ed7e04a066135b80b1de9c019d928a75c |                              |        |                                                              |                                                              |
| ---- | ------------------------------------------------------------ | ---------------------------- | ------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| #    | Reference                                                    | Function/Area                | Yes/No | URL                                                          | URL long                                                     |
| 24   | comms/core/src/peer_manager/identity_signature.rs:141        | fn  construct_challenge      | Yes    | [identity_signature.rs:141](https://github.com/tari-project/tari/blob/development/comms/core/src/peer_manager/identity_signature.rs#L141) | https://github.com/tari-project/tari/blob/development/comms/core/src/peer_manager/identity_signature.rs#L141 |
| 25   | comms/core/src/peer_manager/node_id.rs:74                    | NodeId::from_key             | Yes    | [node_id.rs:74](https://github.com/tari-project/tari/blob/development/comms/core/src/peer_manager/node_id.rs#L74) | https://github.com/tari-project/tari/blob/development/comms/core/src/peer_manager/node_id.rs#L74 |
| 26   | comms/dht/src/dedup/mod.rs:51                                | pub fn  create_message_hash( | Yes    | [mod.rs:51](https://github.com/tari-project/tari/blob/development/comms/dht/src/dedup/mod.rs#L51) | https://github.com/tari-project/tari/blob/development/comms/dht/src/dedup/mod.rs#L51 |

**Comment by sdbondi** [comment]
Implemented one that was missing here in #4432

**Comment by jorgeantonio21** [comment]
I think this issue can be closed as of now.
