### ISSUE TITLE
Implement tari_crypto hashing API: mmr & wallet

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4395]
|      | Effective  GitHub hash: d25d726ed7e04a066135b80b1de9c019d928a75c |                                   |        |                                                              |                                                              |
| ---- | ------------------------------------------------------------ | --------------------------------- | ------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| #    | Reference                                                    | Function/Area                     | Yes/No | URL                                                          | URL long                                                     |
| 18   | base_layer/mmr/src/common.rs:174                             | pub fn  hash_together<D: Digest>( | Yes    | [common.rs:174](https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/common.rs#L174) | https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/common.rs#L174 |
| 19   | base_layer/mmr/src/merkle_mountain_range.rs:137              | pub(crate) fn  hash_to_root(      | Yes    | [merkle_mountain_range.rs:137](https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/merkle_mountain_range.rs#L137) | https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/merkle_mountain_range.rs#L137 |
| 20   | base_layer/mmr/src/merkle_proof.rs:188                       | fn check_root<D:  Digest>(        | Yes    | [merkle_proof.rs:188](https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/merkle_proof.rs#L188) | https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/merkle_proof.rs#L188 |
| 21   | base_layer/mmr/src/mutable_mmr.rs:122                        | pub fn  get_merkle_root(          | Yes    | [mutable_mmr.rs:122](https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/mutable_mmr.rs#L122) | https://github.com/tari-project/tari/blob/development/base_layer/mmr/src/mutable_mmr.rs#L122 |
| 22   | base_layer/wallet/src/output_manager_service/service.rs:2725 | fn hash_secret_key(               | Yes    | [service.rs:2725](https://github.com/tari-project/tari/blob/development/base_layer/wallet/src/output_manager_service/service.rs#L2725) | https://github.com/tari-project/tari/blob/development/base_layer/wallet/src/output_manager_service/service.rs#L2725 |
| 23   | base_layer/wallet/src/transaction_service/service.rs:2629    | fn hash_secret_key(               | Yes    | [service.rs:2629](https://github.com/tari-project/tari/blob/development/base_layer/wallet/src/transaction_service/service.rs#L2629) | https://github.com/tari-project/tari/blob/development/base_layer/wallet/src/transaction_service/service.rs#L2629 |

**Comment by CjS77** [comment]
Nice commit messages ❤️
