### ISSUE TITLE
console_wallet command "coin-split" not working

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4408]
**Describe the bug**

The console wallet opens the TUI without executing the command:
``` 
tari_console_wallet.exe --base-path . --password 1 --network esmeralda --command "coin-split 1000100000 166" --config .\config\config.toml --log-config .\config\log4rs_console_wallet.yml
```

**To Reproduce**

Execute as above

**Expected behavior**

This line must be printed: `info!(target: LOG_TARGET, "Starting wallet command mode");`
The command should execute.

**Screenshots**

``` rust
tari_console_wallet.exe --base-path . --password 1 --network esmeralda --command "coin-split 1000100000 166" --config .\config\config.toml --log-config .\config\log4rs_console_wallet.yml
Initializing logging according to ".\\.\\config\\log4rs_console_wallet.yml"
Tari Console Wallet running... (gRPC mode started)
Tari Console Wallet running... (TUI mode started)

Shutting down wallet... Done.
```

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by stringhandler** [comment]
This has been changed to:

`tari_console_wallet.exe --base-path . --password 1 --network esmeralda  --config .\config\config.toml --log-config .\config\log4rs_console_wallet.yml coin-split 1T 166`
