### ISSUE TITLE
console_wallet command "--command-mode-auto-exit" is broken

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4409]
**Describe the bug**

Command `--command-mode-auto-exit` is broken
```
tari_console_wallet.exe --base-path . --password 1 --command-mode-auto-exit "coin-split 1000100000 166" --config .\config\config.toml --log-config .\config\log4rs_console_wallet.yml  --network esmeralda
```

**To Reproduce**

Run as above.

**Expected behavior**

The command should be executed.

**Screenshots**

``` rust
tari_console_wallet.exe --base-path . --password 1 --command-mode-auto-exit "coin-split 1000100000 166" --config .\config\config.toml --log-config .\config\log4rs_console_wallet.yml  --network esmeralda
error: Invalid value "coin-split 1000100000 166" for '<LOG_LEVEL>': attempted to convert a string that doesn't match an existing log level

For more information try --help
```

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by stringhandler** [comment]
The `--command-mode-auto-exit` works, but you need to specify a command. See `--help` for available commands
