### ISSUE TITLE
Wallet should detect local base nodes and automatically use them unless configured not to

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4414]
1. scan the common port/s on localhost
2. call `identify` and check the result
3. set base node

**Comment by stringhandler** [comment]
The wallet must prompt the user with something like "I detected a local base node running at 18142. Would you like to use this base node? **IF YOU DID NOT START THIS BASE NODE YOU SHOULD SELECT NO** (Y/n)"

**Comment by stringhandler** [comment]
@sdbondi I remember a PR for this. Can this be closed?

**Comment by sdbondi** [comment]
@stringhandler Nope not implemented - I think you're thinking of auto-detecting the tor control port authentication #4428
