### ISSUE TITLE
Console wallet: Reports of "buggy resizing" on tmux on linux and windows 

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4416]
Context: https://t.me/tariproject/61480

**Comment by Cifko** [comment]
I can't reproduce mentioned behavior.
But on windows there is an issue with the base node. By default the app try to resize itself. But that works only in old terminal (Windows Console Host). If you are like me and have Windows Terminal set as a default, then you can't resize and the resizing ends up messing with the outputs. It's a known issue https://github.com/microsoft/terminal/issues/5094 .
