### ISSUE TITLE
Create a simple NewBlockTemplate that creates a block template and inserts the coinbase in one -- one sided coinbase

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4419]
The current 2 step process of creating a block template is inefficient and means that there could be a delay for miners. Mining nodes that have implemented a better get_template will win more blocks, so it should be as efficient as possible

**Comment by SWvheerden** [comment]
The biggest issue we have here is the private key. 
We need some unique key generation here. 
Either 

- we need to send over a private key with grpc
- add in a default wallet to call from the base_node
- add a built-in wallet to the base node
- provide the seed key so the base node can construct the correct key.

**Comment by SWvheerden** [comment]
If the Miner can calculate the MMR roots, then we can do it in a single call.
Problem with this however is that to calculate new MMR roots, the miner needs a copy of the entire pruned set of the MMR.

**Comment by SWvheerden** [comment]
This is very much solved by make the coinbase transactions one-sided. 

We can use two methods on this: normal 1-sided or even stealth-1-sided. 
We can only use the HW wallet method as per RFC 205 -> https://github.com/tari-project/rfcs/pull/98
