### ISSUE TITLE
Increase test coverage on comms

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#442]

**Comment by CjS77** [comment]
Increase test coverage on comms crate to >70% (as measured with the code coverage script)

**Comment by SWvheerden** [comment]
All files read >70% except one file that is tested in the integration tests. The rest are just flagged enums or structs.

**Comment by SWvheerden** [comment]
I investigated tarpaulin as well, but until they fix their threading issue it is not usable for us. The results from single thread crates where positive thou.

**Comment by philipr-za** [comment]
Looks good for now.
