### ISSUE TITLE
MMR root calculation for non tips

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4436]
Currently, the function `calculate_mmr_roots` does not work on any height except the tip height. 
Expand this so it can calculate the function at any height.

**Comment by stringhandler** [comment]
@SWvheerden please expand on the impact of not fixing this.

**Comment by SWvheerden** [comment]
I am very much in favour of not fixing this. This was added due to an offline discussion, I don't know if anyone wants to add a reason for fixing this?

My reasons for not fixing this would be:
MMR roots are calculated for two reasons: creating new blocks for mining, and verifying integrity when adding a new block. 
These cases should only happen at the tip and not anytime else. This falls very much in line with the reason we have MMR roots in the header and that is to validate the tip.
So according to me, there is not really an impact of not fixing this. 

Fixing this in my mind will only complicate the calculation code.

**Comment by stringhandler** [comment]
Closing for now. Can reopen if needed
