### ISSUE TITLE
fix critical cucumber tests

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4457]
We need to fix all cucumber tests marked as `@critical and @broken`

**Comment by hansieodendaal** [comment]
@Cifko, see fix here: https://github.com/tari-project/tari/pull/4445/commits/16da4afa882824c1aaba2dd8d9942c5e0fe8f20f. All (`@critical` and but not `@broken`) tests passed on #4445.

**Comment by Cifko** [comment]
Out of the 7 marked as `@critical and @broken` 4 works fine. There is a comment about flakiness possibility. But I tried to rerun them couple times and they work fine. I'm working on one of the still broken ones. It's still broken after an update.

**Comment by SWvheerden** [comment]
Perhaps we can try then without the `@broken` tag on ci?

**Comment by Cifko** [comment]
> Perhaps we can try then without the `@broken` tag on ci?

I've created a PR for the (I have a hope) working tests: https://github.com/tari-project/tari/pull/4471
