### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/tari#4498]
The newest FFI Lib build have a problem with decrypting the DB from the iCloud backup.

**To Reproduce**
1. Update FFI Lib (with fixed encryption/decryption issue)
2. Build a new iOS Aurora App
3. Upload new DB snapshot to the iCloud
4. Delete App
5. Install App
6. Restore DB from iCloud

**Expected behavior**
The app open the home screen. The transactions and balance is presented on the screen

**Observed behavior**

App crashes when `create_wallet` is called

```
thread 'tokio-runtime-worker' panicked at 'Could not initialize Output Manager Se
rvice: KeyManagerServiceError(KeyManagerStorageError(AeadError("Decryption Error")))', /Users/runner/work/tari/tari/base_layer/wallet/src/output_manager_service/mod.rs:144:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

Log files:
[Logs.zip](https://github.com/tari-project/tari/files/9371567/Logs.zip)

**Comment by stringhandler** [comment]
@agubarev any ideas?
