### ISSUE TITLE
Wallet FFI methods wallet encryption and decryption should have callbacks

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4503]
Currently, the mobile wallets have no indication if this has been completed or not using callbacks will provide the mobile wallets with a method to wait the correct amount of time for these tasks to finish.

**Comment by stringhandler** [comment]
Possible not a problem, waiting for feedback from @TruszczynskiA

**Comment by SWvheerden** [comment]
Fixed in https://github.com/tari-project/tari/pull/4905
