### ISSUE TITLE
[console wallet] p2p comms becomes unresponsive, only resolves by deleting dht and peer db

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4530]
With a recent stress test involving 4 sender and 3 receiver wallets, one of the receiver wallets could not respond to any new transactions being received. This was only resolved when restarting after deleting its dht db _and_ peer db. The specific place where the receiver protocol got stuck (_looking like an interlock_) is shown below:

In `async fn accept_transaction`
- Passed `if self
                .resources
                .db
                .transaction_exists(...).await`
- Passed `let rtp = self
                .resources
                .output_manager_service
                .get_recipient_transaction(...).await`
- Passed `let inbound_transaction = InboundTransaction::new(...)`
- Passed `self.resources
                .db
                .add_pending_inbound_transaction(...).await`
- Got stuck in `let send_result = send_transaction_reply(..).await`
  - Called `send_transaction_reply_direct(...).await`
    - Got stuck in `outbound_message_service
        .send_direct(...).await`
    - Never got to `if wait_on_dial(...).await`
- Never got to `self.resources
                .db
                .increment_send_count(...).await`

**Comment by sdbondi** [comment]
Is this still an issue?

**Comment by hansieodendaal** [comment]
I think we should keep this one around for observation at least, as a reminder, unless we have made a PR that could potentially fix this.

**Comment by hansieodendaal** [comment]
The symptoms were not repeated with the latest stress test, so closing this issue.
