### ISSUE TITLE
base node seed peer connections "forgotten" after some time

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4531]
With a recent stress test involving only 8 base nodes in a private network, where all participating base nodes are configured as peer seeds, the base node connections started falling away after some time. One way to revive the connections, apart from a reboot, was to perform `dial-peer` and/or `discover-peer` from the command console.

**Comment by sdbondi** [comment]
These are difficult without a way to reproduce and/or precise details. I suspect that #4607 could help with this.

**Comment by hansieodendaal** [comment]
I think we can close this one as I have not observed this issue again after #4607 went live.
