### ISSUE TITLE
bug: log dir is relative to binary instead of base-path

### ISSUE THREAD

**Issue by delta1** [tari-project/tari#4538]
**Describe the bug**

logs dir is relative to binary instead of base-path 

**To Reproduce**

`./tari_base_node --base-path /tmp/tari --network dibbler` 

`logs` dir will be in current directory instead of directory specified by `--base-path` 

**Expected behavior**

logs should go in the base-path dir 

**Desktop (please complete the following information):**

 - OS & Version: 
Ubuntu 22.04
0.32.12 dibbler

**Comment by brianp** [comment]
hah cheers mate, came to close this but it's taken care of 😆
