### ISSUE TITLE
Separate storage paths for different networks

### ISSUE THREAD

**Issue by agubarev** [tari-project/tari#4542]
Once base node has been initialized it creates the datastore directories and files for whichever network it was initialized for, but after, when trying to run the same node for another network, the base node notifies that the node identity files isn't found and asks whether you want to create one, this is fine, but it tries to re-use the same datastore path.

One simple solution is to nest everything related to different networks inside `~/.tari/<network>/...`

**Comment by stringhandler** [comment]
Yeah, this makes so much sense. Should have been done like this originally

**Comment by delta1** [comment]
There’s probably a bunch more stuff like this you could copy from bitcoind/monerod.

**Comment by delta1** [comment]
eg: stuff like regtest is invaluable

**Comment by SWvheerden** [comment]
This has been done
