### ISSUE TITLE
Perform burn-utxo stress test (coin split + burn)

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4548]

**Comment by hansieodendaal** [comment]
We need the burn console command (#4547) for this

**Comment by stringhandler** [comment]
Good idea

**Comment by hansieodendaal** [comment]
**Stress Test Feedback:** _Burn-tari stress test_

Burning 49,800 outputs in each of 6 wallets, 298,800 in total

That test went extremely well, with no issues to report. We should see the effect a bit when syncing a new base node due to the burnt data set when compared to a chain without burnt outputs.

**Comment by hansieodendaal** [comment]
**Stress Test Feedback:** _Wallet to wallet interactive_
This latest stress test was a huge success, 100% of 26,999 transactions that were negotiated were mined, and only 1 transaction was not attempted/abandoned. All transactions were mined within 33 blocks, from `#2768` to `#2801`, an average of 818 transactions per block. All 8x base nodes that were monitored also properly kept up with bock chain sync.

**Comment by CjS77** [comment]
What was the minimum number of blocks to mine all 27,000 txs?

**Comment by hansieodendaal** [comment]
We had 6 empty blocks near the end, so it could have been done in 27 blocks - see block fill graph below:

![Image](https://user-images.githubusercontent.com/39146854/207519168-53b62a33-ce46-4313-941d-0e2108af818b.png)
