### ISSUE TITLE
`Command runner exits with 'Diesel error: database is locked'

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4555]
**Edit:** Title changed from `Wallet panics with 'Diesel error: database is locked'` to `Command runner exits with 'Diesel error: database is locked'` (_The wallet did not actually panic_)

Examples:

- Invalid command. Output manager error: `Output manager storage error: `Diesel error: `database is locked```
- Invalid command. Output manager error: `Key manager service error : Storage error: `Diesel error: `database is locked```

Probable (most likely) cause: 
- spawn blocking sql db calls 

The command script file (_condensed for legibility_):

```
# Let us stress the network

get-balance

# 1 of 140
coin-split 0.01T 499
# 2 of 140
coin-split 0.01T 499
.
.
.
# 140 of 140
coin-split 0.01T 499

```

**Comment by stringhandler** [comment]
Needs some more detail

**Comment by hansieodendaal** [comment]
Related PRs to fix this before another test is attempted: #4564, #4575, #4591 and #4597.

**Comment by hansieodendaal** [comment]
**Feedback:**
- I could perform 200 coin spilts producing 99,800 UTXOs on each of 3 wallets successfully without encountering the `Diesel error: 'database is locked'` error.
- However, trying to perform the same test again afterward using the same wallets (with the added transaction and outputs data from the previous test) resulted in the `Diesel error: 'database is locked'` error.

**Comment by hansieodendaal** [comment]
We have implemented all the recommended pragmas
Our error condition is described here: https://www.sqlite.org/rescode.html#locked
#4613 may help to fix the continued error

See related discussion in [stackoverflow](https://stackoverflow.com/questions/57123453/how-to-use-diesel-with-sqlite-connections-and-avoid-database-is-locked-type-of)

**Comment by hansieodendaal** [comment]
See #4615 - `Diesel error: 'database is locked'` is not a non-recoverable error but the command runner stopped prematurely.
