### ISSUE TITLE
Tetiana's Test bug 1

### ISSUE THREAD

**Issue by tatkom** [tari-project/tari#4574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS & Version: [e.g. iOS 10.2.1]
 - Browser & Version [e.g. chrome v71.0.12345]

**Smartphone (please complete the following information):**
 - Browser & Version [e.g. stock browser v0.1.2]

**Additional context**

**Comment by delta1** [comment]
?
