### ISSUE TITLE
[DHT] decrypt should return DhtInboundError

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4596]

**Comment by AaronFeickert** [comment]
Related to this, it may be useful to break message decryption and deserialization errors out further. This would include authentication errors, other decryption failures, and padding errors. Some of these also apply to outbound messages.

For safety, the codebase should avoid leaking specific message failure modes externally, as an adversary may be able to use error types or other timing data to make inferences about messages. That being said, it sounds like having specific error types is still useful for testing or other internal use cases.
