### ISSUE TITLE
Wallet does not use "connected" base node

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4599]
There exist cases where the wallet is connected to a specific user set base_node, and shows its connected. 
But when utxo validation process starts, it uses an rpc connection to a seed node defined in the config. 

This should not happen. When a wallet is connected to a node, it should only use connections to that specific node.

**Comment by sdbondi** [comment]
@SWvheerden Please confirm if this still happens or if #4610 resolves it

**Comment by SWvheerden** [comment]
I think we can close this, I cant seem to validate that the wallet uses any other node if it has a node set, even if the base node is closed
