### ISSUE TITLE
[base node] Force sync peers doesnt work (duplicate config)

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4646]

**Comment by stringhandler** [comment]
To confirm I understand:
 "If you add a force sync peer to the config, it is not enforced"

**Comment by sdbondi** [comment]
This was hack fixed in the PR that references this (https://github.com/tari-project/tari/pull/4647/files#diff-6e9e3f32e84954314cbbdf459c53d1e61da84ab09d309e787fecb99b57970ee6R98) so we can close this one.

I'll look into it and make a proper issue because I think there were a few config fields that were duplicated in different structs that could lead to bugs and should be cleaned up
