### ISSUE TITLE
Local base node discovery by wallet must take current network into account

### ISSUE THREAD

**Issue by agubarev** [tari-project/tari#4658]
When console wallet is initialized, it looks for a local node running and offers to use it if found, but it does so even if wallet and base node's networks mismatch.

**Comment by stringhandler** [comment]
@agubarev is this still the case? I think this  might have been fixed

**Comment by stringhandler** [comment]
Please add reproducable steps

**Comment by SWvheerden** [comment]
I think this has been fixed with the feature gating.
