### ISSUE TITLE
Add pagination to the gRPC Text Message polling request. Investigate gRPC streams to replace polling.

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#466]
Currently when a gRPC client asks for the current text messages they get all the Sent and Received messages ever sent. Rather implement some sort of pagination so that only relevant portions are sent back to the client. A possible strategy is that the first request sends all messages to date and subsequent requests include a timestamp of the previous request and only new messages are returned.

**Comment by CjS77** [comment]
gRPC shelved for time being
