### ISSUE TITLE
Remove message from all sending tx except normal sending

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4660]
The message field on transactions is a field that is directly sent to the other party, Its not stored on chain. 
When burning, sending one-sided etc this field won't be used.

**Comment by stringhandler** [comment]
I'm assuming this is in the console wallet? Maybe a screenshot would help

**Comment by SWvheerden** [comment]
It's in the TMS:
https://github.com/tari-project/tari/blob/55d133494270fe92ab7cf48d58f18d2a2bdecd17/base_layer/wallet/src/transaction_service/handle.rs#L85-L106
