### ISSUE TITLE
[console wallet] Completed transactions should not be rebroadcast to the mempool if connected to a fresh unsynced base node

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4664]
Completed transactions should not be rebroadcast to the mempool if connected to a fresh unsynced base node.

**Comment by stringhandler** [comment]
We could do this, but I don't think it's necessary

**Comment by stringhandler** [comment]
You are welcome to reopen with the impact of not doing this, and what happens if we don't
