### ISSUE TITLE
[console wallet] Many (thousands) notifications should not lock up the TUI

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4665]
A really busy `Notifications` tab with thousands of notificationscoming in locks up the TUI when selected

**Comment by stringhandler** [comment]
@hansieodendaal is this still an issue? Please add some reproducable steps

**Comment by delta1** [comment]
This should reuse the windowed view that @philipr-za created for the transactions tab. 

https://github.com/tari-project/tari/blob/development/applications/tari_console_wallet/src/ui/widgets/list_state.rs#L25

**Comment by hansieodendaal** [comment]
This is easily reproduced by performing a stress test of say 5000 transactions

**Comment by hansieodendaal** [comment]
I think we can close this issue, I did not pick this up again with the latest stress tests.

@stringhandler ?
