### ISSUE TITLE
Emoji ID should bind to network and/or type

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4667]
Right now, an emoji ID (an encoded representation of a public key with checksum) does not specify a network or key type. It is entirely the user's responsibility to use an emoji ID with the right network (e.g. the main network or a test network) and key type (e.g wallet address or base node address).

It would be a better and safer user experience to bind the emoji ID to both the network and type intended for the key. This would make it easier/possible for client software to prevent common user errors.

The following are some factors to consider in any such design:
- How much longer is it acceptable for an emoji ID to be? Currently, each emoji ID contains exactly 33 emoji characters, each of which encodes a single byte. If 4 bits are used to encode each of a network and key type, this adds a single additional emoji character.
- Are there "visual errors" that should be considered? If a network and type are encoded as described above, the additional emoji character will be common to many addresses. Does this mean users are more likely to mistake two addresses for each other when comparing them visually? (A corollary to this is that eagle-eyed users may be able to identify when an address does not contain this expected character, providing an additional layer of safety.)
- Does the checksum protect against enough errors? Right now, the checksum perfectly detects single substitutions (the user enters a single emoji character incorrectly) and adjacent transpositions (the user swaps two neighboring emoji characters). It is possible for combinations of multiple errors to pass the checksum; does this become substantively more problematic when including an encoding for the network and key type?

A somewhat related topic is the encoding alphabet itself. The original [RFC](https://rfc.tari.com/RFC-0152_EmojiId.html) describing the emoji ID design specified a version encoding that would change in the event that the emoji character set were to be modified, or in the event of other address encoding changes. However, it is possible that the use of a different character set might produce ambiguous decoding, which is not desirable. While versioning can be very useful, it may be necessary to require all future emoji ID versions to either retain the same character set or use a character set chosen to avoid ambiguous decoding.

**Comment by stringhandler** [comment]
related: #4881

**Comment by stringhandler** [comment]
related #4886
