### ISSUE TITLE
Investigate wallet validation trigger

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4669]
From the log file it looks the wallet is triggering transactions validation to run about every second:
[log-2022-09-12_16-31-47.txt](https://github.com/tari-project/tari/files/9553777/log-2022-09-12_16-31-47.txt)

Look for validation related to: TxId: 590546471493860469)
It looks like it validates it every second, as well as updates the database more than once per query.

**Comment by SWvheerden** [comment]
This is related to #4582 

It looks like the wallet gets its in the mempool, but resubmits the transaction

**Comment by hansieodendaal** [comment]
See #4689
