### ISSUE TITLE
Burn funds via cli seems to consume the complete UTXO set 

### ISSUE THREAD

**Issue by jorgeantonio21** [tari-project/tari#4683]
**Describe the bug**
In PR #4655, it was added a `burn tari` command line instruction. While testing this new feature, via cucumber, it was realized that the command seems to consume the complete UTXO set of a given wallet. 

**To Reproduce**
1. Consider the cucumber test in #4679. The given error can be reproduced by running it and checking the actual balance of the wallet.
2. After running the burn command, the wallet available funds are at most `18462.621580T`, when they should be `221552.530060T - 201552.500000T = 20000.030060T`. 
3. Moreover, uncommenting line 69 in `WalletCli.features` makes the get balance request to fail, upon time out.

**Comment by SWvheerden** [comment]
We have some problem here, but its not the burn. 
Wallet A mines 15  blocks
That means the balance should be : `276940_297_425 uT` or `276940 T`
Burning `45000_000_000 uT` and paying a fee of `710 uT` 
should mean the wallet must have `231940_296_715 uT` or `231940 T` left. 

The test comes back the end with `166164 T`
But looking at the database, the wallet has the last 3 coinbases marked as `UnspentMinedUnconfirmed`
and the change is still marked as `EncumberedToBeReceived`

Those funds are not counted towards the balance
