### ISSUE TITLE
Revalidate/scan all outputs from wallet

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4695]
We want to be able to let the wallet rescan (run recovery) without dumping the entire wallet and deleting all contacts etc. 

This should be fairly easy; we just need to dump the completed transactions, outputs table, and scanned blocks tables. 
This should force the utxo scanner to start scanning at block 0, and fill in all the required information.

**Comment by stringhandler** [comment]
I'm not sure where this fits in. Please add some more context about where in the wallet this happens and what the core problem is.

**Comment by SWvheerden** [comment]
This was from a requirement of only doing a partial "wallet" reset but we decided against doing this so we can close this
