### ISSUE TITLE
[console wallet/mempool] Mined transactions being invalidated due to `DuplicateKernelError`, `Validation failed due to already mined kernel`

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4721]
In some cases, a perfectly fine transaction that has been submitted to the mempool and being monitored by the wallet will be invalidated in the mempool whren it has been mined due to `DuplicateKernelError`, `Validation failed due to already mined kernel`, but then marked invalid in the wallet as well.

This behaviour surfaces during many coin splits.

**Comment by stringhandler** [comment]
I think the broadcast protocol should not see this as an error.
