### ISSUE TITLE
[console wallet] Verify that invalid UTXOs are re-validated at startup

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4723]

**Comment by stringhandler** [comment]
@hansieodendaal please provide more detail

**Comment by hansieodendaal** [comment]
Sometimes UTXOs are invalidated due to some conditions (that is, not available for spending anymore), but never re-checked when the conditions change.

Procedure to test:
- Create some UTXO in a wallet, e.g. via coin split
- Stop the wallet
- Manually change all the output statuses that are unspent ('0') to some other status like invalid ('4') or cancelled inbound ('5') in the wallet database
- Restart the wallet and verify that all tampered UTXO statuses are returned to unpsent ('0')

**Comment by stringhandler** [comment]
Let's store the time it was detected as invalid and then regularly (e.g. 1 day/week) revalidate it on startup if that period has passed. We can optionally add an exponential backoff and even a max number of retries
