### ISSUE TITLE
Commitment signature does not prove knowledge of witness summands

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4734]
Commitment signatures are used in the protocol as part of transaction authorization. These use a Schnorr-type representation proof that binds a message into the Fiat-Shamir transcript hash to form a signature. However, use in the protocol treats the input commitment as a sum of two values; one is the Pedersen commitment for the input/output, and the other is either a sender offset public key or a script public key. In either case, both values are bound to the signature via the transcript hash, but only their sum is used in the proof statement. This means successful verification of the signature only asserts that the signer(s) knew the sum of each representation component. Any further conclusions about summand representation must be offloaded to other parts of the protocol.

Unless there is a compelling reason to structure the signature this way (in which case it should be carefully documented), it should be modified.

**Comment by AaronFeickert** [comment]
When a sender [completes a commitment signature](https://github.com/tari-project/tari/blob/development/base_layer/core/src/transactions/transaction_protocol/sender.rs#L488-L519), it generates its own Schnorr signature, extracts a component from it, and adds this into the commitment signature. This means there is an assumption about the structure of commitment signatures and their "compatibility" with Schnorr signatures. This doesn't seem like a robust abstraction to make, and it would affect any changes to commitment signatures.

**Comment by SWvheerden** [comment]
This is for the [metadata signature](https://rfc.tari.com/Glossary.html#metadata-signature), just clarifying this. We use the commitment signature in the input as well for the script signature. 

The whole reason for the existence of this signature is that the receiver should not be able to change the script on the utxo the sender sent to the receiver. It was originally designed to be only a schonrr signature signed with the `sender_offset_private_key`

Linking this issue here: #2997

**Comment by AaronFeickert** [comment]
> This is for the [metadata signature](https://rfc.tari.com/Glossary.html#metadata-signature), just clarifying this. We use the commitment signature in the input as well for the script signature.
> 
> The whole reason for the existence of this signature is that the receiver should not be able to change the script on the utxo the sender sent to the receiver. It was originally designed to be only a schonrr signature signed with the `sender_offset_private_key`
> 
> Linking this issue here: #2997

It applies to the script signature as well, if the method in [RFC-0201](https://rfc.tari.com/RFC-0201_TariScript.html#transaction-input-changes) for script signatures also uses a sum of witness values.

**Comment by AaronFeickert** [comment]
Cryptographic functionality to support this is introduced in `tari-crypto` [PR 131](https://github.com/tari-project/tari-crypto/pull/131).
