### ISSUE TITLE
Create procedure for multi-party time locked UTXO creation and spending

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#4747]
The multi-party time-locked UTXO is basically an `n-of-n`  transaction for the creation and an `m-of-n` transaction for spending into a single UTXO, which can again be another multi-party time-locked UTXO. The time-locked aspect of the multi-party UTXO will be governed by `OutputFeatures::maturity`.
   1. Option A: Just secured by TariScript
   1. Option B: Just secured by multi-party UTXO + multi-party range proofs
   1. Option C: Secured by TariScript and multi-party UTXO + multi-party range proofs

**Comment by hansieodendaal** [comment]
See https://demo.hedgedoc.org/NLGbhCd6TC6nxUwGX_2xTw?view

**Comment by CjS77** [comment]
For reference, https://github.com/tari-project/test-faucet/ is a simple method of creating the UTXOs, once he commitments are known.
