### ISSUE TITLE
Transaction input/output versions are not bound to commitment signatures

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#4758]
Transaction inputs and output versions are used when creating commitment signatures. However, a representation of the version is not bound to the signature challenge, which could be used in an attempted downgrade or mismatch attack.

It would be safer to bind the version to the signature challenge.

**Comment by SWvheerden** [comment]
Script signatures do not bound to the version:
https://github.com/tari-project/tari/blob/163dce02ca7d8842f4198b2513f6bdcbb0e0c729/base_layer/core/src/transactions/transaction_components/transaction_input.rs#L162

**Comment by SWvheerden** [comment]
same for output:
https://github.com/tari-project/tari/blob/163dce02ca7d8842f4198b2513f6bdcbb0e0c729/base_layer/core/src/transactions/transaction_components/transaction_output.rs#L290

**Comment by AaronFeickert** [comment]
Fixed in [PR 4983](https://github.com/tari-project/tari/pull/4983).
