### ISSUE TITLE
Find method to determine the public IP address of the local machine in a cross platform manner

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#477]
When a Tari application boots up the Comm's stack needs to be informed what the public facing IP address of the local machine it for the handshake protocol. Currently in the grpc_wallet_server the crate being used, `local_ip`, is a hacky parsing of the ifconfig output which will only work on Unix based systems.

Find a robust cross platform method to do this for the applications.

**Comment by CjS77** [comment]
@philipr-za wasn't this closed by #508 ?

**Comment by philipr-za** [comment]
Sort of, that finds the LAN IP which was the original intention of this issue but we since discussed that the `public` IP would in fact involved figuring out what the internet facing IP address is. Should we make that a new issue or amend this one?

**Comment by sdbondi** [comment]
This this library does the job: https://github.com/maidsafe/get_if_addrs

**Comment by sdbondi** [comment]
Marking as closed as get_if_addrs works well (for LAN address) - public internet IP will either be made irrelevant by tor or have to be entered as an "advertised address" in the config
