### ISSUE TITLE
Wallet TMS validation service sends back bool to FFI

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4806]
The Wallet FFI has two callbacks for validation:
```
callback_txo_validation_complete: unsafe extern "C" fn(u64, u64),
callback_transaction_validation_complete: unsafe extern "C" fn(u64, bool),
```

UTXO validation uses `callback_txo_validation_complete` which sends back:
0 -  Success
1 - Already busy
2 - Failed due to a communication issue
3 - Failed other

TX validation only sends back:
true - success
false - all other including already busy. 

Tx validation also needs to send back 0-4 depending on why it failed. 

This feedback is used to determine if the mobile wallet should select a new base node or not. This is causing the mobile wallets to keep connecting to new base_nodes

**Comment by hansieodendaal** [comment]
Nice, totally agree.
