### ISSUE TITLE
Wallet selects not yet matured utxos

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4811]
Under certain conditions the function `select_utxos` selects utxo's which it cannot spend yet due to the timelocks. 
Since PR #4227, the wallet can under certain conditions (not default) select UTXOs that have not yet been matured. 
The Wallet should ALWAYS look to only select utxos that have matured on `script_lock_height` and `maturity`

**Comment by sdbondi** [comment]
Closed by #4854
