### ISSUE TITLE
Transaction builder over validates

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4813]
The transaction builder seems to validate every single time we add an output, add a signature etc. 
It also validates at the end when it builds. 

We can either remove the final validation check, or the individual checks as it does not seem performant to validate everything every single time.

**Comment by hansieodendaal** [comment]
It seems worthwhile to investigate this, but I would be really cautious in analysing the validation dependency chain.

**Comment by SWvheerden** [comment]
The only place where a transaction really needs to be validated for chain security is on the base nodes when accepting a transaction to be put into the mempool, and when accepting a new block. 

The rest are all just sanity checks. 
But we are overdoing sanity checks as they are not free, they ain't expensive, but they ain't free either.

**Comment by hansieodendaal** [comment]
And from the wallet's perspective?

**Comment by SWvheerden** [comment]
Its all just sanity checks, and not even complete checks as the wallet cannot check consensus rules such as duplicate outputs etc. 
All it can do is check the balance and signatures. We don't even check that the inputs are spendable.
