### ISSUE TITLE
bug: Rewinding past pruning horizon switches base node into archival mode [easy fix]

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4839]
Steps to reproduce:
- `rewind-blockchain 0` on a pruned node 
- when resync happens it synced in archival mode

Problem most likely in rewind_to_height where the chain metadata is set

**Comment by Cifko** [comment]
I'm not able reproduce this. Is this still an issue?
I rewinded 1000 blocks (to 0) and the pruned node had still pruning horizon. And the blocks were pruned (checked using get-block).

**Comment by sdbondi** [comment]
Tested and confirmed - base node remains in pruned mode. Closing
