### ISSUE TITLE
`Mnemonic::to_mnemonic` should wrap the seed words in Zeroizing

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#4861]
https://github.com/tari-project/tari/blob/5b0eb0459c7d29a25339c22a289153d27d57388e/base_layer/key_manager/src/mnemonic.rs#L254

The TariSeedWords ffi struct may need to be updated, but I don't think this will cause a breaking change as it will not change the underlying representation

**Comment by brianp** [comment]
I'll take a look at this one.
