### ISSUE TITLE
Check median timestamp validation is done on wrong section

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4870]
Currently, the validation `check_median_timestamp` is done on orphan headers, which should only be on full main headers added to the main chain. 

On Tari, we use two types of validators, one for orphans, and one for the main chain. Orphan validators only check rudimentary data, like does the block balance equation work out, does the block have one coinbase etc. Main validation checks all validation steps that are dependent on previous chain blocks, like if each input is a valid out, is the PoW valid, etc. 

`check_median_timestamp` is dependent on previous chain headers. In order to ensure the blockchain moves forward in time, there is a median timestamp rule that specifies that the header's timestamp must be greater than the median timestamp of the previous 11 blocks.

This check has no meaning on the orphan blocks, we need to check this as a main check on the validation

**Comment by CjS77** [comment]
Is it currently checked on both orphans _and_ the main chain, or orphans only?

**Comment by SWvheerden** [comment]
both

**Comment by CjS77** [comment]
Ok, so not a chronic trainsmash. The issue is to remove the unnecessary check on orphan blocks.

**Comment by CjS77** [comment]
It's not even consensus-changing, iiuc.

**Comment by SWvheerden** [comment]
Yeah. 
It can happen that an orphan block fails validation because it's looking at the wrong data. Thats the only issue here

**Comment by stringhandler** [comment]
Adding the consensus breaking label because it could result in two nodes validating the block differently
