### ISSUE TITLE
UTXOManager scaffolding

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#49]
Set up the UTXOManager type that essentially exposes an API for handling UTXOs. Most of this functionality will already be handled by the underlying MRR:

- [x] Check whether a given UTXO is in the given set.
- [x] Rewind the UTXO set to a given block height (requires #288)
- [x] Prune the set beyond the pruning horizon
- [x] "Delete" UTXOs when they get spent
- [ ] Filter UTXO set according to specific features (VN node registration / Coinbase whatever)

**Comment by SWvheerden** [comment]
Some features are already in the MMR and some are implemented in the chain_state code

**Comment by CjS77** [comment]
Handled in #131 among others
