### ISSUE TITLE
Remove Metadata from Output features [for non coinbase outputs]

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4908]
Metadata is a remnant of the previous DAN implementation. It should be removed from output features

**Comment by stringhandler** [comment]
it might be useful to allow this field only for coinbases, and store information here to display the mining pool that mined this block. Showing the mining pool will make it useful to see if a mining pool has more than 30 or 51%

**Comment by stringhandler** [comment]
I think the rule should be: This field should be optional for coinbases (mining pools and other merge mined coins can use it), but it  should be empty for non-coinbases.

For coinbases, the maximum length should be 64 bytes (2x hashes), so that arbitrary data cannot be included

**Comment by agubarev** [comment]
Although merged, I should make another PR to reflect Stan's comment, PR got merged before I managed to push an update. Will address to this ticket.

**Comment by agubarev** [comment]
On second thought, satisfying the aforementioned performance nitpick (on the PR), at the moment, would create unnecessary indirection in the code. Perhaps this can be addressed more properly later, via larger optimization.
