### ISSUE TITLE
MMR will not accept duplicate UTXOs

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#492]
The MMR will not allow addition of a second UTXO's that have the same hash. 
We need to investigate the best way to handle this as the hash if the unique identification of the UTXO

**Comment by CjS77** [comment]
My opinion is that 2 tx's with a hash collision is
a) very unlikely (but possible)
b) the 2nd tx should be rejected as invalid (with a `HASH_COLLISION` error, so that we know why it was rejected), and wallets can just try again with a new private key and the problem should self-resolve

**Comment by SWvheerden** [comment]
LMDB by default has dupsort off, which means that it will reject duplicate keys according to the documentation. So we should be fine on the backend. The wallet needs to address this thou.
