### ISSUE TITLE
Ensure clippy fails on warnings

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari#4934]

**Comment by CjS77** [comment]
Why should Clippy fail on warnings? I assume this relates to CI.
I'd argue that it should _not_ fail on warnings. That's why they're warnings. i.e.
`deny` vs `warn`

**Comment by Cifko** [comment]
I think the reasoning behind this is that we want to be more strict.
Currently on nightly we don't have any warning. But on stable there is a bunch.

**Comment by CjS77** [comment]
If you want to be strict, move a lint from `warn` to `deny`; after consulting with maintainers.
I'm going to close this with this advice.

**Comment by stringhandler** [comment]
This used to be the case and has regressed. This repo has always denied any clippy warnings - i.e. There should be no clippy warnings on development.

**Comment by stringhandler** [comment]
I see it's working as expected, just some new clippys are warnings only

**Comment by CjS77** [comment]
> This used to be the case and has regressed. This repo has always denied any clippy warnings - i.e. There should be no clippy warnings on development.

This is wrong IMO. You have two levels, warn and error. You should let warnings through, but errors block the CI
