### ISSUE TITLE
Console Wallet TUI transaction tab needs rescaling

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4939]
Since the update to use Tari Address rather than just public  keys as addresses for the wallet, the transaction tab needs a rescaling to show a clear gap between address and amount
![Screenshot 2022-11-21 at 17 33 21](https://user-images.githubusercontent.com/2579813/203094730-7c0c515c-0982-4d6c-9bc4-7b13404cc039.png)

**Comment by stringhandler** [comment]
I suggest these changes as well:
1. Shorten the pub key in the list, and add the pub keys as well as the emoji id's to the details pane

**Comment by SWvheerden** [comment]
`Source/destination public key`  text is wrong as well
