### ISSUE TITLE
Confirm that RFC-0153 - Stage 1b is implemented correctly

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4954]
In the RFC, stage 1b says:

> The seed phrase MUST NOT be stored on the cloud in Stage 1b. Doing so would result in all future funds of the user being lost if the backup were ever compromised. Since the backup is unencrypted in Stage 1b, we store the minimum amount of data needed to recover the funds and limit the potential loss of funds in case of a breach to just that found in the commitments in the backup, which should not be more than $50.

We need to confirm that the wallet code does this correctly

**Comment by stringhandler** [comment]
Also need to confirm whether onesided payments private keys are stored in the backup

**Comment by stringhandler** [comment]
There should be covering integration tests checking these stages

**Comment by SWvheerden** [comment]
The wallet code definitely does not do this correctly. 

Seed phrase is decrypted and stored in the wallet SQL file. 

We need to re-architecture how we do this. 
Currently, the mobile wallets on recovery just dumps the database in place,
