### ISSUE TITLE
Wallet add export/import functionality of utxos for backups

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#4977]
Currently, the wallet backup process uses decrypts the whole wallet database and copies the SQL file future use. 
This is dangerous see: https://github.com/tari-project/tari/issues/4954

The wallet does support the export of utxos to CSV file. 
We need to ensure that this works, and works with the FFI so mobile wallets can use this backup only the utxos and leave sensitive data alone and encrypted.

**Comment by jorgeantonio21** [comment]
Encryption is possible only when the user provides a password. So we should enforce this on the wallet API, as well.

**Comment by jorgeantonio21** [comment]
Encryption is possible only when user provides a password. So we should enforce this on the wallet API, as well.
