### ISSUE TITLE
Remove silent failure from calling `with_amount` on tari_core::transactions::transaction_protocol::transaction_initializer::SenderTransactionInitializer

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4985]
As per the docs for this method:
`tari_core::transactions::transaction_protocol::transaction_initializer::SenderTransactionInitializer` :

```rust
  /// Set the amount to pay to the ith recipient. This method will silently fail if `receiver_index` >= num_receivers.
    pub fn with_amount(&mut self, receiver_index: usize, amount: MicroTari) -> &mut Self {
        self.amounts.set_item(receiver_index, amount);
        self
    }
```

This silent failure could be a foot gun in future, and this struct should be changed to either:
1. Fail when `build()` is called
2. or increase the `num_recipients` and other related fields when this happens

**Comment by SWvheerden** [comment]
Fixed
