### ISSUE TITLE
Address Aaron's comments in #4943

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4987]
@AaronFeickert added some comments to #4943 after it was merged. Making a tracking issue so that they are not forgotten about

**Comment by SWvheerden** [comment]
Spelling address here: https://github.com/tari-project/tari/pull/4996

**Comment by AaronFeickert** [comment]
Given the discussion in the PR comments, I'm fine closing this issue if the reverse-domain suggestion is deemed unnecessary.
