### ISSUE TITLE
Aead error: Ciphertext too short when trying to burn funds

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#4988]
To reproduce:  have wallet with fund.

Call: 
` cargo run --release --bin tari_console_wallet -- -b . --network igor burn-tari 2T`

Resulting error:
```
Tari Console Wallet running... (Command mode started)
==============
Command Runner
==============

1. BurnTari(BurnTariArgs { amount: MicroTari(2000000), message: "Burn funds" })

BurnTari error! Transaction service error `Output manager error: `Output manager storage error: `Aead error: `Ciphertext is too short````
```

**Comment by SWvheerden** [comment]
I cannot replicate this anymore. We did a massive refactor of how the wallet handles its encryption. This looks like it solved the issue
