### ISSUE TITLE
feat! - Add room for arbitrary miner-supplied info in coinbase

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#4989]
A small field for miners to add arbitrary data has a few main use cases:
* Helps miners / pools track blocks they have won.
* Permits Tari to be used as a parent chain in merge mining.

The first case is largely cosmetic. The 2nd is pretty important.

It should be a fairly minor (sic!) change. Allowing up to 64 bytes of arbitrary data should be sufficient.

**Comment by stringhandler** [comment]
Not consensus breaking because we have the `metadata` field specifically to store this. The miner needs to be updated to store this

**Comment by SWvheerden** [comment]
This has been done, field is called: coinbase_extra

**Comment by stringhandler** [comment]
Reopening as the merge mining use case is not yet handled

**Comment by SWvheerden** [comment]
Addressed documentation on this: https://github.com/tari-project/rfcs/pull/91
