### ISSUE TITLE
[base node] Mempool not populated after a restart

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5034]
This was observed during a coin-split stress test, with two consecutive base nodes

**Comment by SWvheerden** [comment]
This is by design. 
It will only populate after a sync of more than 5 blocks. 
A straight up restart will not count as a sync and thus wont trigger a mempool sync

**Comment by stringhandler** [comment]
I think we are probably missing the case where you quickly restart the node. If a base node can tell it's on the latest tip and it has never synced a mempool, it should sync

**Comment by SWvheerden** [comment]
I am wondering if we should not just revert the change about removing the mempool sync on restart. 

I think the case we are talking about here is not just about the mempool having never synced. It's more about manually forcing a mempool sync.

**Comment by stringhandler** [comment]
I don't think we need to go that far. The mempool sync on restart didn't make sense, because we could not validate it properly.

**Comment by SWvheerden** [comment]
I have now tested this, and it does work. 
Mempool will sync on restart. If it's not on listing state it will await that (this is done in a manual loop that checks the state every 30 sec before starting), but after that, it will await a connection then start a sync. 

Tested this with 2 base nodes:
* sent 2 transactions
* Closed the 1 base node
* Opened BN again, showed 0 tx.
* After about a min, mempool synced the 2 tx's

The base node did not change during this time.

**Comment by hansieodendaal** [comment]
The issue here was that the mempools of the two base nodes in question fell way behind that of the other base nodes, and nothing I tried, multiple restarts included, could get the mempools to sync. The only way I could fix it was to point all stress test wallets to those two base nodes in turn so the wallets could re-broadcast the transactions.

**Comment by SWvheerden** [comment]
Flagging this as more info needed as this is under observation till we can get more info of this happening

**Comment by SWvheerden** [comment]
We have not seen this for a while, closing those for now, as we have made a lot of changes in the code base since opening.
