### ISSUE TITLE
Consolidate Validators

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#5042]
# Problem
Currently, there is duplicate validation logic in multiple places. This makes it hard to reason about whether it is correct according to the RFC, but it also means that as new rules are added or fixed, it could be done in one place, but not the other.

# Proposed solution
Instead, let's change the structure so that a validation rule is found in at most one validator struct, and only those structs are used. 

In all cases, the validation rules should be implemented according to 

These traits should be created:

## Headers
```rust 
pub struct [Internally]ValidHeader(pub Arc<BlockHeader>);

pub trait InternalConsistencyHeaderValidator {
   /// Validates a header in isolation, i.e. without looking at previous headers
   fn validate(&self, header: &BlockHeader) -> Result<ValidHeader, ValidationError>;
}

pub trait ChainLinkedHeaderValidator {
  /// Takes a valid header and validates it in context of previous headers in the chain
  fn validate(&self, header: &ValidHeader, [... state from the db needed for validation...]) -> Result<ChainHeader, ValidationError>;
}
```

There are a few places in the code that a header is validated:
1. During initial sync. In this case it should be validated with the `InternalConsistencyHeaderValidator` impl and then the `ChainLinkedHeaderValidator`.
2. When adding a block. Both should be run
3. When receiving a header via ChainMetadata. The `InternalConsistencyValidator` should be run before saving.

Similarly, the block body should be separated:

```rust
pub trait InternalConsistencyOutputValidator {
  pub fn validate(&self, output: &TransactionOutput) -> Result<(), ValidationError>;
} 

pub trait InternalConsistencyKernelValidator {
  pub fn validate(&self, kernel: &TransactionKernel) -> Result<(), ValidationError>;
}

/// Replaces OrphanValidation and MempoolTransactionValidator
pub trait InternalConsistencyAggregateBodyValidator {
   fn validate(&self, body: AggregateBody, offset: BlindingFactor, script_offset: BlindingFactor) -> Result<(), ValidationError>;
}

pub trait ChainLinkedAggregateBodyValidator {
  fn validate(&self, body: AggregateBody, header: ChainHeader, [.... state or db needed to validate....]) -> Result<(), ValidationError>;
}

```

# Acceptance criteria
Once done, the above validators should be the only validations done. I would also aim to move the `validate_internal_consistency` method from the inputs, outputs and kernels so that all the logic is in the structs implementing these traits. 

# Other requirements
* The async validator should be refactored to use `rayon` instead of tokio. 
* The header sync validator should be removed, and should only use the above traits
* The `add_block` validators should be the same as the initial sync block body trait
* The mempool validator and the `internal_consistency` aggregate body trait should be the same

**Comment by SWvheerden** [comment]
fixed in #5079
