### ISSUE TITLE
[base node] Fix `pub fn batch_verify_range_proofs(..)` to not use powers of two, but batch all proofs

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5048]

**Comment by AaronFeickert** [comment]
Just for clarity, range proofs require a power of two for the aggregation factor; that is, the number of (possibly padded) commitments whose range is asserted in a single proof must be a power of two. The number of proofs that may be verified in a batch is arbitrary, and limited in practice only by any performance concerns relating to multiscalar multiplication and the like.

For batches so large that performance becomes a concern, we can simply split into smaller batches and evaluate them separately.

**Comment by AaronFeickert** [comment]
Here's the [relevant code](https://github.com/tari-project/tari/blob/1cafba73950349b19181f612633040804fe1800d/base_layer/core/src/transactions/transaction_components/transaction_output.rs#L502-L532).
