### ISSUE TITLE
Convert Cucumber tests

### ISSUE THREAD

**Issue by brianp** [tari-project/tari#5050]
# Problem

We are using a javascript framework for testing. We can now move to a rust based framework and believe this will be easier to manage in the longrun. We need to port the existing cucumber tests over, and reimplement all the steps in rust.

The problem is less the need for the port but in the execution itself. It's a lot of code to move. More people involved can create conflicts and unneeded churn. A strategy to move quickly without stepping on toes is important.

# Appetite
The appetite for minimum 80% completion of this port is 2.5 weeks. Ending on December 30th. Failure to meet completion may result in the abandonment of this port. Check-ins:
- [x] Friday 16th: Is the ground work feature branch ready
- [x] Tuesday 20th: What percentage of steps have been ported, 16% needed to stay on minimum target
- [x] Thursday 22nd: What percentage of steps have been ported, 36% needed to stay on minimum target
- [ ] 2nd week TBD

# Solution
It's easy to port the .feature files into the rust library. The difficulty is enabling each of the needed steps without duplicating work. I propose we spend time implementing steps in isolation and uncommenting implemented steps in all tests that use the step assuming this will make that test pass and reduce the chance of conflict. 

Some quick numbers:
- 18% of steps make up 80% of all step invocations
- 29% of steps that are completely unique (used once)
- 15% of steps aren’t used at all, and require no porting 🎉

Implementing 18% of the steps in isolation gives us much more breathing room to begin porting/uncommenting entire tests in quicker succession and with less conflict.

We already have a [base feature branch](feature-cucumber-rs) to work from.

The process for this work will be:
- to check out a branch from the provided base branch
- Assign yourself a single/or set of steps you will implement (see spreadsheet not attached)
- Write the implementations
- Uncomment the step in tests, and ensure it passes
- Create a PR back into the base feature branch

These PR's can be made in rapid succession, and contain as little or as much as you've completed. Had 10 minutes to implement a single step, send the PR. Finished 8 steps but working on a 9th and it's the end of day, submit the PR with 8. We're looking for speed here.

# Rabbit Holes
- If we can eliminate unique or single-use steps in favor of an existing step it can be worth the exercise, but don't devote much time to the effort.

# No Gos
- No writing net new features, we're not looking to increase coverage at the moment.

**Comment by jorgeantonio21** [comment]
@brianp thanks a lot for this detailed explanation :) !

**Comment by brianp** [comment]
- [x] Friday 16th: Is the ground work feature branch ready

Enough of the infrastructure was in place to begin onboarding other developers. As the first week kicked off we found a lot of the holes and did require spending additional time but this is expected and the base of the branch grew quick enough it didn't hold anyone up for long.
Holes included:
 - Not enough randomness between tests so things like ports, and file strutctures continued to stomp on eachother
 - Services initally claiming they were up but immediatley crashing and not present for the rest of the test
 - Logging was a heck of a mess

- [x] Tuesday 20th: What percentage of steps have been ported, 16% needed to stay on minimum target

Of step implementations written but unused we were on target

- [x] Thursday 22nd: What percentage of steps have been ported, 36% needed to stay on minimum target
2nd week TBD

Of activated step implementation invokations we were on target.

# Week 2

The key here is what measurement do we actually want to use to ensure we pass the 80% mark.

- Currently we have steps required for 61% of invokations written
- Only 30% of the total step invokations activated
- 12% of total needed steps written

I think we'll be able to get to 80% or more of invokations activated. Meaning more than the majority of the suite will be running, but things will really slow down once we get to step implementations requireing a whole step of code for only a single use invokation. the 80/20 rule really comes to play. It also means we may not have many complete tests running, so the value of the suite as a safeguard against regressions is low even if the majority of the suite is technically running.

I'll bring this up in standup tomorrow morning to see where people feel the most value will be to target for the rest of the week.
