### ISSUE TITLE
Wallet bad password just continues on

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5127]
When a user selects a weak password:
```
>> 1
Create wallet password: 
Confirm wallet password: 
Passwords match.
However, the password you chose is weak; a determined attacker with access to your device may be able to guess it.
You may want to consider changing it to a stronger one.
Here are some suggestions:
- Add another word or two. Uncommon words are better.
- Avoid sequences.


=========================
       IMPORTANT!        
=========================
These are your wallet seed words.
They can be used to recover your wallet and funds.
WRITE THEM DOWN OR COPY THEM NOW. THIS IS YOUR ONLY CHANCE TO DO SO.

=========================
then frozen garage dash file barely purity illness mother bridge example level short burst swing acid cry orient crawl garbage snap maze mad plate
=========================

I confirm that I will never see these seed words again.
Type the word "confirm" to continue.
>> 
```
The wallet only warns the user, then continues without prompt. 
The user should be prompted if h/she wants to continue or select a new password. 

Currently, the only way to get a better password is to delete the wallet and start new as per this: #5120, the wallet cannot change its passwords once started

**Comment by AaronFeickert** [comment]
I had an [idea](https://github.com/tari-project/tari/pull/5111#issuecomment-1380774004) for one way to do this, but wasn't sure if it would just end up being more confusing to the user than letting them change their password (once it's possible to do so).

**Comment by SWvheerden** [comment]
And add change password feature

**Comment by AaronFeickert** [comment]
Changing the passphrase of a wallet is [already supported](https://github.com/tari-project/tari/pull/5175), but as noted, the user is not prompted to select a different passphrase if they choose a weak one.

From discussions elsewhere, it sounds like the following flow will work:
```mermaid
flowchart TD
    start[User enters new passphrase]
    start --> confirm[User confirms new passphrase]
    confirm --> match{Do they match?}
    match -- No --> exit(Exit)
    match -- Yes --> weak{Is passphrase weak?}
    weak -- No --> change[Change passphrase]
    change --> exit
    weak -- Yes --> proceed{Proceed anyway?}
    proceed -- No --> start
    proceed -- Yes --> change
    proceed -- Cancel --> exit
```
