### ISSUE TITLE
Clean up cargo toml files

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5136]
Ensure all cargo toml files only have the required libraries in them.

**Comment by CjS77** [comment]
https://stackoverflow.com/questions/72082550/how-do-i-remove-unused-dependencies-in-cargo-toml

**Comment by SWvheerden** [comment]
I want to run this as well: https://blog.benj.me/2022/04/27/cargo-machete/#:~:text=cargo%2Dmachete%20is%20a%20new,you%20have%20potentially%20unused%20dependencies

**Comment by CjS77** [comment]
Looks like a really nice tool. Note the comment about false positives and whitelisted known used crates.

**Comment by SWvheerden** [comment]
yeah will definitely manually check the stuff.
