### ISSUE TITLE
[Wallet] One sided mined at timestamp is incorrect

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5167]
The detected mined at the timestamp should be the block time and not unix epoch. 
![Screenshot 2023-02-07 at 07 34 58](https://user-images.githubusercontent.com/2579813/217157653-87bc3daf-143a-46a9-968a-77ad6f8f3799.png)

**Comment by hnidoaht-101** [comment]
@stringhandler I'm on Arch Linux. How can I display the icon same as @SWvheerden's screen for `Source Address` and `Destination Address`?

**Comment by SWvheerden** [comment]
@hnidoaht-101 your terminal should support emojis.

**Comment by brianp** [comment]
Open PR with a fix for this: https://github.com/tari-project/tari/pull/5443
