### ISSUE TITLE
Refactor Wallet handling of blinding factors

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5168]
Currently, the wallet only stores the private keys of the blinding factor and the script key. 
This means we have to store the actual private keys encrypted in the wallet. This is also not compatible with the way hardware wallets work. 

This means we need to change the wallet to rather only store the path and index stored in the output database. 
The wallet should ask the key manager for the key and not store it.

**Comment by CjS77** [comment]
Remember that the wallet DB still needs to support imported keys, so if a refactor takes place, there will still need to be a way to store "naked" private keys.

**Comment by SWvheerden** [comment]
Yeah
the outputs should still be able to handle private keys for which we do not have the derive info

**Comment by SWvheerden** [comment]
It might be worth looking into moving the all the signature signing into the key manager as well

**Comment by SWvheerden** [comment]
I have been hashing this out a bit and this is where I landed up with for hardware support:

1. Add a key value lookup table to the KMS to store imported keys, and keys it did not derive. 
2. Re-write the OMS to ask the key manager for all keys
3. Rewrite KMS to do all transaction key signing
4. Make sure TMS/OMS never handle any private keys
5. Create some logic inside of the KMS to handle when a key is important, created by itself, or comes from a hardware device

Going this route gives us two advantages:
1. It limits the storage of private blinding factors to a single table and single service.
2. It makes sure that the logic defined for hardware support is much easier and confined to a single piece of code.

**Comment by SWvheerden** [comment]
This has been divided into 3 parts, 
1: Change signatures
2: Move key manager service to key manager crate
3: Change tx protocol to use key manager service

Parts 1 and 2 have been done and merge

**Comment by SWvheerden** [comment]
This has been done and merged
