### ISSUE TITLE
add rangeproofs hash to header

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#518]
We need to store the rangerpoofs some where so we can rebuild the blocks
We also need to create a commitment to rangeproofs so we know if they have been changed. 

Current proposal is:
add key-value store to store rangeproofs as witness data. 
Store rangeproofs as hash(commitment, rangeproof)
Add hash to header for rangeproofs of block

**Comment by CjS77** [comment]
Done in PR ??
