### ISSUE TITLE
base node cannot find wallet using wallet address

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5180]
`discover-peer f4f3c406e567720870f3451ecc3a856af6e3c25310c7dc752fe6af7319a29e4168
Command discover-peer f4f3c406e567720870f3451ecc3a856af6e3c25310c7dc752fe6af7319a29e4168 failed: error: Invalid value "f4f3c406e567720870f3451ecc3a856af6e3c25310c7dc752fe6af7319a29e4168" for '<ID>': unknown id type, expected emoji-id, public-key or node-id`

The wallet uses a Tari address, in this example: `f4f3c406e567720870f3451ecc3a856af6e3c25310c7dc752fe6af7319a29e4168`. 
When calling `discover-peer ` it expects a public key and not an Tari address. The command should try to dial detected if the provided peer uses a Tari address and extract the public key from it before trying dial.

**Comment by hnidoaht-101** [comment]
hi I'd like to tackle this issue.

**Comment by stringhandler** [comment]
Go for it

**Comment by SWvheerden** [comment]
fixed
