### ISSUE TITLE
Windows runtime environment and installation are outdated

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5222]
**Describe the bug**
Windows runtime environment and installation are outdated

**To Reproduce**
Install as per README

**Expected behaviour**
The runtime should work without errors

**Screenshots**
- https://discord.com/channels/892738558316662855/894350744419962890/1082495098828361839
- https://discord.com/channels/892738558316662855/894350744419962890/1082503211618926703

**Desktop (please complete the following information):**
Windows

**Smartphone (please complete the following information):**
n/a

**Additional context**
A temporary solution was supplied to the user:
https://discord.com/channels/892738558316662855/894350744419962890/1082601910672044042

(Duplicate of #4801)

**Comment by hansieodendaal** [comment]
natterbot [12:22 AM]
_**[discord] <ggcrypto>** just FYI, in the set_env bat files that are in the windows release, its still trying to set the --init flag for miner and wallet.  this causes the start menu links and the start bat files to fail.  deleting the init from the batch files allows tari to start up properly._

**Comment by hansieodendaal** [comment]
See #187

**Comment by SWvheerden** [comment]
tested as working with latest release
