### ISSUE TITLE
[Wallet]Add last ran wallet version to wallet database. 

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5252]
Add the last ran wallet version to the table `WalletSettingSql`. 
Add the network the wallet is run on on this as well and check it at startup that it matches. 

The version should be retrieved from the FFI without initializing the wallet via `walet_create`

It should not run any migration on the database etc. It should just try and retrieve the version+ network. If this is not found, it should return None/Null

**Comment by stringhandler** [comment]
There should be a different database per network, so no need to include the network

**Comment by stringhandler** [comment]
although I suppose it couldn't hurt

**Comment by SWvheerden** [comment]
Yeah should be as per: #5250 
But I think it would better if we check this.

**Comment by stringhandler** [comment]
You can already see this version from the `__diesel_schema_migrations` table

**Comment by SWvheerden** [comment]
Fixed in #5263
