### ISSUE TITLE
Consider the use of key-blinding signatures for encrypted messages

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#5255]
A [recent preprint](https://eprint.iacr.org/2023/380) formalizes key-blinding signatures, which can be useful in cases where a single key is used to generate unlinkable signatures. It builds on earlier work to describe and prove security for `EdDSA` and `ECDSA` variants.

In this design (modified for non-`EdDSA` Schnorr signatures), the signer blinds their public key and uses it to generate a standard Schnorr signature that any verifier can verify using the blinded public key. A designated entity in possession of the secret data used to construct the blinded public key can additionally unblind the original public key. These signatures have the benefit of being unlinkable in the sense that an adversary (who does not know the secret data) cannot distinguish signatures produced from the same underlying public key from those produced from different keys.

This could be useful for encrypted messages. Right now, signatures and public keys are encrypted to the recipient, who must decrypt them, verify the signature using the public key, and then decrypt the message. Non-recipient entities can only assert that the semantics of the encrypted message, like its length and the presence of expected fields.

With this new design, the sender could instead blind its public key, encrypt the secret data along with the message, and sign both (along with existing header-type data) using the blinded public key. Non-recipient entities can verify the signature, but are unable to identify the underlying public key. The recipient can decrypt the verified message and unblind the public key to identify the sender.

Overall, this seems like a cleaner design that is more in line with some version of the [cryptographic doom principle](https://moxie.org/2011/12/13/the-cryptographic-doom-principle.html).

**Comment by hansieodendaal** [comment]
Well, according to the cryptographic doom principle, identification must be possible before _any_ decryption, and your proposal is in line with that. The added benefit is that non-recipients can block messages with invalid signatures.

**Comment by AaronFeickert** [comment]
We can do even better with this! The requirements on the secret mask data are that it be unknown to an adversary, outside of adversarial control, and uniformly sampled at random. My suggestion is to derive it from the ephemeral Diffie-Hellman exchange used already to generate the message key. With this approach, the only encrypted data is the message body.

Without knowledge of either the ephemeral or recipient secret key, an adversary who intercepts an encrypted message cannot learn this mask. It's also uniformly distributed at random if run through a proper key derivation function (to mitigate key exchange bias). To ensure the adversary can't meaningfully manipulate it, it should suffice to ensure that both the ephemeral and recipient public keys are bound to the signature (which is already the case). This means that any attempt to modify either of these values, which would alter the derived mask, will result in a failed signature with high probability.

What's even more interesting is that we don't even need to modify the underlying signature construction in `tari-crypto` (though we could if we really wanted to). Functionally, the blinded signature is just a Schnorr signature whose secret key is multiplicatively offset by the mask. Verification proceeds identically using the blinded public key, which is included in the clear. Key recovery is as simple as removing the multiplicative offset from the blinded public key. (There are other `EdDSA`- and `ECDSA`-specific design principles, but they don't apply to our "plain" Schnorr signatures.)

**Comment by AaronFeickert** [comment]
For these diagrams, round shapes represent algorithms, rectangular shapes represent secret data, and cylindrical shapes represent public data stored or transmitted as part of a message.

Here's a diagram of the message encryption process:
```mermaid
flowchart TD
    keygen([KeyGen])
    keygen --> skeph[sk_eph]
    keygen --> pkeph[(pk_eph)]

    ecdh([ECDH])
    skeph --> ecdh
    pkrec[(pk_rec)]
    pkrec --> ecdh
    
    ecdh --> kdf([KDF])
    kdf --> keph[k_eph]
    kdf --> mask[mask]

    enc([Encrypt])
    msg[msg] --> enc
    keph -- key --> enc
    enc --> msg1[(msg')]

    blind([KeyBlind])
    sksend[sk_send]
    mask --> blind
    sksend --> blind
    blind --> bpksend[(bpk_send)]
    bpksend -- AD --> enc
    
    sign([Sign])
    header[(header)]
    pkrec --> header
    pkeph --> header
    header --> sign
    msg1 --> sign
    blind -- key --> sign
    sign --> sig[(signature)]
```

After verifying `signature` against the blinded public key `bpk_send` and message tuple `(msg', header)`, the recipient decrypts the message and unblinds the sender public key:
```mermaid
flowchart TD
    ecdh([ECDH])
    pkeph[(pk_eph)] --> ecdh
    skrec[sk_rec] --> ecdh
    
    ecdh --> kdf([KDF])
    kdf --> keph[k_eph]
    kdf --> mask[mask]

    dec([Decrypt])
    msg1[(msg')] --> dec
    keph --> dec
    dec --> msg[msg]

    unblind([KeyUnblind])
    bpksend[(bpk_send)]
    mask --> unblind
    bpksend --> unblind
    bpksend -- AD --> dec
    unblind --> pksend[pk_send]
```

**Comment by AaronFeickert** [comment]
Because the linked preprint's method for public key recovery requires scalar inversion, an implementation is currently blocked since `RistrettoSecretKey` does not expose multiplicative inversion.

But good news! [This PR](https://github.com/tari-project/tari-crypto/pull/173) in `tari-crypto` adds this functionality via a `SecretKey` trait bound and associated `RistrettoSecretKey` implementation.

**Comment by hansieodendaal** [comment]
This looks really great.

I assume `pk_eph` & `sk_rec` into `ECDH` will tell a node if they need to go further to try and decrypt, or at which point do they realize the message is not for them?

**Comment by AaronFeickert** [comment]
> I assume `pk_eph` & `sk_rec` into `ECDH` will tell a node if they need to go further to try and decrypt, or at which point do they realize the message is not for them?

Those values aren't needed for this purpose. Encrypted messages include a destination public key in the header, so any node can trivially determine if it is the intended recipient. The existing protocol was built to accommodate recipient ambiguity, but it wasn't used.

If this property is still desired, we can use authenticated message encryption for `Encrypt`, at which point each node _would_ compute the key exchange (after verifying the signature) and test the decryption. Should this be done?

**Comment by hansieodendaal** [comment]
I think we should just keep the status quo.

My question was more a matter of interest where the decryption algorithm would fail if `pk_eph` was not represented in the encryption but only in the signature. Technically, for whatever reason, the link between `sk_eph` and `k_eph` could be broken.

**Comment by AaronFeickert** [comment]
> I think we should just keep the status quo.
> 
> My question was more a matter of interest where the decryption algorithm would fail if `pk_eph` was not represented in the encryption but only in the signature. Technically, for whatever reason, the link between `sk_eph` and `k_eph` could be broken.

If the signature is valid but the message wasn't encrypted properly with `k_eph`, then decryption would still succeed. Whether or not the decrypted message is valid or meaningful is a matter of context. But even with authenticated message encryption, the same issue could occur if the sender properly encrypts (with authentication) an invalid or meaningless message. In either case, any attempt by another entity to manipulate the message would result in an invalid signature.

In the previous design, the authenticated signature decryption was useful because the signature itself was encrypted, and the doom principle asserted it must be authenticated before decryption. Now, the signature is in the clear and can detect manipulation of the encrypted message on its own.

**Comment by hansieodendaal** [comment]
Ah Aaron, please bear with me :see_no_evil:

I do not understand this: _"If the signature is valid but the message wasn't encrypted properly with `k_eph`, then decryption would still succeed."_

Let us say `k_eph'` (some manipulated `k_eph`) was used to encrypt the message instead of `k_eph`, surely decryption would fail? Thus, `pk_eph` and `sk_rec` into `ECDH` into `KDF` will yield `k_eph`, but the message was encrypted with `k_eph'`.

**Comment by AaronFeickert** [comment]
Without authentication, stream cipher decryption always succeeds, whether or not the same key is used to decrypt as was used to encrypt. The validity of the message would then depend on context.

**Comment by hansieodendaal** [comment]
Do you mean the decrypted message using the wrong key will be meaningless, just some random bytes, and if so, will only the correct key give any meaningful decrypted result? I know with data recovery from a damaged hard disk drive RAID array one can sometimes get some percentage of the original message back and the rest of the bytes will be scrambled beyond repair. So that is not the case here?

**Comment by AaronFeickert** [comment]
Decrypting with the wrong key in the absence of authentication should, in the case of any reasonable cipher, result in garbage. That being said, I did some more work on threat modeling and identified a particular attack that would be mitigated by adding authentication (with a particular associated data binding). It would prevent reuse of ciphertext by an adversary.

**Comment by hansieodendaal** [comment]
Cool, so I think that is what we need then, to add _authentication (with a particular associated data binding)_.

**Comment by AaronFeickert** [comment]
In particular, the additional data is the blinded sender public key.

**Comment by hansieodendaal** [comment]
That would make sense, and I assume it will still comply with the discrete log assumption, or close to it?

**Comment by CjS77** [comment]
Am I right in that the implementation is almost trivial for Schnorr signatures?

Where given some blinding factor, `b`, all of `s` (signature), `P_a` (public key), `a` (private key), `r` (nonce) and `R` (public nonce) are simply multiplied by `b` to get the blinded counterparts?

In your enhanced proposal, `b` is equal to the shared DH key.

**Comment by AaronFeickert** [comment]
> Am I right in that the implementation is almost trivial for Schnorr signatures?
> 
Mostly! The idea is that the blinded keys are produced by multiplicative masking, and that the rest of the signing and verification processes (in this case) are unchanged. There are a few complications specific to `EdDSA` and `ECDSA` that don't apply to the "vanilla" Schnorr signatures used here.

> Where given some blinding factor, `b`, all of `s` (signature), `P_a` (public key), `a` (private key), `r` (nonce) and `R` (public nonce) are simply multiplied by `b` to get the blinded counterparts?
> 
Just the keys. This alters the challenge as well, which mitigates against malleability.

> In your enhanced proposal, `b` is equal to the shared DH key.
>
Sort of. It's derived from the ECDH shared secret via a KDF.
