### ISSUE TITLE
CI - Fix wasm pack install

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5261]
Since commit https://github.com/tari-project/tari/pull/5258/commits/1c65bc7f098a0b6474f2df237772a1a281042e25
Wasm pack has been broken for CI
This needs to be fixed again and re-added. 

Fails with: 
```
found 0 vulnerabilities
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
rustup run nightly-[20](https://github.com/tari-project/tari/actions/runs/4467454060/jobs/7847682092#step:5:21)[22](https://github.com/tari-project/tari/actions/runs/4467454060/jobs/7847682092#step:5:23)-11-03 wasm-pack test --node --features wasm
error: command failed: 'wasm-pack': No such file or directory (os error 2)
make: *** [test] Error 1
Makefile:5: recipe for target 'test' failed
Error: Process completed with exit code 2.
```

**Comment by AaronFeickert** [comment]
This looks to be an upstream issue with `wasm-pack@0.11.0`. Freezing at `wasm-pack@0.10.3` is at least a temporary fix.

Opened an [upstream issue](https://github.com/rustwasm/wasm-pack/issues/1248) for this already.
