### ISSUE TITLE
Change data dir to include network name

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5273]
Change the data directory behavior to include the network name.  
Currently, the folder structure looks as follows:
```
dir
     config
     data
     peer-db
```

This should be changed to be:
```
dir/{network_name}
                  config
                  data
                  peer-db
```

**Comment by hnidoaht-101** [comment]
Does anyone work on it yet? Otherwise, I'd like to resolve this.

**Comment by SWvheerden** [comment]
I think @brianp is.
