### ISSUE TITLE
See if we can make `MutableMmr` more efficient and safer

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#5280]
A [recent PR](https://github.com/tari-project/tari/pull/5278) updates mutable MMR root computation by cloning and compressing the underlying bitmap. This was done to avoid the case where the caller fails to compress the bitmap when necessary, which can produce unintentional differences in root computation. The change is very safe, since it ensures the bitmap is always compressed; however, bitmap cloning and compression are expensive.

We can probably do better. One approach could be storing a flag that tracks deletions. If a leaf is deleted (which updates the bitmap), the tree is flagged as being in a dirty state. When computing the tree's root, we only need to compress the bitmap if the tree is dirty.

This approach is still annoying, since we have two options:
- Compress the bitmap in place, which requires that the tree be mutable when computing the root.
- Compress a clone of the bitmap, which may be expensive.

There's an additional existing subtlety: while `MutableMmr` implements `PartialEq`, it doesn't do so in a way that strictly follows the [documentation](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html). This is the case because two trees are defined to be equal if and only if they have the same root. Because of compression, two trees can be unequal despite having the same leaves and deletion sets. We can't compress a tree's bitmap in place during equality testing, since `PartialEq` requires a non-mutable reference.

A safe approach to handling this could be to define two trees to be equal if and only if they are not in a dirty state (so the bitmaps are compressed) and share the same root. This means that two trees that are honest-to-goodness equal aside from compression status will be declared unequal, but this seems like a safe compromise. It would still be the case (as it is now) that two trees can have the same non-deleted leaves but be unequal, meaning that equality has a very strict definition here.

Finally, it should be asserted that root collisions are not possible. The way that a `MutableMmr` root is computed is that the underlying MMR root is first computed, and then hashed after concatenation with the serialized (and hopefully compressed!) deletion bitmap. This is similar to how the underlying MMR root is computed; because collision attacks exist on generic Merkle trees if leaves and other nodes are not handled carefully, the `MutableMmr` implementation should be checked for similar risks.

**Comment by SWvheerden** [comment]
closing this as we are not using it anymore
