### ISSUE TITLE
Some unmaintained `actions-rs` actions now fail to run in CI

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#5361]
Apparently the [`actions-rs`](https://github.com/actions-rs/) suite of GitHub Actions has been unmaintained for some time now. Coupled with the fact that GitHub [previously indicated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) a change to Actions runtime defaults, this means that certain `actions-rs` actions now [fail to run](https://github.com/tari-project/tari/actions/runs/4834737583?pr=5359).

Since it does not appear that `actions-rs` will see any additional action (pun intended), it may be time to migrate to something better supported. I've seen some folks recommend [`rust-toolchain`](https://github.com/dtolnay/rust-toolchain), but don't know if it can meet all CI needs.

**Comment by AaronFeickert** [comment]
This is fixed in [PR 5362](https://github.com/tari-project/tari/pull/5362), but it still may be prudent to move away from `actions-rs` due to it being unmaintained for quite a while.

**Comment by SWvheerden** [comment]
I have taken a quick look, but this is going to involve a much bigger PR to actually remove actions-rs. 
We might get around to just using the build in rust from the host machine and calling rustup update. 
But for now we just need to get the CI running again.

**Comment by leet4tari** [comment]
We need to replace ```toolchain```, ```cargo``` and ```audit```. 
- ```toolchain``` 10x over 4 files - should be pretty straight forward with  [```actions-rust-lang/setup-rust-toolchain```](https://github.com/actions-rust-lang/setup-rust-toolchain) or [```dtolnay/rust-toolchain```](https://github.com/dtolnay/rust-toolchain)
- ```cargo``` 20x over 5 files - cross-compile needs some work, maybe [```houseabsolute/actions-rust-cross```](https://github.com/houseabsolute/actions-rust-cross)
- ```audit``` only one file to change - [```actions-rust-lang/audit```](https://github.com/actions-rust-lang/audit)

Do we want to do small changes, a little at a time or one big go? Maybe after the next release.

**Comment by stringhandler** [comment]
One big go is fine IMO, no reason to be overly cautious in this area
