### ISSUE TITLE
Range proof rewind and value encryption keys are reused

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#5363]
When producing standard outputs (not one-sided outputs), the wallet [derives](https://github.com/tari-project/tari/blob/536d16d2feea283ac1b8f546f479b76465938c4b/base_layer/wallet/src/output_manager_service/service.rs#L148C7-L153) range proof rewind and value encryption keys using the key manager. The rewind key is later used for commitment mask recovery, and the encryption key is used to encrypt the value with authentication. However, these keys appear to always generate the same keys using a fixed (zero) index in the call to the key manager. It's not clear if this was intentional.

Because commitments use unique masks, and because only one entity (the recipient) can derive the rewind key, it _may_ be the case that fixing this key is safe. However, this is not in line with the expectations of the Bulletproofs+ range proof design, and is likely unsafe if the key were to leak.

[Value encryption](https://github.com/AaronFeickert/tari/blob/536d16d2feea283ac1b8f546f479b76465938c4b/base_layer/core/src/transactions/transaction_components/encrypted_value.rs#L82-L99) is done using `ChaCha20-Poly1305` authenticated encryption with a fixed nonce. The [internal AEAD key derivation](https://github.com/AaronFeickert/tari/blob/536d16d2feea283ac1b8f546f479b76465938c4b/base_layer/core/src/transactions/transaction_components/encrypted_value.rs#L120-L129) process uses both the value encryption key and commitment, which means it will be unique provided a key-and-commitment combination is never reused. If it were, plaintext value recovery could occur.

This uniqueness requirement does not arise in the case of one-sided outputs, where these keys are derived using a Diffie-Hellman key exchange. While a sender could construct a transaction to reuse keys, it already knows the corresponding secrets (the commitment mask and value) and could leak them anyway.

Because the key manager already uses a fresh derivation index for commitment masks, it may be wise to do the same for both rewind and encryption keys.

**Comment by hansieodendaal** [comment]
With [value encryption](https://github.com/AaronFeickert/tari/blob/536d16d2feea283ac1b8f546f479b76465938c4b/base_layer/core/src/transactions/transaction_components/encrypted_value.rs#L82-L99), maybe we need to use a proper random nonce in any case, as it feels wrong to me that the value encryption should rely on external factors to be secure.

**Comment by AaronFeickert** [comment]
This certainly could be changed if desired. It's fine as implemented if the derived AEAD key is unique, as was the intended design. For random nonces, I'd recommend using `XChaCha20-Poly1305`, the extended-nonce variant, for general use. It _may_ be acceptable to use random non-extended nonces in this particular case, since the number of values used in practice is so limited.

**Comment by hansieodendaal** [comment]
I would go with `XChaCha20-Poly1305` as you suggest, which is what I am using in my current WIP for the encrypted openings when we have an optional range proof as `None`.

**Comment by AaronFeickert** [comment]
Somehow I missed that the internal [AEAD key derivation](https://github.com/AaronFeickert/tari/blob/536d16d2feea283ac1b8f546f479b76465938c4b/base_layer/core/src/transactions/transaction_components/encrypted_value.rs#L120-L129) binds in the commitment. If there's a guarantee of uniqueness there, then the external reuse of a value encryption key is no longer problematic.

Updated the initial issue comment for clarity on this.

**Comment by AaronFeickert** [comment]
In-progress [changes](https://github.com/tari-project/tari/pull/5372) to the handling of commitment openings mean this issue is no longer relevant. Closing.
