### ISSUE TITLE
Interest in another 2nd layer Monero project

### ISSUE THREAD

**Issue by dinpd** [tari-project/tari#5369]
Graft (https://github.com/graft-project) was another second layer Monero project with a goal of instant any-to-any currency transactions on the basis of exchange brokers and real-time auth protocol.   There hasn't been any active development on it for a while, but a good chunk of it was completed.  Just testing the waters to see if Tari devs might be interested in picking it up.  Thanks.

**Comment by brianp** [comment]
Thanks for reaching out about the Graft project and its goals. Appreciate your interest in having the Tari team take a look.

However, we're actually quite focused on our own second layer solution that we're building entirely on top of Tari. The team is putting in a lot of effort and we're very excited about the direction of our second layer. So, while we appreciate your suggestion and the progress made by Graft, we'll stick to our own path for now.

Thanks for reaching out, and good luck on the project.
