### ISSUE TITLE
[Discussion] Peer management

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5376]
Currently, a when a peer makes a connection to a node, that node syncs its peer database with the newly connected node. I don't know if it happens both ways, it might?

We need to improve this logic and not just dump the entire DB across as fake and old invalid peers keep getting sent and synced across the network.

**Comment by SWvheerden** [comment]
Perhaps a better way is to only sync/sent nodes that your node has connected to in the past week? 

That way we eventually prune all old and invalid peers from the network by not sending them on.

**Comment by brianp** [comment]
I actually think this is a security issue. Malicious users could max out sqlite db sizes and clog up the network propagating junk data to peers, which could potentially crash or max out the peer db's.

I agree with the suggestion to only sync peers that have been active within the last week, and maybe even a max possible amount. ~50-100 peers seems sufficient. As the node will then connect to these new peers and restart the process.

**Comment by SWvheerden** [comment]
This is fixed, peer will only propagate active connections, and local nodes will ignore inactive peers
