### ISSUE TITLE
Remove internal value/mask AEAD KDF

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari#5393]
A [recent PR](https://github.com/tari-project/tari/pull/5372) updates the handling of commitment value and mask encryption, in part to enable better scanning for interactive outputs. It retains an internal KDF that is applied to an input pre-key. While this is useful (and necessary) in the case where the pre-key is a Diffie-Hellman exchange result from non-interactive one-sided outputs, it is a hit to efficiency in the interactive case where the pre-key is already sufficient to be used directly as the AEAD key.

The efficiency hit comes from a [proposal](https://github.com/tari-project/rfcs/pull/98) to enable offloaded output scanning by having a helper device use a fixed key for attempted decryption of interactive output value-and-mask ciphertext. If the key is used directly, this process is very fast. If it must be run through a per-output KDF, this is a significant efficiency loss.

A straightforward fix is to remove the internal KDF from the encryption and decryption functions, and instead offload it to the caller. This means interactive output decryption can safely use a fixed key, while non-interactive output decryption requires key derivation prior to calling these functions.

Another option, depending on complexity, is to write a new `encrypt_data_no_kdf` function, and use `encrypt_data` as a wrapper that applies the KDF. Then existing callers who need the KDF do not need to be changed, but specific applications that don't need it can use the new functionality, reducing implementation risk.

**Comment by hansieodendaal** [comment]
See #5985

**Comment by hansieodendaal** [comment]
We should discuss the merits of wiring this into the code base, based on the profiling calculations.
(@AaronFeickert , @SWvheerden , @stringhandler, @brianp )

**Comment by hansieodendaal** [comment]
The performance benefits when doing interactive transactions where no KDF is required are huge, but I am voting in favour of not implementing this in the code base due to the increased complexity required when recovering wallets, and due to a performance hit as potentially we would have to run both decryption alternatives during recovery, just to be sure.

In the code below the call to `let (spending_key, committed_value) = match self.attempt_output_recovery(&output).await?` performs decryption.

With `pub async fn scan_and_recover_outputs`
```rust
    pub async fn scan_and_recover_outputs(
        &mut self,
        outputs: Vec<TransactionOutput>,
    ) -> Result<Vec<RecoveredOutput>, OutputManagerError> {
        let start = Instant::now();
        let outputs_length = outputs.len();

        let known_scripts = self.db.get_all_known_one_sided_payment_scripts()?;

        let mut rewound_outputs: Vec<(WalletOutput, bool, FixedHash)> = Vec::new();
        let push_pub_key_script = script!(PushPubKey(Box::default()));
        for output in outputs {
            let known_script_index = known_scripts.iter().position(|s| s.script == output.script);
            if output.script != script!(Nop) &&
                known_script_index.is_none() &&
                !output.script.pattern_match(&push_pub_key_script)
            {
                continue;
            }

            let (spending_key, committed_value) = match self.attempt_output_recovery(&output).await? {
                Some(recovered) => recovered,
                None => continue,
            };
```

**Comment by SWvheerden** [comment]
We should be able to detect which one goes which way, but it does add complexity.

**Comment by AaronFeickert** [comment]
I think it's fair to unify the handling of KDF operations if the benefits of simplicity outweigh the efficiency hit, which is small in absolute terms. Based on @hansieodendaal's benchmarks in #5985, it's an extra 5 seconds or so per million outputs.

It is certainly the case that the no-KDF option is only reasonable if you don't end up attempting decryption twice (once without the KDF, and again with it). The no-KDF option would only apply to interactive transactions, so in the end it really depends on how uniform scripts are between interactive and non-interactive transactions, and if the interactive transaction encryption key can be reliably obtained from the key manager so the recipient only attempts the no-KDF option if it knows the output is part of an interactive transaction to which it's a party.
