### ISSUE TITLE
Create core code for revealed value outputs, with console wallet interface

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#5403]
> I think we need some new tests for:
> 
> 1. receiving onesided payments with revealed values
> 2. block and mempool validation for revealed values
> 3. recovery of interactive and one-sided payments with revealed values

Must do ^^

_Originally posted by @hansieodendaal in https://github.com/tari-project/tari/issues/5372#issuecomment-1559446505_
            
The fees must be more for revealed value proofs. Bulletproof+ type proofs must be the default.

Some notes for implementation:
- In `UnblindedOutput`:
  - Add `pub fn as_revealed_value_transaction_output` with internal test `verify_range_proof` on `output` before returning (_supporting metadata_signature must be pre-existing_)
- In `UnblindedOutputBuilder`:
  - `pub fn try_build` must run  the new `pub fn as_revealed_value_transaction_output`  before returning
- `pub fn  create_receiver_partial_metadata_signature` and `pub fn  create_metadata_signature` will create the correct version of the signature based on `output_features`

**Comment by SWvheerden** [comment]
Going to close this for now. 
New coinbases are revealed value by default now. We don't allow revealed values for non coinbase atm.
