### ISSUE TITLE
Mobile wallet does not pickup mined coinbases 

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5424]
The mobile wallet does not pickup mined coins from a console wallet mined with the same seed phrase.

**Comment by brianp** [comment]
After recovery, it also doesn't pick up any previous balance from sent transactions done on mobile.

**Comment by SWvheerden** [comment]
Going to close this as we have change the way coinbases work: #https://github.com/tari-project/tari/issues/5930
