### ISSUE TITLE
bug(console-wallet): subtract with underflow panic when contact list is empty

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#5465]
**Describe the bug**
Send tab, attempt to send via the contact list. I have a single NeverSeen contact that is not listed in the dialog. I press the down arrow and the console wallet crashes

```
thread 'main' panicked at 'attempt to subtract with overflow', applications/tari_console_wallet/src/ui/widgets/list_state.rs:62:36
```

**To Reproduce**
1. Go to send tab
2. press 'c' to get contacts dialog
3. press up or down arrow
4. panic

**Expected behavior**
The console wallet should not panic when up/down arrow pressed

**Screenshots**
<img width="1166" alt="image" src="https://github.com/tari-project/tari/assets/1057902/9e9da88a-4959-424a-8134-342ef6d3f938">

**Desktop (please complete the following information):**
 - OS & Version: iOS 13.3.1

**Additional context**

**Comment by AaronFeickert** [comment]
I wasn't able to reproduce this bug. I did the following:
- Create a new wallet
- Move to the contacts tab
- Create a new contact
- Move to the send tab
- Activate the contacts dialog
- Press either the up or down arrow key

Regardless of which arrow key I press, the contact is selected and the wallet does not crash.

![Screenshot from 2023-06-27 15-36-10](https://github.com/tari-project/tari/assets/66188213/f30fef3d-5429-44c8-b000-d2600d8e603c)

If I just create the new wallet and do _not_ create a new contact, such that the contact dialog is empty, the wallet also does not crash.

![Screenshot from 2023-06-27 15-38-19](https://github.com/tari-project/tari/assets/66188213/3b17cde3-2dc8-42dd-ab34-98e5dc1bb410)

Do you still get the issue using a new wallet?

**Comment by AaronFeickert** [comment]
Also, why does the contact not appear in the dialog?

**Comment by sdbondi** [comment]
I'll check again, in the code too since it's likely a trivial fix.

**Comment by AaronFeickert** [comment]
Looks like this issue can be closed @sdbondi.
