### ISSUE TITLE
Sender protocol does not send over features for tx sending

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5536]
When doing a new transaction, the sender protocol does not send over to the receiver all the matching features. 
We need to make sure that all information signed in the challenge of the metadata sand kernel signatures are sent over for the receiver to be used and checked. 

Currently, the version info used is `get_current_version()` which should match for a matching running version of a wallet. But if the wallet versions mismatch this will cause invalid sigantures to be generated. 

A sender should send all the signature challenge features over to the receiver. This should be used when generating signatures and if the receiver does not support that version, the tx should be failed

**Comment by stringhandler** [comment]
is this kernel features or output features?

**Comment by SWvheerden** [comment]
Everything in the Metadata signature and kernel signature challenges should be sent over
