### ISSUE TITLE
Tariscript field could be abused to implement Ordinals or other BRC20 kind of features

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#5570]
May be a feature or a bug, but let's find out whether it's a problem

**Comment by CjS77** [comment]
Feature. It's not our place to censor how people use Tari.
It is our place to set the constraints on script size/complexity so that it doesn't hurt the overall performance of the network.

**Comment by stringhandler** [comment]
There is a max_script_size in the constants already (2kb), so this is limited at least
