### ISSUE TITLE
Tari Base Node Docker Image

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#573]
Create scripts/tooling that generates docker images for Tari Base Nodes; batteries included and can communicate via gRPC with the host system.

Sub-issues:

[ ] `Dockerfile` that builds and includes the Tari base node into a minimal docker image
[ ] `docker-compose.yml` file that permits one to start / stop the node as a docker instance; with logs and config set up as a mounted volume optionally.
[ ] Update `README` with Dockery goodness 
[ ] CircleCI job / Github action that automatically builds a new image for quay.io when new releases are tagged.

**Comment by stringhandler** [comment]
See applications/launchpad
