### ISSUE TITLE
Monero transaction version is not limited

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5754]
We should limit the monero tx version to only the current.

**Comment by brianp** [comment]
Where would we do this? I looked for where it might happen but came up empty handed.

**Comment by SWvheerden** [comment]
`TransactionPrefix` has the version in side of it. 
But this means we need to keep using the entire coinbase header in the randomx blocks. 
This is troublesome due to https://github.com/tari-project/tari/issues/5891

**Comment by SWvheerden** [comment]
Going to close this for #5891
