### ISSUE TITLE
Horizon syn correct behavior

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5771]
Currently on Horizon sync, if the node fails horizon sync, the node can be stuck in a broken state if it cannot find a peer with the exact same chain. This can leave the peer in a broken state still a user manually deletes the base node's database. 

This issue is to discuss ideas

**Comment by SWvheerden** [comment]
The correct goal should be that when a peer exit's horizon state, the node is in the best state possible. 

So when a node finds some issue with the kernel sync, it should rewind the kernels back to the starting height. 
Then exit horizon sync and let listing mode + header sync decide the correct approach with a new(or same peer if the peer was not banned) peer.

**Comment by SWvheerden** [comment]
Currently utxo sync is not resumable, which it should be. The utxo set is downloaded in go , but we should be able to make it so that it can resume.

**Comment by hansieodendaal** [comment]
Fixing system-level use for #6006
