### ISSUE TITLE
ChainMetadata uses non standard uint64

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5797]
Should be swapped to uint64

**Comment by brianp** [comment]
@SWvheerden Can you elaborate a little here? I took a look at ChainMetadata and nothing about its `u64`'s jumped out. Do you mean the `u128` for `accumulated_difficulty`?

**Comment by brianp** [comment]
@SWvheerden pointed out it's the proto file using `google.protobuf.UInt64Value` for `height_of_longest_chain` and `timestamp` in https://github.com/tari-project/tari/blob/development/base_layer/core/src/base_node/proto/chain_metadata.proto#L10-L24
