### ISSUE TITLE
GRPC requests are done using http

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5808]
Follow the recommended guidelines at Authentication | gRPC to implement
SSL/TLS based authentication and transport security

**Comment by hnidoaht-101** [comment]
hi @SWvheerden I want to work on this. Please assign to me.

**Comment by SWvheerden** [comment]
cool, you can grab this

**Comment by hnidoaht-101** [comment]
hi, sorry for delay. I'm working on this now

**Comment by SWvheerden** [comment]
The use of HTTP allows an unauthorized attacker to intercept credentials or even
seize control of the connection between a wallet and a node, thereby
compromising the integrity and confidentiality of the data.
The following code snippet shows how the merge miner connects to a wallet
using HTTP:
```rust
info!(target: LOG_TARGET, "Connecting to wallet at {}", wallet_addr);
let wallet_addr = format!("http://{}", wallet_addr);
let wallet_client =
WalletGrpcClient::connect_with_auth(&wallet_addr,
&config.console_wallet_grpc_authentication).await?;
```
The likelihood of this issue is deemed low because it is expected most
configurations will keep wallets and node running on the same host. It also
requires the adversary to be placed on the same network segment.
