### ISSUE TITLE
Merge mining implementation

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#581]
Scope:
* Finalise merge mining strategy (but make changing strategies, e.g. own PoW / Hybrid PoW fairly easy to implement in future).
* Monero coinbase tx modifications
* Tari PoW modifications
* Solo mining process (pool mining is out of scope for testnet)
* Transaction selection strategy (for testnet, a greedy algo will suffice, but should be able to switch out algos easily)
* gRPC API

**Comment by stringhandler** [comment]
Closing this as individual issues have been created
