### ISSUE TITLE
Minotari struct uses floating math in display

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5839]
The MinoTari struct uses floating point math to display. 
This can cause weird rounding due to how f64 works. This is not ideal when displaying actual amounts. It might be used to display the wrong amount. 

Example here: https://github.com/tari-project/tari/pull/5834#discussion_r1356956700

**Comment by hansieodendaal** [comment]
Fixed in  #5834 to get the proper error message printed in `async fn test_fee_overflow()`
