### ISSUE TITLE
Wallet: Chat history

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#585]
Track chat history between peers
* Store messages on a peer basis in a DB
* Delete a given message from history
* Delete all messages for a peer from the history
* Get n messages from nth message for peer
* Get n most recent messages from peer

**Comment by philipr-za** [comment]
The following list items have been implemented in prior PRs (https://github.com/tari-project/tari/pull/526 , https://github.com/tari-project/tari/pull/538):
- Store messages on a peer basis in a DB
- Delete a given message from history
- Other single message CRUD

What remains are the Delete ALL messages for a peer and retrieving messages using pagination.

**Comment by talmahaj** [comment]
@CjS77 @philipr-za can we descope Delete ALL messages and move to backlog, given that we won't have the F/E functionality in the UI for MVP?

**Comment by philipr-za** [comment]
@CjS77 @CjS77 So I propose tagging issues that are scoped for MVP by setting the Milestone to `TestNet Release`. Perhaps to be even clearer would be to make Epics that only contain issues related to MVP and have separate Epics for the later milestones?

**Comment by talmahaj** [comment]
@philipr-za agree!

**Comment by stringhandler** [comment]
@CjS77 @philipr-za @talmahaj Can this issue be closed?

**Comment by CjS77** [comment]
I guess we can label - "Won't implement for now" and close it

**Comment by stringhandler** [comment]
This may be opened again at a later stage
