### ISSUE TITLE
Not possible to disable gRPC methods

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5858]
gRPC server is either enabled or disabled, with no way to filter which methods the
node or wallet operator wants to expose.
While this can be resolved by the use of a reverse-proxy, it is recommended that
the  configuration  exists  to  protect  unaware  operators.  In  particular,  certain
methods should be disabled by default unless the operator explicitly requests
them, because they provide information about a node that in most cases should be
private, such as:
```
check_for_updates
get_version
list_connected_peers
get_sync_progress
get_network_status
get_peers
```

Add  the  capability  to  disable  or  enable  gRPC  methods.  Disable  methods  that
provide internal information of the node by default.

**Comment by hansieodendaal** [comment]
See #5886
