### ISSUE TITLE
wallet utxo scanning very slow

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5915]
Wallet doing utxo scanning take forever to process large blocks. 

Its very easy to see this doing wallet recovery.

**Comment by AaronFeickert** [comment]
Has this gotten worse over time? That is, could recent changes in design or code be at fault?

**Comment by SWvheerden** [comment]
Very likely, there has been numerouse change the last while

**Comment by AaronFeickert** [comment]
Is there a straightforward way to bisect this?

**Comment by SWvheerden** [comment]
create a wallet and do recovery on it with trace logs in the wallet and base node. Then look at the time stamps to see where the wallet/base_node spends most of the time. 

This will be most visible with large blocks with many utxcos.

**Comment by SWvheerden** [comment]
I am going to close this for now. 
This was traced down to slow network especially tor connections. 
Tor is being throttled. 
TCP wallet scanning is very fast. 
Experimental libp2p is fast as well
