### ISSUE TITLE
Miner and Merge mining proxy should print better pretty errors on failing grpc

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5929]
The miner should print pretty errors on failing grpc connection. 

The miner should use a basic function like get constants or something to test the connection 

And then it should use get_version to see if those methods are available. 

It should print pretty and helpful error messages when those steps fail.

**Comment by SWvheerden** [comment]
With the one sided coinbase, the miner should ask the for wallet address rather than fail.

**Comment by hansieodendaal** [comment]
See #6016
