### ISSUE TITLE
Remove GRPC via feature flag in wallet + 1-sided mining

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#5930]
We should hide and remove GRPC from the wallet only adding it in via a compile feature flag. 
The main reason for GRPC is the wallet is mining. 
This requires we must change mining to be one-sided.

**Comment by hansieodendaal** [comment]
See #5967

**Comment by hansieodendaal** [comment]
In the above PR the related gRPC methods and structs that supported mining have been removed from the wallet.

I do not think having a feature flag to hide the remaining gRPC methods is necessary, as we can implement `grpc_server_deny_methods` by default similar to what is done in the base node.

**Comment by CjS77** [comment]
Note that launchpad uses gRPC to control the wallet via the docker API. 

So the builds for the wallet docker container should be updated to _include_ the gRPC feature when this change makes it into the code.

**Comment by SWvheerden** [comment]
We should still feature flag this out. And make sure the dockers compile with the feature flag. 

The configs are not encrypted or protected in anyway, so enabling that is super easy

**Comment by hansieodendaal** [comment]
See #5988 where the `features = ["grpc"]` feature flag is added.
