### ISSUE TITLE
Implement paginated text message retrieval

### ISSUE THREAD

**Issue by philipr-za** [tari-project/tari#594]
Implement the following text message retrieval functions:
- Retrieve `n` most recent text messages To and From a peer
- Retrieve `n` messages from `n`th message To and From a peer
- Retrieve messages based on timestamp range?

Sent and Received messages are stored separately but these retrieval messages will be used to retrieve conversations so should probably merge those lists?

**Comment by CjS77** [comment]
Closing for now, since chat functionality is not likely to be added soon.
