### ISSUE TITLE
Mainnet uses inflating tail emission

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#6122]
# The Minotari emission schedule

The Minotari emission schedule was designed to achieve multiple goals:

* Offer sufficient early liquidity, so that builders of digital assets have equitable access to Tari tokens. This is primarily achieved by implementing an exponential decay function into the primary emission curve.
* Provide support for the continued development and maintenance of the Tari ecosystem. This is achieved via the primary pre-mine.
* Ensure that there are enough tokens to fuel the ecosystem for perpetuity. This is achieved through the tail emission.

Coins that have a fixed supply with no tail emission, such as Bitcoin, are strictly _deflationary_. 

On the other hand, Monero has a constant tail emission. Its total supply is technically infinite, but its emission is _disinflationary_, since the annual inflation rate of the Monero supply is continuously approaching zero. The tail emission is broadly in place to account for coins that are lost due to the fact that people are involved in the system, and people tend to lose and/or break things.

Bitcoin and Monero have one job: To be money.

But Minotari has a very important second role: to be converted into the Tari tokens that fuel the Tari Digital Assets Network.

The word _fuel_ is not just metaphorical. A small portion of the transaction fee in every single one of Tari’s second layer instructions is _burnt_. This creates a small but constant driving force to convert Minotari into Tari. This simple and elegant design is called the [turbine model](https://rfc.tari.com/RFC-0320_TurbineModel.html). It maintains a soft 1:1 peg between Tari and Minotari without having to resort to complicated peg-out mechanisms like drive chains, or federated pegs like Liquid. In fact, there’s no peg-out at all. This offers the tremendous benefit of allowing the Tari network to operate at its native speed (fast!).

Because of the turbine model, in the absence of a tail emission, we would eventually run out of Tari. But even a disinflationary token may experience liquidity problems in the long run if the second layer experiences sustained growth.

Imagine if the Tari tail emission was a constant 800 XTR per block. If the Tari network was burning more than that every two minutes due to sustained high activity, then the supply of Tari globally would fall.

Therefore, Tari’s tail emission is mildly inflationary in nominal terms. Real GDP growth typically sits somewhere between 1% and 3% per annum. The genesis block has encoded parameters that initiate a tail emission inflation rate at the low end of this range.
The tail emission kicks in as soon as the annual inflation rate of Minotari drops below the target rate and is set to provide a 1% supply increase over the course of the next 12 months. Every 12 months, the block reward is boosted to maintain the 1% supply growth going forward. 

So once the tail emission is active, Tari will undergo _boostings_ as opposed to Bitcoin’s _halvings_. 

Given a target rate of 1%, the tail emission will commence in the 13th year of Tari’s existence and each boosting will increase the reward slightly to maintain the inflation rate at a shade under 1%. The first ten boostings are listed in Table 1.

| epoch | reward |
|-------|--------|
| 1     | 764.0  |
| 2     | 771.0  |
| 3     | 779.0  |
| 4     | 787.0  |
| 5     | 795.0  |
| 6     | 803.0  |
| 7     | 811.0  |
| 8     | 819.0  |
| 9     | 827.0  |
| 10    | 835.0  |

**Comment by CjS77** [comment]
Being implemented in tari core with feature flag `tari_feature_mainnet_emission`

**Comment by SWvheerden** [comment]
this is done
