### ISSUE TITLE
Geometric mean analysis from moneromoo

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#6142]
My theory is that because of the geometric mean calculation, monero blocks will always reorg out sha blocks, at least at the tip.

So take a case where the tip is at height 1000, if a sha block comes in at height 1001, there is a high likelihood that a monero block at height 1001 will reorg it out.

This is because the total accumulated difficulty of sha3 is thousands of times that of the monero accumulated difficulty, and a monero block will increase the geometric mean a lot more.

So to find out how much of a problem this is, we will need to look at:
1. In a node running for a long time, how many sha blocks are reorged out (reorg tracking must be on)
2. Out of the sha blocks mined into the chain, how much higher is the achieved difficulty on average, compared to the difference in achieved difficulty of monero. In other words, take all the sha blocks, subtract the achieved difficulty from the target difficulty and average it (or chart it over time) and compare it to monero. What we are looking for here is an indication that the target difficulty for sha3 blocks to **NOT GET REORGED OUT** is much higher than the advertised target difficulty.
3. Find other ways to determine if it is a problem

**Comment by hansieodendaal** [comment]
I have analyzed the last 320 blocks up to block 43074, with some interesting results. My angle was to look at which blocks were added to the blockchain and to analyze the achieved difficulty vs. target difficulty of each.

SHA3 ratio: 41% (design target = 40%)
RandomX ratio: 59% (design target = 60%)

From this alone, all seems fine, but let us look at more stats. As an example:

| Block # | SHA3 Target | SHA3 Achieved | SHA Ratio | RandomX Target | RandomX Achieved | RandomX Ratio |
| ------- | ----------- | ------------- | ----- | -------------- | ---------------- | --------- |
| 1       | 4368343616  | 5795274569    | 0.33  |                |                  |           |
| 2       |             |               |       | 29619308       | 317289624        | 9.71      |
| 3       |             |               |       | 30002691       | 49501841         | 0.65      |
| 4       | 4434774626  | 61454325239   | 12.86 |                |                  |           |

**Normalized Achieved Difficulty per consecutive block**

![Image](https://github.com/tari-project/tari/assets/39146854/37644a6d-c906-4e10-b6d5-b5cbdf311e06)

Zoom in on the y-axis a bit

![Image](https://github.com/tari-project/tari/assets/39146854/2131ae4d-03c5-4fe6-9f4a-c41587454647)

Zoom in on the y-axis some more

![Image](https://github.com/tari-project/tari/assets/39146854/b2130abc-847f-40ac-8bc9-00a6f517ac6b)

**Normalized Achieved Difficulty sorted**

![Image](https://github.com/tari-project/tari/assets/39146854/5bcdcab2-91b7-4a35-adca-4dcf94b362a1)

Zoom in on the y-axis a bit

![Image](https://github.com/tari-project/tari/assets/39146854/35210f0f-9e1e-41d7-9700-8bf6c5cb3a48)

Zoom in on the y-axis some more

![Image](https://github.com/tari-project/tari/assets/39146854/b4326363-49eb-4bad-8450-ab4b1ded6d01)

**Comment by hansieodendaal** [comment]
My conclusion is that if one algo was favoured above the other with re-orgs, we would not have seen the design goal 60:40 split being achieved and that one algo in the final graph would have shown markedly increased sorted normalized achieved difficulties. Each algo has to work as hard as the other algo to get a block into the blockchain.

**Comment by SWvheerden** [comment]
we changed the use away from achieved to target difficulty. We can close this now
