### ISSUE TITLE
[grpc] The call get_network_difficulty returns the difficulty as the target difficulty for that block and not the current network difficulty

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari#6438]
Expected: 
It should return a struct with the randomx and sha3x target difficulty.

Actual:
It returns a number of blocks, and has the target difficulty for that block, which may be either of the two algorithms

**Comment by xG0Ian** [comment]
```rust
async fn get_network_difficulty(
        &self,
        request: Request<tari_rpc::HeightRequest>,
    ) -> Result<Response<Self::GetNetworkDifficultyStream>, Status>
```
`tari_rpc::HeightRequest` requests a block range, so the `get_network_difficulty` returns all of these difficulty of this block range. Do I get it? Should we achieve `get_current_network_difficulty` to returns the current network difficulty?
