### ISSUE TITLE
Refactor ConnectionManager to be an async service

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#647]
ConnectionManager functionality should be refactored to implement `tower_service::Service`.

- ConnectPeer - Initiate or retrieve an existing outbound connection to a Peer
- DropPeerConnection - Drop a connection to a peer
- TBD

**Comment by Tas4tari** [comment]
@Tas4tari

**Comment by sdbondi** [comment]
This has been partially implemented by #747 - the underlying connection manager is not async as that is a longer project involving #762 - feel it's ok to close this issue and make new issues when #762 can get underway
