### ISSUE TITLE
Refactor PeerManager to use async/await 

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#648]
PeerManager should be refactored to implement `tower_service::Service`

- FindPeerByPublicKey - Retrieve a peer by it's public key
- FindPeerByNodeId - Retrieve a peer by a NodeId
- AddPeer - Add a peer
- UpdatePeer - Update a peer (node ID and address)
- BanPeer - mark a peer as banned
- UnbanPeer - remove the banned mark from a peer
- RemovePeer - remove a peer

**Comment by Tas4tari** [comment]
@Tas4tari ]

**Comment by sdbondi** [comment]
Think we can close this for now as peer manager being a shared memory object is working and will be influenced by #762 (probably need a async connections epic?)
