### ISSUE TITLE
handshake session limit

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari#6513]
Base node complains about not enough sessions remaining, but has plenty
```
15:44 v1.1.0-pre.2 esmeralda State: Listening Tip: 9656 (Mon, 12 Aug 2024 13:44:24 +0000) Mempool: 0tx (0g, +/- 0blks) Connections: 3|2 Banned: 0 Messages (last 60s): 10 Rpc: 10/100 ⚡️ 1.17s
15:44 WARN  Rejecting handshake because no more RPC sessions available
```
Rename file type to .zip, it is not a gif file

![Image](https://github.com/user-attachments/assets/75d4134a-7c27-46bf-99cd-6a43892c1707)

See #6507 - must be observed

**Comment by hansieodendaal** [comment]
See #6511 as te most probable solution. Thanks @sdbondi.

**Comment by SWvheerden** [comment]
Closing this for now as we have not seen this again
