### ISSUE TITLE
Create discord bridge to #tari-dev

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#658]
It would be handy to have a bridge from discord to our IRC channel.

This will allow folks who don't like or who don't wish to use IRC to participate in our dev chats.

**Comment by zhangcheng** [comment]
I think this ticket could be closed now since there are already [discard channels](https://discord.gg/q3Sfzb8S2V). Glad to find out that just now (didn't read the official homepage more closely before. 🥲 )
