### ISSUE TITLE
cargo build error for libtorc

### ISSUE THREAD

**Issue by raijinspecial** [tari-project/tari#6722]
i keep getting the following error when trying to build on ubuntu 

error: failed to run custom build command for `libtor-src v47.13.0+0.4.7.13`

**Comment by delta1** [comment]
You should post more information from the error log when building. 

It's likely you need to install the dependencies: https://github.com/tari-project/tari/blob/development/scripts/install_ubuntu_dependencies.sh

**Comment by raijinspecial** [comment]
that did the trick, thanks
