### ISSUE TITLE
Implement code coverage tools

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari#76]
We should have automated test coverage tooling built into out CircleCI automation

**Comment by captainludd** [comment]
Is this open CJ? Ive not used travis but  it looks simple enough, could you point me to  the build  pipeline and the code you want tested.

**Comment by CjS77** [comment]
You're welcome to it. Only caveat is that we've just switched to CircleCI :)

**Comment by captainludd** [comment]
Id love to Cj,  I dont see the permissions to assign myself that issue on this page.  I can only create new ones but Im not going to do that till ive dug around for a bit.  CircleCI looks nice though

**Comment by CjS77** [comment]
Ah, good point. Ok, I'll move this issue into "In Progress" and that should stop anyone else tackling it @captainludd

**Comment by CjS77** [comment]
@captainludd - Are you still keen on tackling this?
