### ISSUE TITLE
Find kernel height via hash

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/tari#812]
We need to be able to find the block height a kernel was added to the block chain. We need this for the relative time locks to work. We currently have an option to store the hash of a linked_kernel in side of the other kernel.  This will allow us to retrieve that kernel.  We just need to know at which height it was added. 

Issue #740

**Comment by Tas4tari** [comment]
As per @neonknight64  Delayed to after TestNet. Required for the relative time-locks
