### ISSUE TITLE
Coinbase validation

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/tari#941]
- A block should only contain 1 Coinbase UTXO and 1 Coinbase kernel
- Verify Coinbase maturity
- Verify Coinbase amount

**Comment by SWvheerden** [comment]
There is already code do to this. 
`pub fn check_internal_consistency(&self, rules: &ConsensusRules) -> Result<(), BlockValidationError>`  in block.rs will check the coinbase rules. This can probably be optimised in the way it checks the block reward. But the code is there to check it.

**Comment by SWvheerden** [comment]
Code is now linked, but breaking many unit tests

**Comment by SWvheerden** [comment]
Done in #1095
