### ISSUE TITLE
[Feature] Launch screen animation

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#990]
**Acceptance Criteria**

1. The entire app launch animation in https://vimeo.com/369345180 is implemented with the exception of the Face ID modal.

2. The animation is built such that it can support the following two sets of behavior:
    1. For existing users, we'll need to be able to easily insert the Face ID/biometric/lock screen interstitial per the animation reference below (though the actual implementation of that authentication is NOT in the scope of this ticket)
    2. For new users, the UX is still TBD, so please go as far as you can such that we can support either of the two flows below. Either:
        1. It will be the same as for existing users above, except instead of authenticating, they're required to hit a CTA button to view the rest of the animation: 
<img width="222" alt="Screen Shot 2019-11-10 at 2 00 36 PM" src="https://user-images.githubusercontent.com/1817246/68551519-92397800-03c2-11ea-960f-8f98457e30ca.png">
        2. OR the animation will play through to the end without any sort of interstitial before the user sees any screens with CTA and/or onboarding steps

-----

**Assets**

Logo assets: https://www.dropbox.com/sh/2770a3fxx6ikll1/AADDByhZ8tyXlVhmJFjJmLwaa?dl=0
(Note that rotating "I" asset is missing, @Karim-tari pls delete this line once it's added)

Animation reference: https://vimeo.com/369345180
Timestamp 00:00 through 00:13 (everything until the white screen **except** the Face ID prompt)

-----

**Implementation Notes**

The splash animation gives the app an opportunity to load libwallet, and establish a connection with the base node. This doesn't have to be implemented now, but should be kept in mind when completing this ticket.

On Android, libwallet will (highly likely) run as a foreground service.
On iOS will (probably) run as a background task.

**Comment by talmahaj** [comment]
@Karim-tari can you add the asset files for just the "I" in Tari that animates in Dropbox as well? Thx!

**Comment by CjS77** [comment]
The splash animation gives the app an opportunity to load libwallet, and establish a connection with the base node. This doesn't have to be implemented now, but should be kept in mind when completing this ticket. 

On Android, libwallet will (highly likely) run as a foreground service.
On iOS will (probably) run as a background task.

**Comment by talmahaj** [comment]
@CjS77 updated ticket description per your comment, feel free to edit it directly in the future. Also revised to indicate that first time user experience is still TBD until @Karim-tari has time to revisit.

**Comment by Karim-tari** [comment]
> @Karim-tari can you add the asset files for just the "I" in Tari that animates in Dropbox as well? Thx!

[data.json.zip](https://github.com/tari-project/tari/files/3832025/data.json.zip)

**Comment by Karim-tari** [comment]
Just added it to the shared DB folder
