### ISSUE TITLE
[Feature] New user - splash screen and loading sequence

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#991]
**Acceptance Criteria**

1. A new user opening the app sees the loading screen, splash screen, and pre-onboarding loading sequence in timestamp 00:00 through 00:30 of https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

2. Timing is the same as in video (even if artificial delays required)

-----

**Implementation Notes**

The only new screen to be built for the scope of this ticket is the one with the purple orb, including the interaction and loading indicator on the CTA button.

The gem icon loading state you can see at 00:03, and the TARI logo animation at around 00:27 after the user hits the create wallet button, of https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 should have been built already as part of the loading and splash screen UX for existing users, so can be reused for the new user flow. See that ticket here: https://github.com/tari-project/tari/issues/990

-----

**Assets**

Animation reference: https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0
Timestamp 00:00 through 00:30 (opening the app through the purple orb splash screen through TARI logo animation)

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e25486e4feafc28d64dd73f

Assets should be in the Dropbox folder: https://www.dropbox.com/sh/2770a3fxx6ikll1/AADDByhZ8tyXlVhmJFjJmLwaa?dl=0

----

**Open Questions**

How should @Karim-tari export the animation for the purple orb thingy? Lottie file?

**Comment by Jasonvdb** [comment]
@talmahaj yeah lottie file in the same format as the Tari animation would be best. And I think the animation needs to end on the same appearance as the first frame so we can play it on a loop without it jumping every time it restarts

**Comment by talmahaj** [comment]
> @talmahaj yeah lottie file in the same format as the Tari animation would be best. And I think the animation needs to end on the same appearance as the first frame so we can play it on a loop without it jumping every time it restarts

Thanks! @Karim-tari see above

**Comment by CjS77** [comment]
@Karim-tari -- as you mentioned, videos with alpha channels are generally lossless, so running the animation with transparency doesn't look viable (or at least smaller than what we have).

But returning to a video with a black background, I propose we use _one_ video -- compressed to ~5MB that operates are follows:

```
|<-------------->|<--------------------------------------------------------------------->|
0:00            0:nn                                                                    0:kk
    Fade In      A                      Loop                                             A
```

The frame A at `0:nn` and `0:kk` should be identical. 
We loop by running two copies of the same video, which plays from `0:nn` to `0:kk` continuously; except the first loop, which includes the fade-in portion.

Is it possible to edit the video to produce this? And also to let us know what `0:kk` is (to millisecond precision)

**Comment by Karim-tari** [comment]
@CjS77 Yeah, that makes sense. I added a new video here https://www.dropbox.com/sh/wvopjo6cu7b6js1/AACEHmQ9GG9CRElWSBlWWeRwa?dl=0 which is just the video that loops. (there is a compressed version and a regular version in there). 

This is a view of how it can loop and fade. (The fades in this example are exactly 1 second and they overlap each other)
![Loop-demo](https://user-images.githubusercontent.com/43279391/73681332-1d599f80-468c-11ea-9bb6-606917c43642.png)

**Comment by CjS77** [comment]
You can include the fade-in. I just need the timestamp of the point where I can loop it back (Frame A) above

**Comment by Karim-tari** [comment]
@CjS77 Do you mean to include the actual fading in the video? I was thinking about that, however because the video is not transparent we need to have all the fading happen through code. Fading it in the video + code might give us a weird effect.

**Comment by CjS77** [comment]
I thought you had some special sequence in the beginning.  If we can fade it in and just loop the video from the beginning that can work too

**Comment by Karim-tari** [comment]
Ah yeah, there is an intro to the orb effect. I removed it to make it easier to loop and save the extra 4MB file.

However, if we can include I think that would be awesome. I added it to the files now. The loop file would technically start right after this without any fading because it continues perfectly, then the loop file would continue to loop with fading on top of itself.

**Comment by CjS77** [comment]
That makes it harder actually :)

I still think it's best to have  _one_ video and the exact timestamp that we should loop back to. I seem to be unable to explain this effectively :/

```
|<-------------->|--------------------------------------------------------->|
0:00            0:nn                                                       0:kk
    Fade In      A                      Loop                                A
                 ^                                                          v
                 ⎣__________________________________________________________⎦
```
