### ISSUE TITLE
[Feature] New user - Authorize local authentication

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#993]
**User Story**

> Before I transact, I want to set up a login wall(s) to give me peace of mind my funds are secure

To reduce user friction, and to communicate that we don't have any sort of centralized authentication mechanism, we'd like to require users to enable local authentication in order to use our app.

-----

**Outstanding**

1. UX/UI: Screen and step in flow from which user is asked to authorize local authentication (will have explicit CTA)

-----

**Open Questions**

1. iOS: Though this is out of scope for this ticket, if a user doesn't have biometrics enabled at all on iOS, can we enable the same flow as Face ID/Touch ID but with their screen passcode? If so, what is the LOE? Or would we need to build some sort of custom local PIN creation/storage feature a la Robinhood or Coinbase?

2. Android: Android's docs make it clear that we can do local auth without a fingerprint sensor available or enabled (see https://developer.android.com/training/sign-in/biometric-auth "Allow fallback for non-biometric credentials") but it's unclear what the default UI/UX would be here how much customization we have.

3. Android/iOS: Is there any policy that we *must* allow users to continue to be able to use the app if they opt out of local authentication?

-----

**Acceptance Criteria**

1. iOS/Android: Since UI is still TBD for the screen which prompts user to enable local authentication, feel free to just use a blank view with only a CTA button reading "Log in with Face ID," "Log in with Touch ID," "Log in with PIN," "Log in with Pattern," etc. based on what is available and enabled on the user's device

2. iOS
    1. For users with Face ID available and enabled, hitting a CTA that reads "Log in with Face ID" will trigger the permissions flow like in the following app: https://assets.pcmag.com/media/images/491454-quick-authentication.png?width=740&height=740&boxFit=y
    2. For users with Touch ID available and enabled, hitting a CTA that reads "Log in with Touch ID" will trigger the same flow above but with Touch ID instead of Face ID
    3. For users **without** Touch ID or Face ID available and/or enabled, please display button in disabled state reading "Touch ID not enabled" or "Face ID not enabled" (based on user's device) with text below button reading "Please enable [Touch ID/Face ID] to use our app and protect your funds"

3. Android
    1. For users with fingerprint available and enabled, hitting a CTA that reads "Log in with Fingerprint" will trigger the permissions flow like in the following app: 
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1N3dhMnLJpesbm8F_wbAHAcOX35f5gLYR%2Fas-fingerprinticon-anatomy-informationarchitecture.png
    2. For users without fingerprint available and enabled... [TBD per open questions above]

-----

**Implementation Notes**

the setConfirmationRequired() method (Android) should be set with false to eliminate an extra click in the initial UX flow.

-----

**Relevant Documentation**

iOS:
https://developer.apple.com/documentation/localauthentication

Android:
https://developer.android.com/training/sign-in/biometric-auth
https://source.android.com/security/authentication
Creating custom biometric prompt UI for older versions of Android than P: https://proandroiddev.com/5-steps-to-implement-biometric-authentication-in-android-dbeb825aeee8

**Comment by Jasonvdb** [comment]
Regarding open question 1. There are 2 types of local auth for iOS:
- `deviceOwnerAuthenticationWithBiometrics`: Restriction for the user to only use biometric (face/touch ID). In this case if that fails we would need to fallback to a custom pin/password to unlock.
- `deviceOwnerAuthentication `: Allows the app to authenticate with biometrics or the device password. 

Most apps like this always have a fallback to a custom pin/password screen as there can be a few reasons biometrics are unavailable. e.g. older phone, haven't set it up yet, locked out after too many attempts. So having a fallback is definitely required in the end but I don't know if it's MVP worthy @talmahaj

**Comment by CjS77** [comment]
>  but it's unclear what the default UI/UX would be here how much customization we have.
I'm pretty sure it uses the system PIN/PW UI

**Comment by CjS77** [comment]
the `setConfirmationRequired()` method (Android) should be set with `false` to eliminate an extra click in the initial UX flow.

**Comment by talmahaj** [comment]
> Regarding open question 1. There are 2 types of local auth for iOS:
> 
> * `deviceOwnerAuthenticationWithBiometrics`: Restriction for the user to only use biometric (face/touch ID). In this case if that fails we would need to fallback to a custom pin/password to unlock.
> * `deviceOwnerAuthentication `: Allows the app to authenticate with biometrics or the device password.
> 
> Most apps like this always have a fallback to a custom pin/password screen as there can be a few reasons biometrics are unavailable. e.g. older phone, haven't set it up yet, locked out after too many attempts. So having a fallback is definitely required in the end but I don't know if it's MVP worthy @talmahaj

@Jasonvdb Thanks! Agree we'll need a cleaner fallback eventually even if after MVP -- those other apps have custom screens to set a 4 digit PIN as you mention -- I just wanted to know if we could **already** fall back to passcode only with no custom work for phones where it's unavailable or not enabled (which would only leave us the edge case where you're locked out). Sounds like deviceOwnerAuthentication would enable that -- what is the level of effort of adding the passcode fallback for those devices?

Rationale: When a few of us were discussing this, we weren't too worried about supporting old phones given the target market, but were thinking that there may be people who don't enable biometrics for privacy reasons, but still use a passcode.

**Comment by talmahaj** [comment]
> the `setConfirmationRequired()` method (Android) should be set with `false` to eliminate an extra click in the initial UX flow.

Added to implementation notes section

**Comment by Jasonvdb** [comment]
Just tested the code out quick on iOS and it seems like a fairly quick win just falling back to the passcode if the face ID is disabled. If the user doesn't enable biometrics it'll just instantly go for the device pin/password each time https://cl.ly/024f766faf73

**Comment by talmahaj** [comment]
@Jasonvdb Awesome, let's do it.

Quick copy change on the alert: "...unlock your wallet" --> "protect your wallet"

A few followup Qs:
- Is the passcode screen custom? It doesn't look like the default passcode screen I'm familiar with, but I have a numeric passcode enabled as opposed to an alphanumeric one
- What happens if the user doesn't have Face ID configured/enabled on their device at all, e.g. if they're the tinfoil hat type?

**Comment by Jasonvdb** [comment]
- It's the standard device unlock screen, when you set up your device code you can make it numeric or alphanumeric and it'll just display the num pad or full keyboard depending on what you used. I was using the simulator here which just accepts anything to unlock.
- If the user isn't enrolled for face ID/fingerprint then that's something we can check. What do you reckon should happen there though? Ideally that's when we let them setup a custom app level pin. Or for testnet MVP we can just let them in?

**Comment by Jasonvdb** [comment]
For now we're just using the biometrics to determine if the user can move forward in the app or not but going forward I think the idea is to leverage the secure enclave on the iPhone. So a wallet's private keys can be encrypted and can only be decrypted with the Face ID.

**Comment by talmahaj** [comment]
> @talmahaj
> 
> * It's the standard device unlock screen, when you set up your device code you can make it numeric or alphanumeric and it'll just display the num pad or full keyboard depending on what you used. I was using the simulator here which just accepts anything to unlock.
> * If the user isn't enrolled for face ID/fingerprint then that's something we can check. What do you reckon should happen there though? Ideally that's when we let them setup a custom app level pin. Or for testnet MVP we can just let them in?

If the user isn't enrolled, wouldn't it just fall back to the device passcode as well? Because that would bee totally fine for testnet MVP.

**Comment by talmahaj** [comment]
> For now we're just using the biometrics to determine if the user can move forward in the app or not but going forward I think the idea is to leverage the secure enclave on the iPhone. So a wallet's private keys can be encrypted and can only be decrypted with the Face ID.

Do we need to create a separate ticket to track this task so we don't forget it? @CjS77

**Comment by Jasonvdb** [comment]
> > @talmahaj
> > 
> > * It's the standard device unlock screen, when you set up your device code you can make it numeric or alphanumeric and it'll just display the num pad or full keyboard depending on what you used. I was using the simulator here which just accepts anything to unlock.
> > * If the user isn't enrolled for face ID/fingerprint then that's something we can check. What do you reckon should happen there though? Ideally that's when we let them setup a custom app level pin. Or for testnet MVP we can just let them in?
> 
> If the user isn't enrolled, wouldn't it just fall back to the device passcode as well? Because that would bee totally fine for testnet MVP.

Just tested that and yeah, just falls back to the device passcode

**Comment by talmahaj** [comment]
Saweeeeeet

**Comment by CjS77** [comment]
>  what happens if the user does the auth, backgrounds the app & then foregrounds it? 

My vote is to have to do the biometric auth again. Maybe we can add a timeout feature where this isn't necessary in future, but I vote not for MVP

**Comment by kukabi** [comment]
> > what happens if the user does the auth, backgrounds the app & then foregrounds it?
> 
> My vote is to have to do the biometric auth again. Maybe we can add a timeout feature where this isn't necessary in future, but I vote not for MVP

Banking app I use most often forces a re-login after a no-action timeout, but I can sure implement auth every time from back to fore.

There's also the case of no lock screen (i.e. no passcode) on Android. What should we do in that case? Maybe a custom app-level pin as @Jasonvdb suggested, or just a warning and no auth? @talmahaj  @CjS77

**Comment by talmahaj** [comment]
Sorry @kukabi @CjS77 not sure how I missed the last two notes. 

@CjS77 Agree they should have to do the auth again each time they foreground the app

@kukabi My guess is that that's an edge case, so handle it as cheaply and quickly as you can think of; I'm totally OK with just popping an alert with a warning as you suggest (and then no auth)
