### ISSUE TITLE
[Feature] New user - Enable Push Notifications

### ISSUE THREAD

**Issue by talmahaj** [tari-project/tari#995]
**User Story**

> When I am prompted to enable push notifs, I want to understand why it's important and feel confident I won't be spammed with marketing crap

-----

**Acceptance Criteria**

1. [After enabling local authentication] The screen that explains why they should enable push notifications should animate in per 1:18ish in  https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0 
2. Animation sequence is connected with prior step in onboarding, such that user can go through the flow from first app launch through push notif authorization seamlessly
3. Hitting “Enable Notifications” button pops the default native permissions modals for users to enable push notifs on iOS and Android
4. User should be able to opt out of push by hitting Skip on the top right (which means that the permissions modal should not appear)
    1. If user hits “Don’t Allow” from permissions modal, they should also be allowed to continue despite opting out
 
-----

**Implementation Notes**

Reuse button styles, including loading state, from prior tickets like https://github.com/tari-project/tari/issues/990

For scope of Testnet MVP, user will not be able to change this setting after the onboarding flow. We’ll create a separate GH ticket so we remember to implement that setting in the future.

-----

**Assets**

Animation reference: https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0
Timestamp: 1:18ish

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e25489c3f64c9571e01a1f2

Assets should be in the Dropbox folder.

@Karim-tari pls add animation files, assuming we need Lottie here?

**Comment by kukabi** [comment]
Do we have the backend services required to send push notifications? We need to register the push id of the device (i.e. wallet). And this introduces a central server. Is a central server in line with our no-center principle @CjS77?

**Comment by CjS77** [comment]
@kukabi -- correct me if I'm wrong, but because we're going with a foreground service (in Android), we don't need push notifications. In-app notifications are sufficient to let the user know when txs are finalised and so on

**Comment by kukabi** [comment]
@CjS77 Correct but there's the case of the user turning off an back on, we cannot enforce the service at os startup afaik. If we can omit this case then we're fine.

**Comment by kukabi** [comment]
@CjS77 actually there might be a way of starting up at boot https://stackoverflow.com/questions/6391902/how-do-i-start-my-app-on-startup. Never tried it tho, will give it a try.

**Comment by Tas4tari** [comment]
Spoke to @kukabi and this can be closed off
