### ISSUE TITLE
Investigate options for over-the-wire compression

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari#996]
Libraries to investigate:

https://github.com/ende76/brotli-rs
https://docs.rs/compression/0.1.4/compression/
https://github.com/BurntSushi/rust-snappy

Compression of largely random binary data is potentially flawed/ limited in it's benefits (see https://www.wikiwand.com/en/Kolmogorov_complexity). However there could be gains by compressing before data is encrypted.

**Comment by stringhandler** [comment]
Needs more info

**Comment by sdbondi** [comment]
Closing for now
